IF EXISTS (SELECT 'X'
           FROM   INFORMATION_SCHEMA.VIEWS
           WHERE  TABLE_NAME = 'VW_IVLD_INVENTORY_WD_ACTUAL_PROJ_MAS'
                  AND TABLE_SCHEMA = 'dbo')
  BEGIN
      DROP VIEW   [dbo].[VW_IVLD_INVENTORY_WD_ACTUAL_PROJ_MAS]
  END

GO

CREATE VIEW [dbo].[VW_IVLD_INVENTORY_WD_ACTUAL_PROJ_MAS]
AS
SELECT DISTINCT IVLD_INVENTORY_WD_ACTUAL_PROJ_MAS_SID
	,INVENTORY_WD_ACTUAL_PROJ_MAS_INTF_ID
	,YEAR
	,MONTH
	,DAY
	,WEEK
	,COMPANY_ID
	,COMPANY_NAME
	,BRAND_ID
	,BRAND_NAME
	,ITEM_ID
	,ITEM_NAME
	,UNITS_WITHDRAWN
	,AMOUNT_WITHDRAWN
	,NULL AS UNITS_ON_HAND
	,NULL AS AMOUNT_ON_HAND
	,NULL AS QUANTITY_ON_ORDER
	,NULL AS AMOUNT_ON_ORDER
	,NULL AS QUANTITY_RECEIVED
	,NULL AS AMOUNT_RECEIVED
	,PRICE
	,CREATED_BY
	,CREATED_DATE
	,MODIFIED_BY
	,MODIFIED_DATE
	,ADD_CHG_DEL_INDICATOR
	,BATCH_ID
	,SOURCE
	,FORECAST_NAME
	,FORECAST_VER
	,COUNTRY
	,ORGANIZATION_KEY
	,INTF_INSERTED_DATE
	,REASON_FOR_FAILURE
	,ERROR_CODE
	,ERROR_FIELD
	,REPROCESSED_FLAG
	,1 AS IS_FORECAST
	,1 AS IS_MASTER
	,CASE 
		WHEN A.INVENTORY_TYPE = 'Actuals'
			THEN (
					SELECT HELPER_TABLE_SID
					FROM HELPER_TABLE
					WHERE LIST_NAME = 'INVENTORY_TYPE'
						AND DESCRIPTION = 'Actuals'
					)
		ELSE (
				SELECT HELPER_TABLE_SID
				FROM HELPER_TABLE
				WHERE LIST_NAME = 'INVENTORY_TYPE'
					AND DESCRIPTION = 'Projections'
				)
		END AS INVENTORY_TYPE
	,CASE 
		WHEN A.INVENTORY_LEVEL = 'Details'
			THEN (
					SELECT HELPER_TABLE_SID
					FROM HELPER_TABLE
					WHERE LIST_NAME = 'INVENTORY_LEVEL'
						AND DESCRIPTION = 'Details'
					)
		ELSE (
				SELECT HELPER_TABLE_SID
				FROM HELPER_TABLE
				WHERE LIST_NAME = 'INVENTORY_LEVEL'
					AND DESCRIPTION = 'Summary'
				)
		END AS INVENTORY_LEVEL
	,CHECK_RECORD
FROM (
	SELECT IWP.IVLD_INVENTORY_WD_PROJ_MAS_SID AS IVLD_INVENTORY_WD_ACTUAL_PROJ_MAS_SID
		,IWP.INVENTORY_WD_PROJ_MAS_INTF_ID AS INVENTORY_WD_ACTUAL_PROJ_MAS_INTF_ID
		,IWP.YEAR
		,IWP.MONTH
		,IWP.DAY
		,IWP.WEEK
		,COMPANY_ID
		,COMPANY_NAME
		,BM.BRAND_ID
		,BM.BRAND_NAME
		,IWP.ITEM_ID
		,IM.ITEM_NAME
		,IWP.UNITS_WITHDRAWN
		,IWP.AMOUNT_WITHDRAWN
		,NULL AS UNITS_ON_HAND
		,NULL AS AMOUNT_ON_HAND
		,NULL AS QUANTITY_ON_ORDER
		,NULL AS AMOUNT_ON_ORDER
		,NULL AS QUANTITY_RECEIVED
		,NULL AS AMOUNT_RECEIVED
		,PRICE
		,IWP.CREATED_BY
		,IWP.CREATED_DATE
		,IWP.MODIFIED_BY
		,IWP.MODIFIED_DATE
		,IWP.ADD_CHG_DEL_INDICATOR
		,IWP.BATCH_ID
		,IWP.SOURCE
		,FORECAST_NAME
		,FORECAST_VER
		,IWP.COUNTRY
		,IWP.ORGANIZATION_KEY
		,IWP.INTF_INSERTED_DATE
		,IWP.REASON_FOR_FAILURE
		,IWP.ERROR_CODE
		,IWP.ERROR_FIELD
		,IWP.REPROCESSED_FLAG
		,1 AS IS_FORECAST
		,1 AS IS_MASTER
		,'Projections' AS INVENTORY_TYPE
		,'Summary' AS INVENTORY_LEVEL
		,IWP.CHECK_RECORD
	FROM IVLD_INVENTORY_WD_PROJ_MAS IWP
	JOIN COMPANY_MASTER CM ON CM.COMPANY_ID = IWP.ORGANIZATION_KEY
	JOIN ITEM_MASTER IM ON IM.ITEM_ID = IWP.ITEM_ID
	JOIN BRAND_MASTER BM ON BM.BRAND_MASTER_SID = IM.BRAND_MASTER_SID
	
	UNION ALL
	
	SELECT IWA.IVLD_INVENTORY_WD_ACTUAL_MAS_SID AS INVENTORY_WD_ACTUAL_PROJ_MAS_SID
		,IWA.INVENTORY_WD_ACT_MAS_INTF_ID AS INVENTORY_WD_ACTUAL_PROJ_MAS_INTF_ID
		,IWA.YEAR
		,IWA.MONTH
		,IWA.DAY
		,IWA.WEEK
		,COMPANY_ID
		,COMPANY_NAME
		,BM.BRAND_ID
		,BM.BRAND_NAME
		,IWA.ITEM_ID
		,IM.ITEM_NAME
		,IWA.UNITS_WITHDRAWN
		,IWA.AMOUNT_WITHDRAWN
		,IWA.UNITS_ON_HAND
		,IWA.AMOUNT_ON_HAND
		,IWA.QUANTITY_ON_ORDER
		,IWA.AMOUNT_ON_ORDER
		,IWA.QUANTITY_RECEIVED
		,IWA.AMOUNT_RECEIVED
		,NULL PRICE
		,IWA.CREATED_BY
		,IWA.CREATED_DATE
		,IWA.MODIFIED_BY
		,IWA.MODIFIED_DATE
		,IWA.ADD_CHG_DEL_INDICATOR
		,IWA.BATCH_ID
		,IWA.SOURCE
		,NULL FORECAST_NAME
		,NULL FORECAST_VER
		,IWA.COUNTRY
		,IWA.ORGANIZATION_KEY
		,IWA.INTF_INSERTED_DATE
		,IWA.REASON_FOR_FAILURE
		,IWA.ERROR_CODE
		,IWA.ERROR_FIELD
		,IWA.REPROCESSED_FLAG
		,0 AS IS_FORECAST
		,1 AS IS_MASTER
		,'Actuals' AS INVENTORY_TYPE
		,'Summary' AS INVENTORY_LEVEL
		,IWA.CHECK_RECORD
	FROM IVLD_INVENTORY_WD_ACTUAL_MAS IWA
	JOIN COMPANY_MASTER CM ON CM.COMPANY_ID = IWA.ORGANIZATION_KEY
	JOIN ITEM_MASTER IM ON IM.ITEM_ID = IWA.ITEM_ID
	JOIN BRAND_MASTER BM ON BM.BRAND_MASTER_SID = IM.BRAND_MASTER_SID
	
	UNION ALL
	
	SELECT IVLD_INVENTORY_WD_ACTUAL_DT_SID AS INVENTORY_WD_ACTUAL_PROJ_MAS_SID
		,INVENTORY_WD_ACTUAL_DT_INTF_ID AS INVENTORY_WD_ACTUAL_PROJ_MAS_INTF_ID
		,YEAR
		,MONTH
		,DAY
		,WEEK
		,CM.COMPANY_ID
		,COMPANY_NAME
		,BM.BRAND_ID
		,BM.BRAND_NAME
		,IWA.ITEM_ID
		,IM.ITEM_NAME
		,UNITS_WITHDRAWN
		,AMOUNT_WITHDRAWN
		,UNITS_ON_HAND
		,AMOUNT_ON_HAND
		,QUANTITY_ON_ORDER
		,AMOUNT_ON_ORDER
		,QUANTITY_RECEIVED
		,AMOUNT_RECEIVED
		,NULL PRICE
		,IWA.CREATED_BY
		,IWA.CREATED_DATE
		,IWA.MODIFIED_BY
		,IWA.MODIFIED_DATE
		,ADD_CHG_DEL_INDICATOR
		,IWA.BATCH_ID
		,IWA.SOURCE
		,NULL FORECAST_NAME
		,NULL FORECAST_VER
		,IWA.COUNTRY
		,IWA.ORGANIZATION_KEY
		,INTF_INSERTED_DATE
		,REASON_FOR_FAILURE
		,ERROR_CODE
		,ERROR_FIELD
		,REPROCESSED_FLAG
		,0 AS IS_FORECAST
		,0 AS IS_MASTER
		,'Actuals' AS INVENTORY_TYPE
		,'Details' AS INVENTORY_LEVEL
		,IWA.CHECK_RECORD
	FROM IVLD_INVENTORY_WD_ACTUAL_DT IWA
	JOIN COMPANY_MASTER CM ON CM.COMPANY_ID = IWA.COMPANY_ID
	JOIN ITEM_MASTER IM ON IM.ITEM_ID = IWA.ITEM_ID
	JOIN BRAND_MASTER BM ON BM.BRAND_MASTER_SID = IM.BRAND_MASTER_SID
	
	UNION ALL
	
	SELECT IWP.IVLD_INVENTORY_WD_PROJ_DT_SID AS INVENTORY_WD_ACTUAL_PROJ_MAS_SID
		,IWP.INVENTORY_WD_PROJ_DT_INTF_ID AS INVENTORY_WD_ACTUAL_PROJ_MAS_INTF_ID
		,IWP.YEAR
		,IWP.MONTH
		,IWP.DAY
		,IWP.WEEK
		,CM.COMPANY_ID
		,COMPANY_NAME
		,BM.BRAND_ID
		,BM.BRAND_NAME
		,IWP.ITEM_ID
		,IM.ITEM_NAME
		,IWP.UNITS_WITHDRAWN
		,IWP.AMOUNT_WITHDRAWN
		,NULL AS UNITS_ON_HAND
		,NULL AS AMOUNT_ON_HAND
		,NULL AS QUANTITY_ON_ORDER
		,NULL AS AMOUNT_ON_ORDER
		,NULL AS QUANTITY_RECEIVED
		,NULL AS AMOUNT_RECEIVED
		,PRICE
		,IWP.CREATED_BY
		,IWP.CREATED_DATE
		,IWP.MODIFIED_BY
		,IWP.MODIFIED_DATE
		,IWP.ADD_CHG_DEL_INDICATOR
		,IWP.BATCH_ID
		,IWP.SOURCE
		,FORECAST_NAME
		,FORECAST_VER
		,IWP.COUNTRY
		,IWP.ORGANIZATION_KEY
		,IWP.INTF_INSERTED_DATE
		,IWP.REASON_FOR_FAILURE
		,IWP.ERROR_CODE
		,IWP.ERROR_FIELD
		,IWP.REPROCESSED_FLAG
		,1 AS IS_FORECAST
		,0 AS IS_MASTER
		,'Projections' AS INVENTORY_TYPE
		,'Details' AS INVENTORY_LEVEL
		,IWP.CHECK_RECORD
	FROM IVLD_INVENTORY_WD_PROJ_DT IWP
	JOIN COMPANY_MASTER CM ON CM.COMPANY_ID = IWP.COMPANY_ID
	JOIN ITEM_MASTER IM ON IM.ITEM_ID = IWP.ITEM_ID
	JOIN BRAND_MASTER BM ON BM.BRAND_MASTER_SID = IM.BRAND_MASTER_SID
	) A

GO


