IF EXISTS (SELECT 'X'
           FROM   INFORMATION_SCHEMA.VIEWS
           WHERE  TABLE_NAME = 'VW_IVLD_INVENTORY_WD_ACTUAL_PROJ_MAS'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      DROP VIEW [DBO].[VW_IVLD_INVENTORY_WD_ACTUAL_PROJ_MAS]
  END

GO


CREATE VIEW [dbo].[VW_IVLD_INVENTORY_WD_ACTUAL_PROJ_MAS]
AS
  SELECT IWP.IVLD_INVENTORY_WD_PROJ_MAS_SID AS IVLD_INVENTORY_WD_ACTUAL_PROJ_MAS_SID,
         IWP.INVENTORY_WD_PROJ_MAS_INTF_ID  AS INVENTORY_WD_ACTUAL_PROJ_MAS_INTF_ID,
         IWP.YEAR,
         IWP.MONTH,
         IWP.DAY,
         IWP.WEEK,
         COMPANY_ID,
         COMPANY_NAME,
         IWP.ITEM_ID,
         IM.ITEM_NAME,
         IWP.UNITS_WITHDRAWN,
         IWP.AMOUNT_WITHDRAWN,
         UNITS_ON_HAND = NULL,
         AMOUNT_ON_HAND = NULL,
         QUANTITY_ON_ORDER = NULL,
         AMOUNT_ON_ORDER = NULL,
         QUANTITY_RECEIVED = NULL,
         AMOUNT_RECEIVED = NULL,
         PRICE,
         IWP.CREATED_BY,
         IWP.CREATED_DATE,
         IWP.MODIFIED_BY,
         IWP.MODIFIED_DATE,
         IWP.ADD_CHG_DEL_INDICATOR,
         IWP.BATCH_ID,
         IWP.SOURCE,
         FORECAST_NAME,
         FORECAST_VER,
         IWP.COUNTRY,
         IWP.ORGANIZATION_KEY,
         IWP.INTF_INSERTED_DATE,
         IWP.REASON_FOR_FAILURE,
         IWP.ERROR_CODE,
         IWP.ERROR_FIELD,
         IWP.REPROCESSED_FLAG,
         1                                  AS IS_FORECAST,
         1                                  AS IS_MASTER
  FROM   IVLD_INVENTORY_WD_PROJ_MAS IWP
         JOIN COMPANY_MASTER CM
           ON CM.COMPANY_ID = IWP.ORGANIZATION_KEY
         JOIN ITEM_MASTER IM
           ON IM.ITEM_ID = IWP.ITEM_ID
  UNION ALL
  SELECT IWA.IVLD_INVENTORY_WD_ACTUAL_MAS_SID,
         IWA.INVENTORY_WD_ACT_MAS_INTF_ID,
         IWA.YEAR,
         IWA.MONTH,
         IWA.DAY,
         IWA.WEEK,
         COMPANY_ID,
         COMPANY_NAME,
         IWA.ITEM_ID,
         IM.ITEM_NAME,
         IWA.UNITS_WITHDRAWN,
         IWA.AMOUNT_WITHDRAWN,
         IWA.UNITS_ON_HAND,
         IWA.AMOUNT_ON_HAND,
         IWA.QUANTITY_ON_ORDER,
         IWA.AMOUNT_ON_ORDER,
         IWA.QUANTITY_RECEIVED,
         IWA.AMOUNT_RECEIVED,
         PRICE = NULL,
         IWA.CREATED_BY,
         IWA.CREATED_DATE,
         IWA.MODIFIED_BY,
         IWA.MODIFIED_DATE,
         IWA.ADD_CHG_DEL_INDICATOR,
         IWA.BATCH_ID,
         IWA.SOURCE,
         FORECAST_NAME = NULL,
         FORECAST_VER = NULL,
         IWA.COUNTRY,
         IWA.ORGANIZATION_KEY,
         IWA.INTF_INSERTED_DATE,
         IWA.REASON_FOR_FAILURE,
         IWA.ERROR_CODE,
         IWA.ERROR_FIELD,
         IWA.REPROCESSED_FLAG,
         0 AS IS_FORECAST,
         1 AS IS_MASTER
  FROM   IVLD_INVENTORY_WD_ACTUAL_MAS IWA
         JOIN COMPANY_MASTER CM
           ON CM.COMPANY_ID = IWA.ORGANIZATION_KEY
         JOIN ITEM_MASTER IM
           ON IM.ITEM_ID = IWA.ITEM_ID
  UNION ALL
  SELECT IVLD_INVENTORY_WD_ACTUAL_DT_SID,
         INVENTORY_WD_ACTUAL_DT_INTF_ID,
         YEAR,
         MONTH,
         DAY,
         WEEK,
         CM.COMPANY_ID,
         COMPANY_NAME,
         IWA.ITEM_ID,
         IM.ITEM_NAME,
         UNITS_WITHDRAWN,
         AMOUNT_WITHDRAWN,
         UNITS_ON_HAND,
         AMOUNT_ON_HAND,
         QUANTITY_ON_ORDER,
         AMOUNT_ON_ORDER,
         QUANTITY_RECEIVED,
         AMOUNT_RECEIVED,
         PRICE = NULL,
         IWA.CREATED_BY,
         IWA.CREATED_DATE,
         IWA.MODIFIED_BY,
         IWA.MODIFIED_DATE,
         ADD_CHG_DEL_INDICATOR,
         IWA.BATCH_ID,
         IWA.SOURCE,
         FORECAST_NAME = NULL,
         FORECAST_VER = NULL,
         IWA.COUNTRY,
         IWA.ORGANIZATION_KEY,
         INTF_INSERTED_DATE,
         REASON_FOR_FAILURE,
         ERROR_CODE,
         ERROR_FIELD,
         REPROCESSED_FLAG,
         0 AS IS_FORECAST,
         0 AS IS_MASTER
  FROM   IVLD_INVENTORY_WD_ACTUAL_DT IWA
         JOIN COMPANY_MASTER CM
           ON CM.COMPANY_ID = IWA.COMPANY_ID
         JOIN ITEM_MASTER IM
           ON IM.ITEM_ID = IWA.ITEM_ID
  UNION ALL
  SELECT IWP.IVLD_INVENTORY_WD_PROJ_DT_SID,
         IWP.INVENTORY_WD_PROJ_DT_INTF_ID,
         IWP.YEAR,
         IWP.MONTH,
         IWP.DAY,
         IWP.WEEK,
         CM.COMPANY_ID,
         COMPANY_NAME,
         IWP.ITEM_ID,
         IM.ITEM_NAME,
         IWP.UNITS_WITHDRAWN,
         IWP.AMOUNT_WITHDRAWN,
         UNITS_ON_HAND = NULL,
         AMOUNT_ON_HAND = NULL,
         QUANTITY_ON_ORDER = NULL,
         AMOUNT_ON_ORDER = NULL,
         QUANTITY_RECEIVED = NULL,
         AMOUNT_RECEIVED = NULL,
         PRICE,
         IWP.CREATED_BY,
         IWP.CREATED_DATE,
         IWP.MODIFIED_BY,
         IWP.MODIFIED_DATE,
         IWP.ADD_CHG_DEL_INDICATOR,
         IWP.BATCH_ID,
         IWP.SOURCE,
         FORECAST_NAME,
         FORECAST_VER,
         IWP.COUNTRY,
         IWP.ORGANIZATION_KEY,
         IWP.INTF_INSERTED_DATE,
         IWP.REASON_FOR_FAILURE,
         IWP.ERROR_CODE,
         IWP.ERROR_FIELD,
         IWP.REPROCESSED_FLAG,
         1 AS IS_FORECAST,
         0 AS IS_MASTER
  FROM   IVLD_INVENTORY_WD_PROJ_DT IWP
         JOIN COMPANY_MASTER CM
           ON CM.COMPANY_ID = IWP.COMPANY_ID
         JOIN ITEM_MASTER IM
           ON IM.ITEM_ID = IWP.ITEM_ID


GO


