-----------------------------f.k's for FORECASTING_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'FORECASTING_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FORECASTING_MASTER_COMPANY_MASTER_BUSINESS_UNIT'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE FORECASTING_MASTER
        ADD CONSTRAINT FK_FORECASTING_MASTER_COMPANY_MASTER_BUSINESS_UNIT  FOREIGN KEY(BUSINESS_UNIT) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO
------------------------f.k's for DEMAND_FORECAST
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'DEMAND_FORECAST'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_DEMAND_FORECAST_COMPANY_MASTER_BUSINESS_UNIT'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE DEMAND_FORECAST
        ADD CONSTRAINT FK_DEMAND_FORECAST_COMPANY_MASTER_BUSINESS_UNIT  FOREIGN KEY(BUSINESS_UNIT) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO
--------------------f.k's for ADJUSTED_DEMAND_FORECAST
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ADJUSTED_DEMAND_FORECAST'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ADJUSTED_DEMAND_FORECAST_COMPANY_MASTER_BUSINESS_UNIT'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ADJUSTED_DEMAND_FORECAST
        ADD CONSTRAINT FK_ADJUSTED_DEMAND_FORECAST_COMPANY_MASTER_BUSINESS_UNIT  FOREIGN KEY(BUSINESS_UNIT) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO
---------------------------f.k's for CUSTOMER_GTS_FORECAST
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CUSTOMER_GTS_FORECAST'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CUSTOMER_GTS_FORECAST_COMPANY_MASTER_BUSINESS_UNIT'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CUSTOMER_GTS_FORECAST
        ADD CONSTRAINT FK_CUSTOMER_GTS_FORECAST_COMPANY_MASTER_BUSINESS_UNIT  FOREIGN KEY(BUSINESS_UNIT) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO
--------------------------f.k's for INVENTORY_WD_PROJ_DT
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'INVENTORY_WD_PROJ_DT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_INVENTORY_WD_PROJ_DT_COMPANY_MASTER_BUSINESS_UNIT'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE INVENTORY_WD_PROJ_DT
        ADD CONSTRAINT FK_INVENTORY_WD_PROJ_DT_COMPANY_MASTER_BUSINESS_UNIT  FOREIGN KEY(BUSINESS_UNIT) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO
------------------------f.k's for INVENTORY_WD_PROJ_MAS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'INVENTORY_WD_PROJ_MAS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_INVENTORY_WD_PROJ_MAS_COMPANY_MASTER_BUSINESS_UNIT'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE INVENTORY_WD_PROJ_MAS
        ADD CONSTRAINT FK_INVENTORY_WD_PROJ_MAS_COMPANY_MASTER_BUSINESS_UNIT  FOREIGN KEY(BUSINESS_UNIT) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO