IF EXISTS (SELECT 'X'
           FROM   INFORMATION_SCHEMA.VIEWS
           WHERE  TABLE_NAME = 'VW_ADJUST_DEMAND_FORECAST_ACT'
                  AND TABLE_SCHEMA = 'dbo')
  BEGIN
      DROP VIEW [dbo].[VW_ADJUST_DEMAND_FORECAST_ACT]
  END

GO

CREATE VIEW [dbo].[VW_ADJUST_DEMAND_FORECAST_ACT]
AS

SELECT      ADF.ADJUSTED_DEMAND_FORECAST_SID AS ADJUSTED_DEMAND_FORECAST_ID,
            ADF.FORECAST_NAME,
            ADF.FORECAST_TYPE,
            ADF.FORECAST_VER,
            ADF.YEAR  AS FORECAST_YEAR,
            ADF.MONTH AS FORECAST_MONTH,
            ADF.ITEM_ID,
            IM.ITEM_NAME,
            ADF.BRAND_ID,
            BM.BRAND_NAME,
            ADF.SEGMENT,
            ADF.MARKET_SIZE_UNITS,
            ADF.MARKET_SHARE_RATIO,
            ADF.MARKET_SHARE_UNITS,
            ADF.UNCAPTURED_UNITS,
            ADF.UNCAPTURED_UNITS_RATIO,
            ADF.TOTAL_DEMAND_UNITS,
            ADF.TOTAL_DEMAND_AMOUNT,
            ADF.INVENTORY_UNIT_CHANGE,
            ADF.GROSS_UNITS,
            ADF.GROSS_PRICE,
            ADF.GROSS_AMOUNT,
            ADF.NET_SALES_PRICE,
            ADF.NET_SALES_AMOUNT,
            CM.COMPANY_NO                BUSINESS_UNIT_NO,
            CM.COMPANY_NAME              BUSINESS_UNIT_NAME,
            ADF.BATCH_ID,
            ADF.SOURCE,
            ADF.COUNTRY,
            ADF.ORGANIZATION_KEY,
            1                            AS IS_FORECAST,
			(select HELPER_TABLE_SID from HELPER_TABLE where list_name ='FORECAST_TYPE' and description='projections') as FORECAST_TYPE_SID
  FROM      dbo.ADJUSTED_DEMAND_FORECAST ADF
  LEFT JOIN dbo.BRAND_MASTER BM ON BM.BRAND_ID = ADF.BRAND_ID
  LEFT JOIN dbo.COMPANY_MASTER CM ON CM.COMPANY_ID = ADF.ORGANIZATION_KEY
  LEFT JOIN dbo.ITEM_MASTER IM ON IM.ITEM_ID = ADF.ITEM_ID
  WHERE ADF.INBOUND_STATUS<>'D'
  UNION ALL
  SELECT    ADF.ADJUSTED_DEMAND_ACTUAL_SID AS ADJUSTED_DEMAND_FORECAST_ID,
            NULL                       FORECAST_NAME,
            ADF.FORECAST_TYPE,
            NULL                       FORECAST_VER,
            ADF.FORECAST_YEAR,
            ADF.FORECAST_MONTH,
            ADF.ITEM_ID,
            IM.ITEM_NAME,
            ADF.BRAND_ID,
            BM.BRAND_NAME,
            ADF.SEGMENT,
            ADF.MARKET_SIZE_UNITS,
            ADF.MARKET_SHARE_RATIO,
            ADF.MARKET_SHARE_UNITS,
            NULL                       UNCAPTURED_UNITS,
            NULL                       UNCAPTURED_UNITS_RATIO,
            ADF.TOTAL_DEMAND_UNITS,
            ADF.TOTAL_DEMAND_AMOUNT,
            NULL                       AS INVENTORY_UNIT_CHANGE,
            ADF.GROSS_UNITS,
            ADF.GROSS_PRICE,
            ADF.GROSS_AMOUNT,
            ADF.NET_SALES_PRICE,
            ADF.NET_SALES_AMOUNT,
            CM.COMPANY_NO              BUSINESS_UNIT_NO,
            CM.COMPANY_NAME            BUSINESS_UNIT_NAME,
            ADF.BATCH_ID,
            ADF.SOURCE,
            ADF.COUNTRY,
            ADF.ORGANIZATION_KEY,
            0                          AS IS_FORECAST,
			(select HELPER_TABLE_SID from HELPER_TABLE where list_name ='FORECAST_TYPE' and description='Actuals') as FORECAST_TYPE_SID
  FROM      dbo.ADJUSTED_DEMAND_ACTUAL ADF
  LEFT JOIN dbo.BRAND_MASTER BM ON BM.BRAND_ID = ADF.BRAND_ID
  LEFT JOIN dbo.COMPANY_MASTER CM ON CM.COMPANY_ID = ADF.ORGANIZATION_KEY
  LEFT JOIN dbo.ITEM_MASTER IM ON IM.ITEM_ID = ADF.ITEM_ID
  WHERE ADF.INBOUND_STATUS<>'D'


GO 