IF EXISTS (SELECT
    'X'
  FROM INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_NAME = 'VW_COMPANY_IDENTIFIER'
  AND TABLE_SCHEMA = 'dbo')
BEGIN
  DROP VIEW [dbo].VW_COMPANY_IDENTIFIER
END
GO

CREATE VIEW [dbo].[VW_COMPANY_IDENTIFIER]
AS
SELECT
  CI.COMPANY_IDENTIFIER_SID,
  CM.COMPANY_ID,
  CM.COMPANY_NO,
  CM.COMPANY_NAME,
  CQ.COMPANY_QUALIFIER_VALUE IDENTIFIER_CODE_QUALIFIER,
  CQ.COMPANY_QUALIFIER_NAME IDENTIFIER_CODE_QUALIFIER_NAME,
  CI.COMPANY_IDENTIFIER_VALUE COMPANY_IDENTIFIER,
  HT.DESCRIPTION IDENTIFIER_STATUS,
  CI.START_DATE,
  CI.END_DATE,
  CI.ENTITY_CODE,
  CI.SOURCE,
  CI.CREATED_BY,
  CI.CREATED_DATE,
  CI.MODIFIED_BY,
  CI.MODIFIED_DATE,
  CI.INBOUND_STATUS ADD_CHG_DEL_INDICATOR,
  CI.BATCH_ID
FROM dbo.COMPANY_IDENTIFIER CI
JOIN dbo.COMPANY_MASTER CM
  ON CM.COMPANY_MASTER_SID = CI.COMPANY_MASTER_SID
JOIN dbo.COMPANY_QUALIFIER CQ
  ON CQ.COMPANY_QUALIFIER_SID = CI.COMPANY_QUALIFIER_SID
LEFT JOIN dbo.HELPER_TABLE HT
  ON HT.HELPER_TABLE_SID = CI.IDENTIFIER_STATUS
WHERE CI.INBOUND_STATUS <> 'D'
AND CM.INBOUND_STATUS <> 'D'
AND CQ.INBOUND_STATUS <> 'D'

GO