IF EXISTS (SELECT
    'X'
  FROM INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_NAME = 'VW_COMPANY_MASTER'
  AND TABLE_SCHEMA = 'dbo')
BEGIN
  DROP VIEW [dbo].[VW_COMPANY_MASTER]
END

GO

CREATE VIEW [dbo].[VW_COMPANY_MASTER]
AS
SELECT
  CM.COMPANY_MASTER_SID,
  CM.COMPANY_ID,
  CM.COMPANY_NO,
  CM.COMPANY_NAME,
  CASE
    WHEN HT9.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT9.DESCRIPTION
  END COMPANY_TYPE,
  CASE
    WHEN HT10.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT10.DESCRIPTION
  END COMPANY_CATEGORY,
  CASE
    WHEN HT11.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT11.DESCRIPTION
  END COMPANY_GROUP,
  CASE
    WHEN HT12.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT12.DESCRIPTION
  END COMPANY_STATUS,
  CASE
    WHEN HT13.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT13.DESCRIPTION
  END ORGANIZATION_KEY,
  CM.COMPANY_START_DATE,
  CM.COMPANY_END_DATE,
  CM.LIVES,
  CM.ADDRESS1,
  CM.ADDRESS2,
  CM.CITY,
  CASE
    WHEN HT14.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT14.DESCRIPTION
  END STATE,
  CM.ZIP_CODE,
  CM.REGION_CODE,
  CASE
    WHEN HT15.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT15.DESCRIPTION
  END COUNTRY,
  CM.FINANCIAL_SYSTEM,
  CASE
    WHEN HT3.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT3.DESCRIPTION
  END UDC1,
  CASE
    WHEN HT4.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT4.DESCRIPTION
  END UDC2,
  CASE
    WHEN HT5.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT5.DESCRIPTION
  END UDC3,
  CASE
    WHEN HT6.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT6.DESCRIPTION
  END UDC4,
  CASE
    WHEN HT7.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT7.DESCRIPTION
  END UDC5,
  CASE
    WHEN HT8.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT8.DESCRIPTION
  END UDC6,
  CM.LAST_UPDATED_DATE,
  CM.SOURCE,
  CM.CREATED_BY,
  CM.CREATED_DATE,
  CM.MODIFIED_BY,
  CM.MODIFIED_DATE,
  CM.INBOUND_STATUS AS ADD_CHG_DEL_INDICATOR,
  CM.BATCH_ID
FROM dbo.COMPANY_MASTER CM
LEFT JOIN dbo.UDCS UD
  ON CM.COMPANY_MASTER_SID = UD.MASTER_SID
  AND UD.MASTER_TYPE = 'COMPANY_MASTER'
LEFT JOIN dbo.HELPER_TABLE HT3
  ON HT3.HELPER_TABLE_SID = UD.UDC1
LEFT JOIN dbo.HELPER_TABLE HT4
  ON HT4.HELPER_TABLE_SID = UD.UDC2
LEFT JOIN dbo.HELPER_TABLE HT5
  ON HT5.HELPER_TABLE_SID = UD.UDC3
LEFT JOIN dbo.HELPER_TABLE HT6
  ON HT6.HELPER_TABLE_SID = UD.UDC4
LEFT JOIN dbo.HELPER_TABLE HT7
  ON HT7.HELPER_TABLE_SID = UD.UDC5
LEFT JOIN dbo.HELPER_TABLE HT8
  ON HT8.HELPER_TABLE_SID = UD.UDC6
LEFT JOIN dbo.HELPER_TABLE HT9
  ON HT9.HELPER_TABLE_SID = CM.COMPANY_TYPE
LEFT JOIN dbo.HELPER_TABLE HT10
  ON HT10.HELPER_TABLE_SID = CM.COMPANY_CATEGORY
LEFT JOIN dbo.HELPER_TABLE HT11
  ON HT11.HELPER_TABLE_SID = CM.COMPANY_GROUP
LEFT JOIN dbo.HELPER_TABLE HT12
  ON HT12.HELPER_TABLE_SID = CM.COMPANY_STATUS
LEFT JOIN dbo.HELPER_TABLE HT13
  ON HT13.HELPER_TABLE_SID = CM.ORGANIZATION_KEY
LEFT JOIN dbo.HELPER_TABLE HT14
  ON HT14.HELPER_TABLE_SID = CM.STATE
LEFT JOIN dbo.HELPER_TABLE HT15
  ON HT15.HELPER_TABLE_SID = CM.COUNTRY
WHERE CM.INBOUND_STATUS <> 'D'

GO