IF EXISTS (SELECT 'X' 
           FROM   INFORMATION_SCHEMA.VIEWS 
           WHERE  TABLE_NAME = 'VW_CONTRACT_HEADER' 
                  AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      DROP VIEW [DBO].VW_CONTRACT_HEADER 
  END 

GO 

CREATE VIEW [DBO].VW_CONTRACT_HEADER 
AS 
  SELECT CNT.CONTRACT_MASTER_SID, 
         CNT.CONTRACT_ID, 
         CNT.CONTRACT_NO, 
         CNT.[CONTRACT_NAME], 
         CASE 
           WHEN CONT_TYPE.HELPER_TABLE_SID = 0 THEN '' 
           ELSE CONT_TYPE.DESCRIPTION 
         END              AS CONTRACT_TYPE, 
         CASE 
           WHEN CONT_STATUS.HELPER_TABLE_SID = 0 THEN '' 
           ELSE CONT_STATUS.DESCRIPTION 
         END              AS CONTRACT_STATUS, 
         CNT.[START_DATE], 
         CNT.END_DATE, 
         CASE 
           WHEN CONT_TRADE_CLASS.HELPER_TABLE_SID = 0 THEN '' 
           ELSE CONT_TRADE_CLASS.DESCRIPTION 
         END              AS TRADE_CLASS, 
         CNT.ORGANIZATION_KEY,
		 DOC_TYPE.DESCRIPTION AS DOC_TYPE,
		 DOC_CLASS.DESCRIPTION AS DOC_CLASS,
         CNT.TERM, 
         CNT.RENEGOTIATION_START_DATE, 
         CNT.RENEGOTIATION_END_DATE, 
         CNT.PRICEPROTECTION_START_DATE, 
         CNT.PRICEPROTECTION_END_DATE, 
         CNT.ADVANCE_NOTICE_DAYS, 
         CNT.INSIDE_OWNER, 
         CNT.INSIDE_PHONE, 
         CNT.INSIDE_AUTHOR, 
         CNT.INSIDE_ADDITIONAL, 
         CNT.INSIDE_ADDITIONAL_NAME, 
         CNT.INSIDE_ADDITIONAL_PHONE, 
         CNT.OUTSIDE_OWNER, 
         CNT.OUTSIDE_PHONE, 
         CNT.OUTSIDE_AUTHOR, 
         CNT.OUTSIDE_ADDITIONAL, 
         CNT.OUTSIDE_ADDITIONAL_NAME, 
         CNT.OUTSIDE_ADDITIONAL_PHONE, 
         CNT.AFFILIATED_CONTRACT_INFO, 
         CNT.SHIPPING_TERMS, 
         CNT.PROPOSAL_START_DATE, 
         CNT.PROPOSAL_END_DATE, 
         CNT.ORIGINAL_START_DATE, 
         CNT.ORIGINAL_END_DATE, 
         CASE 
           WHEN AWA_STATUS.HELPER_TABLE_SID = 0 THEN '' 
           ELSE AWA_STATUS.DESCRIPTION 
         END              AS AWARD_STATUS, 
         CNT.LAST_UPDATED_DATE, 
         CNT.PRICE_ESCALATION_CLAUSE, 
         CNT.EXEMPT_FROM_LOW_PRICE, 
         CASE 
           WHEN PRI.HELPER_TABLE_SID = 0 THEN '' 
           ELSE PRI.DESCRIPTION 
         END              AS PRICE_RESET_INDICATOR, 
         CNT.CANCELLATION_CLAUSE, 
         CNT.MOST_FAVORED_NATION, 
         CNT.CATEGORY, 
         CNT.CURRENCY, 
         CNT.MINIMUM_ORDER, 
         CASE 
           WHEN PT.HELPER_TABLE_SID = 0 THEN '' 
           ELSE PT.DESCRIPTION 
         END              AS PAYMENT_TERMS, 
         CNT.BATCH_ID, 
         CNT.SOURCE, 
         CNT.CREATED_BY, 
         CNT.CREATED_DATE, 
         CNT.MODIFIED_BY, 
         CNT.MODIFIED_DATE, 
         CM1.COMPANY_NO   AS COMPANY_NO, 
         CM1.COMPANY_NAME AS COMPANY_NAME, 
         CM2.COMPANY_NO   AS TRADING_PARTNER_NO, 
         CM2.COMPANY_NAME AS TRADING_PARTNER_NAME 
  FROM   CONTRACT_MASTER CNT 
         LEFT JOIN dbo.COMPANY_MASTER CM1 
                ON CM1.COMPANY_MASTER_SID = CNT.BUNIT_COMPANY_MASTER_SID 
                   AND CM1.INBOUND_STATUS <> 'D' 
         LEFT JOIN dbo.COMPANY_MASTER CM2 
                ON CM2.COMPANY_MASTER_SID = CNT.CONT_HOLD_COMPANY_MASTER_SID 
                   AND CM2.INBOUND_STATUS <> 'D' 
         LEFT JOIN dbo.HELPER_TABLE CONT_TYPE 
                ON CONT_TYPE.HELPER_TABLE_SID = CNT.CONTRACT_TYPE 
         LEFT JOIN dbo.HELPER_TABLE CONT_STATUS 
                ON CONT_STATUS.HELPER_TABLE_SID = CNT.CONTRACT_STATUS 
         LEFT JOIN dbo.HELPER_TABLE CONT_TRADE_CLASS 
                ON CONT_TRADE_CLASS.HELPER_TABLE_SID = CNT.CONTRACT_TRADE_CLASS 
         LEFT JOIN dbo.HELPER_TABLE DOC_TYPE 
                ON DOC_TYPE.HELPER_TABLE_SID = CNT.DOCUMENT_TYPE 
         LEFT JOIN dbo.HELPER_TABLE DOC_CLASS 
                ON DOC_CLASS.HELPER_TABLE_SID = CNT.DOCUMENT_CLASS 
         LEFT JOIN dbo.HELPER_TABLE AWA_STATUS 
                ON AWA_STATUS.HELPER_TABLE_SID = CNT.AWARD_STATUS 
         LEFT JOIN dbo.HELPER_TABLE PRI 
                ON PRI.HELPER_TABLE_SID = CNT.PRICE_RESET_INDICATOR 
         LEFT JOIN dbo.HELPER_TABLE PT 
                ON PT.HELPER_TABLE_SID = CNT.PAYMENT_TERMS 
  WHERE  CNT.INBOUND_STATUS <> 'D' 

GO 