IF EXISTS (SELECT
    'X'
  FROM INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_NAME = 'VW_COMPANY_TRADE_CLASS'
  AND TABLE_SCHEMA = 'dbo')
BEGIN
  DROP VIEW [dbo].VW_COMPANY_TRADE_CLASS
END
GO

CREATE VIEW [dbo].[VW_COMPANY_TRADE_CLASS]
AS
SELECT
  CTC.COMPANY_TRADE_CLASS_SID,
  CM.COMPANY_ID,
  CASE
    WHEN HT.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT.DESCRIPTION
  END COMPANY_TRADE_CLASS,
  CTC.TRADE_CLASS_START_DATE,
  CTC.TRADE_CLASS_END_DATE,
  CASE
    WHEN HT1.HELPER_TABLE_SID = 0 THEN ''
    ELSE HT1.DESCRIPTION
  END PRIOR_TRADE_CLASS,
  CTC.PRIOR_TRADE_CLASS_START_DATE,
  CTC.LAST_UPDATED_DATE,
  CTC.SOURCE,
  CTC.INBOUND_STATUS ADD_CHG_DEL_INDICATOR,
  CTC.CREATED_BY,
  CTC.CREATED_DATE,
  CTC.MODIFIED_BY,
  CTC.MODIFIED_DATE,
  CTC.BATCH_ID
FROM dbo.COMPANY_TRADE_CLASS CTC
JOIN dbo.COMPANY_MASTER CM
  ON CM.COMPANY_MASTER_SID = CTC.COMPANY_MASTER_SID
LEFT JOIN dbo.HELPER_TABLE HT
  ON HT.HELPER_TABLE_SID = CTC.COMPANY_TRADE_CLASS
LEFT JOIN dbo.HELPER_TABLE HT1
  ON HT1.HELPER_TABLE_SID = CTC.PRIOR_TRADE_CLASS
WHERE CM.INBOUND_STATUS <> 'D'
AND CTC.INBOUND_STATUS <> 'D'

GO