IF EXISTS (SELECT
    'X'
  FROM INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_NAME = 'VW_CUSTOMER_GTS_FORECAST'
  AND TABLE_SCHEMA = 'dbo')
BEGIN
  DROP VIEW [dbo].[VW_CUSTOMER_GTS_FORECAST]
END

GO

CREATE VIEW [dbo].[VW_CUSTOMER_GTS_FORECAST]
AS
SELECT
  CGT.CUSTOMER_GTS_FORECAST_SID,
  CGT.FORECAST_YEAR,
  CGT.FORECAST_MONTH,
  CGT.ITEM_ID,
  CGT.COMPANY_ID,
  CGT.UNITS,
  CGT.PRICE_TYPE,
  CGT.PRICE,
  CGT.SALES_AMOUNT,
  CGT.SALES_INCLUSION,
  CGT.DEDUCTION_ID,
  HT.DESCRIPTION AS DEDUCTION_CATEGORY,
  HT1.DESCRIPTION AS DEDUCTION_TYPE,
  HT2.DESCRIPTION AS DEDUCTION_PROGRAM_TYPE,
  CGT.ADJUSTMENT_CODE,
  CGT.DEDUCTION_RATE,
  CGT.DEDUCTION_AMOUNT,
  CGT.DEDUCTION_INCLUSION,
  CGT.FORECAST_VALUE_TYPE,
  CGT.BRAND,
  CGT.SEGMENT,
  CGT.ADD_CHG_DEL_INDICATOR,
  U.UDC1,
  U.UDC2,
  U.UDC3,
  U.UDC4,
  U.UDC5,
  U.UDC6,
  CGT.CREATED_BY,
  CGT.CREATED_DATE,
  CGT.MODIFIED_BY,
  CGT.MODIFIED_DATE,
  CGT.BATCH_ID,
  CGT.SOURCE,
  CGT.FORECAST_VER,
  CGT.COUNTRY,
  CGT.FORECAST_NAME,
  CGT.FORECAST_DATE,
  CGT.CUSTOMER_GTS_FORECAST_INTF_ID
FROM dbo.CUSTOMER_GTS_FORECAST CGT
LEFT JOIN dbo.ITEM_MASTER IM
  ON IM.ITEM_ID = CGT.ITEM_ID
LEFT JOIN dbo.BRAND_MASTER BM
  ON BM.BRAND_MASTER_SID = IM.BRAND_MASTER_SID
LEFT JOIN dbo.COMPANY_MASTER CM
  ON CM.COMPANY_ID = CGT.COMPANY_ID
LEFT JOIN dbo.UDCS U
  ON U.MASTER_SID = CGT.CUSTOMER_GTS_FORECAST_SID
  AND U.master_type = 'CUSTOMER_GTS_FORECAST'
LEFT JOIN dbo.HELPER_TABLE HT
  ON HT.HELPER_TABLE_SID = CGT.DEDUCTION_CATEGORY
LEFT JOIN dbo.HELPER_TABLE HT1
  ON HT1.HELPER_TABLE_SID = CGT.DEDUCTION_TYPE
LEFT JOIN dbo.HELPER_TABLE HT2
  ON HT2.HELPER_TABLE_SID = CGT.DEDUCTION_PROGRAM_TYPE
GO