IF EXISTS (SELECT
    'X'
  FROM INFORMATION_SCHEMA.VIEWS
  WHERE TABLE_NAME = 'VW_COMPANY_PARENT_DETAILS'
  AND TABLE_SCHEMA = 'dbo')
BEGIN
  DROP VIEW [dbo].VW_COMPANY_PARENT_DETAILS
END
GO

CREATE VIEW [dbo].[VW_COMPANY_PARENT_DETAILS]
AS
SELECT
  CPD.COMPANY_PARENT_DETAILS_SID,
  CM.COMPANY_ID,
  PCM.COMPANY_ID PARENT_COMPANY_ID,
  CPD.PARENT_START_DATE,
  CPD.PARENT_END_DATE,
  CPD.PRIOR_PARENT_START_DATE,
  CPD.LAST_UPDATED_DATE,
  CPD.SOURCE,
  CPD.INBOUND_STATUS ADD_CHG_DEL_INDICATOR,
  CPD.CREATED_BY,
  CPD.CREATED_DATE,
  CPD.MODIFIED_BY,
  CPD.MODIFIED_DATE,
  PPCM.COMPANY_ID PRIOR_PARENT_COMPANY_ID,
  CPD.BATCH_ID
FROM dbo.COMPANY_PARENT_DETAILS CPD
LEFT JOIN dbo.COMPANY_MASTER CM
  ON CPD.COMPANY_MASTER_SID = CM.COMPANY_MASTER_SID
  AND CM.INBOUND_STATUS <> 'D'
LEFT JOIN dbo.COMPANY_MASTER PCM
  ON CPD.PARENT_COMPANY_MASTER_SID = PCM.COMPANY_MASTER_SID
  AND PCM.INBOUND_STATUS <> 'D'
LEFT JOIN dbo.COMPANY_MASTER PPCM
  ON CPD.PRIOR_PARENT_CMPY_MASTER_SID = PPCM.COMPANY_MASTER_SID
  AND PPCM.INBOUND_STATUS <> 'D'
WHERE CPD.INBOUND_STATUS <> 'D'
GO