IF EXISTS (SELECT 'X'
           FROM   INFORMATION_SCHEMA.VIEWS
           WHERE  TABLE_NAME = 'VW_ITEM_IDENTIFIER'
                  AND TABLE_SCHEMA = 'dbo')
  BEGIN
      DROP VIEW [dbo].VW_ITEM_IDENTIFIER
  END
GO
CREATE VIEW [dbo].[VW_ITEM_IDENTIFIER]
AS
SELECT ITEM_IDENTIFIER_SID
	,IM.ITEM_ID
	,IM.ITEM_NO
	,IM.ITEM_NAME
	,IQ.ITEM_QUALIFIER_VALUE IDENTIFIER_CODE_QUALIFIER
	,IQ.ITEM_QUALIFIER_NAME IDENTIFIER_CODE_QUALIFIER_NAME
	,ID.ITEM_IDENTIFIER_VALUE ITEM_IDENTIFIER
	,HT.DESCRIPTION ITEM_STATUS
	,ID.START_DATE
	,ID.END_DATE
	,ID.ENTITY_CODE
	,ID.SOURCE
	,ID.CREATED_BY
	,ID.CREATED_DATE
	,ID.MODIFIED_BY
	,ID.MODIFIED_DATE
	,ID.INBOUND_STATUS ADD_CHG_DEL_INDICATOR
	,ID.BATCH_ID
FROM ITEM_IDENTIFIER ID
JOIN ITEM_MASTER IM ON IM.ITEM_MASTER_SID = ID.ITEM_MASTER_SID
JOIN ITEM_QUALIFIER IQ ON IQ.ITEM_QUALIFIER_SID = ID.ITEM_QUALIFIER_SID
LEFT JOIN HELPER_TABLE HT ON HT.HELPER_TABLE_SID = ID.IDENTIFIER_STATUS
WHERE ID.INBOUND_STATUS <> 'D'
	AND IM.INBOUND_STATUS <> 'D'
	AND IQ.INBOUND_STATUS <> 'D'
GO


