IF EXISTS (SELECT 'X'
           FROM   INFORMATION_SCHEMA.VIEWS
           WHERE  TABLE_NAME = 'VW_IVLD_ADJ_DEMAND_FORE_ACTUAL'
                  AND TABLE_SCHEMA = 'dbo')
  BEGIN
      DROP VIEW [dbo].[VW_IVLD_ADJ_DEMAND_FORE_ACTUAL]
  END

GO

CREATE VIEW [dbo].[VW_IVLD_ADJ_DEMAND_FORE_ACTUAL]
AS
  SELECT    IVLD_ADJUSTED_DEMAND_FORECAST_SID,
            ADJUSTED_DEMAND_FORECAST_INTF_ID,
            FORECAST_NAME,
            FORECAST_TYPE,
            FORECAST_VER        AS FORECAST_VERSION,
            YEAR,
            MONTH,
            IM.ITEM_ID,
            IM.ITEM_NAME,
            ITEM_IDENTIFIER_CODE_QUALIFIER,
            ITEM_IDENTIFIER,
            BM.BRAND_ID,
            BM.BRAND_NAME,
            SEGMENT,
            MARKET_SIZE_UNITS,
            MARKET_SHARE_RATIO,
            MARKET_SHARE_UNITS,
            UNCAPTURED_UNITS,
            UNCAPTURED_UNITS_RATIO,
            TOTAL_DEMAND_UNITS  AS TOTAL_ADJUSTED_DEMAND_UNITS,
            TOTAL_DEMAND_AMOUNT AS TOTAL_ADJUSTED_DEMAND_AMOUNT,
            INVENTORY_UNIT_CHANGE,
            GROSS_UNITS,
            GROSS_PRICE,
            GROSS_AMOUNT,
            NET_SALES_PRICE,
            NET_SALES_AMOUNT,
            CM.COMPANY_NO       AS BUSINESS_UNIT_NO,
            CM.COMPANY_NAME     AS BUSINESS_UNIT_NAME,
            DF.BATCH_ID,
            DF.SOURCE,
            DF.COUNTRY,
            DF.ORGANIZATION_KEY,
            ERROR_CODE,
            REASON_FOR_FAILURE,
            ERROR_FIELD,
            REPROCESSED_FLAG,
            ADD_CHG_DEL_INDICATOR,
            DF.CREATED_BY,
            DF.CREATED_DATE,
            DF.MODIFIED_BY,
            DF.MODIFIED_DATE,
            1                   AS IS_FORECAST
			,DF.CHECK_RECORD
  FROM      IVLD_ADJUSTED_DEMAND_FORECAST DF
  LEFT JOIN ITEM_MASTER IM ON IM.ITEM_ID = DF.ITEM_ID
  LEFT JOIN BRAND_MASTER BM ON BM.BRAND_ID = DF.BRAND_ID
  LEFT JOIN COMPANY_MASTER CM ON CM.COMPANY_NO = DF.ORGANIZATION_KEY
  UNION ALL
  SELECT    IVLD_ADJUSTED_DEMAND_ACTUAL_SID,
            ADJUSTED_DEMAND_ACTUAL_INTF_ID,
            NULL                AS FORECAST_NAME,
            FORECAST_TYPE,
            NULL                AS FORECAST_VERSION,
            FORECAST_YEAR       AS YEAR,
            FORECAST_MONTH      AS MONTH,
            IM.ITEM_ID,
            IM.ITEM_NAME,
            ITEM_IDENTIFIER_CODE_QUALIFIER,
            ITEM_IDENTIFIER,
            BM.BRAND_ID,
            BM.BRAND_NAME,
            SEGMENT,
            MARKET_SIZE_UNITS,
            MARKET_SHARE_RATIO,
            MARKET_SHARE_UNITS,
            NULL                AS UNCAPTURED_UNITS,
            NULL                AS UNCAPTURED_UNITS_RATIO,
            TOTAL_DEMAND_UNITS  AS TOTAL_ADJUSTED_DEMAND_UNITS,
            TOTAL_DEMAND_AMOUNT AS TOTAL_ADJUSTED_DEMAND_AMOUNT,
            NULL                AS INVENTORY_UNIT_CHANGE,
            GROSS_UNITS,
            GROSS_PRICE,
            GROSS_AMOUNT,
            NET_SALES_PRICE,
            NET_SALES_AMOUNT,
            CM.COMPANY_NO       AS BUSINESS_UNIT_NO,
            CM.COMPANY_NAME     AS BUSINESS_UNIT_NAME,
            DF.BATCH_ID,
            DF.SOURCE,
            DF.COUNTRY,
            DF.ORGANIZATION_KEY,
            ERROR_CODE,
            REASON_FOR_FAILURE,
            ERROR_FIELD,
            REPROCESSED_FLAG,
            ADD_CHG_DEL_INDICATOR,
            DF.CREATED_BY,
            DF.CREATED_DATE,
            DF.MODIFIED_BY,
            DF.MODIFIED_DATE,
            0                   AS IS_FORECAST
			,DF.CHECK_RECORD
  FROM      IVLD_ADJUSTED_DEMAND_ACTUAL DF
  LEFT JOIN ITEM_MASTER IM ON IM.ITEM_ID = DF.ITEM_ID
  LEFT JOIN BRAND_MASTER BM ON BM.BRAND_ID = DF.BRAND_ID
  LEFT JOIN COMPANY_MASTER CM ON CM.COMPANY_NO = DF.ORGANIZATION_KEY

GO 
