IF EXISTS (SELECT 'X'
           FROM   INFORMATION_SCHEMA.VIEWS
           WHERE  TABLE_NAME = 'VW_IVLD_ADJ_DEMAND_FORE_ACTUAL'
                  AND TABLE_SCHEMA = 'dbo')
  BEGIN
      DROP VIEW [dbo].[VW_IVLD_ADJ_DEMAND_FORE_ACTUAL]
  END

GO


CREATE VIEW [dbo].[VW_IVLD_ADJ_DEMAND_FORE_ACTUAL]

AS
SELECT    DF.IVLD_ADJUSTED_DEMAND_FORECAST_SID,
            DF.ADJUSTED_DEMAND_FORECAST_INTF_ID,
            DF.FORECAST_NAME,
            DF.FORECAST_TYPE,
            DF.FORECAST_VER,   
            DF.YEAR AS FORECAST_YEAR,
            DF.MONTH AS FORECAST_MONTH,
            IM.ITEM_ID,
            IM.ITEM_NAME,
            DF.ITEM_IDENTIFIER_CODE_QUALIFIER,
            DF.ITEM_IDENTIFIER,
            BM.BRAND_ID,
            BM.BRAND_NAME,
            DF.SEGMENT,
            DF.MARKET_SIZE_UNITS,
            DF.MARKET_SHARE_RATIO,
            DF.MARKET_SHARE_UNITS,
            DF.UNCAPTURED_UNITS,
            DF.UNCAPTURED_UNITS_RATIO,
            DF.TOTAL_DEMAND_UNITS,
            DF.TOTAL_DEMAND_AMOUNT,
            DF.INVENTORY_UNIT_CHANGE,
            DF.GROSS_UNITS,
            DF.GROSS_PRICE,
            DF.GROSS_AMOUNT,
            DF.NET_SALES_PRICE,
            DF.NET_SALES_AMOUNT,
            CM.COMPANY_NO       AS BUSINESS_UNIT_NO,
            CM.COMPANY_NAME     AS BUSINESS_UNIT_NAME,
            DF.BATCH_ID,
            DF.SOURCE,
            DF.COUNTRY,
            DF.ORGANIZATION_KEY,
            DF.ERROR_CODE,
            DF.REASON_FOR_FAILURE,
            DF.ERROR_FIELD,
            DF.REPROCESSED_FLAG,
            DF.ADD_CHG_DEL_INDICATOR,
            DF.CREATED_BY,
            DF.CREATED_DATE,
            DF.MODIFIED_BY,
            DF.MODIFIED_DATE,
            1                   AS IS_FORECAST,
			DF.CHECK_RECORD,
			(select HELPER_TABLE_SID from HELPER_TABLE where list_name ='FORECAST_TYPE' and description='projections') as FORECAST_TYPE_SID
  FROM      dbo.IVLD_ADJUSTED_DEMAND_FORECAST DF
  LEFT JOIN dbo.ITEM_MASTER IM ON IM.ITEM_ID = DF.ITEM_ID
  LEFT JOIN dbo.BRAND_MASTER BM ON BM.BRAND_ID = DF.BRAND_ID
  LEFT JOIN dbo.COMPANY_MASTER CM ON CM.COMPANY_NO = DF.ORGANIZATION_KEY
  UNION ALL
  SELECT    DF.IVLD_ADJUSTED_DEMAND_ACTUAL_SID,
            DF.ADJUSTED_DEMAND_ACTUAL_INTF_ID,
            NULL                AS FORECAST_NAME,
            DF.FORECAST_TYPE,
			
            NULL                AS FORECAST_VER,
            DF.FORECAST_YEAR,
            DF.FORECAST_MONTH,
            IM.ITEM_ID,
            IM.ITEM_NAME,
            DF.ITEM_IDENTIFIER_CODE_QUALIFIER,
            DF.ITEM_IDENTIFIER,
            BM.BRAND_ID,
            BM.BRAND_NAME,
            DF.SEGMENT,
            DF.MARKET_SIZE_UNITS,
            DF.MARKET_SHARE_RATIO,
            DF.MARKET_SHARE_UNITS,
            NULL                AS UNCAPTURED_UNITS,
            NULL                AS UNCAPTURED_UNITS_RATIO,
            DF.TOTAL_DEMAND_UNITS,
            DF.TOTAL_DEMAND_AMOUNT,
            NULL                AS INVENTORY_UNIT_CHANGE,
            DF.GROSS_UNITS,
            DF.GROSS_PRICE,
            DF.GROSS_AMOUNT,
            DF.NET_SALES_PRICE,
            DF.NET_SALES_AMOUNT,
            CM.COMPANY_NO       AS BUSINESS_UNIT_NO,
            CM.COMPANY_NAME     AS BUSINESS_UNIT_NAME,
            DF.BATCH_ID,
            DF.SOURCE,
            DF.COUNTRY,
            DF.ORGANIZATION_KEY,
            DF.ERROR_CODE,
            DF.REASON_FOR_FAILURE,
            DF.ERROR_FIELD,
            DF.REPROCESSED_FLAG,
            DF.ADD_CHG_DEL_INDICATOR,
            DF.CREATED_BY,
            DF.CREATED_DATE,
            DF.MODIFIED_BY,
            DF.MODIFIED_DATE,
            0                   AS IS_FORECAST,
			DF.CHECK_RECORD,
			(select HELPER_TABLE_SID from HELPER_TABLE where list_name ='FORECAST_TYPE' and description='Actuals') as FORECAST_TYPE_SID
  FROM      dbo.IVLD_ADJUSTED_DEMAND_ACTUAL DF
  LEFT JOIN dbo.ITEM_MASTER IM ON IM.ITEM_ID = DF.ITEM_ID
  LEFT JOIN dbo.BRAND_MASTER BM ON BM.BRAND_ID = DF.BRAND_ID
  LEFT JOIN dbo.COMPANY_MASTER CM ON CM.COMPANY_NO = DF.ORGANIZATION_KEY

GO 