IF EXISTS (
		SELECT 'X'
		FROM INFORMATION_SCHEMA.VIEWS
		WHERE TABLE_NAME = 'VW_ITEM_PRICING'
			AND TABLE_SCHEMA = 'dbo'
		)
BEGIN
	DROP VIEW [dbo].VW_ITEM_PRICING
END
GO

CREATE VIEW [dbo].[VW_ITEM_PRICING]
AS
SELECT ITEM_PRICING_SID
	,IM.ITEM_ID
	,IM.ITEM_NO
	,IM.ITEM_NAME
	,IPQ.PRICING_QUALIFIER PRICING_CODE_QUALIFIER
	,IPQ.ITEM_PRICING_QUALIFIER_NAME PRICING_CODE_QUALIFIER_NAME
	,HT.DESCRIPTION ITEM_UOM
	,IP.ITEM_PRICE
	,HT1.DESCRIPTION PRICING_CODE_STATUS
	,IP.START_DATE
	,IP.END_DATE
	,IP.ENTITY_CODE
	,IP.SOURCE
	,IP.CREATED_BY
	,IP.CREATED_DATE
	,IP.MODIFIED_BY
	,IP.MODIFIED_DATE
	,IP.INBOUND_STATUS ADD_CHG_DEL_INDICATOR
	,IP.BATCH_ID
	,IP.ITEM_PRICE_PRECISION
FROM ITEM_PRICING IP
JOIN ITEM_MASTER IM ON IM.ITEM_MASTER_SID = IP.ITEM_MASTER_SID
JOIN ITEM_PRICING_QUALIFIER IPQ ON IPQ.ITEM_PRICING_QUALIFIER_SID = IP.ITEM_PRICING_QUALIFIER_SID
LEFT JOIN HELPER_TABLE HT ON HT.HELPER_TABLE_SID = IP.ITEM_UOM
LEFT JOIN HELPER_TABLE HT1 ON HT1.HELPER_TABLE_SID = IP.PRICING_CODE_STATUS
WHERE IM.INBOUND_STATUS <> 'D'
	AND IP.INBOUND_STATUS <> 'D'
	AND IPQ.INBOUND_STATUS <> 'D'
GO

