IF EXISTS (SELECT 'X'
           FROM   INFORMATION_SCHEMA.VIEWS
           WHERE  TABLE_NAME = 'VW_RETURN_RESERVE'
                  AND TABLE_SCHEMA = 'dbo')
  BEGIN
      DROP VIEW [dbo].[VW_RETURN_RESERVE]
  END

GO
--------------------
CREATE VIEW [dbo].[VW_RETURN_RESERVE]
AS

	SELECT   A.RETURN_RESERVE_SID,
             A.RETURN_RESERVE_INTF_ID,
             A.[YEAR],
             A.[MONTH],
             A.BRAND_MASTER_SID,
             A.BRAND_ID,
             A.BRAND_NAME,
             A.ITEM_MASTER_SID,
             A.ITEM_ID,
             A.ITEM_NO,
             A.ITEM_NAME,
             A.UNITS,
             A.AMOUNT,
             A.COUNTRY,
             A.BU_COMPANY_MASTER_SID,
             A.BUSINESS_UNIT,
             A.BUSINESS_UNIT_NAME,
             A.GL_COMPANY_MASTER_SID,
             A.GL_COMPANY,
             A.GL_COMPANY AS COMPANY_ID,
             A.COMPANY_NO,
             A.COMPANY_NAME,
             A.DIVISION,
             A.COST_CENTER,
             A.ACCOUNT,
             A.PROJECT,
             A.FUTURE1,
             A.FUTURE2,
			 H1.DESCRIPTION AS UDC1,
			 H2.DESCRIPTION AS UDC2,
			 H3.DESCRIPTION AS UDC3,
			 H4.DESCRIPTION AS UDC4,
			 H5.DESCRIPTION AS UDC5,
			 H6.DESCRIPTION AS UDC6,
             A.CREATED_BY,
             A.CREATED_DATE,
             A.MODIFIED_BY,
             A.MODIFIED_DATE,
             A.INBOUND_STATUS,
             A.RECORD_LOCK_STATUS,
             A.BATCH_ID,
             A.SOURCE 
	FROM RETURN_RESERVE A JOIN UDCS U ON U.MASTER_SID=A.RETURN_RESERVE_SID AND U.MASTER_TYPE='RETURN_RESERVE'
	JOIN HELPER_TABLE H1 ON H1.HELPER_TABLE_SID=U.UDC1
	JOIN HELPER_TABLE H2 ON H2.HELPER_TABLE_SID=U.UDC2
	JOIN HELPER_TABLE H3 ON H3.HELPER_TABLE_SID=U.UDC3
	JOIN HELPER_TABLE H4 ON H4.HELPER_TABLE_SID=U.UDC4
	JOIN HELPER_TABLE H5 ON H5.HELPER_TABLE_SID=U.UDC5
	JOIN HELPER_TABLE H6 ON H6.HELPER_TABLE_SID=U.UDC6
GO