IF EXISTS (SELECT 'X' 
           FROM   INFORMATION_SCHEMA.VIEWS 
           WHERE  TABLE_NAME = 'VW_REBATE_SCHEDULE' 
                  AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      DROP VIEW [DBO].VW_REBATE_SCHEDULE 
  END 

GO 
CREATE VIEW [dbo].[VW_REBATE_SCHEDULE]
AS

SELECT 	RS.RS_MODEL_SID
	,RS.RS_ID AS REBATE_SCHEDULE_ID
	,RS.RS_NO AS REBATE_SCHEDULE_NO
	,RS.RS_NAME AS REBATE_SCHEDULE_NAME
	,CASE WHEN HT7.HELPER_TABLE_SID  = 0 then '' ELSE HT7.DESCRIPTION  END REBATE_SCHEDULE_TYPE
	,CASE WHEN HT8.HELPER_TABLE_SID  = 0 then '' ELSE HT8.DESCRIPTION  END REBATE_SCHEDULE_CATEGORY
	,CASE WHEN HT9.HELPER_TABLE_SID  = 0 then '' ELSE HT9.DESCRIPTION  END REBATE_SCHEDULE_STATUS
	,CASE WHEN HT10.HELPER_TABLE_SID  = 0 then '' ELSE HT10.DESCRIPTION  END REBATE_SCHEDULE_DESIGNATION
	,CASE WHEN HT11.HELPER_TABLE_SID  = 0 then '' ELSE HT11.DESCRIPTION  END REBATE_PROGRAM_TYPE
	,CASE WHEN HT1.HELPER_TABLE_SID = 0 then '' ELSE HT1.DESCRIPTION END UDC1
	,CASE WHEN HT2.HELPER_TABLE_SID = 0 then '' ELSE HT2.DESCRIPTION END UDC2
	,CASE WHEN HT3.HELPER_TABLE_SID = 0 then '' ELSE HT3.DESCRIPTION END UDC3
	,CASE WHEN HT4.HELPER_TABLE_SID = 0 then '' ELSE HT4.DESCRIPTION END UDC4
	,CASE WHEN HT5.HELPER_TABLE_SID = 0 then '' ELSE HT5.DESCRIPTION END UDC5
	,CASE WHEN HT6.HELPER_TABLE_SID = 0 then '' ELSE HT6.DESCRIPTION END UDC6
	,RS.RS_START_DATE
	,RS.RS_END_DATE
	,RS.RS_TRADE_CLASS AS TRADE_CLASS
	,RS.RS_TRANS_REF_ID AS REBATE_SCHEDULE_TRANS_REF_ID
	,RS.RS_TRANS_REF_NAME AS REBATE_SCHEDULE_TRANS_REF_NAME
	,RS.RS_TRANS_REF_NO AS REBATE_SCHEDULE_TRANS_REF_NO
	,RS.PARENT_RS_ID AS PARENT_REBATE_SCHEDULE_ID
	,RS.PARENT_RS_NAME AS PARENT_REBATE_SCHEDULE_NAME
	,RS.BATCH_ID
	,RS.SOURCE
	,RS.CREATED_BY
	,RS.CREATED_DATE
	,RS.MODIFIED_BY
	,RS.MODIFIED_DATE
	,RS.INBOUND_STATUS AS ADD_CHG_DEL_INDICATOR
	
FROM dbo.RS_MODEL RS
LEFT JOIN dbo.UDCS UD ON RS.RS_MODEL_SID = UD.MASTER_SID
 AND UD.MASTER_TYPE = 'RS_MODEL'
LEFT JOIN dbo.HELPER_TABLE HT1 ON HT1.HELPER_TABLE_SID = UD.UDC1
LEFT JOIN dbo.HELPER_TABLE HT2 ON  HT2.HELPER_TABLE_SID = UD.UDC2
LEFT JOIN dbo.HELPER_TABLE HT3 ON  HT3.HELPER_TABLE_SID = UD.UDC3
LEFT JOIN dbo.HELPER_TABLE HT4 ON  HT4.HELPER_TABLE_SID = UD.UDC4
LEFT JOIN dbo.HELPER_TABLE HT5 ON  HT5.HELPER_TABLE_SID = UD.UDC5
LEFT JOIN dbo.HELPER_TABLE HT6 ON  HT6.HELPER_TABLE_SID = UD.UDC6
LEFT JOIN dbo.HELPER_TABLE HT7 ON HT7.HELPER_TABLE_SID=RS.RS_TYPE
LEFT JOIN dbo.HELPER_TABLE HT8 ON HT8.HELPER_TABLE_SID=RS.RS_CATEGORY
LEFT JOIN dbo.HELPER_TABLE HT9 ON HT9.HELPER_TABLE_SID=RS.RS_STATUS
LEFT JOIN dbo.HELPER_TABLE HT10 ON HT10.HELPER_TABLE_SID=RS.RS_DESIGNATION
LEFT JOIN dbo.HELPER_TABLE HT11 ON HT11.HELPER_TABLE_SID=RS.REBATE_PROGRAM_TYPE
WHERE RS.INBOUND_STATUS<>'D'

GO 