------------------------------------------ HIERARCHY_DEFINITION ------------------------------

------------------------------------------ HIERARCHY_TYPE REFERENCE FROM HELPER TABLE ----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'HIERARCHY_DEFINITION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_HIERARCHY_DEFINITION_HELPER_TABLE_HELPER_TABLE_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE HIERARCHY_DEFINITION
        ADD CONSTRAINT FK_HIERARCHY_DEFINITION_HELPER_TABLE_HELPER_TABLE_SID FOREIGN KEY(HIERARCHY_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO


------------------------------------------ HIERARCHY_LEVEL_DEFINITION ---------------------

---------------------------------------- HIERARCHY_DEFINITION_SID REFERENCE FROM HIERARCHY_DEFINITION TABLE -------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_HIERARCHY_LEVEL_DEFINITION_HIERARCHY_DEFINITION_SID'
                     AND TABLE_NAME = 'HIERARCHY_LEVEL_DEFINITION')
  BEGIN
      ALTER TABLE [DBO].[HIERARCHY_LEVEL_DEFINITION]
        ADD CONSTRAINT FK_HIERARCHY_LEVEL_DEFINITION_HIERARCHY_DEFINITION_SID FOREIGN KEY(HIERARCHY_DEFINITION_SID) REFERENCES HIERARCHY_DEFINITION(HIERARCHY_DEFINITION_SID)
  END
GO

--------------------------------------- HIERARCHY_LEVEL_VALUES ---------------------------------------

--------------------------------------- HIERARCHY_LEVEL_DEFINITION_SID REFERENCE FROM HIERARCHY_LEVEL_DEFINITION ----------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_HIERARCHY_LEVEL_VALUES_HIERARCHY_LEVEL_DEFINITION_SID'
                     AND TABLE_NAME = 'HIERARCHY_LEVEL_VALUES')
  BEGIN
      ALTER TABLE [DBO].[HIERARCHY_LEVEL_VALUES]
        ADD CONSTRAINT FK_HIERARCHY_LEVEL_VALUES_HIERARCHY_LEVEL_DEFINITION_SID FOREIGN KEY(HIERARCHY_LEVEL_DEFINITION_SID) REFERENCES HIERARCHY_LEVEL_DEFINITION(HIERARCHY_LEVEL_DEFINITION_SID)
  END
GO

--------------------------------------- FILE_MANAGEMENT ------------------------------------------------

--------------------------------------- COUNTRY REFERENCE FROM HELPER TABLE ----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'FILE_MANAGEMENT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FILE_MANAGEMENT_HELPER_TABLE_HELPER_TABLE_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE FILE_MANAGEMENT
        ADD CONSTRAINT FK_FILE_MANAGEMENT_HELPER_TABLE_HELPER_TABLE_SID FOREIGN KEY(COUNTRY) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

----------------------------------------- RELATIONSHIP_BUILDER -------------------------------------------

----------------------------------------- RELATIONSHIP_TYPE REFERENCE FROM HELPER TABLE ---------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RELATIONSHIP_BUILDER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RELATIONSHIP_BUILDER_HELPER_TABLE_HELPER_TABLE_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RELATIONSHIP_BUILDER
        ADD CONSTRAINT FK_RELATIONSHIP_BUILDER_HELPER_TABLE_HELPER_TABLE_SID FOREIGN KEY(RELATIONSHIP_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

----------------------------------------- HIERARCHY_DEFINITION_SID REFERENCE FROM HIERARCHY_DEFINITION TABLE ---------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RELATIONSHIP_BUILDER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RELATIONSHIP_BUILDER_HIERARCHY_DEFINITION_HIERARCHY_DEFINITION_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RELATIONSHIP_BUILDER
        ADD CONSTRAINT FK_RELATIONSHIP_BUILDER_HIERARCHY_DEFINITION_HIERARCHY_DEFINITION_SID FOREIGN KEY(HIERARCHY_DEFINITION_SID) REFERENCES HIERARCHY_DEFINITION(HIERARCHY_DEFINITION_SID)
  END
GO

------------------------------------------- RELATIONSHIP_LEVEL_DEFINITION ------------------------------------------------------------------

----------------------------------------- HIERARCHY_LEVEL_DEFINITION_SID REFERENCE FROM HIERARCHY_LEVEL_DEFINITION TABLE ---------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_RELATIONSHIP_LEVEL_DEFINITION_HIERARCHY_LEVEL_DEFINITION_SID'
                     AND TABLE_NAME = 'RELATIONSHIP_LEVEL_DEFINITION')
  BEGIN
      ALTER TABLE [DBO].[RELATIONSHIP_LEVEL_DEFINITION]
        ADD CONSTRAINT FK_RELATIONSHIP_LEVEL_DEFINITION_HIERARCHY_LEVEL_DEFINITION_SID FOREIGN KEY(HIERARCHY_LEVEL_DEFINITION_SID) REFERENCES HIERARCHY_LEVEL_DEFINITION(HIERARCHY_LEVEL_DEFINITION_SID)
END
GO

----------------------------------------- RELATIONSHIP_BUILDER_SID REFERENCE FROM RELATIONSHIP_BUILDER TABLE ---------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_BUILDER_SID'
                     AND TABLE_NAME = 'RELATIONSHIP_LEVEL_DEFINITION')
  BEGIN
      ALTER TABLE [DBO].[RELATIONSHIP_LEVEL_DEFINITION]
        ADD CONSTRAINT FK_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_BUILDER_SID FOREIGN KEY(RELATIONSHIP_BUILDER_SID) REFERENCES RELATIONSHIP_BUILDER(RELATIONSHIP_BUILDER_SID)
END
GO

----------------------------------------- COMPANY_GROUP_DETAILS -------------------------------------------------------------

----------------------------------------- COMPANY_GROUP_SID REFERENCE FROM COMPANY_GROUP TABLE ------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_COMPANY_GROUP_DETAILS_COMPANY_GROUP_SID'
                     AND TABLE_NAME = 'COMPANY_GROUP_DETAILS')
  BEGIN
      ALTER TABLE [DBO].[COMPANY_GROUP_DETAILS]
        ADD CONSTRAINT FK_COMPANY_GROUP_DETAILS_COMPANY_GROUP_SID FOREIGN KEY(COMPANY_GROUP_SID) REFERENCES COMPANY_GROUP(COMPANY_GROUP_SID)
  END
GO

----------------------------------------- COMPANY_MASTER_SID REFERENCE FROM COMPANY_MASTER TABLE ------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_COMPANY_GROUP_DETAILS_COMPANY_MASTER_SID'
                     AND TABLE_NAME = 'COMPANY_GROUP_DETAILS')
  BEGIN
      ALTER TABLE [DBO].[COMPANY_GROUP_DETAILS]
        ADD CONSTRAINT FK_COMPANY_GROUP_DETAILS_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END
GO

----------------------------------------- COMPANY_TRADECLASS_SID REFERENCE FROM COMPANY_TRADE_CLASS TABLE ------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_COMPANY_GROUP_DETAILS_COMPANY_TRADECLASS_SID'
                     AND TABLE_NAME = 'COMPANY_GROUP_DETAILS')
  BEGIN
      ALTER TABLE [DBO].[COMPANY_GROUP_DETAILS]
        ADD CONSTRAINT FK_COMPANY_GROUP_DETAILS_COMPANY_TRADECLASS_SID FOREIGN KEY(COMPANY_TRADECLASS_SID) REFERENCES COMPANY_TRADE_CLASS(COMPANY_TRADE_CLASS_SID)
  END
GO

----------------------------------------- COMPANY_PARENT_DETAILS_SID REFERENCE FROM COMPANY_PARENT_DETAILS TABLE ------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_COMPANY_GROUP_DETAILS_COMPANY_PARENT_DETAILS_SID'
                     AND TABLE_NAME = 'COMPANY_GROUP_DETAILS')
  BEGIN
      ALTER TABLE [DBO].[COMPANY_GROUP_DETAILS]
        ADD CONSTRAINT FK_COMPANY_GROUP_DETAILS_COMPANY_PARENT_DETAILS_SID FOREIGN KEY(COMPANY_PARENT_DETAILS_SID) REFERENCES COMPANY_PARENT_DETAILS(COMPANY_PARENT_DETAILS_SID)
  END
GO

------------------------------------------- ITEM_GROUP ------------------------------------------------------

------------------------------------------- COMPANY_MASTER_SID REFERENCE FROM COMPANY_MASTER TABLE ----------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_ITEM_GROUP_COMPANY_MASTER_SID'
                     AND TABLE_NAME = 'ITEM_GROUP')
  BEGIN
      ALTER TABLE [DBO].[ITEM_GROUP]
        ADD CONSTRAINT FK_ITEM_GROUP_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END
GO

---------------------------------------------- ITEM_GROUP_DETAILS --------------------------------------------------- 

------------------------------------------- ITEM_GROUP_SID REFERENCE FROM ITEM_GROUP TABLE ----------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_ITEM_GROUP_DETAILS_ITEM_GROUP_SID'
                     AND TABLE_NAME = 'ITEM_GROUP_DETAILS')
  BEGIN
      ALTER TABLE [DBO].[ITEM_GROUP_DETAILS]
        ADD CONSTRAINT FK_ITEM_GROUP_DETAILS_ITEM_GROUP_SID FOREIGN KEY(ITEM_GROUP_SID) REFERENCES ITEM_GROUP(ITEM_GROUP_SID)
  END
GO

------------------------------------------- ITEM_MASTER_SID REFERENCE FROM ITEM_MASTER TABLE ----------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_ITEM_GROUP_DETAILS_ITEM_MASTER_SID'
                     AND TABLE_NAME = 'ITEM_GROUP_DETAILS')
  BEGIN
      ALTER TABLE [DBO].[ITEM_GROUP_DETAILS]
        ADD CONSTRAINT FK_ITEM_GROUP_DETAILS_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END
GO

---------------------------------------------- DEDUCTION_GROUP_DETAILS ---------------------------------------------------------

------------------------------------------- DEDUCTION_GROUP_SID REFERENCE FROM DEDUCTION_GROUP TABLE ----------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_DEDUCTION_GROUP_DETAILS_DEDUCTION_GROUP_DEDUCTION_GROUP_SID'
                     AND TABLE_NAME = 'DEDUCTION_GROUP_DETAILS')
  BEGIN
      ALTER TABLE [DBO].[DEDUCTION_GROUP_DETAILS]
        ADD CONSTRAINT FK_DEDUCTION_GROUP_DETAILS_DEDUCTION_GROUP_DEDUCTION_GROUP_SID FOREIGN KEY(DEDUCTION_GROUP_SID) REFERENCES DEDUCTION_GROUP(DEDUCTION_GROUP_SID)
  END
GO

------------------------------------------- RS_MODEL_SID REFERENCE FROM RS_MODEL TABLE ----------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_DEDUCTION_GROUP_DETAILS_RS_MODEL_RS_MODEL_SID'
                     AND TABLE_NAME = 'DEDUCTION_GROUP_DETAILS')
  BEGIN
      ALTER TABLE [DBO].[DEDUCTION_GROUP_DETAILS]
        ADD CONSTRAINT FK_DEDUCTION_GROUP_DETAILS_RS_MODEL_RS_MODEL_SID FOREIGN KEY(RS_MODEL_SID) REFERENCES RS_MODEL(RS_MODEL_SID)
  END
GO 

---------------------------------------------------------forecast config with helper table entries FOREIGN_KEYS starts here----------------------------------------------------------------
--HIST_FREQ
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'FORECAST_CONFIG'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FORECAST_CONFIG_HELPER_TABLE_HIST_FREQ'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE FORECAST_CONFIG
        ADD CONSTRAINT FK_FORECAST_CONFIG_HELPER_TABLE_HIST_FREQ FOREIGN KEY(HIST_FREQ) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO
--PROJ_FREQ
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'FORECAST_CONFIG'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FORECAST_CONFIG_HELPER_TABLE_PROJ_FREQ'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE FORECAST_CONFIG
        ADD CONSTRAINT FK_FORECAST_CONFIG_HELPER_TABLE_PROJ_FREQ FOREIGN KEY(PROJ_FREQ) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO
--BUSINESS_PROCESS_TYPE
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'FORECAST_CONFIG'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FORECAST_CONFIG_HELPER_TABLE_BUSINESS_PROCESS_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE FORECAST_CONFIG
        ADD CONSTRAINT FK_FORECAST_CONFIG_HELPER_TABLE_BUSINESS_PROCESS_TYPE FOREIGN KEY(BUSINESS_PROCESS_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO

---------------------------------------------------------forecast config with helper table entries FOREIGN_KEYS ends here----------------------------------------------------------------
----------------------------------------------- FILE_MANAGEMENT--------------------------------------------------

  IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'FILE_MANAGEMENT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FILE_MANAGEMENT_COMPANY_MASTER_BUSINESS_UNIT'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE FILE_MANAGEMENT
        ADD CONSTRAINT FK_FILE_MANAGEMENT_COMPANY_MASTER_BUSINESS_UNIT FOREIGN KEY(BUSINESS_UNIT) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END
GO
------------------------------------------- HIERARCHY_TABLE_MASTER_SID REFERENCE FROM HIERARCHY_ENTITY_MASTER TABLE ----------------------------------
IF NOT EXISTS (SELECT
    1
  FROM SYS.FOREIGN_KEYS
  WHERE OBJECT_NAME(PARENT_OBJECT_ID) = 'HIERARCHY_ENTITY_MASTER'
  AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
  AND NAME = 'FK_HIERARCHY_ENTITY_MASTER_HIERARCHY_TABLE_MASTER_HIERARCHY_TABLE_MASTER_SID'
  AND TYPE = 'F')
BEGIN
  ALTER TABLE
  HIERARCHY_ENTITY_MASTER ADD CONSTRAINT FK_HIERARCHY_ENTITY_MASTER_HIERARCHY_TABLE_MASTER_HIERARCHY_TABLE_MASTER_SID FOREIGN KEY (HIERARCHY_TABLE_MASTER_SID) REFERENCES HIERARCHY_TABLE_MASTER (MASTER_TABLE_SID)
END
GO

------------------------------------------- TABLE_MASTER_SID REFERENCE FROM HIERARCHY_TABLE_RELATION TABLE ----------------------------------
IF NOT EXISTS (SELECT
    1
  FROM SYS.FOREIGN_KEYS
  WHERE OBJECT_NAME(PARENT_OBJECT_ID) = 'HIERARCHY_TABLE_RELATION'
  AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
  AND NAME = 'FK_HIERARCHY_TABLE_RELATION_HIERARCHY_TABLE_MASTER_LEFT_TABLE_SID'
  AND TYPE = 'F')
BEGIN
  ALTER TABLE
  HIERARCHY_TABLE_RELATION ADD CONSTRAINT FK_HIERARCHY_TABLE_RELATION_HIERARCHY_TABLE_MASTER_LEFT_TABLE_SID FOREIGN KEY (LEFT_TABLE_SID) REFERENCES HIERARCHY_TABLE_MASTER (MASTER_TABLE_SID)
END
GO

IF NOT EXISTS (SELECT
    1
  FROM SYS.FOREIGN_KEYS
  WHERE OBJECT_NAME(PARENT_OBJECT_ID) = 'HIERARCHY_TABLE_RELATION'
  AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
  AND NAME = 'FK_HIERARCHY_TABLE_RELATION_HIERARCHY_TABLE_MASTER_RIGHT_TABLE_SID'
  AND TYPE = 'F')
BEGIN
  ALTER TABLE
  HIERARCHY_TABLE_RELATION ADD CONSTRAINT FK_HIERARCHY_TABLE_RELATION_HIERARCHY_TABLE_MASTER_RIGHT_TABLE_SID FOREIGN KEY (RIGHT_TABLE_SID) REFERENCES HIERARCHY_TABLE_MASTER (MASTER_TABLE_SID)
END
GO
------------------------------------------- ENTITY_ID REFERENCE FROM HIERARCHY_TYPE_TABLE_RELATION TABLE ----------------------------------
IF NOT EXISTS (SELECT
    1
  FROM SYS.FOREIGN_KEYS
  WHERE OBJECT_NAME(PARENT_OBJECT_ID) = 'HIERARCHY_TYPE_TABLE_RELATION'
  AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
  AND NAME = 'FK_HIERARCHY_TYPE_TABLE_RELATION_HIERARCHY_ENTITY_MASTER_ENTITY_ID'
  AND TYPE = 'F')
BEGIN
  ALTER TABLE
  HIERARCHY_TYPE_TABLE_RELATION ADD CONSTRAINT FK_HIERARCHY_TYPE_TABLE_RELATION_HIERARCHY_ENTITY_MASTER_ENTITY_ID FOREIGN KEY (ENTITY_ID) REFERENCES HIERARCHY_ENTITY_MASTER (ENTITY_ID)
END
GO
------------------------------------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'HIERARCHY_LEVEL_QUERIES'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_HIERARCHY_LEVEL_QUERIES_HIERARCHY_LEVEL_DEFINITION_HIERARCHY_LEVEL_DEFINITION_SID'
                     AND TYPE = 'F')
  BEGIN

ALTER TABLE  HIERARCHY_LEVEL_QUERIES ADD CONSTRAINT FK_HIERARCHY_LEVEL_QUERIES_HIERARCHY_LEVEL_DEFINITION_HIERARCHY_LEVEL_DEFINITION_SID FOREIGN KEY(HIERARCHY_LEVEL_DEFINITION_SID) REFERENCES HIERARCHY_LEVEL_DEFINITION(HIERARCHY_LEVEL_DEFINITION_SID)

END
GO
-------------------------------------------------HIERARCHY_RESTRICTION_MASTER-----------------------------------------------------
IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE Object_name(PARENT_OBJECT_ID) = 'HIERARCHY_RESTRICTION_MASTER'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_HIERARCHY_RESTRICTION_MASTER_HIERARCHY_TABLE_MASTER_HIERARCHY_TABLE_MASTER_SID'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE HIERARCHY_RESTRICTION_MASTER ADD CONSTRAINT FK_HIERARCHY_RESTRICTION_MASTER_HIERARCHY_TABLE_MASTER_HIERARCHY_TABLE_MASTER_SID FOREIGN KEY (HIERARCHY_TABLE_MASTER_SID) REFERENCES HIERARCHY_TABLE_MASTER (MASTER_TABLE_SID)
END
GO

