------ FOREIGN_KEYS SCRIPT-------
IF OBJECT_ID('TEMPDB..#A') IS NOT NULL
	DROP TABLE #A

CREATE TABLE #A (
	ID INT IDENTITY(1, 1)
	,NAME VARCHAR(MAX)
	)

INSERT INTO #A (NAME)
SELECT CONCAT (
		' IF  NOT  EXISTS(SELECT 1 FROM   SYS.FOREIGN_KEYS WHERE OBJECT_NAME(PARENT_OBJECT_ID) ='''
		,OBJECT_NAME(SYS.PARENT_OBJECT_ID)
		,''' AND SCHEMA_NAME(SCHEMA_ID) = ''DBO'''
		,' AND NAME = '''
		,SYS.NAME
		,'''AND TYPE=''F'') BEGIN  ALTER TABLE '
		,OBJECT_NAME(SYS.PARENT_OBJECT_ID)
		,' ADD CONSTRAINT '
		,SYS.NAME
		,' FOREIGN KEY('
		,COL_NAME(SYS1.PARENT_OBJECT_ID, PARENT_COLUMN_ID)
		,')  REFERENCES  RELATIONSHIP_LEVEL_DEFINITION(RELATIONSHIP_LEVEL_SID) END ; '
		) NAME
FROM SYS.FOREIGN_KEYS SYS
JOIN SYS.FOREIGN_KEY_COLUMNS SYS1 ON SYS.OBJECT_ID = SYS1.CONSTRAINT_OBJECT_ID
JOIN SYS.COLUMNS SYS2 ON OBJECT_NAME(SYS2.OBJECT_ID) = OBJECT_NAME(SYS.PARENT_OBJECT_ID)
	AND SYS2.NAME = 'RELATIONSHIP_LEVEL_SID'
WHERE SYS.REFERENCED_OBJECT_ID = OBJECT_ID('RELATIONSHIP_LEVEL_DEFINITION')
	AND COL_NAME(SYS1.PARENT_OBJECT_ID, PARENT_COLUMN_ID) = 'RELATIONSHIP_LEVEL_SID'
--AND OBJECT_NAME(SYS.PARENT_OBJECT_ID) NOT LIKE 'ST%'
ORDER BY OBJECT_NAME(SYS.PARENT_OBJECT_ID)

---------------dropping FKS------------------
DECLARE @SQL VARCHAR(max)

SET @SQL = (
		SELECT CONCAT (
				' IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='''
				,OBJECT_NAME(SYS.PARENT_OBJECT_ID)
				,''' AND COLUMN_NAME=''RELATIONSHIP_LEVEL_SID'' AND DATA_TYPE=''INT'')'
				,' BEGIN ALTER TABLE '
				,OBJECT_NAME(SYS.PARENT_OBJECT_ID)
				,' DROP CONSTRAINT '
				,SYS.NAME
				,'  END  '
				,';'
				)
		FROM SYS.FOREIGN_KEYS SYS
		JOIN SYS.FOREIGN_KEY_COLUMNS SYS1 ON SYS.OBJECT_ID = SYS1.CONSTRAINT_OBJECT_ID
		JOIN SYS.COLUMNS SYS2 ON OBJECT_NAME(SYS2.OBJECT_ID) = OBJECT_NAME(SYS.PARENT_OBJECT_ID)
			AND SYS2.NAME = 'RELATIONSHIP_LEVEL_SID'
		WHERE SYS.REFERENCED_OBJECT_ID = OBJECT_ID('RELATIONSHIP_LEVEL_DEFINITION')
			AND COL_NAME(SYS1.PARENT_OBJECT_ID, PARENT_COLUMN_ID) = 'RELATIONSHIP_LEVEL_SID'
		ORDER BY OBJECT_NAME(SYS.PARENT_OBJECT_ID)
		FOR XML PATH('')
		)
		exec(@SQL)




-------------dropping existing PK--------------
IF  EXISTS (
		SELECT 1
		FROM SYS.KEY_CONSTRAINTS
		WHERE Object_name(PARENT_OBJECT_ID) = 'RELATIONSHIP_LEVEL_DEFINITION'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'PK_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID'
			AND TYPE = 'PK'
		)
BEGIN
	ALTER TABLE [DBO].[RELATIONSHIP_LEVEL_DEFINITION]

	DROP CONSTRAINT PK_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID
END
GO

------------------altering nullable columns------


IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'RELATIONSHIP_LEVEL_DEFINITION'
                      AND COLUMN_NAME = 'VERSION_NO'
					  AND TABLE_SCHEMA='DBO')
  BEGIN
      ALTER TABLE RELATIONSHIP_LEVEL_DEFINITION
        ALTER COLUMN VERSION_NO INT NOT NULL
  END
GO

------------DROPPING STASTICS
IF EXISTS (
		SELECT 1
		FROM SYS.STATS
		WHERE OBJECT_NAME(OBJECT_ID) = 'RELATIONSHIP_LEVEL_DEFINITION'
			AND AUTO_CREATED = 0
			AND NAME = 'RELATIONSHIP_BUILDER_SID'
		)
BEGIN
	DROP STATISTICS RELATIONSHIP_LEVEL_DEFINITION.RELATIONSHIP_BUILDER_SID
END
GO



-----------------------

IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'RELATIONSHIP_LEVEL_DEFINITION'
                      AND COLUMN_NAME = 'RELATIONSHIP_BUILDER_SID'
					  AND TABLE_SCHEMA='DBO')
  BEGIN
      ALTER TABLE RELATIONSHIP_LEVEL_DEFINITION
        ALTER COLUMN RELATIONSHIP_BUILDER_SID INT NOT NULL
  END
GO

------------DROPPING STASTICS
IF EXISTS (
		SELECT 1
		FROM SYS.STATS
		WHERE OBJECT_NAME(OBJECT_ID) = 'RELATIONSHIP_LEVEL_DEFINITION'
			AND AUTO_CREATED = 0
			AND NAME = 'LEVEL_NO'
		)
BEGIN
	DROP STATISTICS RELATIONSHIP_LEVEL_DEFINITION.LEVEL_NO
END
GO



IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'RELATIONSHIP_LEVEL_DEFINITION'
                      AND COLUMN_NAME = 'LEVEL_NO'
					  AND TABLE_SCHEMA='DBO')
  BEGIN
      ALTER TABLE RELATIONSHIP_LEVEL_DEFINITION
        ALTER COLUMN LEVEL_NO VARCHAR(50) NOT NULL
  END
GO
------------DROPPING STASTICS
IF EXISTS (
		SELECT 1
		FROM SYS.STATS
		WHERE OBJECT_NAME(OBJECT_ID) = 'RELATIONSHIP_LEVEL_DEFINITION'
			AND AUTO_CREATED = 0
			AND NAME = 'LEVEL_NAME'
		)
BEGIN
	DROP STATISTICS RELATIONSHIP_LEVEL_DEFINITION.LEVEL_NAME
END
GO

IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'RELATIONSHIP_LEVEL_DEFINITION'
                      AND COLUMN_NAME = 'LEVEL_NAME'
					  AND TABLE_SCHEMA='DBO')
  BEGIN
      ALTER TABLE RELATIONSHIP_LEVEL_DEFINITION
        ALTER COLUMN LEVEL_NAME VARCHAR(50) NOT NULL
  END
GO



IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'RELATIONSHIP_LEVEL_DEFINITION'
                      AND COLUMN_NAME = 'RELATIONSHIP_LEVEL_SID'
					  AND TABLE_SCHEMA='DBO')
  BEGIN
      ALTER TABLE RELATIONSHIP_LEVEL_DEFINITION
        ALTER COLUMN RELATIONSHIP_LEVEL_SID INT NOT NULL
  END
GO

------------DROPPING STASTICS
IF EXISTS (
		SELECT 1
		FROM SYS.STATS
		WHERE OBJECT_NAME(OBJECT_ID) = 'RELATIONSHIP_LEVEL_DEFINITION'
			AND AUTO_CREATED = 0
			AND NAME = 'RELATIONSHIP_LEVEL_VALUES'
		)
BEGIN
	DROP STATISTICS RELATIONSHIP_LEVEL_DEFINITION.RELATIONSHIP_LEVEL_VALUES
END
GO
IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'RELATIONSHIP_LEVEL_DEFINITION'
                      AND COLUMN_NAME = 'RELATIONSHIP_LEVEL_VALUES'
					  AND TABLE_SCHEMA='DBO')
  BEGIN
      ALTER TABLE RELATIONSHIP_LEVEL_DEFINITION
        ALTER COLUMN RELATIONSHIP_LEVEL_VALUES VARCHAR(50) NOT NULL
  END
GO


-----------------------------------------



-----------------------------PK--------------------------------
IF NOT EXISTS (
		SELECT 1
		FROM SYS.KEY_CONSTRAINTS
		WHERE Object_name(PARENT_OBJECT_ID) = 'RELATIONSHIP_LEVEL_DEFINITION'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'PK_RELATIONSHIP_LEVEL_DEFINITION_VERSION_NO_RELATIONSHIP_BUILDER_SID_LNO_LNAME_RELATIONSHIP_LSID_RELATIONSHIP_LVALUES'
			AND TYPE = 'PK'
		)
BEGIN
	ALTER TABLE RELATIONSHIP_LEVEL_DEFINITION ADD CONSTRAINT PK_RELATIONSHIP_LEVEL_DEFINITION_VERSION_NO_RELATIONSHIP_BUILDER_SID_LNO_LNAME_RELATIONSHIP_LSID_RELATIONSHIP_LVALUES PRIMARY KEY (
		VERSION_NO
		,RELATIONSHIP_BUILDER_SID
		,LEVEL_NO
		,LEVEL_NAME
		,RELATIONSHIP_LEVEL_SID
		,RELATIONSHIP_LEVEL_VALUES
		)
END
GO




----------------------------UK--------------------------------------------
IF NOT EXISTS (
		SELECT 1
		FROM SYS.KEY_CONSTRAINTS
		WHERE TYPE_DESC = 'UNIQUE_CONSTRAINT'
			AND PARENT_OBJECT_ID = Object_id('RELATIONSHIP_LEVEL_DEFINITION')
			AND NAME = 'UQ_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID'
		)
BEGIN
	ALTER TABLE RELATIONSHIP_LEVEL_DEFINITION ADD CONSTRAINT UQ_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID UNIQUE (RELATIONSHIP_LEVEL_SID)
END
GO

-----------------------EXEC-------------------------
DECLARE @COUNT INT
	,@ROW INT = 1
	,@NAME VARCHAR(2000)
	,@D_SQL VARCHAR(2000)

SELECT @COUNT = COUNT(DISTINCT ID)
FROM #A

WHILE (@ROW <= @COUNT)
BEGIN
	SET @NAME = (
			SELECT DISTINCT NAME
			FROM #A
			WHERE ID = @ROW
			)
	SET @D_SQL = '

' + @NAME + ''

	exec (@D_SQL)

	SET @ROW = @ROW + 1
END
---------------------------------------------------------



 