package com.stpl.app.model.impl;

import com.stpl.app.model.BusinessroleModule;
import com.stpl.app.service.BusinessroleModuleLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the BusinessroleModule service. Represents a row in the &quot;BUSINESSROLE_MODULE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BusinessroleModuleImpl}.
 * </p>
 *
 * @author
 * @see BusinessroleModuleImpl
 * @see com.stpl.app.model.BusinessroleModule
 * @generated
 */
public abstract class BusinessroleModuleBaseImpl
    extends BusinessroleModuleModelImpl implements BusinessroleModule {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a businessrole module model instance should use the {@link BusinessroleModule} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BusinessroleModuleLocalServiceUtil.addBusinessroleModule(this);
        } else {
            BusinessroleModuleLocalServiceUtil.updateBusinessroleModule(this);
        }
    }
}
