package com.stpl.app.model.impl;

import com.stpl.app.model.CustomViewDetails;
import com.stpl.app.service.CustomViewDetailsLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the CustomViewDetails service. Represents a row in the &quot;CUSTOM_VIEW_DETAILS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomViewDetailsImpl}.
 * </p>
 *
 * @author
 * @see CustomViewDetailsImpl
 * @see com.stpl.app.model.CustomViewDetails
 * @generated
 */
public abstract class CustomViewDetailsBaseImpl
    extends CustomViewDetailsModelImpl implements CustomViewDetails {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a custom view details model instance should use the {@link CustomViewDetails} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CustomViewDetailsLocalServiceUtil.addCustomViewDetails(this);
        } else {
            CustomViewDetailsLocalServiceUtil.updateCustomViewDetails(this);
        }
    }
}
