package com.stpl.app.model.impl;

import com.stpl.app.model.NetSalesFormulaMaster;
import com.stpl.app.service.NetSalesFormulaMasterLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the NetSalesFormulaMaster service. Represents a row in the &quot;NET_SALES_FORMULA_MASTER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NetSalesFormulaMasterImpl}.
 * </p>
 *
 * @author
 * @see NetSalesFormulaMasterImpl
 * @see com.stpl.app.model.NetSalesFormulaMaster
 * @generated
 */
public abstract class NetSalesFormulaMasterBaseImpl
    extends NetSalesFormulaMasterModelImpl implements NetSalesFormulaMaster {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a net sales formula master model instance should use the {@link NetSalesFormulaMaster} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            NetSalesFormulaMasterLocalServiceUtil.addNetSalesFormulaMaster(this);
        } else {
            NetSalesFormulaMasterLocalServiceUtil.updateNetSalesFormulaMaster(this);
        }
    }
}
