package com.stpl.app.model.impl;

import com.stpl.app.model.StMSupplementalDiscProj;
import com.stpl.app.service.StMSupplementalDiscProjLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the StMSupplementalDiscProj service. Represents a row in the &quot;ST_M_SUPPLEMENTAL_DISC_PROJ&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StMSupplementalDiscProjImpl}.
 * </p>
 *
 * @author
 * @see StMSupplementalDiscProjImpl
 * @see com.stpl.app.model.StMSupplementalDiscProj
 * @generated
 */
public abstract class StMSupplementalDiscProjBaseImpl
    extends StMSupplementalDiscProjModelImpl implements StMSupplementalDiscProj {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a st m supplemental disc proj model instance should use the {@link StMSupplementalDiscProj} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            StMSupplementalDiscProjLocalServiceUtil.addStMSupplementalDiscProj(this);
        } else {
            StMSupplementalDiscProjLocalServiceUtil.updateStMSupplementalDiscProj(this);
        }
    }
}
