------------------------------------------------FOREIGN_KEYS----------------------------------------
----CFF_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_MASTER_COMPANY_GROUP_COMPANY_GROUP_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_MASTER]
        ADD CONSTRAINT FK_CFF_MASTER_COMPANY_GROUP_COMPANY_GROUP_SID FOREIGN KEY(COMPANY_GROUP_SID) REFERENCES COMPANY_GROUP ( COMPANY_GROUP_SID)
  END

GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_MASTER_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_MASTER]
        ADD CONSTRAINT FK_CFF_MASTER_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER (COMPANY_MASTER_SID)
  END

GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_MASTER_HIERARCHY_DEFINITION_CUSTOMER_HIERARCHY_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_MASTER]
        ADD CONSTRAINT FK_CFF_MASTER_HIERARCHY_DEFINITION_CUSTOMER_HIERARCHY_SID FOREIGN KEY(CUSTOMER_HIERARCHY_SID) REFERENCES HIERARCHY_DEFINITION ( HIERARCHY_DEFINITION_SID)
  END

GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_MASTER_HIERARCHY_DEFINITION_PRODUCT_HIERARCHY_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_MASTER]
        ADD CONSTRAINT FK_CFF_MASTER_HIERARCHY_DEFINITION_PRODUCT_HIERARCHY_SID FOREIGN KEY(PRODUCT_HIERARCHY_SID) REFERENCES HIERARCHY_DEFINITION (HIERARCHY_DEFINITION_SID)
  END

GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_MASTER_ITEM_GROUP_ITEM_GROUP_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_MASTER]
        ADD CONSTRAINT FK_CFF_MASTER_ITEM_GROUP_ITEM_GROUP_SID FOREIGN KEY(ITEM_GROUP_SID) REFERENCES ITEM_GROUP ( ITEM_GROUP_SID)
  END

GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_MASTER_RELATIONSHIP_BUILDER_CUST_RELATIONSHIP_BUILDER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_MASTER]
        ADD CONSTRAINT FK_CFF_MASTER_RELATIONSHIP_BUILDER_CUST_RELATIONSHIP_BUILDER_SID FOREIGN KEY(CUST_RELATIONSHIP_BUILDER_SID) REFERENCES RELATIONSHIP_BUILDER ( RELATIONSHIP_BUILDER_SID)
  END

GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_MASTER_RELATIONSHIP_BUILDER_PROD_RELATIONSHIP_BUILDER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_MASTER]
        ADD CONSTRAINT FK_CFF_MASTER_RELATIONSHIP_BUILDER_PROD_RELATIONSHIP_BUILDER_SID FOREIGN KEY(PROD_RELATIONSHIP_BUILDER_SID) REFERENCES RELATIONSHIP_BUILDER ( RELATIONSHIP_BUILDER_SID)
  END

GO 


IF NOT EXISTS (
              SELECT 1
              FROM SYS.FOREIGN_KEYS
              WHERE Object_name(PARENT_OBJECT_ID) = 'CFF_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_MASTER_COMPANY_MASTER_BUSINESS_UNIT'
                     AND TYPE = 'F'
              )
BEGIN
       ALTER TABLE CFF_MASTER ADD CONSTRAINT FK_CFF_MASTER_COMPANY_MASTER_BUSINESS_UNIT FOREIGN KEY (BUSINESS_UNIT) REFERENCES COMPANY_MASTER (COMPANY_MASTER_SID)
END
GO

----CFF_FILE_SELECTION----------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CFF_FILE_SELECTION'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_FILE_SELECTION_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_FILE_SELECTION]
        ADD CONSTRAINT FK_CFF_FILE_SELECTION_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) 
		REFERENCES CFF_MASTER ( CFF_MASTER_SID)
  END
GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CFF_FILE_SELECTION'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_FILE_SELECTION_FILE_MANAGEMENT_FILE_MANAGEMENT_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_FILE_SELECTION]
        ADD CONSTRAINT FK_CFF_FILE_SELECTION_FILE_MANAGEMENT_FILE_MANAGEMENT_SID FOREIGN KEY(FILE_MANAGEMENT_SID) 
		REFERENCES FILE_MANAGEMENT ( FILE_MANAGEMENT_SID)
  END
GO 


-- IF NOT EXISTS(SELECT 1
              -- FROM   SYS.FOREIGN_KEYS
              -- WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CFF_FILE_SELECTION'
                     -- AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     -- AND NAME = 'FK_CFF_FILE_SELECTION_HELPER_TABLE_FILE_TYPE'
                     -- AND TYPE = 'F')
  -- BEGIN
      -- ALTER TABLE [DBO].[CFF_FILE_SELECTION]
        -- ADD CONSTRAINT FK_CFF_FILE_SELECTION_HELPER_TABLE_FILE_TYPE FOREIGN KEY(CFF_FILE_SELECTION_SID) 
		-- REFERENCES HELPER_TABLE ( HELPER_TABLE_SID)
  -- END
-- GO 

IF EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS AS F
		INNER JOIN SYS.FOREIGN_KEY_COLUMNS AS FC ON F.OBJECT_ID = FC.CONSTRAINT_OBJECT_ID
		WHERE OBJECT_NAME(F.PARENT_OBJECT_ID) = 'CFF_FILE_SELECTION'
			AND F.NAME = 'FK_CFF_FILE_SELECTION_HELPER_TABLE_FILE_TYPE'
			AND COL_NAME(FC.PARENT_OBJECT_ID, FC.PARENT_COLUMN_ID) = 'CFF_FILE_SELECTION_SID'
		)
BEGIN
	ALTER TABLE [DBO].[CFF_FILE_SELECTION]

	DROP CONSTRAINT FK_CFF_FILE_SELECTION_HELPER_TABLE_FILE_TYPE
END
GO


IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CFF_FILE_SELECTION'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_FILE_SELECTION_HELPER_TABLE_FILE_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_FILE_SELECTION]
        ADD CONSTRAINT FK_CFF_FILE_SELECTION_HELPER_TABLE_FILE_TYPE FOREIGN KEY(FILE_TYPE) 
		REFERENCES HELPER_TABLE ( HELPER_TABLE_SID)
  END
GO 


----------CFF_CUST_HIERARCHY
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_CUST_HIERARCHY'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_CUST_HIERARCHY_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_CUST_HIERARCHY]
        ADD CONSTRAINT FK_CFF_CUST_HIERARCHY_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER ( CFF_MASTER_SID)
  END

GO 


IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_CUST_HIERARCHY'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_CUST_HIERARCHY_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_CUST_HIERARCHY]
        ADD CONSTRAINT FK_CFF_CUST_HIERARCHY_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID FOREIGN KEY(RELATIONSHIP_LEVEL_SID) 
		REFERENCES RELATIONSHIP_LEVEL_DEFINITION ( RELATIONSHIP_LEVEL_SID)
  END

GO 
----------CFF_PROD_HIERARCHY
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_PROD_HIERARCHY'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_PROD_HIERARCHY_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_PROD_HIERARCHY]
        ADD CONSTRAINT FK_CFF_PROD_HIERARCHY_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER ( CFF_MASTER_SID)
  END

GO 


IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_PROD_HIERARCHY'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_PROD_HIERARCHY_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_PROD_HIERARCHY]
        ADD CONSTRAINT FK_CFF_PROD_HIERARCHY_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID FOREIGN KEY(RELATIONSHIP_LEVEL_SID) 
		REFERENCES RELATIONSHIP_LEVEL_DEFINITION ( RELATIONSHIP_LEVEL_SID)
  END

GO 


---CFF_SELECTION
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_SELECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_SELECTION_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_SELECTION]
        ADD CONSTRAINT FK_CFF_SELECTION_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER ( CFF_MASTER_SID)
  END

GO 

-----------------------------------------------'CFF_DOC_DETAILS'---------------


IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_DOC_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_DOC_DETAILS_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_DOC_DETAILS]
        ADD CONSTRAINT FK_CFF_DOC_DETAILS_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER (CFF_MASTER_SID)
  END

GO 

---------------------CFF_DETAILS----------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_DETAILS_CCP_DETAILS_CCP_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_DETAILS]
        ADD CONSTRAINT FK_CFF_DETAILS_CCP_DETAILS_CCP_DETAILS_SID FOREIGN KEY(CCP_DETAILS_SID) REFERENCES CCP_DETAILS ( CCP_DETAILS_SID)
  END

GO 



IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_DETAILS_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_DETAILS]
        ADD CONSTRAINT FK_CFF_DETAILS_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER( CFF_MASTER_SID)
  END

GO 


IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_DETAILS]
        ADD CONSTRAINT FK_CFF_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER ( PROJECTION_MASTER_SID)
  END

GO 

-------------CFF_ADDITIONAL_INFO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_ADDITIONAL_INFO'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_ADDITIONAL_INFO_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_ADDITIONAL_INFO]
        ADD CONSTRAINT FK_CFF_ADDITIONAL_INFO_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER ( CFF_MASTER_SID)
  END

GO 
------------------------CFF_APPROVAL_DETAILS----------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_APPROVAL_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_APPROVAL_DETAILS_HELPER_TABLE_APPROVAL_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_APPROVAL_DETAILS]
        ADD CONSTRAINT FK_CFF_APPROVAL_DETAILS_HELPER_TABLE_APPROVAL_STATUS FOREIGN KEY(APPROVAL_STATUS) REFERENCES HELPER_TABLE ( HELPER_TABLE_SID)
  END

GO 


IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_APPROVAL_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_APPROVAL_DETAILS_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_APPROVAL_DETAILS]
        ADD CONSTRAINT FK_CFF_APPROVAL_DETAILS_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER ( CFF_MASTER_SID)
  END

GO 
---------------------------CFF_CUSTOM_VIEW_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_CUSTOM_VIEW_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_CUSTOM_VIEW_DETAILS_CFF_CUSTOM_VIEW_MASTER_CFF_CUSTOM_VIEW_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_CUSTOM_VIEW_DETAILS]
        ADD CONSTRAINT FK_CFF_CUSTOM_VIEW_DETAILS_CFF_CUSTOM_VIEW_MASTER_CFF_CUSTOM_VIEW_MASTER_SID FOREIGN KEY(CFF_CUSTOM_VIEW_MASTER_SID) REFERENCES CFF_CUSTOM_VIEW_MASTER ( CFF_CUSTOM_VIEW_MASTER_SID)
  END

GO 
-------------------------------CFF_CUSTOM_VIEW_MASTER

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_CUSTOM_VIEW_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_CUSTOM_VIEW_MASTER_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CFF_CUSTOM_VIEW_MASTER]
        ADD CONSTRAINT FK_CFF_CUSTOM_VIEW_MASTER_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER ( CFF_MASTER_SID)
  END

GO 

--------------------------------CFF_CUSTOM_RELATIONSHIP_BUILDER
IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE Object_name(PARENT_OBJECT_ID) = 'CFF_CUSTOM_RELATIONSHIP_BUILDER'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_CFF_CUSTOM_RELATIONSHIP_BUILDER_CFF_CUSTOM_VIEW_DETAILS_CFF_CUSTOM_VIEW_DETAILS_SID'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE [DBO].[CFF_CUSTOM_RELATIONSHIP_BUILDER] ADD CONSTRAINT FK_CFF_CUSTOM_RELATIONSHIP_BUILDER_CFF_CUSTOM_VIEW_DETAILS_CFF_CUSTOM_VIEW_DETAILS_SID FOREIGN KEY (CFF_CUSTOM_VIEW_DETAILS_SID) REFERENCES CFF_CUSTOM_VIEW_DETAILS (CFF_CUSTOM_VIEW_DETAILS_SID)
END
GO

------------------------CFF_CUSTOM_VIEW---------
IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE Object_name(PARENT_OBJECT_ID) = 'CFF_CUSTOM_VIEW'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_CFF_CUSTOM_VIEW_CFF_CUSTOM_VIEW_DETAILS_CFF_CUSTOM_VIEW_DETAILS_SID'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE [DBO].[CFF_CUSTOM_VIEW] ADD CONSTRAINT FK_CFF_CUSTOM_VIEW_CFF_CUSTOM_VIEW_DETAILS_CFF_CUSTOM_VIEW_DETAILS_SID FOREIGN KEY (CFF_CUSTOM_VIEW_DETAILS_SID) REFERENCES CFF_CUSTOM_VIEW_DETAILS (CFF_CUSTOM_VIEW_DETAILS_SID)
END
GO
 -----------------CFF_VIEW_MASTER-------CEL-413
 IF EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE Object_name(PARENT_OBJECT_ID) = 'CFF_VIEW_MASTER'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_CFF_VIEW_MASTER_CFF_MASTER_CFF_MASTER_SID'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE [DBO].[CFF_VIEW_MASTER] DROP CONSTRAINT FK_CFF_VIEW_MASTER_CFF_MASTER_CFF_MASTER_SID
END
GO
 IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE Object_name(PARENT_OBJECT_ID) = 'CFF_VIEW_MASTER'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_CFF_VIEW_MASTER_CFF_MASTER_CFF_MASTER_SID'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE [DBO].[CFF_VIEW_MASTER] ADD CONSTRAINT FK_CFF_VIEW_MASTER_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY (CFF_MASTER_SID) REFERENCES CFF_MASTER (CFF_MASTER_SID)
END
GO
-----------------------------------------------F.K's FOR CFF_DEDUCTION_INCLUSION------------------------------------------------
--CFF_DETAILS_SID
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_DEDUCTION_INCLUSION'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_DEDUCTION_INCLUSION_CFF_DETAILS_CFF_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFF_DEDUCTION_INCLUSION
        ADD CONSTRAINT FK_CFF_DEDUCTION_INCLUSION_CFF_DETAILS_CFF_DETAILS_SID FOREIGN KEY(CFF_DETAILS_SID) REFERENCES CFF_DETAILS(CFF_DETAILS_SID)
  END

GO

--RS_MODEL_SID
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_DEDUCTION_INCLUSION'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_DEDUCTION_INCLUSION_RS_MODEL_RS_MODEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFF_DEDUCTION_INCLUSION
        ADD CONSTRAINT FK_CFF_DEDUCTION_INCLUSION_RS_MODEL_RS_MODEL_SID FOREIGN KEY(RS_MODEL_SID) REFERENCES RS_MODEL(RS_MODEL_SID)
  END

GO 
--------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CUSTOM_CCP_MAP'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CUSTOM_CCP_MAP_CUSTOM_VIEW_DETAILS_CUSTOM_VIEW_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CUSTOM_CCP_MAP]
        ADD CONSTRAINT FK_CUSTOM_CCP_MAP_CUSTOM_VIEW_DETAILS_CUSTOM_VIEW_DETAILS_SID FOREIGN KEY(CUSTOM_VIEW_DETAILS_SID)
            REFERENCES CUSTOM_VIEW_DETAILS ( CUSTOM_VIEW_DETAILS_SID)
  END
GO  
 
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CUSTOM_CCP_MAP'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CUSTOM_CCP_MAP_CCP_DETAILS_CCP_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CUSTOM_CCP_MAP]
        ADD CONSTRAINT FK_CUSTOM_CCP_MAP_CCP_DETAILS_CCP_DETAILS_SID FOREIGN KEY(CCP_DETAILS_SID)
            REFERENCES CCP_DETAILS ( CCP_DETAILS_SID)
  END
GO  
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CUSTOM_RELATIONSHIP_BUILDER'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CUSTOM_RELATIONSHIP_BUILDER_CUSTOM_VIEW_DETAILS_CUSTOM_VIEW_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[CUSTOM_RELATIONSHIP_BUILDER]
        ADD CONSTRAINT FK_CUSTOM_RELATIONSHIP_BUILDER_CUSTOM_VIEW_DETAILS_CUSTOM_VIEW_DETAILS_SID FOREIGN KEY(CUSTOM_VIEW_DETAILS_SID)
            REFERENCES CUSTOM_VIEW_DETAILS ( CUSTOM_VIEW_DETAILS_SID)
  END
GO  