--------------------------------------------------------------- CCP_DETAILS ---------------------------------------------------
---------------------------------------------------------- COMPANY_MASTER_SID REFERENCE FROM COMPANY_MASTER TABLE -------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CCP_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CCP_DETAILS_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CCP_DETAILS
        ADD CONSTRAINT FK_CCP_DETAILS_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO

---------------------------------------------------------- CONTRACT_MASTER_SID REFERENCE FROM CONTRACT_MASTER TABLE -------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CCP_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CCP_DETAILS_CONTRACT_MASTER_CONTRACT_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CCP_DETAILS
        ADD CONSTRAINT FK_CCP_DETAILS_CONTRACT_MASTER_CONTRACT_MASTER_SID FOREIGN KEY(CONTRACT_MASTER_SID) REFERENCES CONTRACT_MASTER(CONTRACT_MASTER_SID)
  END

GO

---------------------------------------------------------- ITEM_MASTER_SID REFERENCE FROM ITEM_MASTER TABLE -------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CCP_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CCP_DETAILS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CCP_DETAILS
        ADD CONSTRAINT FK_CCP_DETAILS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

---------------------CCP_MAP------------------------
---------------------CCP_DETAILS_SID REFERENCE FROM CCP_DETAILS TABLE------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CCP_MAP'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CCP_MAP_CCP_DETAILS_CCP_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CCP_MAP
        ADD CONSTRAINT FK_CCP_MAP_CCP_DETAILS_CCP_DETAILS_SID FOREIGN KEY(CCP_DETAILS_SID) REFERENCES CCP_DETAILS(CCP_DETAILS_SID)
  END

GO

---------------------RELATIONSHIP_LEVEL_SID REFERENCE FROM RELATIONSHIP_LEVEL_DEFINITION TABLE------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CCP_MAP'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CCP_MAP_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CCP_MAP
        ADD CONSTRAINT FK_CCP_MAP_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID FOREIGN KEY(RELATIONSHIP_LEVEL_SID) REFERENCES RELATIONSHIP_LEVEL_DEFINITION(RELATIONSHIP_LEVEL_SID)
  END

GO

-------------------------------------------- PROJECTION MASTER ---------------------------------------------
------------------------------------------ CUSTOMER_HIERARCHY_SID REFERENCE FROM HIERARCHY_DEFINITION TABLE -------------------------------- 
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_MASTER_HIERARCHY_DEFINITION_CUSTOMER_HIERARCHY_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_MASTER
        ADD CONSTRAINT FK_PROJECTION_MASTER_HIERARCHY_DEFINITION_CUSTOMER_HIERARCHY_SID FOREIGN KEY(CUSTOMER_HIERARCHY_SID) REFERENCES HIERARCHY_DEFINITION(HIERARCHY_DEFINITION_SID)
  END

GO

------------------------------------------ PRODUCT_HIERARCHY_SID REFERENCE FROM HIERARCHY_DEFINITION TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_MASTER_HIERARCHY_DEFINITION_PRODUCT_HIERARCHY_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_MASTER
        ADD CONSTRAINT FK_PROJECTION_MASTER_HIERARCHY_DEFINITION_PRODUCT_HIERARCHY_SID FOREIGN KEY(PRODUCT_HIERARCHY_SID) REFERENCES HIERARCHY_DEFINITION(HIERARCHY_DEFINITION_SID)
  END

GO

------------------------------------------ COMPANY_MASTER_SID REFERENCE FROM COMPANY_MASTER TABLE ----------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_MASTER_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_MASTER
        ADD CONSTRAINT FK_PROJECTION_MASTER_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO

------------------------------------------ COMPANY_GROUP_SID REFERENCE FROM COMPANY_GROUP TABLE ----------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_MASTER_COMPANY_GROUP_COMPANY_GROUP_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_MASTER
        ADD CONSTRAINT FK_PROJECTION_MASTER_COMPANY_GROUP_COMPANY_GROUP_SID FOREIGN KEY(COMPANY_GROUP_SID) REFERENCES COMPANY_GROUP(COMPANY_GROUP_SID)
  END

GO

------------------------------------------ ITEM_GROUP_SID REFERENCE FROM ITEM_GROUP TABLE ----------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_MASTER_ITEM_GROUP_ITEM_GROUP_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_MASTER
        ADD CONSTRAINT FK_PROJECTION_MASTER_ITEM_GROUP_ITEM_GROUP_SID FOREIGN KEY(ITEM_GROUP_SID) REFERENCES ITEM_GROUP(ITEM_GROUP_SID)
  END

GO

------------------------------------------ RELATIONSHIP_BUILDER_SID REFERENCE FROM RELATIONSHIP_BUILDER TABLE(CUST_RELATIONSHIP_BUILDER_SID)----------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_MASTER_RELATIONSHIP_BUILDER_CUST_RELATIONSHIP_BUILDER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_MASTER
        ADD CONSTRAINT FK_PROJECTION_MASTER_RELATIONSHIP_BUILDER_CUST_RELATIONSHIP_BUILDER_SID FOREIGN KEY(CUST_RELATIONSHIP_BUILDER_SID) REFERENCES RELATIONSHIP_BUILDER(RELATIONSHIP_BUILDER_SID)
  END

GO 

------------------------------------------ RELATIONSHIP_BUILDER_SID REFERENCE FROM RELATIONSHIP_BUILDER TABLE(PROD_RELATIONSHIP_BUILDER_SID)----------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_MASTER_RELATIONSHIP_BUILDER_PROD_RELATIONSHIP_BUILDER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_MASTER
        ADD CONSTRAINT FK_PROJECTION_MASTER_RELATIONSHIP_BUILDER_PROD_RELATIONSHIP_BUILDER_SID FOREIGN KEY(PROD_RELATIONSHIP_BUILDER_SID) REFERENCES RELATIONSHIP_BUILDER(RELATIONSHIP_BUILDER_SID)
  END

GO 
-------------------------------------------------------------------------company_master_sid for BUSINESS_UNIT-----------------------------------------------------
IF NOT EXISTS (
              SELECT 1
              FROM SYS.FOREIGN_KEYS
              WHERE Object_name(PARENT_OBJECT_ID) = 'PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_MASTER_COMPANY_MASTER_BUSINESS_UNIT'
                     AND TYPE = 'F'
              )
BEGIN
       ALTER TABLE PROJECTION_MASTER ADD CONSTRAINT FK_PROJECTION_MASTER_COMPANY_MASTER_BUSINESS_UNIT FOREIGN KEY (BUSINESS_UNIT) REFERENCES COMPANY_MASTER (COMPANY_MASTER_SID)
END
GO

-------------------------------------------------------------- PROJECTION_DETAILS ------------------------------------------
---------------------------------------------------------- PROJECTION_MASTER_SID REFERENCE FROM PROJECTION MASTER TABLE ---------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_DETAILS
        ADD CONSTRAINT FK_PROJECTION_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

---------------------------------------------------------- CCP_DETAILS_SID REFERENCE FROM CCP_DETAILS TABLE ---------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_DETAILS_CCP_DETAILS_CCP_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_DETAILS
        ADD CONSTRAINT FK_PROJECTION_DETAILS_CCP_DETAILS_CCP_DETAILS_SID FOREIGN KEY(CCP_DETAILS_SID) REFERENCES CCP_DETAILS(CCP_DETAILS_SID)
  END

GO

--------------------------------------------------- PROJECTION_CUST_HIERARCHY -----------------------------------------
------------------------------------------------ RELATIONSHIP_LEVEL_SID REFERENCE FROM RELATIONSHIP_LEVEL_DEFINITION TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_CUST_HIERARCHY'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_CUST_HIERARCHY_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_CUST_HIERARCHY
        ADD CONSTRAINT FK_PROJECTION_CUST_HIERARCHY_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID FOREIGN KEY(RELATIONSHIP_LEVEL_SID) REFERENCES RELATIONSHIP_LEVEL_DEFINITION(RELATIONSHIP_LEVEL_SID)
  END

GO

------------------------------------------------ PROJECTION_MASTER_SID REFERENCE FROM PROJECTION_MASTER TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_CUST_HIERARCHY'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_CUST_HIERARCHY_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_CUST_HIERARCHY
        ADD CONSTRAINT FK_PROJECTION_CUST_HIERARCHY_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

------------------------------------------------------------- PROJECTION_PROD_HIERARCHY -------------------------------------------------------
----------------------------------------------- RELATIONSHIP_LEVEL_SID REFERENCE FROM RELATIONSHIP_LEVEL_DEFINITION TABLE ----------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_PROD_HIERARCHY'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_PROD_HIERARCHY_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_PROD_HIERARCHY
        ADD CONSTRAINT FK_PROJECTION_PROD_HIERARCHY_RELATIONSHIP_LEVEL_DEFINITION_RELATIONSHIP_LEVEL_SID FOREIGN KEY(RELATIONSHIP_LEVEL_SID) REFERENCES RELATIONSHIP_LEVEL_DEFINITION(RELATIONSHIP_LEVEL_SID)
  END

GO

----------------------------------------------- PROJECTION_MASTER_SID REFERENCE FROM PROJECTION_MASTER TABLE ----------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PROJECTION_PROD_HIERARCHY'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PROJECTION_PROD_HIERARCHY_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PROJECTION_PROD_HIERARCHY
        ADD CONSTRAINT FK_PROJECTION_PROD_HIERARCHY_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO 


----------------------------------------------- WORKFLOW_MASTER -----------------------------------------------

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE  TABLE_SCHEMA = 'DBO'
                      AND TABLE_NAME = 'WORKFLOW_MASTER'
                      AND CONSTRAINT_TYPE = 'FOREIGN KEY'
                      AND CONSTRAINT_NAME = 'FK_WORKFLOW_MASTER_PROJECTION_MASTER_PROJECTION_MASTER_SID')
  BEGIN
      ALTER TABLE [DBO].[WORKFLOW_MASTER]
        ADD CONSTRAINT [FK_WORKFLOW_MASTER_PROJECTION_MASTER_PROJECTION_MASTER_SID] FOREIGN KEY([PROJECTION_MASTER_SID]) REFERENCES [DBO].[PROJECTION_MASTER] ([PROJECTION_MASTER_SID])
  END 
GO

----------------------------------------------- WORKFLOW_PROCESS_INFO ----------------------------------------------- 

--CONTRACT_MASTER_SID
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'WORKFLOW_PROCESS_INFO'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_WORKFLOW_PROCESS_INFO_CONTRACT_MASTER_CONTRACT_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[WORKFLOW_PROCESS_INFO]
        ADD CONSTRAINT FK_WORKFLOW_PROCESS_INFO_CONTRACT_MASTER_CONTRACT_MASTER_SID FOREIGN KEY(CONTRACT_MASTER_SID) REFERENCES CONTRACT_MASTER (CONTRACT_MASTER_SID)
  END

GO 

--CFF_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_DETAILS_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFF_DETAILS
        ADD CONSTRAINT FK_CFF_DETAILS_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER(CFF_MASTER_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFF_DETAILS
        ADD CONSTRAINT FK_CFF_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_DETAILS_CCP_DETAILS_CCP_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFF_DETAILS
        ADD CONSTRAINT FK_CFF_DETAILS_CCP_DETAILS_CCP_DETAILS_SID FOREIGN KEY(CCP_DETAILS_SID) REFERENCES CCP_DETAILS(CCP_DETAILS_SID)
  END

GO

--CFF_DOC_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_DOC_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_DOC_DETAILS_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFF_DOC_DETAILS
        ADD CONSTRAINT FK_CFF_DOC_DETAILS_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER(CFF_MASTER_SID)
  END

GO

--CFF_APPROVAL_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_APPROVAL_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_APPROVAL_DETAILS_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFF_APPROVAL_DETAILS
        ADD CONSTRAINT FK_CFF_APPROVAL_DETAILS_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER(CFF_MASTER_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_APPROVAL_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_APPROVAL_DETAILS_HELPER_TABLE_HELPER_TABLE_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFF_APPROVAL_DETAILS
        ADD CONSTRAINT FK_CFF_APPROVAL_DETAILS_HELPER_TABLE_HELPER_TABLE_SID FOREIGN KEY(APPROVAL_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO

--CFF_ADDITIONAL_INFO
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFF_ADDITIONAL_INFO'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFF_ADDITIONAL_INFO_CFF_MASTER_CFF_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFF_ADDITIONAL_INFO
        ADD CONSTRAINT FK_CFF_ADDITIONAL_INFO_CFF_MASTER_CFF_MASTER_SID FOREIGN KEY(CFF_MASTER_SID) REFERENCES CFF_MASTER(CFF_MASTER_SID)
  END

GO 
------------------------------------------------------- NM_PROJECTION_SELECTION -------------------------------------------------

----------------------------------------------- PROJECTION_MASTER_SID REFERENCE FROM PROJECTION_MASTER ------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'NM_PROJECTION_SELECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NM_PROJECTION_SELECTION_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE NM_PROJECTION_SELECTION
        ADD CONSTRAINT FK_NM_PROJECTION_SELECTION_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END
GO

------------------------------------------------------- CUSTOM_VIEW_MASTER -------------------------------------------------

----------------------------------------------- PROJECTION_MASTER_SID REFERENCE FROM PROJECTION_MASTER ------------------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_CUSTOM_VIEW_MASTER_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TABLE_NAME = 'CUSTOM_VIEW_MASTER')
  BEGIN
      ALTER TABLE CUSTOM_VIEW_MASTER
        ADD CONSTRAINT FK_CUSTOM_VIEW_MASTER_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY (PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END
GO

------------------------------------------------------- CUSTOM_VIEW_DETAILS -------------------------------------------------

----------------------------------------------- PROJECTION_MASTER_SID REFERENCE FROM PROJECTION_MASTER ------------------------------------------
  IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'FK_CUSTOM_VIEW_DETAILS_CUSTOM_VIEW_MASTER_CUSTOM_VIEW_MASTER_SID'
                     AND TABLE_NAME = 'CUSTOM_VIEW_DETAILS')
  BEGIN
      ALTER TABLE CUSTOM_VIEW_DETAILS
        ADD CONSTRAINT FK_CUSTOM_VIEW_DETAILS_CUSTOM_VIEW_MASTER_CUSTOM_VIEW_MASTER_SID FOREIGN KEY (CUSTOM_VIEW_MASTER_SID) REFERENCES CUSTOM_VIEW_MASTER(CUSTOM_VIEW_MASTER_SID)
  END 
GO

--------------------------------------------------------------- WORKFLOW_PROCESS_INFO ---------------------------------------------------

----------------------------------------------- PROJECTION_MASTER_SID REFERENCE FROM PROJECTION_MASTER ------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_Name(PARENT_OBJECT_ID) = 'WORKFLOW_PROCESS_INFO'
                 AND scHema_Name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_WORKFLOW_PROCESS_INFO_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                 AND TYPE = 'F')
  BEGIN
      ALTER TABLE WORKFLOW_PROCESS_INFO
        ADD CONSTRAINT FK_WORKFLOW_PROCESS_INFO_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES [dbo].[PROJECTION_MASTER] ([PROJECTION_MASTER_SID])
  END

GO 

---------------------------------------------FK'S FOR WORKFLOW_INBOX----------------------------------------------------------------------------------------
--COMPANY_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'WORKFLOW_INBOX'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_WORKFLOW_INBOX_COMPANY_MASTER_GL_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE WORKFLOW_INBOX
        ADD CONSTRAINT FK_WORKFLOW_INBOX_COMPANY_MASTER_GL_COMPANY_MASTER_SID FOREIGN KEY(GL_COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO

------------------------------------------------------------FORECASTING_FORMULA----------------------------------------------------------------------

----------------------------------------------- HELPER_TABLE_SID REFERENCE FROM HELPER_TABLE------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_Name(PARENT_OBJECT_ID) = 'FORECASTING_FORMULA'
                 AND scHema_Name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_FORECASTING_FORMULA_HELPER_TABLE_FORMULA_TYPE'
                 AND TYPE = 'F')
BEGIN  
  ALTER TABLE [dbo].[FORECASTING_FORMULA]
    ADD CONSTRAINT FK_FORECASTING_FORMULA_HELPER_TABLE_FORMULA_TYPE FOREIGN KEY(FORMULA_TYPE)
	REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
END
GO

------------------------------------------------------------ADDITIONAL_NOTES----------------------------------------------------------------------
IF NOT EXISTS (SELECT 1 
               FROM   SYS.FOREIGN_KEYS 
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'ADDITIONAL_NOTES' 
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                      AND NAME = 'FK_ADDITIONAL_NOTES_CURRENCY' 
                      AND TYPE = 'F') 
  BEGIN 
      ALTER TABLE ADDITIONAL_NOTES 
        ADD CONSTRAINT FK_ADDITIONAL_NOTES_CURRENCY FOREIGN KEY (CURRENCY) REFERENCES HELPER_TABLE (HELPER_TABLE_SID)
  END 

GO 