IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_AL_HISTORY_CUSTOMER_SELECTION'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[ST_AL_HISTORY_CUSTOMER_SELECTION]
        (
           CONTRACT_MASTER_SID INT NOT NULL,
           COMPANY_MASTER_SID  INT NOT NULL,
           AVAILABLE_CHECKBOX  BIT NULL,
           SELECTED_CHECKBOX   BIT NULL,
           SELECTED_RECORDS    BIT NULL,
           USER_ID             INT NOT NULL,
           SESSION_ID          INT NOT NULL,
           LAST_MODIFIED_DATE  DATETIME
        )
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_AL_HISTORY_CUSTOMER_SELECTION'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ST_AL_HISTORY_CUSTOMER_SELECTION_CONTRACT_MASTER_SID_COMPANY_MASTER_SID_USER_ID_SESSION_ID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].[ST_AL_HISTORY_CUSTOMER_SELECTION]
        ADD CONSTRAINT PK_ST_AL_HISTORY_CUSTOMER_SELECTION_CONTRACT_MASTER_SID_COMPANY_MASTER_SID_USER_ID_SESSION_ID PRIMARY KEY (CONTRACT_MASTER_SID, COMPANY_MASTER_SID, USER_ID, SESSION_ID)
  END

GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_AL_HISTORY_ITEM_SELECTION'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[ST_AL_HISTORY_ITEM_SELECTION]
        (
           ITEM_MASTER_SID    INT NOT NULL,
           AVAILABLE_CHECKBOX BIT NULL,
           SELECTED_CHECKBOX  BIT,
           SELECTED_RECORDS   BIT,
           USER_ID            INT NOT NULL,
           SESSION_ID         INT NOT NULL,
           LAST_MODIFIED_DATE DATETIME
        )
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_AL_HISTORY_ITEM_SELECTION'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ST_AL_HISTORY_ITEM_SELECTION_ITEM_MASTER_SID_USER_ID_SESSION_ID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].[ST_AL_HISTORY_ITEM_SELECTION]
        ADD CONSTRAINT PK_ST_AL_HISTORY_ITEM_SELECTION_ITEM_MASTER_SID_USER_ID_SESSION_ID PRIMARY KEY (ITEM_MASTER_SID, USER_ID, SESSION_ID)
  END

GO 
