IF NOT EXISTS (
		SELECT 1
		FROM SYS.TABLE_TYPES
		WHERE NAME = 'UDT_FILE'
		)
CREATE TYPE [dbo].[UDT_FILE] AS TABLE(
	[FILE_TYPE] [varchar](100) NULL,
	[FILE_NAME] [varchar](100) NULL,
	[FILE_VERSION] [varchar](50) NULL
)
GO

