IF NOT EXISTS (SELECT 'X'
               FROM   SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'CUSTOMER_SALES'
                      AND Schema_name(SCHEMA_ID) = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[CUSTOMER_SALES]
        (
           HIERARCHY_NO    VARCHAR(8000) NOT NULL,
           PERIOD          SMALLINT NOT NULL,
           [YEAR]          SMALLINT NOT NULL,
           SALES           NUMERIC(22, 6) NULL,
           UNITS           NUMERIC(22, 6) NULL,
           SALES_INCLUSION BIT NULL,
           INDICATOR       BIT NULL,
           ACCOUNT_GROWTH  NUMERIC(22, 6) NULL,
           PRODUCT_GROWTH  NUMERIC(22, 6) NULL
        )
  END

GO

IF NOT EXISTS (SELECT 'X'
               FROM   SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'PRODUCT_SALES'
                      AND Schema_name(SCHEMA_ID) = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[PRODUCT_SALES]
        (
           HIERARCHY_NO    VARCHAR(8000) NOT NULL,
           PERIOD          SMALLINT NOT NULL,
           [YEAR]          SMALLINT NOT NULL,
           SALES           NUMERIC(22, 6) NULL,
           UNITS           NUMERIC(22, 6) NULL,
           SALES_INCLUSION BIT NULL,
           INDICATOR       BIT NULL,
           ACCOUNT_GROWTH  NUMERIC(22, 6) NULL,
           PRODUCT_GROWTH  NUMERIC(22, 6) NULL
        )
  END

GO

IF NOT EXISTS (SELECT 'X'
               FROM   SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'CUSTOM_DISCOUNT'
                      AND Schema_name(SCHEMA_ID) = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[CUSTOM_DISCOUNT]
        (
           HIERARCHY_NO        INT NOT NULL,
           RS_CONTRACT_SID     INT NOT NULL,
           PERIOD              SMALLINT NOT NULL,
           [YEAR]              SMALLINT NOT NULL,
           DISCOUNT            NUMERIC(22, 6) NULL,
           SALES               NUMERIC(22, 6) NULL,
           UNITS               NUMERIC(22, 6) NULL,
           DEDUCTION_INCLUSION BIT NULL,
           INDICATOR           BIT NULL,
           GROWTH              NUMERIC(22, 6)
        )
  END

GO

IF NOT EXISTS (SELECT 'X'
               FROM   SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'CUSTOM_SALES'
                      AND Schema_name(SCHEMA_ID) = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[CUSTOM_SALES]
        (
           HIERARCHY_NO    INT NOT NULL,
           PERIOD          SMALLINT NOT NULL,
           [YEAR]          SMALLINT NOT NULL,
           SALES           NUMERIC(22, 6) NULL,
           UNITS           NUMERIC(22, 6) NULL,
           SALES_INCLUSION SMALLINT NOT NULL,
           INDICATOR       BIT NOT NULL,
           ACCOUNT_GROWTH  NUMERIC(22, 6) NULL,
           PRODUCT_GROWTH  NUMERIC(22, 6) NULL
        )
  END

GO
------------------ALTERING TO NOT NULL
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUSTOM_SALES'
                  AND COLUMN_NAME = 'SALES_INCLUSION'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUSTOM_SALES
        ALTER COLUMN SALES_INCLUSION SMALLINT NOT NULL
  END

GO
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUSTOM_SALES'
                  AND COLUMN_NAME = 'INDICATOR'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUSTOM_SALES
        ALTER COLUMN INDICATOR BIT NOT NULL
  END

GO
IF NOT EXISTS (SELECT 1
               FROM   SYS.KEY_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CUSTOM_SALES'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'PK_CUSTOM_SALES_HIERARCHY_NO_PERIOD_YEAR_SALES_INCLUSION_INDICATOR'
                      AND TYPE = 'PK')
  BEGIN
      ALTER TABLE CUSTOM_SALES
        ADD CONSTRAINT PK_CUSTOM_SALES_HIERARCHY_NO_PERIOD_YEAR_SALES_INCLUSION_INDICATOR PRIMARY KEY ( HIERARCHY_NO,
PERIOD,
YEAR,
SALES_INCLUSION,
INDICATOR
 )
  END

GO
IF NOT EXISTS (SELECT 'X'
               FROM   SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'CUSTOMER_DISCOUNT'
                      AND Schema_name(SCHEMA_ID) = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[CUSTOMER_DISCOUNT]
        (
           HIERARCHY_NO        VARCHAR(8000) NOT NULL,
           RS_CONTRACT_SID     INT NOT NULL,
           PERIOD              SMALLINT NOT NULL,
           [YEAR]              SMALLINT NOT NULL,
           DISCOUNT            NUMERIC(22, 6) NULL,
           SALES               NUMERIC(22, 6) NULL,
           UNITS               NUMERIC(22, 6) NULL,
           DEDUCTION_INCLUSION BIT NULL,
           INDICATOR           BIT NULL,
           GROWTH              NUMERIC(22, 6)
        )
  END

GO
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUSTOMER_DISCOUNT'
                  AND COLUMN_NAME = 'RS_CONTRACT_SID'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUSTOMER_DISCOUNT
        DROP COLUMN RS_CONTRACT_SID
  END

GO
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUSTOMER_DISCOUNT'
                  AND COLUMN_NAME = 'SALES'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUSTOMER_DISCOUNT
        DROP COLUMN SALES
  END

GO
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUSTOMER_DISCOUNT'
                  AND COLUMN_NAME = 'UNITS'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUSTOMER_DISCOUNT
        DROP COLUMN UNITS
  END

GO
------------------altering to not null
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUSTOMER_DISCOUNT'
                  AND COLUMN_NAME = 'DEDUCTION_INCLUSION'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUSTOMER_DISCOUNT
        ALTER COLUMN DEDUCTION_INCLUSION SMALLINT NOT NULL
  END

GO
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUSTOMER_DISCOUNT'
                  AND COLUMN_NAME = 'INDICATOR'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUSTOMER_DISCOUNT
        ALTER COLUMN INDICATOR BIT NOT NULL
  END

GO
IF NOT EXISTS (SELECT 1
               FROM   SYS.KEY_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'CUSTOMER_DISCOUNT'
                      AND Schema_name(SCHEMA_ID) = 'DBO'
                      AND NAME = 'PK_CUSTOMER_DISCOUNT_HIERARCHY_NO_PERIOD_YEAR_DEDUCTION_INCLUSION_INDICATOR'
                      AND TYPE = 'PK')
  BEGIN
      ALTER TABLE CUSTOMER_DISCOUNT
        ADD CONSTRAINT PK_CUSTOMER_DISCOUNT_HIERARCHY_NO_PERIOD_YEAR_DEDUCTION_INCLUSION_INDICATOR PRIMARY KEY ( HIERARCHY_NO,
PERIOD,
YEAR,
DEDUCTION_INCLUSION,
INDICATOR
 )
  END

GO
IF NOT EXISTS (SELECT 'X'
               FROM   SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'PRODUCT_DISCOUNT'
                      AND Schema_name(SCHEMA_ID) = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[PRODUCT_DISCOUNT]
        (
           HIERARCHY_NO        VARCHAR(8000) NOT NULL,
           RS_CONTRACT_SID     INT NOT NULL,
           PERIOD              SMALLINT NOT NULL,
           [YEAR]              SMALLINT NOT NULL,
           SALES               NUMERIC(22, 6) NULL,
           UNITS               NUMERIC(22, 6) NULL,
           DISCOUNT            NUMERIC(22, 6) NULL,
           DEDUCTION_INCLUSION BIT NULL,
           INDICATOR           BIT NULL,
           GROWTH              NUMERIC(22, 6)
        )
  END

GO 