IF NOT EXISTS (SELECT 'X'
               FROM   SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'CUST_VIEW_MASTER'
                      AND Schema_name(SCHEMA_ID) = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[CUST_VIEW_MASTER]
        (
           CUST_VIEW_MASTER_SID      INT NOT NULL IDENTITY(1, 1),
           CUST_VIEW_NAME            VARCHAR(100) NULL,
           CUST_VIEW_DESCRIPTION     VARCHAR(100) NULL,
           CUST_VIEW_TYPE            VARCHAR(100) NULL,
           CUSTOMER_RELATIONSHIP_SID INT NULL,
           PRODUCT_RELATIONSHIP_SID  INT NOT NULL,
           CREATED_BY                INT NULL,
           CREATED_DATE              DATETIME NULL,
           MODIFIED_BY               INT NULL,
           MODIFIED_DATE             DATETIME NULL,
           SCREEN_NAME               VARCHAR(100) NULL
        )
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.KEY_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'CUST_VIEW_MASTER'
                      AND Schema_name(SCHEMA_ID) = 'DBO'
                      AND NAME = 'PK_CUST_VIEW_MASTER_CUST_VIEW_MASTER_SID'
                      AND TYPE = 'PK')
  BEGIN
      ALTER TABLE CUST_VIEW_MASTER
        ADD CONSTRAINT PK_CUST_VIEW_MASTER_CUST_VIEW_MASTER_SID PRIMARY KEY (CUST_VIEW_MASTER_SID)
  END

GO
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUST_VIEW_MASTER'
                  AND COLUMN_NAME = 'LEVEL_NAME'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUST_VIEW_MASTER
        DROP COLUMN LEVEL_NAME
  END

GO

IF NOT EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUST_VIEW_MASTER'
                  AND COLUMN_NAME = 'MODULE_TYPE'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUST_VIEW_MASTER
        ADD MODULE_TYPE INT NULL
  END
  
GO


IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CUST_VIEW_MASTER'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CUST_VIEW_MASTER_HELPER_TABLE_MODULE_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CUST_VIEW_MASTER
        ADD CONSTRAINT FK_CUST_VIEW_MASTER_HELPER_TABLE_MODULE_TYPE FOREIGN KEY(MODULE_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
  
 GO

IF NOT EXISTS (SELECT 'X'
               FROM   SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'CUST_VIEW_DETAILS'
                      AND Schema_name(SCHEMA_ID) = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[CUST_VIEW_DETAILS]
        (
           CUSTOM_VIEW_DETAILS_SID INT NOT NULL IDENTITY(1, 1),
           CUSTOM_VIEW_MASTER_SID  INT,
           HIERARCHY_ID            INT,
           HIERARCHY_INDICATOR     CHAR(1),
           LEVEL_NO                INT
        )
  END

GO
IF NOT EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUST_VIEW_DETAILS'
                  AND COLUMN_NAME = 'LEVEL_NAME'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUST_VIEW_DETAILS
        ADD LEVEL_NAME VARCHAR(50)
  END

GO


IF NOT EXISTS (SELECT 1
               FROM   SYS.KEY_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'CUST_VIEW_DETAILS'
                      AND Schema_name(SCHEMA_ID) = 'DBO'
                      AND NAME = 'PK_CUST_VIEW_DETAILS_CUSTOM_VIEW_DETAILS_SID'
                      AND TYPE = 'PK')
  BEGIN
      ALTER TABLE CUST_VIEW_DETAILS
        ADD CONSTRAINT PK_CUST_VIEW_DETAILS_CUSTOM_VIEW_DETAILS_SID PRIMARY KEY (CUSTOM_VIEW_DETAILS_SID)
  END

GO 

IF NOT EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'CUST_VIEW_DETAILS'
                  AND COLUMN_NAME = 'VARIABLE_COUNT'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE CUST_VIEW_DETAILS
        ADD VARIABLE_COUNT INT
  END

GO
IF NOT EXISTS (SELECT name FROM sys.indexes  
            WHERE name = N'IDX_CUST_VIEW_DETAILS_CUSTOM_VIEW_MASTER_SID_HIERARCHY_INDICATOR')   
BEGIN
CREATE NONCLUSTERED INDEX IDX_CUST_VIEW_DETAILS_CUSTOM_VIEW_MASTER_SID_HIERARCHY_INDICATOR
    ON CUST_VIEW_DETAILS (CUSTOM_VIEW_MASTER_SID) INCLUDE(HIERARCHY_INDICATOR);
END     
GO  
