IF NOT EXISTS (
		SELECT 'X'
		FROM SYS.TABLES
		WHERE OBJECT_NAME(OBJECT_ID) = 'CUSTOM_CCP_DETAILS'
			AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
		)
BEGIN
	CREATE TABLE [DBO].[CUSTOM_CCP_DETAILS] (
		CUSTOMER_RELATIONSHIP_BUILDER_SID INT NOT NULL,
		PRODUCT_RELATIONSHIP_BUILDER_SID INT NOT NULL,
		CUSTOMER_VERSION INT NOT NULL,
		PRODUCT_VERSION INT NOT NULL,
		CCP_DETAILS_SID INT NOT NULL,
		CUST_HIERARCHY_NO VARCHAR(100),
		PROD_HIERARCHY_NO VARCHAR(100),
		CUST_VIEW_MASTER_SID INT NOT NULL
		)
END
GO


IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CUSTOM_CCP_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_CUSTOM_CCP_DETAILS_CUST_VIEW_MASTER_SID_CUSTOMER_RELATIONSHIP_BUILDER_SID_PRODUCT_RELATIONSHIP_BUILDER_SID_CCP_DETAILS_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE CUSTOM_CCP_DETAILS
        ADD CONSTRAINT PK_CUSTOM_CCP_DETAILS_CUST_VIEW_MASTER_SID_CUSTOMER_RELATIONSHIP_BUILDER_SID_PRODUCT_RELATIONSHIP_BUILDER_SID_CCP_DETAILS_SID PRIMARY KEY(CUST_VIEW_MASTER_SID,CUSTOMER_RELATIONSHIP_BUILDER_SID, PRODUCT_RELATIONSHIP_BUILDER_SID,CCP_DETAILS_SID)
  END
   GO