IF NOT EXISTS (
				SELECT 1 
				FROM SYS.TABLES 
			    WHERE  Object_name(OBJECT_ID) = 'CUSTOM_SALES_REPORT'
                      AND Schema_name(SCHEMA_ID) = 'dbo')
	 BEGIN
      	CREATE TABLE [dbo].[CUSTOM_SALES_REPORT]
		(
			CCP_DETAILS_SID		INT NOT NULL,
			PERIOD				TINYINT NOT NULL,
			YEAR				SMALLINT NOT NULL,
			SALES				NUMERIC(22,6) NULL,
			EXFACTORY_SALES		NUMERIC(22,6) NULL,
			SALES_INCLUSION		INT  NULL,
			UNITS				NUMERIC(22,6) NULL,
			INDICATOR			BIT NOT NULL			
		)
	END
GO

--- ALTER CUSTOMER_SALES_REPORT TABLE FOR PK CONSTRAINT

IF NOT EXISTS 
			(
				SELECT 1
				FROM SYS.KEY_CONSTRAINTS
				WHERE Object_name(PARENT_OBJECT_ID) = 'CUSTOM_SALES_REPORT'
					AND Schema_name(SCHEMA_ID) = 'dbo'
					AND NAME = 'PK_CUSTOM_SALES_REPORT_CCP_DETAILS_SID_PERIOD_YEAR_INDICATOR'
					AND TYPE = 'PK'
			)
			BEGIN
					ALTER TABLE CUSTOM_SALES_REPORT ADD CONSTRAINT PK_CUSTOM_SALES_REPORT_CCP_DETAILS_SID_PERIOD_YEAR_INDICATOR PRIMARY KEY 
					(
						CCP_DETAILS_SID,
						PERIOD,
						YEAR,
						INDICATOR
					)
				END
GO

--- 2. FOR CUSTOMER_DISCOUNT_REPORT TABLE CREATION
IF NOT EXISTS 
			(
				SELECT 1 
				FROM SYS.TABLES
				WHERE object_name(OBJECT_ID) = 'CUSTOM_DISCOUNT_REPORT'
					AND schema_name(SCHEMA_ID) = 'dbo'
			)
		BEGIN
			CREATE TABLE [dbo].[CUSTOM_DISCOUNT_REPORT]
			(
				CCP_DETAILS_SID		INT NOT NULL,
				RS_CONTRACT_SID INT NOT NULL,
				PERIOD					TINYINT NOT NULL,
				YEAR					SMALLINT NOT NULL,
				DISCOUNT				NUMERIC(22,6) NULL,
				ACCURAL_DISCOUNT		NUMERIC(22,6) NULL,
				DEDUCTION_INCLUSION		TINYINT  NULL,
				INDICATOR				BIT NOT NULL
			)			
		END
GO

---  ALTER CUSTOMER_DISCOUNT_REPORT TABLE FOR PK CONSTRAINT
IF NOT EXISTS	
			(
				SELECT 1 
				FROM SYS.KEY_CONSTRAINTS
				WHERE object_name(PARENT_OBJECT_ID) = 'CUSTOM_DISCOUNT_REPORT'
					AND schema_name(SCHEMA_ID) = 'dbo'
					AND NAME = 'PK_CUSTOM_DISCOUNT_REPORT_CCP_DETAILS_SID_RS_CONTRACT_SID_PERIOD_YEAR_INDICATOR'
					AND TYPE = 'PK'
			)
			BEGIN 
					ALTER TABLE CUSTOM_DISCOUNT_REPORT ADD CONSTRAINT PK_CUSTOM_DISCOUNT_REPORT_CCP_DETAILS_SID_RS_CONTRACT_SID_PERIOD_YEAR_INDICATOR PRIMARY KEY
					(
						CCP_DETAILS_SID,
						RS_CONTRACT_SID,			
						PERIOD ,					
						YEAR ,					
						INDICATOR				
					)
			END
GO


--- 3. FOR APPROVED_REPORT TABLE CREATION
IF NOT EXISTS 
			(
				SELECT 1 
				FROM SYS.TABLES
				WHERE object_name(OBJECT_ID) = 'APPROVED_REPORT'
					AND schema_name(SCHEMA_ID) = 'dbo'
			)
		BEGIN
			CREATE TABLE [dbo].[APPROVED_REPORT]
			(
				CCP_DETAILS_SID		INT NOT NULL,
				RS_CONTRACT_SID INT NOT NULL,
				PERIOD					TINYINT NOT NULL,
				YEAR					SMALLINT NOT NULL,
				PROJECTION_MASTER_SID	INT NOT NULL,
				SALES					NUMERIC(22,6) NULL,
				UNITS					NUMERIC(22,6) NULL,
				DISCOUNT				NUMERIC(22,6) NULL,
				EXFACTORY_SALES         NUMERIC(22,6) NULL,
				ACCURAL_DISCOUNT		NUMERIC(22,6) NULL,
				INDICATOR               BIT NOT NULL
			)			
		END
GO

---  ALTER APPROVED_REPORT TABLE FOR PK CONSTRAINT
IF NOT EXISTS 
			(
				SELECT 1 
				FROM SYS.KEY_CONSTRAINTS
				WHERE object_name(PARENT_OBJECT_ID) = 'APPROVED_REPORT'
					AND schema_name(SCHEMA_ID) = 'dbo'
					AND NAME = 'PK_APPROVED_REPORT_CCP_DETAILS_SID_RS_CONTRACT_SID_PERIOD_YEAR_PROJECTION_MASTER_SID_INDICATOR'
					AND TYPE = 'PK'
			)
		BEGIN
				ALTER TABLE APPROVED_REPORT ADD CONSTRAINT PK_APPROVED_REPORT_CCP_DETAILS_SID_RS_CONTRACT_SID_PERIOD_YEAR_PROJECTION_MASTER_SID_INDICATOR PRIMARY KEY
				(
					CCP_DETAILS_SID ,
					RS_CONTRACT_SID,
					PERIOD ,
					YEAR ,
					PROJECTION_MASTER_SID,
					INDICATOR
				)				
		END
GO


-- Re-runnable script for VARIABLE_BR_REPORT table
IF NOT EXISTS (SELECT 'X'
               FROM     SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'VARIABLE_BR_REPORT'
                      AND Schema_name(SCHEMA_ID) = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[VARIABLE_BR_REPORT]
        (
           MASTER_SID           INT NOT NULL ,
           PERIOD               INT NOT NULL,
           [YEAR]               INT NOT NULL,
           SELECTED_VARIABLE	TINYINT NOT NULL
        )
  END
  
IF NOT EXISTS (SELECT 1
			   FROM SYS.KEY_CONSTRAINTS
			   WHERE Object_name(PARENT_OBJECT_ID) = 'VARIABLE_BR_REPORT'
			   		AND Schema_name(SCHEMA_ID) = 'DBO'
					AND NAME = 'PK_VARIABLE_BR_REPORT_MASTER_SID_PERIOD_YEAR'
					AND TYPE = 'PK'
			   )
	BEGIN
		ALTER TABLE VARIABLE_BR_REPORT 
		ADD CONSTRAINT PK_VARIABLE_BR_REPORT_MASTER_SID_PERIOD_YEAR 
		PRIMARY KEY 
		(
		    MASTER_SID,
			PERIOD,
			[YEAR]
		)
END
GO

-- Re-runnable script for COMPARISION_REPORT table
IF NOT EXISTS (SELECT 'X'
               FROM     SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'COMPARISION_REPORT'
                      AND Schema_name(SCHEMA_ID) = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[COMPARISION_REPORT]
        (
           PROJECTION_MASTER_SID	INT NOT NULL ,
           PERIOD               	INT NOT NULL,
           [YEAR]               	INT NOT NULL,
           SELECTED_VARIABLE		SMALLINT NOT NULL
        )
  END
  
IF NOT EXISTS (SELECT 1
			   FROM SYS.KEY_CONSTRAINTS
			   WHERE Object_name(PARENT_OBJECT_ID) = 'COMPARISION_REPORT'
			   		AND Schema_name(SCHEMA_ID) = 'DBO'
					AND NAME = 'PK_COMPARISION_REPORT_PROJECTION_MASTER_SID_PERIOD_YEAR'
					AND TYPE = 'PK'
			   )
	BEGIN
		ALTER TABLE COMPARISION_REPORT 
		ADD CONSTRAINT PK_COMPARISION_REPORT_PROJECTION_MASTER_SID_PERIOD_YEAR 
		PRIMARY KEY 
		(  PROJECTION_MASTER_SID,
			PERIOD,
			[YEAR]
		)
END
GO

--CUSTOM_VIEW_VARIABLES

IF NOT EXISTS (SELECT 'X'
               FROM     SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'CUSTOM_VIEW_VARIABLES'
                      AND Schema_name(SCHEMA_ID) = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[CUSTOM_VIEW_VARIABLES]
        (
           CUSTOM_VIEW_DETAILS_SID	INT NOT NULL ,
           VARIABLE_SID             INT NOT NULL,
           VARIABLE_INDICATOR       CHAR(1) NOT NULL
        )
  END
  
IF NOT EXISTS (SELECT 1
			   FROM SYS.KEY_CONSTRAINTS
			   WHERE Object_name(PARENT_OBJECT_ID) = 'CUSTOM_VIEW_VARIABLES'
			   		AND Schema_name(SCHEMA_ID) = 'DBO'
					AND NAME = 'PK_CUSTOM_VIEW_VARIABLES_CUSTOM_VIEW_DETAILS_SID_VARIABLE_SID_VARIABLE_INDICATOR'
					AND TYPE = 'PK'
			   )
	BEGIN
		ALTER TABLE CUSTOM_VIEW_VARIABLES 
		ADD CONSTRAINT PK_CUSTOM_VIEW_VARIABLES_CUSTOM_VIEW_DETAILS_SID_VARIABLE_SID_VARIABLE_INDICATOR 
		PRIMARY KEY 
		(CUSTOM_VIEW_DETAILS_SID,
			VARIABLE_SID,
			VARIABLE_INDICATOR
		)
END
GO


---------------FOREIGN KEYS
-------------------------------- PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CUSTOM_VIEW_VARIABLES'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NM_CUSTOM_VIEW_VARIABLES_CUST_VIEW_DETAILS_CUSTOM_VIEW_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CUSTOM_VIEW_VARIABLES
        ADD CONSTRAINT FK_NM_CUSTOM_VIEW_VARIABLES_CUST_VIEW_DETAILS_CUSTOM_VIEW_DETAILS_SID FOREIGN KEY(CUSTOM_VIEW_DETAILS_SID) REFERENCES CUST_VIEW_DETAILS(CUSTOM_VIEW_DETAILS_SID)
  END 
GO


IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CUSTOM_VIEW_VARIABLES'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NM_CUSTOM_VIEW_VARIABLES_HELPER_TABLE_VARIABLE_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CUSTOM_VIEW_VARIABLES
        ADD CONSTRAINT FK_NM_CUSTOM_VIEW_VARIABLES_HELPER_TABLE_VARIABLE_SID FOREIGN KEY(VARIABLE_SID) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END 
GO

------------CUSTOM_VARIABLE_HIERARCHY

IF NOT EXISTS (SELECT 'X'
               FROM     SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'CUSTOM_VARIABLE_HIERARCHY'
                      AND Schema_name(SCHEMA_ID) = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[CUSTOM_VARIABLE_HIERARCHY]
        (
           HIERARCHY_NO	INT NOT NULL ,
           LEVELNO             INT NOT NULL,
           CUSTOM_VIEW_DETAILS_SID       CHAR(1) NOT NULL,
		   RELATIONSHIP_LEVEL_VALUES     INT,
		   ROWID						INT

        )
  END
  
IF NOT EXISTS (SELECT 1
			   FROM SYS.KEY_CONSTRAINTS
			   WHERE Object_name(PARENT_OBJECT_ID) = 'CUSTOM_VARIABLE_HIERARCHY'
			   		AND Schema_name(SCHEMA_ID) = 'DBO'
					AND NAME = 'PK_CUSTOM_VARIABLE_HIERARCHY_HIERARCHY_NO_LEVEL_NO_CUSTOM_VIEW_DETAILS_SID'
					AND TYPE = 'PK'
			   )
	BEGIN
		ALTER TABLE CUSTOM_VIEW_VARIABLES 
		ADD CONSTRAINT PK_CUSTOM_VIEW_VARIABLES_CUSTOM_VIEW_DETAILS_SID_VARIABLE_SID_VARIABLE_INDICATOR 
		PRIMARY KEY 
		(HIERARCHY_NO,
			LEVEL_NO,
			CUSTOM_VIEW_DETAILS_SID
		)
END
GO
