IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = 'CUSTOMER_CFF_SALES'
			AND TABLE_SCHEMA = 'DBO'
		)
	CREATE TABLE CUSTOMER_CFF_SALES (
		HIERARCHY_NO VARCHAR(1000) NOT NULL
		,PERIOD SMALLINT NOT NULL
		,YEAR SMALLINT NOT NULL
		,SALES NUMERIC(22, 6)
		,UNITS NUMERIC(22, 6)
		,INDICATOR BIT
		,SALES_INCLUSION SMALLINT
		,FILTER_CCP BIT
		,CFF_MASTER_SID INT
		,COGS_VALUE NUMERIC(22, 6)
		)
GO

IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = 'PRODUCT_CFF_SALES'
			AND TABLE_SCHEMA = 'DBO'
		)
	CREATE TABLE PRODUCT_CFF_SALES (
		HIERARCHY_NO VARCHAR(1000) NOT NULL
		,PERIOD SMALLINT NOT NULL
		,YEAR SMALLINT NOT NULL
		,SALES NUMERIC(22, 6)
		,UNITS NUMERIC(22, 6)
		,INDICATOR BIT
		,SALES_INCLUSION SMALLINT
		,FILTER_CCP BIT
		,CFF_MASTER_SID INT
		,COGS_VALUE NUMERIC(22, 6)
		)
GO

IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = 'CUSTOM_CFF_SALES'
			AND TABLE_SCHEMA = 'DBO'
		)
	CREATE TABLE CUSTOM_CFF_SALES (
		HIERARCHY_NO INT NOT NULL
		,PERIOD SMALLINT NOT NULL
		,YEAR SMALLINT NOT NULL
		,SALES NUMERIC(22, 6)
		,UNITS NUMERIC(22, 6)
		,INDICATOR BIT NOT NULL
		,SALES_INCLUSION SMALLINT NOT NULL
		,FILTER_CCP BIT
		,CFF_MASTER_SID INT NOT NULL
		,COGS_VALUE NUMERIC(22, 6)
		)
GO

---------Primary Key
IF NOT EXISTS (
		SELECT 1
		FROM SYS.KEY_CONSTRAINTS
		WHERE Object_name(PARENT_OBJECT_ID) = 'CUSTOM_CFF_SALES'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'PK_CUSTOM_CFF_SALES_HIERARCHY_NO_PERIOD_YEAR_INDICATOR_CFF_MASTER_SID_SALES_INCLUSION'
			AND TYPE = 'PK'
		)
BEGIN
	ALTER TABLE CUSTOM_CFF_SALES ADD CONSTRAINT PK_CUSTOM_CFF_SALES_HIERARCHY_NO_PERIOD_YEAR_INDICATOR_CFF_MASTER_SID_SALES_INCLUSION PRIMARY KEY (
		HIERARCHY_NO
		,CFF_MASTER_SID
		,PERIOD
		,YEAR
		,SALES_INCLUSION
		,INDICATOR
		)
END
GO
IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = 'CUSTOMER_CFF_DISCOUNT'
			AND TABLE_SCHEMA = 'DBO'
		)
	CREATE TABLE CUSTOMER_CFF_DISCOUNT (
		HIERARCHY_NO VARCHAR(1000) NOT NULL
		,PERIOD SMALLINT NOT NULL
		,YEAR SMALLINT NOT NULL
		,SALES NUMERIC(22, 6)
		,UNITS NUMERIC(22, 6)
		,INDICATOR BIT
		,DEDUCTION_INCLUSION SMALLINT
		,FILTER_CCP BIT
		,CFF_MASTER_SID INT
		,ACCRUALS NUMERIC(22, 6)
		,EXFACTORY_ACTUAL_SALES NUMERIC(22, 6)
		,EXFACTORY_FORECAST_SALES NUMERIC(22, 6)
		,DISCOUNT NUMERIC(22, 6)
		,RS_CONTRACT_SID INT
		,DISCOUNT_TYPE TINYINT
		)
GO

IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = 'PRODUCT_CFF_DISCOUNT'
			AND TABLE_SCHEMA = 'DBO'
		)
	CREATE TABLE PRODUCT_CFF_DISCOUNT (
		HIERARCHY_NO VARCHAR(1000) NOT NULL
		,PERIOD SMALLINT NOT NULL
		,YEAR SMALLINT NOT NULL
		,SALES NUMERIC(22, 6)
		,UNITS NUMERIC(22, 6)
		,INDICATOR BIT
		,DEDUCTION_INCLUSION SMALLINT
		,FILTER_CCP BIT
		,CFF_MASTER_SID INT
		,ACCRUALS NUMERIC(22, 6)
		,EXFACTORY_ACTUAL_SALES NUMERIC(22, 6)
		,EXFACTORY_FORECAST_SALES NUMERIC(22, 6)
		,DISCOUNT NUMERIC(22, 6)
		,RS_CONTRACT_SID INT
		,DISCOUNT_TYPE TINYINT
		)
GO

IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = 'CUSTOM_CFF_DISCOUNT'
			AND TABLE_SCHEMA = 'DBO'
		)
	CREATE TABLE CUSTOM_CFF_DISCOUNT (
		HIERARCHY_NO INT NOT NULL
		,PERIOD SMALLINT NOT NULL
		,YEAR SMALLINT NOT NULL
		,SALES NUMERIC(22, 6)
		,UNITS NUMERIC(22, 6)
		,INDICATOR BIT NOT NULL
		,DEDUCTION_INCLUSION SMALLINT NOT NULL
		,FILTER_CCP BIT
		,CFF_MASTER_SID INT NOT NULL
		,ACCRUALS NUMERIC(22, 6)
		,EXFACTORY_ACTUAL_SALES NUMERIC(22, 6)
		,EXFACTORY_FORECAST_SALES NUMERIC(22, 6)
		,DISCOUNT NUMERIC(22, 6)
		,RS_CONTRACT_SID INT NOT NULL
		,DISCOUNT_TYPE TINYINT
		)
GO

---PK
--IF NOT EXISTS (
--		SELECT 1
--		FROM SYS.KEY_CONSTRAINTS
--		WHERE Object_name(PARENT_OBJECT_ID) = 'CUSTOM_CFF_DISCOUNT'
--			AND Schema_name(SCHEMA_ID) = 'DBO'
--			AND NAME = 'PK_CUSTOM_CFF_SALES_HIERARCHY_NO_PERIOD_YEAR_INDICATOR_CFF_MASTER_SID_DEDUCTION_INCLUSION'
--			AND TYPE = 'PK'
--		)
--BEGIN
--	ALTER TABLE CUSTOM_CFF_DISCOUNT ADD CONSTRAINT PK_CUSTOM_CFF_SALES_HIERARCHY_NO_PERIOD_YEAR_INDICATOR_CFF_MASTER_SID_DEDUCTION_INCLUSION PRIMARY KEY (
--		HIERARCHY_NO
--		,RS_CONTRACT_SID
--		,CFF_MASTER_SID
--		,PERIOD
--		,YEAR
--		,DEDUCTION_INCLUSION
--		,INDICATOR
--		)
--END
--GO
IF EXISTS (
		SELECT 1
		FROM SYS.KEY_CONSTRAINTS
		WHERE Object_name(PARENT_OBJECT_ID) = 'CUSTOM_CFF_DISCOUNT'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'PK_CUSTOM_CFF_SALES_HIERARCHY_NO_PERIOD_YEAR_INDICATOR_CFF_MASTER_SID_DEDUCTION_INCLUSION'
			AND TYPE = 'PK'
		)
BEGIN
	ALTER TABLE CUSTOM_CFF_DISCOUNT drop CONSTRAINT PK_CUSTOM_CFF_SALES_HIERARCHY_NO_PERIOD_YEAR_INDICATOR_CFF_MASTER_SID_DEDUCTION_INCLUSION
END
GO
IF NOT EXISTS (
		SELECT 1
		FROM SYS.KEY_CONSTRAINTS
		WHERE Object_name(PARENT_OBJECT_ID) = 'CUSTOM_CFF_DISCOUNT'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'PK_CUSTOM_CFF_DISCOUNT_HIERARCHY_NO_RS_CONTRACT_SID_CFF_MASTER_SID_PERIOD_YEAR_DEDUCTION_INCLUSION_INDICATOR'
			AND TYPE = 'PK'
		)
BEGIN
	ALTER TABLE CUSTOM_CFF_DISCOUNT ADD CONSTRAINT PK_CUSTOM_CFF_DISCOUNT_HIERARCHY_NO_RS_CONTRACT_SID_CFF_MASTER_SID_PERIOD_YEAR_DEDUCTION_INCLUSION_INDICATOR PRIMARY KEY (
		HIERARCHY_NO
		,RS_CONTRACT_SID
		,CFF_MASTER_SID
		,PERIOD
		,YEAR
		,DEDUCTION_INCLUSION
		,INDICATOR
		)
END
GO
IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'CFF_MASTER'
			AND COLUMN_NAME = 'CUSTOM_VW_MASTR_SALES'
		)
BEGIN
	ALTER TABLE CFF_MASTER ADD CUSTOM_VW_MASTR_SALES INT
END
GO

IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'CFF_MASTER'
			AND COLUMN_NAME = 'CUSTOM_VW_MASTR_DISCOUNT'
		)
BEGIN
	ALTER TABLE CFF_MASTER ADD CUSTOM_VW_MASTR_DISCOUNT INT
END
GO

