package org.r2.etl.common.action;
import java.util.HashMap;
import java.util.Map;

public class FileNameUtil {
	private static final  Map<String,String> map=new HashMap<String,String>();
	private static final  Map<String,String> interfaceNameMap=new HashMap<String,String>();
	
//	public static void main(String[] arg) {
//		String key="/opt/etlgal/Interface_Job/.extract/webapps/BPI_ETL/WEB-INF/classes//COMPANY_MASTER_INTERFACE_HISTORY/COMPANY_MASTER_INTERFACE_HISTORY.kjb";
//		String subKey[]=key.split("/");
//		System.out.println(subKey[subKey.length-1]);
//		System.out.println(subKey[subKey.length-2]);
////		System.out.println(key.substring(key.indexOf('/')+1,key.lastIndexOf('/')));
//	}
	public static Map<String, String> getMap() {
		if(map.isEmpty()){
			map.put("COMPANY_MASTER_INTERFACE", "COMPANY_MASTER_INTERFACE");
			map.put("COMPANY_MASTER_INTERFACE_HISTORY", "COMPANY_MASTER_INTERFACE");
			map.put("COMPANY_PARENT_HISTORY_INTERFACE", "COMPANY_PARENT_INTERFACE");
			map.put("COMPANY_PARENT_INTERFACE", "COMPANY_PARENT_INTERFACE");
			map.put("COMPANY_TRADE_CLASS_HISTORY_INTERFACE", "COMPANY_TRADE_CLASS_INTERFACE");
			map.put("COMPANY_TRADE_CLASS_INTERFACE", "COMPANY_TRADE_CLASS_INTERFACE");
			map.put("COMPANY_IDENTIFIER_INTERFACE_HISTORY", "COMPANY_IDENTIFIER_INTERFACE");
			map.put("COMPANY_IDENTIFIER_INTERFACE", "COMPANY_IDENTIFIER_INTERFACE");			
			map.put("ITEM_MASTER_INTERFACE", "ITEM_MASTER_INTERFACE");
			map.put("ITEM_MASTER_INTERFACE_HISTORY", "ITEM_MASTER_INTERFACE");
			map.put("ITEM_PRICING_INTERFACE", "ITEM_PRICING_INTERFACE");
			map.put("ITEM_PRICING_INTERFACE_HISTORY", "ITEM_PRICING_INTERFACE");
			map.put("ITEM_IDENTIFIER_INTERFACE_HISTORY", "ITEM_IDENTIFIER_INTERFACE");
			map.put("ITEM_IDENTIFIER_INTERFACE", "ITEM_IDENTIFIER_INTERFACE");
			
			
			
			map.put("CONTRACT_HEADER_INTERFACE_HISTORY", "CONTRACT_HEADER_INTERFACE");
			map.put("CONTRACT_HEADER_INTERFACE", "CONTRACT_HEADER_INTERFACE");			
			map.put("COMPANY_FAMILYPLAN_INTERFACE_HISTORY", "COMPANY_FAMILY_PLAN_INTERFACE");
			map.put("COMPANY_FAMILYPLAN_INTERFACE", "COMPANY_FAMILY_PLAN_INTERFACE");			
			map.put("ITEM_FAMILY_PLAN_INTERFACE_HISTORY", "ITEM_FAMILY_PLAN_INTERFACE");
			map.put("ITEM_FAMILY_PLAN_INTERFACE", "ITEM_FAMILY_PLAN_INTERFACE");			
			map.put("PRICE_SCHEDULE_INTERFACE_HISTORY", "PRICE_SCHEDULE_INTERFACE");
			map.put("PRICE_SCHEDULE_INTERFACE", "PRICE_SCHEDULE_INTERFACE");			
			map.put("REBATE_PLAN_INTERFACE_HISTORY", "REBATE_PLAN_INTERFACE");
			map.put("REBATE_PLAN_INTERFACE", "REBATE_PLAN_INTERFACE");			
			map.put("REBATE_SCHEDULE_INTERFACE_HISTORY", "REBATE_SCHEDULE_INTERFACE");
			map.put("REBATE_SCHEDULE_INTERFACE", "REBATE_SCHEDULE_INTERFACE");
			
			
			map.put("ACTUAL_MASTER_INTERFACE_HISTORY", "ACTUAL_MASTER_INTERFACE");
			map.put("ACTUAL_MASTER_INTERFACE", "ACTUAL_MASTER_INTERFACE");			
			map.put("SALES_MASTER_INTERFACE_HISTORY", "SALES_MASTER_INTERFACE");
			map.put("SALES_MASTER_INTERFACE", "SALES_MASTER_INTERFACE");			
			map.put("ITEM_HIERARCHY_INTERFACE_HISTORY", "ITEM_HIERARCHY_INTERFACE");
			map.put("ITEM_HIERARCHY_INTERFACE", "ITEM_HIERARCHY_INTERFACE");			
			map.put("ITEM_HIERARCHY_DEF_INTERFACE_HISTORY", "ITEM_HIERARCHY_DEFINATION_INTERFACE");
			map.put("ITEM_HIERARCHY_DEF_INTERFACE", "ITEM_HIERARCHY_DEFINATION_INTERFACE");			
			map.put("FORECASTING_MASTER_INTERFACE_HISTORY", "FORECAST_SALES_INTERFACE");
			map.put("FORECASTING_MASTER_INTERFACE", "FORECAST_SALES_INTERFACE");			
			map.put("GL_BALANCE_INTERFACE_HISTORY", "GL_BALANCE_INTERFACE");
			map.put("GL_BALANCE_INTERFACE", "GL_BALANCE_INTERFACE");			
			map.put("CPI_INDEX_INTERFACE_HISTORY", "CPI_INTERFACE");
			map.put("CPI_INDEX_INTERFACE", "CPI_INTERFACE");			
			map.put("FORMULA_DETAILS_INTERFACE_HISTORY", "FORMULA_DETAILS_INTERFACE");
			map.put("FORMULA_DETAILS_INTERFACE", "FORMULA_DETAILS_INTERFACE");			
			map.put("MASTER_DATA_INTERFACE_HISTORY", "MASTER_DATA_ATTRIBUTE_INTERFACE");
			map.put("MASTER_DATA_INTERFACE", "MASTER_DATA_ATTRIBUTE_INTERFACE");			
			map.put("BEST_PRICE_INTERFACE_HISTORY", "BEST_PRICE_INTERFACE");
			map.put("BEST_PRICE_INTERFACE", "BEST_PRICE_INTERFACE");			
			map.put("AVERAGE_SHELF_LIFE_INTERFACE_HISTORY", "AVERAGE_SHELF_LIFE_INTERFACE");
			map.put("AVERAGE_SHELF_LIFE_INTERFACE", "AVERAGE_SHELF_LIFE_INTERFACE");			
			map.put("GL_COST_CENTER_INTERFACE_HISTORY", "GL_COST_CENTER_INTERFACE");
			map.put("GL_COST_CENTER_INTERFACE", "GL_COST_CENTER_INTERFACE");			
			map.put("LOT_MASTER_INTERFACE_HISTORY", "LOT_MASTER_INTERFACE");
			map.put("LOT_MASTER_INTERFACE", "LOT_MASTER_INTERFACE");
			
			map.put("ACCRUAL_MASTER_INBOUND", "ACCRUAL_INBOUND_INTERFACE");
		
			//map.put("ACCRUAL_DETAIL_OUTBOUND", "LOT_MASTER_INTERFACE");
			
			map.put("GL_POSTING_INTERFACE", "GL_POSTING_INTERFACE");
			
			map.put("INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE", "INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE");			
			map.put("INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE", "INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE");			
			map.put("INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE", "INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE");			
			map.put("INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE", "INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE");
			
			map.put("DEMAND_ACTUAL_INTERFACE", "DEMAND_ACTUAL_INTERFACE");			
			map.put("DEMAND_FORECAST_INTERFACE", "DEMAND_FORECAST_INTERFACE");	
			
			map.put("RETURNS_INTERFACE", "RETURNS_INTERFACE");			
			
			map.put("CUSTOMER_GTS_ACTUAL_INTERFACE", "CUSTOMER_GTS_ACTUAL_INTERFACE");			
			map.put("CUSTOMER_GTS_FORECAST_INTERFACE", "CUSTOMER_GTS_FORECAST_INTERFACE");	
			
			map.put("ADJUSTED_DEMAND_ACTUAL_INTERFACE", "ADJUSTED_DEMAND_ACTUAL_INTERFACE");			
			map.put("ADJUSTED_DEMAND_FORECAST_INTERFACE", "ADJUSTED_DEMAND_FORECAST_INTERFACE");
			map.put("RETURN_RESERVE_INTERFACE", "RETURN_RESERVE_INTERFACE");
			
		}

		return map;
	}
	public static Map<String, String> getInterfaceName() {
		if(interfaceNameMap.isEmpty()){
			interfaceNameMap.put("COMPANY_MASTER_INTERFACE", "COMPANY_MASTER_INTERFACE");
			interfaceNameMap.put("COMPANY_MASTER_INTERFACE_HISTORY", "COMPANY_MASTER_INTERFACE");
			interfaceNameMap.put("COMPANY_PARENT_HISTORY_INTERFACE", "COMPANY_PARENT_INTERFACE");
			interfaceNameMap.put("COMPANY_PARENT_INTERFACE", "COMPANY_PARENT_INTERFACE");
			interfaceNameMap.put("COMPANY_TRADE_CLASS_HISTORY_INTERFACE", "COMPANY_TRADE_CLASS_INTERFACE");
			interfaceNameMap.put("COMPANY_TRADE_CLASS_INTERFACE", "COMPANY_TRADE_CLASS_INTERFACE");
			interfaceNameMap.put("COMPANY_IDENTIFIER_INTERFACE_HISTORY", "COMPANY_IDENTIFIER_INTERFACE");
			interfaceNameMap.put("COMPANY_IDENTIFIER_INTERFACE", "COMPANY_IDENTIFIER_INTERFACE");			
			interfaceNameMap.put("ITEM_MASTER_INTERFACE", "ITEM_MASTER_INTERFACE");
			interfaceNameMap.put("ITEM_MASTER_INTERFACE_HISTORY", "ITEM_MASTER_INTERFACE");
			interfaceNameMap.put("ITEM_PRICING_INTERFACE", "ITEM_PRICING_INTERFACE");
			interfaceNameMap.put("ITEM_PRICING_INTERFACE_HISTORY", "ITEM_PRICING_INTERFACE");
			interfaceNameMap.put("ITEM_IDENTIFIER_INTERFACE_HISTORY", "ITEM_IDENTIFIER_INTERFACE");
			interfaceNameMap.put("ITEM_IDENTIFIER_INTERFACE", "ITEM_IDENTIFIER_INTERFACE");
			
			
			
			interfaceNameMap.put("CONTRACT_HEADER_INTERFACE_HISTORY", "CONTRACT_HEADER_INTERFACE");
			interfaceNameMap.put("CONTRACT_HEADER_INTERFACE", "CONTRACT_HEADER_INTERFACE");			
			interfaceNameMap.put("COMPANY_FAMILYPLAN_INTERFACE_HISTORY", "COMPANY_FAMILY_PLAN_INTERFACE");
			interfaceNameMap.put("COMPANY_FAMILYPLAN_INTERFACE", "COMPANY_FAMILY_PLAN_INTERFACE");			
			interfaceNameMap.put("ITEM_FAMILY_PLAN_INTERFACE_HISTORY", "ITEM_FAMILY_PLAN_INTERFACE");
			interfaceNameMap.put("ITEM_FAMILY_PLAN_INTERFACE", "ITEM_FAMILY_PLAN_INTERFACE");			
			interfaceNameMap.put("PRICE_SCHEDULE_INTERFACE_HISTORY", "PRICE_SCHEDULE_INTERFACE");
			interfaceNameMap.put("PRICE_SCHEDULE_INTERFACE", "PRICE_SCHEDULE_INTERFACE");			
			interfaceNameMap.put("REBATE_PLAN_INTERFACE_HISTORY", "REBATE_PLAN_INTERFACE");
			interfaceNameMap.put("REBATE_PLAN_INTERFACE", "REBATE_PLAN_INTERFACE");			
			interfaceNameMap.put("REBATE_SCHEDULE_INTERFACE_HISTORY", "REBATE_SCHEDULE_INTERFACE");
			interfaceNameMap.put("REBATE_SCHEDULE_INTERFACE", "REBATE_SCHEDULE_INTERFACE");
			
			
			interfaceNameMap.put("ACTUAL_MASTER_INTERFACE_HISTORY", "ACTUAL_MASTER_INTERFACE");
			interfaceNameMap.put("ACTUAL_MASTER_INTERFACE", "ACTUAL_MASTER_INTERFACE");			
			interfaceNameMap.put("SALES_MASTER_INTERFACE_HISTORY", "SALES_MASTER_INTERFACE");
			interfaceNameMap.put("SALES_MASTER_INTERFACE", "SALES_MASTER_INTERFACE");			
			interfaceNameMap.put("ITEM_HIERARCHY_INTERFACE_HISTORY", "ITEM_HIERARCHY_INTERFACE");
			interfaceNameMap.put("ITEM_HIERARCHY_INTERFACE", "ITEM_HIERARCHY_INTERFACE");			
			interfaceNameMap.put("ITEM_HIERARCHY_DEF_INTERFACE_HISTORY", "ITEM_HIERARCHY_DEFINATION_INTERFACE");
			interfaceNameMap.put("ITEM_HIERARCHY_DEF_INTERFACE", "ITEM_HIERARCHY_DEFINATION_INTERFACE");			
			interfaceNameMap.put("FORECASTING_MASTER_INTERFACE_HISTORY", "FORECAST_SALES_INTERFACE");
			interfaceNameMap.put("FORECASTING_MASTER_INTERFACE", "FORECAST_SALES_INTERFACE");			
			interfaceNameMap.put("GL_BALANCE_INTERFACE_HISTORY", "GL_BALANCE_INTERFACE");
			interfaceNameMap.put("GL_BALANCE_INTERFACE", "GL_BALANCE_INTERFACE");			
			interfaceNameMap.put("CPI_INDEX_INTERFACE_HISTORY", "CPI_INTERFACE");
			interfaceNameMap.put("CPI_INDEX_INTERFACE", "CPI_INTERFACE");			
			interfaceNameMap.put("FORMULA_DETAILS_INTERFACE_HISTORY", "FORMULA_DETAILS_INTERFACE");
			interfaceNameMap.put("FORMULA_DETAILS_INTERFACE", "FORMULA_DETAILS_INTERFACE");			
			interfaceNameMap.put("MASTER_DATA_INTERFACE_HISTORY", "MASTER_DATA_ATTRIBUTE_INTERFACE");
			interfaceNameMap.put("MASTER_DATA_INTERFACE", "MASTER_DATA_ATTRIBUTE_INTERFACE");			
			interfaceNameMap.put("BEST_PRICE_INTERFACE_HISTORY", "BEST_PRICE_INTERFACE");
			interfaceNameMap.put("BEST_PRICE_INTERFACE", "BEST_PRICE_INTERFACE");			
			interfaceNameMap.put("AVERAGE_SHELF_LIFE_INTERFACE_HISTORY", "AVERAGE_SHELF_LIFE_INTERFACE");
			interfaceNameMap.put("AVERAGE_SHELF_LIFE_INTERFACE", "AVERAGE_SHELF_LIFE_INTERFACE");			
			interfaceNameMap.put("GL_COST_CENTER_INTERFACE_HISTORY", "GL_COST_CENTER_INTERFACE");
			interfaceNameMap.put("GL_COST_CENTER_INTERFACE", "GL_COST_CENTER_INTERFACE");			
			interfaceNameMap.put("LOT_MASTER_INTERFACE_HISTORY", "LOT_MASTER_INTERFACE");
			interfaceNameMap.put("LOT_MASTER_INTERFACE", "LOT_MASTER_INTERFACE");
			
			interfaceNameMap.put("ACCRUAL_MASTER_INBOUND", "ACCRUAL_INBOUND_INTERFACE");
		
			//interfaceNameMap.put("ACCRUAL_DETAIL_OUTBOUND", "LOT_MASTER_INTERFACE");
			
			interfaceNameMap.put("GL_POSTING_INTERFACE", "GL_POSTING_INTERFACE");
			
			interfaceNameMap.put("INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE", "INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE");			
			interfaceNameMap.put("INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE", "INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE");			
			interfaceNameMap.put("INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE", "INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE");			
			interfaceNameMap.put("INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE", "INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE");
			
			interfaceNameMap.put("DEMAND_ACTUAL_INTERFACE", "DEMAND_ACTUAL_INTERFACE");			
			interfaceNameMap.put("DEMAND_FORECAST_INTERFACE", "DEMAND_FORECAST_INTERFACE");	
			
			interfaceNameMap.put("RETURNS_INTERFACE", "RETURNS_INTERFACE");			
			
			interfaceNameMap.put("CUSTOMER_GTS_ACTUAL_INTERFACE", "CUSTOMER_GTS_ACTUAL_INTERFACE");			
			interfaceNameMap.put("CUSTOMER_GTS_FORECAST_INTERFACE", "CUSTOMER_GTS_FORECAST_INTERFACE");	
			
			interfaceNameMap.put("ADJUSTED_DEMAND_ACTUAL_INTERFACE", "ADJUSTED_DEMAND_ACTUAL_INTERFACE");			
			interfaceNameMap.put("ADJUSTED_DEMAND_FORECAST_INTERFACE", "ADJUSTED_DEMAND_FORECAST_INTERFACE");
			interfaceNameMap.put("RETURN_RESERVE_INTERFACE", "RETURN_RESERVE_INTERFACE");
		}

	return interfaceNameMap;
	}
}
