IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'GTNWS_AUTH_TOKEN'
                      AND TABLE_SCHEMA = 'DBO')
BEGIN
      CREATE TABLE [DBO].[GTNWS_AUTH_TOKEN]		
        (
		
CLIENT_TOKEN_DETAILS_SID 	INT IDENTITY(1, 1) NOT NULL,
 [USER_NAME] 	VARCHAR(500)  ,
 SESSION_ID VARCHAR(500),
OAUTH_TOKEN VARCHAR(1000) ,
CREATED_DATE	 DATETIME  
        )
END

GO
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'GTNWS_AUTH_TOKEN'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_GTNWS_AUTH_TOKEN_CLIENT_TOKEN_DETAILS_SID'
                     AND TYPE = 'PK')
BEGIN
      ALTER TABLE [DBO].GTNWS_AUTH_TOKEN
        ADD CONSTRAINT PK_GTNWS_AUTH_TOKEN_CLIENT_TOKEN_DETAILS_SID PRIMARY KEY ( CLIENT_TOKEN_DETAILS_SID)
END

GO
IF NOT EXISTS (SELECT 'X'
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  parent_object_id = Object_id('dbo.GTNWS_AUTH_TOKEN')
                      AND NAME = 'DF_GTNWS_AUTH_TOKEN_CREATED_DATE')
BEGIN
      ALTER TABLE [dbo].GTNWS_AUTH_TOKEN
        ADD CONSTRAINT DF_GTNWS_AUTH_TOKEN_CREATED_DATE DEFAULT (GETDATE()) FOR CREATED_DATE
END