
INSERT INTO HELPER_TABLE (DESCRIPTION,LIST_NAME,REF_COUNT) VALUES('Base',	        'ACCRUAL_TYPE',0)
INSERT INTO HELPER_TABLE (DESCRIPTION,LIST_NAME,REF_COUNT) VALUES('Fixed Dollar',	'ACCRUAL_TYPE',0)
INSERT INTO HELPER_TABLE (DESCRIPTION,LIST_NAME,REF_COUNT) VALUES('Recon',	        'ACCRUAL_TYPE',0)
INSERT INTO HELPER_TABLE (DESCRIPTION,LIST_NAME,REF_COUNT) VALUES('Other',	        'ACCRUAL_TYPE',0)


ALTER TABLE ACCRUAL_DETAILS ADD ACCRUAL_TYPE_SID INT;