IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_PROJ_MASTER_TEST'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[RETURNS_PROJ_MASTER_TEST]
        (
           [PROJECTION_MASTER_SID]  [INT] NOT NULL,
           [ITEM_MASTER_SID]        [INT] NOT NULL,
           [METHODOLOGY]            [VARCHAR](50) NULL,
           [METHODOLOGY_START_DATE] [VARCHAR](50) NULL,
           [METHODOLOGY_END_DATE]   [VARCHAR](50) NULL,
           [CALCULATION_PERIODS]    [VARCHAR](4000) NULL,
           [LAG]                    [INT] NULL,
           [CLOSED_DATE]            [DATETIME] NULL,
           [LOE_DATE]               [DATETIME] NULL,
           [CHECK_RECORD]           [BIT] NOT NULL
        )
  END 


-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_PROJ_MASTER_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID'
                     AND TABLE_NAME = 'RETURNS_PROJ_MASTER_TEST')
BEGIN
  ALTER TABLE RETURNS_PROJ_MASTER_TEST
    ADD CONSTRAINT PK_RETURNS_PROJ_MASTER_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID PRIMARY KEY(PROJECTION_MASTER_SID, ITEM_MASTER_SID)
END

GO

-------------DEFAULT CONSTRAINTS---------------------
IF NOT EXISTS (SELECT 'X'
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  PARENT_OBJECT_ID = Object_id('DBO.RETURNS_PROJ_MASTER_TEST')
                      AND NAME = 'DF_RETURNS_PROJ_MASTER_CHECK_RECORD_TEST')
  BEGIN
      ALTER TABLE [DBO].RETURNS_PROJ_MASTER_TEST
        ADD CONSTRAINT DF_RETURNS_PROJ_MASTER_CHECK_RECORD_TEST DEFAULT (0) FOR CHECK_RECORD
  END

GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_PROJ_DETAILS_TEST'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [dbo].[RETURNS_PROJ_DETAILS_TEST]
        (
           [PROJECTION_MASTER_SID]         [INT] NOT NULL,
           [ITEM_MASTER_SID]               [INT] NOT NULL,
           [PERIOD_SID]                    [INT] NOT NULL,
           [GROWTH_RATE]                   [NUMERIC](22, 6) NULL,
           [PROJECTED_RETURN_PERCENT]      [NUMERIC](22, 6) NULL,
           [PROJECTED_RPU]                 [NUMERIC](22, 6) NULL,
           [PROJECTED_RETURN_AMOUNT]       [NUMERIC](22, 6) NULL,
           [PROJECTED_RETURN_UNITS]        [NUMERIC](22, 6) NULL,
           [ACTIVE_EXFACTORY_SALES_AMOUNT] [NUMERIC](22, 6) NULL,
           [ACTIVE_EXFACTORY_SALES_UNITS]  [NUMERIC](22, 6) NULL,
           [REFRESHED_NAME]                [VARCHAR](50) NULL,
        )
  END 


IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_PROJ_DETAILS_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID'
                     AND TABLE_NAME = 'RETURNS_PROJ_DETAILS_TEST')
  BEGIN
      ALTER TABLE RETURNS_PROJ_DETAILS_TEST
        ADD CONSTRAINT PK_RETURNS_PROJ_DETAILS_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID PRIMARY KEY(PROJECTION_MASTER_SID, ITEM_MASTER_SID, PERIOD_SID)
  END

GO 
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_ACTUALS_TEST'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [dbo].[RETURNS_ACTUALS_TEST]
        (
           [PROJECTION_MASTER_SID] [INT] NOT NULL,
           [ITEM_MASTER_SID]       [INT] NOT NULL,
           [PERIOD_SID]            [INT] NOT NULL,
           [ACTUAL_RETURN_PERCENT] [NUMERIC](22, 6) NULL,
           [ACTUAL_RPU]            [NUMERIC](22, 6) NULL,
           [ACTUAL_RETURN_AMOUNT]  [NUMERIC](22, 6) NULL,
           [ORIG_SALE_UNITS]       [NUMERIC](22, 6) NULL,
           [ORIG_SALE_DOLLARS]     [NUMERIC](22, 6) NULL,
           [CUM_RETURN_UNITS]      [NUMERIC](22, 6) NULL,
           [EXPECTED_RETURN_RATE]  [NUMERIC](22, 6) NULL
        )
  END 
GO

IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_ACTUALS_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID'
                     AND TABLE_NAME = 'RETURNS_ACTUALS_TEST')
  BEGIN
      ALTER TABLE RETURNS_ACTUALS_TEST
        ADD CONSTRAINT PK_RETURNS_ACTUALS_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID PRIMARY KEY(PROJECTION_MASTER_SID, ITEM_MASTER_SID, PERIOD_SID)
  END

GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.COLUMNS
              WHERE  NAME = 'ASP' AND object_id = Object_id('RETURNS_ACTUALS_TEST'))
  BEGIN
      ALTER TABLE RETURNS_ACTUALS_TEST ADD ASP NUMERIC(22, 6)
  END 
GO