package com.stpl.gtn.gtn2o.ws.entity.hierarchyroutebuilder;


/**
 * HierarchyEntityMaster generated by hbm2java
 */
public class HierarchyEntityMaster implements java.io.Serializable {

	private Integer entityId;
	private String entityName;
	private int hierarchyTableMasterSid;

	public HierarchyEntityMaster() {
	}

	public HierarchyEntityMaster(String entityName, int hierarchyTableMasterSid) {
		this.entityName = entityName;
		this.hierarchyTableMasterSid = hierarchyTableMasterSid;
	}

	public Integer getEntityId() {
		return this.entityId;
	}

	public void setEntityId(Integer entityId) {
		this.entityId = entityId;
	}

	public String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	public int getHierarchyTableMasterSid() {
		return this.hierarchyTableMasterSid;
	}

	public void setHierarchyTableMasterSid(int hierarchyTableMasterSid) {
		this.hierarchyTableMasterSid = hierarchyTableMasterSid;
	}

}
