IF NOT EXISTS(SELECT 1
				FROM   SYS.TABLES
				WHERE  Object_name(OBJECT_ID) = 'MASTER_DATA_FILES'
						AND Schema_name(SCHEMA_ID) = 'DBO')
	BEGIN
		CREATE TABLE MASTER_DATA_FILES
		(
			MASTER_DATA_FILES_SID INT IDENTITY(1, 1),
			MASTER_TABLE_SID      INT,
			MASTER_TABLE_NAME     VARCHAR(30),
			FILE_PATH             VARCHAR(260),
			CREATED_DATE          DATETIME,
			CREATED_BY            INT
		)
	END 
	GO
	
--------------ADD TABLE ATTACHMENT -------------------
	
IF NOT EXISTS (SELECT 'X'
               FROM   SYS.TABLES
               WHERE  Object_name(OBJECT_ID) = 'ATTACHMENT'
                      AND Schema_name(SCHEMA_ID) = 'dbo')
BEGIN
CREATE TABLE ATTACHMENT
(
  ATTACHMENT_SID INT IDENTITY(1,1) NOT NULL ,
  ATTACHMENT_TABLE_SID INT,
  [FILE_NAME]   VARCHAR(8000) NOT NULL,
  FILE_DATA   VARBINARY(MAX) NOT NULL,
  MASTER_TABLE_NAME VARCHAR(100) NOT NULL,
  CREATED_DATE DATETIME,
  CREATED_BY INT 
) ;

END
GO

-------------ADD PRIMARY KEY CONSTRAINT ---------------

IF NOT EXISTS(SELECT 'X'
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ATTACHMENT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ATTACHMENT_ATTACHMENT_SID'
                     AND TYPE = 'PK')
BEGIN
ALTER TABLE ATTACHMENT   
          ADD  CONSTRAINT PK_ATTACHMENT_ATTACHMENT_SID PRIMARY KEY(ATTACHMENT_SID) ; 
END
GO