IF NOT EXISTS(SELECT 1
				FROM   SYS.TABLES
				WHERE  Object_name(OBJECT_ID) = 'MASTER_DATA_FILES'
						AND Schema_name(SCHEMA_ID) = 'DBO')
	BEGIN
		CREATE TABLE MASTER_DATA_FILES
		(
			MASTER_DATA_FILES_SID INT IDENTITY(1, 1),
			MASTER_TABLE_SID      INT,
			MASTER_TABLE_NAME     VARCHAR(30),
			FILE_PATH             VARCHAR(260),
			CREATED_DATE          DATETIME,
			CREATED_BY            INT
		)
	END 
	go