------ Remove not required File Types for Allergan-----------
IF EXISTS (
		SELECT 1
		FROM HELPER_TABLE
		WHERE DESCRIPTION = 'Adjusted Demand'
			AND LIST_NAME = 'FILE_TYPE'
		)
BEGIN
	DELETE FROM HELPER_TABLE WHERE DESCRIPTION = 'Adjusted Demand'
		 AND LIST_NAME = 'FILE_TYPE'
		AND REF_COUNT = 0
END
GO

IF EXISTS (
		SELECT 1
		FROM HELPER_TABLE
		WHERE DESCRIPTION = 'Demand'
			AND LIST_NAME = 'FILE_TYPE'
		)
BEGIN
	DELETE FROM HELPER_TABLE WHERE DESCRIPTION = 'Demand'
		 AND LIST_NAME = 'FILE_TYPE'
		AND REF_COUNT = 0
END
GO

IF EXISTS (
		SELECT 1
		FROM HELPER_TABLE
		WHERE DESCRIPTION = 'Inventory Withdrawal - Forecast Summary'
			AND LIST_NAME = 'FILE_TYPE'
		)
BEGIN
	DELETE FROM HELPER_TABLE WHERE DESCRIPTION = 'Inventory Withdrawal - Forecast Summary'
		 AND LIST_NAME = 'FILE_TYPE'
		AND REF_COUNT = 0
END
GO

IF EXISTS (
		SELECT 1
		FROM HELPER_TABLE
		WHERE DESCRIPTION = 'Inventory Withdrawal - Forecast Detail'
			AND LIST_NAME = 'FILE_TYPE'
		)
BEGIN
	DELETE FROM HELPER_TABLE WHERE DESCRIPTION = 'Inventory Withdrawal - Forecast Detail'
		 AND LIST_NAME = 'FILE_TYPE'
		AND REF_COUNT = 0
END
GO


----------- Removing not required interfaces from Workflow_Profile table---------
IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'ACCRUAL_OUTBOUND_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'ACCRUAL_OUTBOUND_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'ACCRUAL_RATE_PROJECTION_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'ACCRUAL_RATE_PROJECTION_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'ADJUSTED_DEMAND_ACTUAL_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'ADJUSTED_DEMAND_ACTUAL_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'ADJUSTED_DEMAND_FORECAST_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'ADJUSTED_DEMAND_FORECAST_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'AVERAGE_SHELF_LIFE_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'AVERAGE_SHELF_LIFE_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'BEST_PRICE_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'BEST_PRICE_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'DEMAND_ACTUAL_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'DEMAND_ACTUAL_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'DEMAND_FORECAST_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'DEMAND_FORECAST_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'FORMULA_DETAILS_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'FORMULA_DETAILS_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'GL_BALANCE_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'GL_BALANCE_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'GL_POSTING_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'GL_POSTING_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'HIERARCHY_DEFINITION_OUTBOUND'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'HIERARCHY_DEFINITION_OUTBOUND'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'ITEM_HIERARCHY_DEFINITION_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'ITEM_HIERARCHY_DEFINITION_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'ITEM_HIERARCHY_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'ITEM_HIERARCHY_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'LOT_MASTER_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'LOT_MASTER_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'MASTER_DATA_ATTRIBUTE_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'MASTER_DATA_ATTRIBUTE_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'RETURNS_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'RETURNS_INTERFACE'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'RELATIONSHIP_BUILDER_OUTBOUND'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'RELATIONSHIP_BUILDER_OUTBOUND'
END
GO

IF EXISTS (
		SELECT 1
		FROM WORKFLOW_PROFILE
		WHERE PROCESS_NAME = 'SALES_MASTER_INTERFACE'
		)
BEGIN
	DELETE FROM WORKFLOW_PROFILE WHERE PROCESS_NAME = 'SALES_MASTER_INTERFACE'
END
GO
