IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.CDR_DETAILS') 
                      AND NAME = 'DF_CDR_DETAILS_COMPARISON') 
  BEGIN 
      ALTER TABLE CDR_DETAILS 
        ADD CONSTRAINT DF_CDR_DETAILS_COMPARISON DEFAULT(0) FOR COMPARISON 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.CDR_DETAILS') 
                      AND NAME = 'DF_CDR_DETAILS_LOGICAL_OPERATOR') 
  BEGIN 
      ALTER TABLE CDR_DETAILS 
        ADD CONSTRAINT DF_CDR_DETAILS_LOGICAL_OPERATOR DEFAULT(0) FOR 
        LOGICAL_OPERATOR 
  END 
   Go

IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.COMPANY_MASTER') 
                      AND NAME = 'DF_COMPANY_MASTER_COMPANY_CATEGORY') 
  BEGIN 
      ALTER TABLE COMPANY_MASTER 
        ADD CONSTRAINT DF_COMPANY_MASTER_COMPANY_CATEGORY DEFAULT(0) FOR 
        COMPANY_CATEGORY 
  END 
 Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.COMPANY_MASTER') 
                      AND NAME = 'DF_COMPANY_MASTER_COUNTRY') 
  BEGIN 
      ALTER TABLE COMPANY_MASTER 
        ADD CONSTRAINT DF_COMPANY_MASTER_COUNTRY DEFAULT(0) FOR COUNTRY 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.COMPANY_MASTER') 
                      AND NAME = 'DF_COMPANY_MASTER_STATE') 
  BEGIN 
      ALTER TABLE COMPANY_MASTER 
        ADD CONSTRAINT DF_COMPANY_MASTER_STATE DEFAULT(0) FOR STATE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.COMPANY_MASTER') 
                      AND NAME = 'DF_COMPANY_MASTER_ORGANIZATION_KEY') 
  BEGIN 
      ALTER TABLE COMPANY_MASTER 
        ADD CONSTRAINT DF_COMPANY_MASTER_ORGANIZATION_KEY DEFAULT(0) FOR 
        ORGANIZATION_KEY 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.COMPANY_MASTER') 
                      AND NAME = 'DF_COMPANY_MASTER_COMPANY_GROUP') 
  BEGIN 
      ALTER TABLE COMPANY_MASTER 
        ADD CONSTRAINT DF_COMPANY_MASTER_COMPANY_GROUP DEFAULT(0) FOR 
        COMPANY_GROUP 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.COMPANY_TRADE_CLASS') 
                      AND NAME = 'DF_COMPANY_TRADE_CLASS_PRIOR_TRADE_CLASS') 
  BEGIN 
      ALTER TABLE COMPANY_TRADE_CLASS 
        ADD CONSTRAINT DF_COMPANY_TRADE_CLASS_PRIOR_TRADE_CLASS DEFAULT(0) FOR 
        PRIOR_TRADE_CLASS 
  END 
   Go

IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.ITEM_MASTER') 
                      AND NAME = 'DF_ITEM_MASTER_PACKAGE_SIZE') 
  BEGIN 
      ALTER TABLE ITEM_MASTER 
        ADD CONSTRAINT DF_ITEM_MASTER_PACKAGE_SIZE DEFAULT(0) FOR PACKAGE_SIZE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.ITEM_MASTER') 
                      AND NAME = 'DF_ITEM_MASTER_ITEM_TYPE') 
  BEGIN 
      ALTER TABLE ITEM_MASTER 
        ADD CONSTRAINT DF_ITEM_MASTER_ITEM_TYPE DEFAULT(0) FOR ITEM_TYPE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.ITEM_MASTER') 
                      AND NAME = 'DF_ITEM_MASTER_SHELF_LIFE_TYPE') 
  BEGIN 
      ALTER TABLE ITEM_MASTER 
        ADD CONSTRAINT DF_ITEM_MASTER_SHELF_LIFE_TYPE DEFAULT(0) FOR 
        SHELF_LIFE_TYPE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.ITEM_MASTER') 
                      AND NAME = 'DF_ITEM_MASTER_ITEM_CATEGORY') 
  BEGIN 
      ALTER TABLE ITEM_MASTER 
        ADD CONSTRAINT DF_ITEM_MASTER_ITEM_CATEGORY DEFAULT(0) FOR ITEM_CATEGORY 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.ITEM_MASTER') 
                      AND NAME = 'DF_ITEM_MASTER_THERAPEUTIC_CLASS') 
  BEGIN 
      ALTER TABLE ITEM_MASTER 
        ADD CONSTRAINT DF_ITEM_MASTER_THERAPEUTIC_CLASS DEFAULT(0) FOR 
        THERAPEUTIC_CLASS 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.ITEM_MASTER') 
                      AND NAME = 'DF_ITEM_MASTER_ITEM_CLASS') 
  BEGIN 
      ALTER TABLE ITEM_MASTER 
        ADD CONSTRAINT DF_ITEM_MASTER_ITEM_CLASS DEFAULT(0) FOR ITEM_CLASS 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.ITEM_MASTER') 
                      AND NAME = 'DF_ITEM_MASTER_PRIMARY_UOM') 
  BEGIN 
      ALTER TABLE ITEM_MASTER 
        ADD CONSTRAINT DF_ITEM_MASTER_PRIMARY_UOM DEFAULT(0) FOR PRIMARY_UOM 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.ITEM_MASTER') 
                      AND NAME = 'DF_ITEM_MASTER_SECONDARY_UOM') 
  BEGIN 
      ALTER TABLE ITEM_MASTER 
        ADD CONSTRAINT DF_ITEM_MASTER_SECONDARY_UOM DEFAULT(0) FOR SECONDARY_UOM 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.ITEM_MASTER') 
                      AND NAME = 'DF_ITEM_MASTER_ITEM_TYPE_INDICATION') 
  BEGIN 
      ALTER TABLE ITEM_MASTER 
        ADD CONSTRAINT DF_ITEM_MASTER_ITEM_TYPE_INDICATION DEFAULT(0) FOR 
        ITEM_TYPE_INDICATION 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE 
          PARENT_OBJECT_ID = OBJECT_ID('DBO.NET_SALES_FORMULA_MASTER') 
          AND NAME = 'DF_NET_SALES_FORMULA_MASTER_NET_SALES_FORMULA_CATEGORY') 
  BEGIN 
      ALTER TABLE NET_SALES_FORMULA_MASTER 
        ADD CONSTRAINT DF_NET_SALES_FORMULA_MASTER_NET_SALES_FORMULA_CATEGORY 
        DEFAULT( 
        0) FOR NET_SALES_FORMULA_CATEGORY 
  END 
   Go

IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_PRICE_TOLERANCE_INTERVAL') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_PRICE_TOLERANCE_INTERVAL DEFAULT(0) FOR 
        PRICE_TOLERANCE_INTERVAL 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_PRICE_TOLERANCE_TYPE') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_PRICE_TOLERANCE_TYPE DEFAULT(0) FOR 
        PRICE_TOLERANCE_TYPE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_ITEM_PS_ATTACHED_STATUS') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_ITEM_PS_ATTACHED_STATUS DEFAULT(0) FOR 
        ITEM_PS_ATTACHED_STATUS 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_PRICE_TOLERANCE_FREQUENCY') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_PRICE_TOLERANCE_FREQUENCY DEFAULT(0) FOR 
        PRICE_TOLERANCE_FREQUENCY 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_PRICE_PROTECTION_STATUS') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_PRICE_PROTECTION_STATUS DEFAULT(0) FOR 
        PRICE_PROTECTION_STATUS 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_RESET_TYPE') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_RESET_TYPE DEFAULT(0) FOR RESET_TYPE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_RESET_INTERVAL') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_RESET_INTERVAL DEFAULT(0) FOR 
        RESET_INTERVAL 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_RESET_FREQUENCY') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_RESET_FREQUENCY DEFAULT(0) FOR 
        RESET_FREQUENCY 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_NET_BASE_PRICE') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_NET_BASE_PRICE DEFAULT(0) FOR 
        NET_BASE_PRICE 
  END  
  Go

IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_NET_SUBSEQUENT_PERIOD_PRICE') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_NET_SUBSEQUENT_PERIOD_PRICE DEFAULT(0) FOR 
        NET_SUBSEQUENT_PERIOD_PRICE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_NET_RESET_PRICE_TYPE') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_NET_RESET_PRICE_TYPE DEFAULT(0) FOR 
        NET_RESET_PRICE_TYPE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_DETAILS') 
                      AND NAME = 'DF_PS_DETAILS_BASE_PRICE_TYPE') 
  BEGIN 
      ALTER TABLE PS_DETAILS 
        ADD CONSTRAINT DF_PS_DETAILS_BASE_PRICE_TYPE DEFAULT(0) FOR 
        BASE_PRICE_TYPE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_MODEL') 
                      AND NAME = 'DF_PS_MODEL_PS_TYPE') 
  BEGIN 
      ALTER TABLE PS_MODEL 
        ADD CONSTRAINT DF_PS_MODEL_PS_TYPE DEFAULT(0) FOR PS_TYPE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_MODEL') 
                      AND NAME = 'DF_PS_MODEL_PS_CATEGORY') 
  BEGIN 
      ALTER TABLE PS_MODEL 
        ADD CONSTRAINT DF_PS_MODEL_PS_CATEGORY DEFAULT(0) FOR PS_CATEGORY 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_MODEL') 
                      AND NAME = 'DF_PS_MODEL_PS_TRADE_CLASS') 
  BEGIN 
      ALTER TABLE PS_MODEL 
        ADD CONSTRAINT DF_PS_MODEL_PS_TRADE_CLASS DEFAULT(0) FOR PS_TRADE_CLASS 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.PS_MODEL') 
                      AND NAME = 'DF_PS_MODEL_PS_DESIGNATION') 
  BEGIN 
      ALTER TABLE PS_MODEL 
        ADD CONSTRAINT DF_PS_MODEL_PS_DESIGNATION DEFAULT(0) FOR PS_DESIGNATION 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.REBATE_PLAN_MASTER') 
                      AND NAME = 'DF_REBATE_PLAN_MASTER_REBATE_PLAN_TYPE') 
  BEGIN 
      ALTER TABLE REBATE_PLAN_MASTER 
        ADD CONSTRAINT DF_REBATE_PLAN_MASTER_REBATE_PLAN_TYPE DEFAULT(0) FOR 
        REBATE_PLAN_TYPE 
  END 
   Go

IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_REBATE_PROCESSING_TYPE') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_REBATE_PROCESSING_TYPE DEFAULT(0) FOR 
        REBATE_PROCESSING_TYPE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_REBATE_RULE_TYPE') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_REBATE_RULE_TYPE DEFAULT(0) FOR 
        REBATE_RULE_TYPE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_PAYMENT_TERMS') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_PAYMENT_TERMS DEFAULT(0) FOR PAYMENT_TERMS 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_CALCULATION_RULE_LEVEL') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_CALCULATION_RULE_LEVEL DEFAULT(0) FOR 
        CALCULATION_RULE_LEVEL 
  END 
   Go

IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_STATE') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_STATE DEFAULT(0) FOR STATE 
  END 
 Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_EVALUATION_RULE_TYPE') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_EVALUATION_RULE_TYPE DEFAULT(0) FOR 
        EVALUATION_RULE_TYPE 
  END 
 Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_RS_TRADE_CLASS') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_RS_TRADE_CLASS DEFAULT(0) FOR RS_TRADE_CLASS 
  END 
 Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_EVALUATION_RULE_LEVEL') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_EVALUATION_RULE_LEVEL DEFAULT(0) FOR 
        EVALUATION_RULE_LEVEL 
  END 
 Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_REBATE_FREQUENCY') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_REBATE_FREQUENCY DEFAULT(0) FOR 
        REBATE_FREQUENCY 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_RS_VALIDATION_PROFILE') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_RS_VALIDATION_PROFILE DEFAULT(0) FOR 
        RS_VALIDATION_PROFILE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_RS_DESIGNATION') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_RS_DESIGNATION DEFAULT(0) FOR RS_DESIGNATION 
  END 
 Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_PAYMENT_LEVEL') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_PAYMENT_LEVEL DEFAULT(0) FOR PAYMENT_LEVEL 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_INTEREST_BEARING_BASIS') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_INTEREST_BEARING_BASIS DEFAULT(0) FOR 
        INTEREST_BEARING_BASIS 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_INTEREST_BEARING_INDICATOR') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_INTEREST_BEARING_INDICATOR DEFAULT(0) FOR 
        INTEREST_BEARING_INDICATOR 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_REBATE_PLAN_LEVEL') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_REBATE_PLAN_LEVEL DEFAULT(0) FOR 
        REBATE_PLAN_LEVEL 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_CALCULATION_LEVEL') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_CALCULATION_LEVEL DEFAULT(0) FOR 
        CALCULATION_LEVEL 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.RS_MODEL') 
                      AND NAME = 'DF_RS_MODEL_CALCULATION_TYPE') 
  BEGIN 
      ALTER TABLE RS_MODEL 
        ADD CONSTRAINT DF_RS_MODEL_CALCULATION_TYPE DEFAULT(0) FOR 
        CALCULATION_TYPE 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.UDCS') 
                      AND NAME = 'DF_UDCS_UDC1') 
  BEGIN 
      ALTER TABLE UDCS 
        ADD CONSTRAINT DF_UDCS_UDC1 DEFAULT(0) FOR UDC1 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.UDCS') 
                      AND NAME = 'DF_UDCS_UDC2') 
  BEGIN 
      ALTER TABLE UDCS 
        ADD CONSTRAINT DF_UDCS_UDC2 DEFAULT(0) FOR UDC2 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.UDCS') 
                      AND NAME = 'DF_UDCS_UDC3') 
  BEGIN 
      ALTER TABLE UDCS 
        ADD CONSTRAINT DF_UDCS_UDC3 DEFAULT(0) FOR UDC3 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.UDCS') 
                      AND NAME = 'DF_UDCS_UDC4') 
  BEGIN 
      ALTER TABLE UDCS 
        ADD CONSTRAINT DF_UDCS_UDC4 DEFAULT(0) FOR UDC4 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.UDCS') 
                      AND NAME = 'DF_UDCS_UDC5') 
  BEGIN 
      ALTER TABLE UDCS 
        ADD CONSTRAINT DF_UDCS_UDC5 DEFAULT(0) FOR UDC5 
  END 
   Go
IF NOT EXISTS (SELECT 'X' 
               FROM   SYS.DEFAULT_CONSTRAINTS 
               WHERE  PARENT_OBJECT_ID = OBJECT_ID('DBO.UDCS') 
                      AND NAME = 'DF_UDCS_UDC6') 
  BEGIN 
      ALTER TABLE UDCS 
        ADD CONSTRAINT DF_UDCS_UDC6 DEFAULT(0) FOR UDC6 
  END
  go 