--------------------------------------ACCRUAL_PROJ_DETAILS -----------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ACCRUAL_PROJ_DETAILS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].ACCRUAL_PROJ_DETAILS
        (
           ACCRUAL_PROJ_DETAILS_SID INT IDENTITY(1, 1) NOT NULL,
           CCP_DETAILS_SID          INT NOT NULL,
           RS_MODEL_SID             INT NOT NULL,
           PROJECTION_MASTER_SID    INT NOT NULL
        )
  END

GO
---------------PRIMARY KEY CONSTRAINTS
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_PROJ_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ACCRUAL_PROJ_DETAILS_ACCRUAL_PROJ_DETAILS_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].ACCRUAL_PROJ_DETAILS
        ADD CONSTRAINT PK_ACCRUAL_PROJ_DETAILS_ACCRUAL_PROJ_DETAILS_SID PRIMARY KEY ( ACCRUAL_PROJ_DETAILS_SID)
  END

GO
---------COLUMN ADDITION FOR GAL-1163
IF NOT EXISTS (SELECT 1 
               FROM   INFORMATION_SCHEMA.COLUMNS 
               WHERE  TABLE_NAME = 'ACCRUAL_PROJ_DETAILS' 
                      AND COLUMN_NAME = 'RS_CONTRACT_SID') 
  BEGIN 
      ALTER TABLE ACCRUAL_PROJ_DETAILS 
        ADD RS_CONTRACT_SID INT 
  END 
GO

-------------------------------------   ACCRUAL_PROJ_SELECTION --------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ACCRUAL_PROJ_SELECTION'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].ACCRUAL_PROJ_SELECTION
        (
           ACCRUAL_PROJ_SELECTION_SID INT IDENTITY(1, 1) NOT NULL,
           PROJECTION_MASTER_SID      INT NOT NULL,
           SCREEN_NAME                VARCHAR(50) NULL,
           FIELD_NAME                 VARCHAR(30) NULL,
           FIELD_VALUES               VARCHAR(4000) NULL
        )
  END

GO

---------------PRIMARY KEY CONSTRAINTS
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_PROJ_SELECTION'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ACCRUAL_PROJ_SELECTION_ACCRUAL_PROJ_SELECTION_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].ACCRUAL_PROJ_SELECTION
        ADD CONSTRAINT PK_ACCRUAL_PROJ_SELECTION_ACCRUAL_PROJ_SELECTION_SID PRIMARY KEY (ACCRUAL_PROJ_SELECTION_SID)
  END

GO 
--------------------------------------------------

IF  EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'ACCRUAL_PROJ_SELECTION'
                  AND COLUMN_NAME = 'FIELD_NAME'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ACCRUAL_PROJ_SELECTION
       ALTER COLUMN FIELD_NAME VARCHAR(100)  
  END

GO