-------------------------------------   ACCRUAL_SALES_ACTUALS --------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ACCRUAL_SALES_ACTUALS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].ACCRUAL_SALES_ACTUALS
        (
           PROJECTION_MASTER_SID INT NOT NULL,
           ITEM_MASTER_SID       INT NOT NULL,
           PERIOD_SID            INT NOT NULL,
           TOTAL_UNITS           NUMERIC(22, 6) NULL,
           EXCLUDED_UNITS        NUMERIC(22, 6) NULL,
           NET_UNITS             NUMERIC(22, 6) NULL,
           PRICE                 NUMERIC(22, 6) NULL,
           SALES                 NUMERIC(22, 6) NULL,
           EXCLUDED_DOLLARS      NUMERIC(22, 6) NULL,
           DEMAND                NUMERIC(22, 6) NULL,
           ADJUSTED_DEMAND       NUMERIC(22, 6) NULL
        )
  END

GO
---------------PRIMARY KEY CONSTRAINTS
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_SALES_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ACCRUAL_SALES_ACTUALS_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].ACCRUAL_SALES_ACTUALS
        ADD CONSTRAINT PK_ACCRUAL_SALES_ACTUALS_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID PRIMARY KEY (PROJECTION_MASTER_SID, ITEM_MASTER_SID, PERIOD_SID)
  END

GO

-------------------------------------   ST_ACCRUAL_SALES_ACTUALS --------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_ACCRUAL_SALES_ACTUALS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].ST_ACCRUAL_SALES_ACTUALS
        (
           PROJECTION_MASTER_SID INT NOT NULL,
           ITEM_MASTER_SID       INT NOT NULL,
           PERIOD_SID            INT NOT NULL,
           TOTAL_UNITS           NUMERIC(22, 6) NULL,
           EXCLUDED_UNITS        NUMERIC(22, 6) NULL,
           NET_UNITS             NUMERIC(22, 6) NULL,
           PRICE                 NUMERIC(22, 6) NULL,
           SALES                 NUMERIC(22, 6) NULL,
           EXCLUDED_DOLLARS      NUMERIC(22, 6) NULL,
           DEMAND                NUMERIC(22, 6) NULL,
           ADJUSTED_DEMAND       NUMERIC(22, 6) NULL,
           USER_ID               INT NOT NULL,
           SESSION_ID            INT NOT NULL
        )
  END

GO
---------------PRIMARY KEY CONSTRAINTS
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_SALES_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ST_ACCRUAL_SALES_ACTUALS_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID_USER_ID_SESSION_ID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].ST_ACCRUAL_SALES_ACTUALS
        ADD CONSTRAINT PK_ST_ACCRUAL_SALES_ACTUALS_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID_USER_ID_SESSION_ID PRIMARY KEY (PROJECTION_MASTER_SID, ITEM_MASTER_SID, PERIOD_SID, USER_ID, SESSION_ID)
  END

GO

-------------------------------------   ACCRUAL_SALES_DETAILS --------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ACCRUAL_SALES_DETAILS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].ACCRUAL_SALES_DETAILS
        (
           PROJECTION_MASTER_SID INT NOT NULL,
           ITEM_MASTER_SID       INT NOT NULL,
           PERIOD_SID            INT NOT NULL,
           TOTAL_UNITS           NUMERIC(22, 6) NULL,
           EXCLUDED_UNITS        NUMERIC(22, 6) NULL,
           NET_UNITS             NUMERIC(22, 6) NULL,
           PRICE                 NUMERIC(22, 6) NULL,
           SALES                 NUMERIC(22, 6) NULL,
           EXCLUDED_DOLLARS      NUMERIC(22, 6) NULL,
           DEMAND                NUMERIC(22, 6) NULL,
           ADJUSTED_DEMAND       NUMERIC(22, 6) NULL
        )
  END

GO
---------------PRIMARY KEY CONSTRAINTS
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_SALES_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ACCRUAL_SALES_DETAILS_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].ACCRUAL_SALES_DETAILS
        ADD CONSTRAINT PK_ACCRUAL_SALES_DETAILS_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID PRIMARY KEY (PROJECTION_MASTER_SID, ITEM_MASTER_SID, PERIOD_SID)
  END

GO

-------------------------------------   ST_ACCRUAL_SALES_DETAILS --------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_ACCRUAL_SALES_DETAILS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].ST_ACCRUAL_SALES_DETAILS
        (
           PROJECTION_MASTER_SID INT NOT NULL,
           ITEM_MASTER_SID       INT NOT NULL,
           PERIOD_SID            INT NOT NULL,
           TOTAL_UNITS           NUMERIC(22, 6) NULL,
           EXCLUDED_UNITS        NUMERIC(22, 6) NULL,
           NET_UNITS             NUMERIC(22, 6) NULL,
           PRICE                 NUMERIC(22, 6) NULL,
           SALES                 NUMERIC(22, 6) NULL,
           EXCLUDED_DOLLARS      NUMERIC(22, 6) NULL,
           DEMAND                NUMERIC(22, 6) NULL,
           ADJUSTED_DEMAND       NUMERIC(22, 6) NULL,
           USER_ID               INT NOT NULL,
           SESSION_ID            INT NOT NULL
        )
  END

GO
---------------PRIMARY KEY CONSTRAINTS
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_SALES_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ST_ACCRUAL_SALES_DETAILS_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID_USER_ID_SESSION_ID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].ST_ACCRUAL_SALES_DETAILS
        ADD CONSTRAINT PK_ST_ACCRUAL_SALES_DETAILS_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID_USER_ID_SESSION_ID PRIMARY KEY (PROJECTION_MASTER_SID, ITEM_MASTER_SID, PERIOD_SID, USER_ID, SESSION_ID)
  END

GO

-------------------------------------   EXCLUSION_DETAILS --------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'EXCLUSION_DETAILS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].EXCLUSION_DETAILS
        (
           PROJECTION_MASTER_SID INT NOT NULL,
           COMPANY_MASTER_SID    INT NOT NULL,
        )
  END

GO

---------------PRIMARY KEY CONSTRAINTS
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'EXCLUSION_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_EXCLUSION_DETAILS_PROJECTION_MASTER_SID_COMPANY_MASTER_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].EXCLUSION_DETAILS
        ADD CONSTRAINT PK_EXCLUSION_DETAILS_PROJECTION_MASTER_SID_COMPANY_MASTER_SID PRIMARY KEY (PROJECTION_MASTER_SID, COMPANY_MASTER_SID)
  END

GO

-------------------------------------   ST_EXCLUSION_DETAILS --------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_EXCLUSION_DETAILS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].ST_EXCLUSION_DETAILS
        (
           PROJECTION_MASTER_SID INT NOT NULL,
           COMPANY_MASTER_SID    INT NOT NULL,
           USER_ID               INT NOT NULL,
           SESSION_ID            INT NOT NULL
        )
  END

GO
---------------PRIMARY KEY CONSTRAINTS
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_EXCLUSION_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ST_EXCLUSION_DETAILS_PROJECTION_MASTER_SID_COMPANY_MASTER_SID_USER_ID_SESSION_ID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].ST_EXCLUSION_DETAILS
        ADD CONSTRAINT PK_ST_EXCLUSION_DETAILS_PROJECTION_MASTER_SID_COMPANY_MASTER_SID_USER_ID_SESSION_ID PRIMARY KEY (PROJECTION_MASTER_SID, COMPANY_MASTER_SID, USER_ID, SESSION_ID)
  END

GO 
