--------------------------------------------------BALANCE_REPORT_PIPELINE_PERIOD----------------------------- 
IF NOT EXISTS (SELECT 1 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'BALANCE_REPORT_PIPELINE_PERIOD') 
  BEGIN 
      CREATE TABLE BALANCE_REPORT_PIPELINE_PERIOD 
        ( 
           ARM_ADJUSTMENT_DETAILS_SID INT, 
           STARTING_BALANCE           NUMERIC(22, 6), 
           PERIOD_SID                 INT, 
           ADJUSTMENT_TYPE            INT, 
           PERIOD_ADJUSTMENT_VALUE    NUMERIC(22, 6), 
           ACTUAL_PAYMENT             NUMERIC(22, 6), 
           TOTAL_PERIOD_ADJ           NUMERIC(22, 6), 
           ENDING_BALANCE             NUMERIC(22, 6) 
        ) 
  END 

IF NOT EXISTS (SELECT 1 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'BALANCE_REPORT_PIPELINE_CUM') 
  BEGIN 
      CREATE TABLE BALANCE_REPORT_PIPELINE_CUM 
        ( 
           ARM_ADJUSTMENT_DETAILS_SID INT, 
           STARTING_BALANCE           NUMERIC(22, 6), 
           ADJUSTMENT_TYPE            INT, 
           CUM_ADJUSTMENT_VALUE       NUMERIC(22, 6), 
           TOTAL_CUM_ADJ              NUMERIC(22, 6), 
           ENDING_BALANCE             NUMERIC(22, 6) 
        ) 
  END 

IF NOT EXISTS (SELECT 1 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'BALANCE_REPORT_DEMAND_PERIOD') 
  BEGIN 
      CREATE TABLE BALANCE_REPORT_DEMAND_PERIOD 
        ( 
           ARM_ADJUSTMENT_DETAILS_SID INT, 
           PERIOD_SID                 INT, 
           ADJUSTMENT_TYPE            INT, 
           ADJUSTMENT_TYPE_BALANCE    NUMERIC(22, 6), 
           ACTUALS_PAYMENTS           NUMERIC(22, 6), 
           PAYMENT_RATIO              NUMERIC(22, 6), 
           PERIOD_BALANCE             NUMERIC(22, 6) 
        ) 
  END 

IF NOT EXISTS (SELECT 1 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'BALANCE_REPORT_DEMAND_CUM') 
  BEGIN 
      CREATE TABLE BALANCE_REPORT_DEMAND_CUM 
        ( 
           ARM_ADJUSTMENT_DETAILS_SID INT, 
           ADJUSTMENT_TYPE            INT, 
           ADJUSTMENT_TYPE_BALANCE    NUMERIC(22, 6), 
           ACTUALS_PAYMENTS           NUMERIC(22, 6), 
           CUMMULATIVE_BALANCE        NUMERIC(22, 6), 
           PAYMENT_RATIO              NUMERIC(22, 6) 
        ) 
  END 

IF NOT EXISTS (SELECT 'X' 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'CALCULATION_PROFILE_MASTER' 
                      AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      CREATE TABLE [DBO].CALCULATION_PROFILE_MASTER 
        ( 
           CALCULATION_PROFILE_MASTER_SID INT IDENTITY(1, 1) NOT NULL, 
           PROFILE_NAME                   VARCHAR(100), 
           PROJECTION_MASTER_SID          INT, 
           PROFILE_DESCRIPTION            VARCHAR(100), 
           SAVE_FLAG                      BIT, 
           CREATED_BY                     INT, 
           CREATED_DATE                   DATETIME, 
           MODIFIED_BY                    INT, 
           MODIFIED_DATE                  DATETIME 
        ) 
  END 

GO 

IF NOT EXISTS(SELECT 1 
              FROM   SYS.KEY_CONSTRAINTS 
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CALCULATION_PROFILE_MASTER' 
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                     AND NAME = 'PK_CALCULATION_PROFILE_MASTER_CALCULATION_PROFILE_MASTER_SID'
                     AND TYPE = 'PK') 
  BEGIN 
      ALTER TABLE [DBO].CALCULATION_PROFILE_MASTER 
        ADD CONSTRAINT PK_CALCULATION_PROFILE_MASTER_CALCULATION_PROFILE_MASTER_SID PRIMARY KEY ( CALCULATION_PROFILE_MASTER_SID)
  END 

GO 

IF NOT EXISTS(SELECT 1 
              FROM   SYS.DEFAULT_CONSTRAINTS 
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CALCULATION_PROFILE_MASTER' 
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                     AND NAME = 'DF_CALCULATION_PROFILE_MASTER_CREATED_DATE' 
                     AND TYPE = 'D') 
  BEGIN 
      ALTER TABLE [DBO].CALCULATION_PROFILE_MASTER 
        ADD CONSTRAINT DF_CALCULATION_PROFILE_MASTER_CREATED_DATE DEFAULT GETDATE() FOR CREATED_DATE
  END 

GO 

--MODIFIED_BY 
IF NOT EXISTS(SELECT 1 
              FROM   SYS.DEFAULT_CONSTRAINTS 
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CALCULATION_PROFILE_MASTER' 
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                     AND NAME = 'DF_CALCULATION_PROFILE_MASTER_MODIFIED_BY' 
                     AND TYPE = 'D') 
  BEGIN 
      ALTER TABLE [DBO].CALCULATION_PROFILE_MASTER 
        ADD CONSTRAINT DF_CALCULATION_PROFILE_MASTER_MODIFIED_BY DEFAULT (1) FOR MODIFIED_BY 
  END 

GO 

--MODIFIED_DATE 
IF NOT EXISTS(SELECT 1 
              FROM   SYS.DEFAULT_CONSTRAINTS 
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CALCULATION_PROFILE_MASTER' 
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                     AND NAME = 'DF_CALCULATION_PROFILE_MASTER_MODIFIED_DATE' 
                     AND TYPE = 'D') 
  BEGIN 
      ALTER TABLE [DBO].CALCULATION_PROFILE_MASTER 
        ADD CONSTRAINT DF_CALCULATION_PROFILE_MASTER_MODIFIED_DATE DEFAULT GETDATE() FOR MODIFIED_DATE
  END 

GO 

IF NOT EXISTS (SELECT 'X' 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'CALCULATION_PROFILE_DETAILS' 
                      AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      CREATE TABLE [DBO].CALCULATION_PROFILE_DETAILS 
        ( 
           CALCULATION_PROFILE_DETAILS_SID INT IDENTITY(1, 1) NOT NULL, 
           CALCULATION_PROFILE_MASTER_SID  INT, 
           ADJUSTMENT_TYPE                 INT, 
           ACCOUNT_TYPE                    VARCHAR(100), 
           INCLUDE                         VARCHAR(100), 
           INDICATOR                       VARCHAR(100), 
           PRIORITY                        INT 
        ) 
  END 

GO 

IF NOT EXISTS(SELECT 1 
              FROM   SYS.KEY_CONSTRAINTS 
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CALCULATION_PROFILE_DETAILS' 
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                     AND NAME = 'PK_CALCULATION_PROFILE_DETAILS_CALCULATION_PROFILE_DETAILS_SID'
                     AND TYPE = 'PK') 
  BEGIN 
      ALTER TABLE [DBO].CALCULATION_PROFILE_DETAILS 
        ADD CONSTRAINT PK_CALCULATION_PROFILE_DETAILS_CALCULATION_PROFILE_DETAILS_SID PRIMARY KEY ( CALCULATION_PROFILE_DETAILS_SID)
  END 

GO 

IF NOT EXISTS (SELECT 'X' 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'CALCULATION_PROFILE_VIEW_MASTER' 
                      AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      CREATE TABLE [DBO].CALCULATION_PROFILE_VIEW_MASTER 
        ( 
           CALCULATION_PROFILE_VIEW_MASTER_SID INT IDENTITY(1, 1) NOT NULL, 
           VIEW_NAME                           VARCHAR(100), 
           VIEW_TYPE                           VARCHAR(100), 
           CREATED_BY                          INT, 
           CREATED_DATE                        DATETIME, 
           MODIFIED_BY                         INT, 
           MODIFIED_DATE                       DATETIME, 
           CALCULATION_PROFILE_MASTER_SID      INT 
        ) 
  END 

GO 

IF NOT EXISTS(SELECT 1 
              FROM   SYS.KEY_CONSTRAINTS 
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CALCULATION_PROFILE_VIEW_MASTER' 
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                     AND NAME = 'PK_CALCULATION_PROFILE_VIEW_MASTER_CALCULATION_PROFILE_VIEW_MASTER_SID'
                     AND TYPE = 'PK') 
  BEGIN 
      ALTER TABLE [DBO].CALCULATION_PROFILE_VIEW_MASTER 
        ADD CONSTRAINT PK_CALCULATION_PROFILE_VIEW_MASTER_CALCULATION_PROFILE_VIEW_MASTER_SID PRIMARY KEY ( CALCULATION_PROFILE_VIEW_MASTER_SID)
  END 

GO 

IF NOT EXISTS(SELECT 1 
              FROM   SYS.DEFAULT_CONSTRAINTS 
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CALCULATION_PROFILE_VIEW_MASTER' 
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                     AND NAME = 'DF_CALCULATION_PROFILE_VIEW_MASTER_CREATED_BY' 
                     AND TYPE = 'D') 
  BEGIN 
      ALTER TABLE [DBO].CALCULATION_PROFILE_VIEW_MASTER 
        ADD CONSTRAINT DF_CALCULATION_PROFILE_VIEW_MASTER_CREATED_BY DEFAULT (1) FOR CREATED_BY
  END 

GO 

--CREATED_DATE 
IF NOT EXISTS(SELECT 1 
              FROM   SYS.DEFAULT_CONSTRAINTS 
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CALCULATION_PROFILE_VIEW_MASTER' 
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                     AND NAME = 'DF_CALCULATION_PROFILE_VIEW_MASTER_CREATED_DATE' 
                     AND TYPE = 'D') 
  BEGIN 
      ALTER TABLE [DBO].CALCULATION_PROFILE_VIEW_MASTER 
        ADD CONSTRAINT DF_CALCULATION_PROFILE_VIEW_MASTER_CREATED_DATE DEFAULT GETDATE() FOR CREATED_DATE
  END 

GO 

--MODIFIED_BY 
IF NOT EXISTS(SELECT 1 
              FROM   SYS.DEFAULT_CONSTRAINTS 
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CALCULATION_PROFILE_VIEW_MASTER' 
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                     AND NAME = 'DF_CALCULATION_PROFILE_VIEW_MASTER_MODIFIED_BY' 
                     AND TYPE = 'D') 
  BEGIN 
      ALTER TABLE [DBO].CALCULATION_PROFILE_VIEW_MASTER 
        ADD CONSTRAINT DF_CALCULATION_PROFILE_VIEW_MASTER_MODIFIED_BY DEFAULT (1) FOR MODIFIED_BY
  END 

GO 

--MODIFIED_DATE 
IF NOT EXISTS(SELECT 1 
              FROM   SYS.DEFAULT_CONSTRAINTS 
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'CALCULATION_PROFILE_VIEW_MASTER' 
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                     AND NAME = 'DF_CALCULATION_PROFILE_VIEW_MASTER_MODIFIED_DATE' 
                     AND TYPE = 'D') 
  BEGIN 
      ALTER TABLE [DBO].CALCULATION_PROFILE_VIEW_MASTER 
        ADD CONSTRAINT DF_CALCULATION_PROFILE_VIEW_MASTER_MODIFIED_DATE DEFAULT GETDATE() FOR MODIFIED_DATE
  END 

GO 

-------------------------------------------ARM_BSR_PIPELINE----------------------------------------
IF NOT EXISTS (SELECT 'X' 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'ARM_BSR_PIPELINE' 
                      AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      CREATE TABLE [DBO].ARM_BSR_PIPELINE 
        ( 
           ARM_ADJUSTMENT_DETAILS_SID INT NOT NULL, 
           PERIOD_SID                 SMALLINT NOT NULL, 
           STARTING_BALANCE           NUMERIC(22, 6) NULL, 
           PIPELINE_ACCRUAL           NUMERIC(22, 6) NULL, 
           DEMAND_ACCRUAL             NUMERIC(22, 6) NULL, 
           PIPELINE_INVENTORY         NUMERIC(22, 6) NULL, 
           DEMAND_REFORECAST          NUMERIC(22, 6) NULL, 
           TOTAL_PERIOD_ADJ           NUMERIC(22, 6) NULL, 
           ENDING_BALANCE             NUMERIC(22, 6) NULL 
        ) 
  END 

GO 

IF NOT EXISTS (SELECT 1 
               FROM   SYS.KEY_CONSTRAINTS 
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'ARM_BSR_PIPELINE' 
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                      AND NAME = 'PK_ARM_BSR_PIPELINE_ARM_ADJUSTMENT_DETAILS_SID_PERIOD_SID' 
                      AND TYPE = 'PK') 
  BEGIN 
      ALTER TABLE [DBO].ARM_BSR_PIPELINE 
        ADD CONSTRAINT PK_ARM_BSR_PIPELINE_ARM_ADJUSTMENT_DETAILS_SID_PERIOD_SID PRIMARY KEY (ARM_ADJUSTMENT_DETAILS_SID,PERIOD_SID )
  END 

GO 

-------------------------------------------ARM_BSR_DEMAND----------------------------------------
IF NOT EXISTS (SELECT 'X' 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'ARM_BSR_DEMAND' 
                      AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      CREATE TABLE [DBO].ARM_BSR_DEMAND 
        ( 
           ARM_ADJUSTMENT_DETAILS_SID INT NOT NULL, 
           PERIOD_SID                 SMALLINT NOT NULL, 
           DEMAND_ACCRUAL             NUMERIC(22, 6) NULL,
           DEMAND_REFORECAST          NUMERIC(22, 6) NULL,
           DEMAND_PAYMENT_TRUE_UP	  NUMERIC(22, 6) NULL,
           ACTUAL_PAYMENTS			  NUMERIC(22, 6) NULL,
           PERIOD_BALANCE			  NUMERIC(22, 6) NULL,
           PAYMENT_RATIO			  NUMERIC(22, 6) NULL

        ) 
  END 

GO 

IF NOT EXISTS (SELECT 1 
               FROM   SYS.KEY_CONSTRAINTS 
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'ARM_BSR_DEMAND' 
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                      AND NAME = 'PK_ARM_BSR_DEMAND_ARM_ADJUSTMENT_DETAILS_SID_PERIOD_SID' 
                      AND TYPE = 'PK') 
  BEGIN 
      ALTER TABLE [DBO].ARM_BSR_DEMAND 
        ADD CONSTRAINT PK_ARM_BSR_DEMAND_ARM_ADJUSTMENT_DETAILS_SID_PERIOD_SID PRIMARY KEY (ARM_ADJUSTMENT_DETAILS_SID,PERIOD_SID )
  END 

GO 

-------------------------------------------ARM_BSR_CUM_DEMAND----------------------------------------
IF NOT EXISTS (SELECT 'X' 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'ARM_BSR_CUM_DEMAND' 
                      AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      CREATE TABLE [DBO].ARM_BSR_CUM_DEMAND 
        ( 
           ARM_ADJUSTMENT_DETAILS_SID INT NOT NULL, 
           DEMAND_ACCRUAL             NUMERIC(22, 6) NULL,
           DEMAND_REFORECAST          NUMERIC(22, 6) NULL,
           DEMAND_PAYMENT_TRUE_UP	  NUMERIC(22, 6) NULL,
           ACTUAL_PAYMENTS			  NUMERIC(22, 6) NULL,
           PERIOD_BALANCE			  NUMERIC(22, 6) NULL,
           PAYMENT_RATIO			  NUMERIC(22, 6) NULL

        ) 
  END 

GO 

IF NOT EXISTS (SELECT 1 
               FROM   SYS.KEY_CONSTRAINTS 
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'ARM_BSR_CUM_DEMAND' 
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                      AND NAME = 'PK_ARM_BSR_CUM_DEMAND_ARM_ADJUSTMENT_DETAILS_SID' 
                      AND TYPE = 'PK') 
  BEGIN 
      ALTER TABLE [DBO].ARM_BSR_CUM_DEMAND 
        ADD CONSTRAINT PK_ARM_BSR_CUM_DEMAND_ARM_ADJUSTMENT_DETAILS_SID PRIMARY KEY (ARM_ADJUSTMENT_DETAILS_SID)
  END 

GO 

-------------------------------------------ARM_BSR_SINGLE_LIABILITY----------------------------------------
IF NOT EXISTS (SELECT 'X' 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'ARM_BSR_SINGLE_LIABILITY' 
                      AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      CREATE TABLE [DBO].ARM_BSR_SINGLE_LIABILITY 
        ( 
           ARM_ADJUSTMENT_DETAILS_SID INT NOT NULL, 
           PERIOD_SID                 SMALLINT NOT NULL, 
           FEES_ACCRUAL               NUMERIC(22,6) NULL,
           INFLATION_ADJ              NUMERIC(22,6) NULL, 
           CREDIT_CARD_FEES			  NUMERIC(22,6) NULL,
           OTHER_FIXED_DOLLAR_FEES	  NUMERIC(22,6) NULL,
           INVENTORY_VALULATION		  NUMERIC(22,6) NULL,
           DEMAND_PAYMENT_TRUE_UP	  NUMERIC(22,6) NULL,
           ACTUALS_PAYMENTS			  NUMERIC(22,6) NULL,
           PERIOD_BALANCE			  NUMERIC(22,6) NULL
        ) 
  END 

GO 

IF NOT EXISTS (SELECT 1 
               FROM   SYS.KEY_CONSTRAINTS 
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'ARM_BSR_SINGLE_LIABILITY' 
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                      AND NAME = 'PK_ARM_BSR_SINGLE_LIABILITY_ARM_ADJUSTMENT_DETAILS_SID_PERIOD_SID' 
                      AND TYPE = 'PK') 
  BEGIN 
      ALTER TABLE [DBO].ARM_BSR_SINGLE_LIABILITY 
        ADD CONSTRAINT PK_ARM_BSR_SINGLE_LIABILITY_ARM_ADJUSTMENT_DETAILS_SID_PERIOD_SID PRIMARY KEY (ARM_ADJUSTMENT_DETAILS_SID,PERIOD_SID )
  END 

GO 

-------------------------------------------ARM_BSR_CUM_SINGLE_LIABILITY----------------------------------------
IF NOT EXISTS (SELECT 'X' 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'ARM_BSR_CUM_SINGLE_LIABILITY' 
                      AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      CREATE TABLE [DBO].ARM_BSR_CUM_SINGLE_LIABILITY 
        ( 
           ARM_ADJUSTMENT_DETAILS_SID INT NOT NULL, 
           FEES_ACCRUAL               NUMERIC(22,6) NULL,
           INFLATION_ADJ              NUMERIC(22,6) NULL, 
           CREDIT_CARD_FEES			  NUMERIC(22,6) NULL,
           OTHER_FIXED_DOLLAR_FEES	  NUMERIC(22,6) NULL,
           INVENTORY_VALULATION		  NUMERIC(22,6) NULL,
           DEMAND_PAYMENT_TRUE_UP	  NUMERIC(22,6) NULL,
           ACTUALS_PAYMENTS			  NUMERIC(22,6) NULL,
           PERIOD_BALANCE			  NUMERIC(22,6) NULL
        ) 
  END 

GO 

IF NOT EXISTS (SELECT 1 
               FROM   SYS.KEY_CONSTRAINTS 
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'ARM_BSR_CUM_SINGLE_LIABILITY' 
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                      AND NAME = 'PK_ARM_BSR_CUM_SINGLE_LIABILITY_ARM_ADJUSTMENT_DETAILS_SID' 
                      AND TYPE = 'PK') 
  BEGIN 
      ALTER TABLE [DBO].ARM_BSR_CUM_SINGLE_LIABILITY 
        ADD CONSTRAINT PK_ARM_BSR_CUM_SINGLE_LIABILITY_ARM_ADJUSTMENT_DETAILS_SID PRIMARY KEY (ARM_ADJUSTMENT_DETAILS_SID)
  END 

GO 
-------------------------------------------ARM_BSR_RETURN_RESERVE----------------------------------------
IF NOT EXISTS (SELECT 'X' 
               FROM   INFORMATION_SCHEMA.TABLES 
               WHERE  TABLE_NAME = 'ARM_BSR_RETURN_RESERVE' 
                      AND TABLE_SCHEMA = 'DBO') 
  BEGIN 
      CREATE TABLE [DBO].ARM_BSR_RETURN_RESERVE 
        ( 
           ARM_ADJUSTMENT_DETAILS_SID INT NOT NULL, 
           PERIOD_SID                 SMALLINT NOT NULL, 
           STARTING_BALANCE           NUMERIC(22,6) NULL,
           RETURN_RESERVE             NUMERIC(22,6) NULL, 
           ENDING_BALANCE			  NUMERIC(22,6) NULL
        ) 
  END 

GO 

IF NOT EXISTS (SELECT 1 
               FROM   SYS.KEY_CONSTRAINTS 
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'ARM_BSR_RETURN_RESERVE' 
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO' 
                      AND NAME = 'PK_ARM_BSR_RETURN_RESERVE_ARM_ADJUSTMENT_DETAILS_SID_PERIOD_SID' 
                      AND TYPE = 'PK') 
  BEGIN 
      ALTER TABLE [DBO].ARM_BSR_RETURN_RESERVE 
        ADD CONSTRAINT PK_ARM_BSR_RETURN_RESERVE_ARM_ADJUSTMENT_DETAILS_SID_PERIOD_SID PRIMARY KEY (ARM_ADJUSTMENT_DETAILS_SID,PERIOD_SID )
  END 

GO 