/*Insert Script to populate the created date information for the respective ARP existing projection*/


INSERT INTO ACCRUAL_PROJ_SELECTION (PROJECTION_MASTER_SID, SCREEN_NAME, FIELD_NAME, FIELD_VALUES)
  SELECT
    PM.PROJECTION_MASTER_SID,
    'Sales' SCREEN_NAME,
    'currentDate' FIELD_NAME,
    CONVERT(char(10), CASE
      WHEN PM.CREATED_DATE > PM.MODIFIED_DATE THEN PM.CREATED_DATE
      ELSE PM.MODIFIED_DATE
    END, 120) FIELD_VALUES
  FROM PROJECTION_MASTER PM
  JOIN WORKFLOW_MASTER WM
    ON WM.PROJECTION_MASTER_SID = PM.PROJECTION_MASTER_SID
  WHERE PM.FORECASTING_TYPE = 'AccrualRateProjection'
  AND NOT EXISTS (SELECT
    1
  FROM ACCRUAL_PROJ_SELECTION APS
  WHERE APS.PROJECTION_MASTER_SID = PM.PROJECTION_MASTER_SID
  AND APS.SCREEN_NAME = 'Sales'
  AND APS.FIELD_NAME = 'currentDate')
GO


/*To Update the dates information for the ARP Projection*/

UPDATE PROJECTION_MASTER
SET FROM_DATE = DATEADD(MONTH, -6, CONVERT(char(10), DATEADD(DAY, 1 - DAY(CREATED_DATE), CREATED_DATE), 120)),
    TO_DATE = DATEADD(MONTH, 36, CONVERT(char(10), DATEADD(DAY, 1 - DAY(CREATED_DATE), CREATED_DATE), 120))
WHERE FORECASTING_TYPE = 'AccrualRateProjection'
AND FROM_DATE < DATEADD(MONTH, -6, CONVERT(char(10), DATEADD(DAY, 1 - DAY(CREATED_DATE), CREATED_DATE), 120))
GO