IF NOT EXISTS (
              SELECT 'X'
              FROM INFORMATION_SCHEMA.TABLES
              WHERE TABLE_NAME = 'ARP_OUTBOUND'
                     AND TABLE_SCHEMA = 'DBO'
              )
BEGIN
       CREATE TABLE ARP_OUTBOUND (
              PROJECTION_MASTER_SID INT NOT NULL
              ,ARP_WORKFLOW_ID VARCHAR(50) NOT NULL
              ,COMPANY_MASTER_SID INT NOT NULL
              ,ITEM_MASTER_SID INT NOT NULL
              ,BRAND_MASTER_SID INT NOT NULL
              ,RS_MODEL_SID INT NULL
              ,ACCOUNT VARCHAR(50) NOT NULL
              ,ACCOUNT_TYPE VARCHAR(50) NOT NULL
              ,YEAR INT NOT NULL
              ,JAN NUMERIC(22, 6)
              ,FEB NUMERIC(22, 6)
              ,MAR NUMERIC(22, 6)
              ,APR NUMERIC(22, 6)
              ,MAY NUMERIC(22, 6)
              ,JUN NUMERIC(22, 6)
              ,JUL NUMERIC(22, 6)
              ,AUG NUMERIC(22, 6)
              ,SEP NUMERIC(22, 6)
              ,OCT NUMERIC(22, 6)
              ,NOV NUMERIC(22, 6)
              ,DEC NUMERIC(22, 6)
              ,ARP_CREATION_DATE DATETIME
              ,ARP_APPROVAL_DATE DATETIME
              ,OUTBOUND_STATUS BIT
              ,ORIGINAL_BATCH_ID VARCHAR(50)
              ,CREATED_DATE DATETIME NOT NULL
              ,MODIFIED_DATE DATETIME NOT NULL
              )
END
GO

----------------------- column addition --------------------

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ARP_OUTBOUND'
                      AND COLUMN_NAME = 'UOM'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ARP_OUTBOUND
        ADD UOM VARCHAR(50) NOT NULL
  END

GO


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ARP_OUTBOUND'
                      AND COLUMN_NAME = 'ACCOUNT_CATEGORY'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ARP_OUTBOUND
        ADD ACCOUNT_CATEGORY VARCHAR(50)  NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'ARP_OUTBOUND'
                      AND COLUMN_NAME = 'ACCOUNT_GROUP'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ARP_OUTBOUND
        ADD ACCOUNT_GROUP VARCHAR(50)  NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'ARP_OUTBOUND'
                      AND COLUMN_NAME = 'REBATE_PROGRAM_TYPE'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ARP_OUTBOUND
        ADD REBATE_PROGRAM_TYPE VARCHAR(50)  NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'ARP_OUTBOUND'
                      AND COLUMN_NAME = 'RS_CATEGORY'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ARP_OUTBOUND
        ADD RS_CATEGORY VARCHAR(50)  NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'ARP_OUTBOUND'
                      AND COLUMN_NAME = 'RS_TYPE'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ARP_OUTBOUND
        ADD RS_TYPE VARCHAR(50)  NULL
  END

  GO
------------------------------------------------------------UNIQUE KEY-------------------------------------------------------
  IF EXISTS (SELECT 1
                     FROM   SYS.KEY_CONSTRAINTS
                     WHERE TYPE_DESC = 'UNIQUE_CONSTRAINT'
                            AND PARENT_OBJECT_ID = OBJECT_ID('ARP_OUTBOUND')
                            AND NAME = 'UQ_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_YEAR_ACCOUNT_TYPE')
        BEGIN
            ALTER TABLE ARP_OUTBOUND
              DROP CONSTRAINT UQ_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_YEAR_ACCOUNT_TYPE 
        END

IF EXISTS (SELECT NAME
           FROM   SYS.TABLES
           WHERE NAME = 'ARP_OUTBOUND')
  BEGIN
      IF NOT EXISTS (SELECT 1
                     FROM   SYS.KEY_CONSTRAINTS
                     WHERE TYPE_DESC = 'UNIQUE_CONSTRAINT'
                            AND PARENT_OBJECT_ID = OBJECT_ID('ARP_OUTBOUND')
                            AND NAME = 'UQ_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_YEAR_ACCOUNT_TYPE_UOM_ACCOUNT_CATEGORY_ACCOUNT_GROUP')
        BEGIN
            ALTER TABLE ARP_OUTBOUND
              ADD CONSTRAINT UQ_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_YEAR_ACCOUNT_TYPE_UOM_ACCOUNT_CATEGORY_ACCOUNT_GROUP UNIQUE(ARP_WORKFLOW_ID, ITEM_MASTER_SID,RS_MODEL_SID,YEAR,ACCOUNT_TYPE,UOM,ACCOUNT_CATEGORY,ACCOUNT_GROUP)
        END
  END

GO

IF EXISTS (SELECT 1
                     FROM   SYS.KEY_CONSTRAINTS
                     WHERE TYPE_DESC = 'UNIQUE_CONSTRAINT'
                            AND PARENT_OBJECT_ID = OBJECT_ID('ARP_OUTBOUND')
                            AND NAME = 'UQ_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_YEAR_ACCOUNT_TYPE_UOM_ACCOUNT_CATEGORY_ACCOUNT_GROUP')
        BEGIN
            ALTER TABLE ARP_OUTBOUND
              DROP CONSTRAINT UQ_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_YEAR_ACCOUNT_TYPE_UOM_ACCOUNT_CATEGORY_ACCOUNT_GROUP
        END
  GO
IF EXISTS (SELECT NAME
           FROM   SYS.TABLES
           WHERE NAME = 'ARP_OUTBOUND')
  BEGIN
      IF NOT EXISTS (SELECT 1
                     FROM   SYS.KEY_CONSTRAINTS
                     WHERE TYPE_DESC = 'UNIQUE_CONSTRAINT'
                            AND PARENT_OBJECT_ID = OBJECT_ID('ARP_OUTBOUND')
                            AND NAME = 'UQ_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_YEAR_ACC_TYPE_UOM_ACC_CATEGORY_ACC_GROUP_RS_TYPE_RS_CAT_RP_TYPE')
        BEGIN
            ALTER TABLE ARP_OUTBOUND
              ADD CONSTRAINT UQ_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_YEAR_ACC_TYPE_UOM_ACC_CATEGORY_ACC_GROUP_RS_TYPE_RS_CAT_RP_TYPE UNIQUE(ARP_WORKFLOW_ID, ITEM_MASTER_SID, RS_MODEL_SID, YEAR, ACCOUNT_TYPE, UOM, ACCOUNT_CATEGORY, ACCOUNT_GROUP, RS_TYPE, RS_CATEGORY, REBATE_PROGRAM_TYPE)
        END
  END
 
GO
-------------------------------------------default const-------------------------------------------------------------
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ARP_OUTBOUND'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ARP_OUTBOUND_CREATED_DATE')
  BEGIN
      ALTER TABLE ARP_OUTBOUND
        ADD CONSTRAINT DF_ARP_OUTBOUND_CREATED_DATE DEFAULT (Getdate()) FOR CREATED_DATE
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ARP_OUTBOUND'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ARP_OUTBOUND_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ARP_OUTBOUND
        ADD CONSTRAINT DF_ARP_OUTBOUND_MODIFIED_DATE DEFAULT (Getdate()) FOR MODIFIED_DATE
  END

GO
------------------------------------------hist arp_outbound-------------------------------------------------------
IF NOT EXISTS (
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_NAME = 'HIST_ARP_OUTBOUND'
			AND TABLE_SCHEMA = 'DBO'
		)
BEGIN
	CREATE TABLE HIST_ARP_OUTBOUND (

	            PROJECTION_MASTER_SID INT NOT NULL
              ,ARP_WORKFLOW_ID VARCHAR(50) NOT NULL
              ,COMPANY_MASTER_SID INT NOT NULL
              ,ITEM_MASTER_SID INT NOT NULL
              ,BRAND_MASTER_SID INT NOT NULL
              ,RS_MODEL_SID INT NULL
              ,ACCOUNT VARCHAR(50) NOT NULL
              ,ACCOUNT_TYPE VARCHAR(50) NOT NULL
              ,YEAR INT NOT NULL
              ,JAN NUMERIC(22, 6)
              ,FEB NUMERIC(22, 6)
              ,MAR NUMERIC(22, 6)
              ,APR NUMERIC(22, 6)
              ,MAY NUMERIC(22, 6)
              ,JUN NUMERIC(22, 6)
              ,JUL NUMERIC(22, 6)
              ,AUG NUMERIC(22, 6)
              ,SEP NUMERIC(22, 6)
              ,OCT NUMERIC(22, 6)
              ,NOV NUMERIC(22, 6)
              ,DEC NUMERIC(22, 6)
              ,ARP_CREATION_DATE DATETIME
              ,ARP_APPROVAL_DATE DATETIME
              ,OUTBOUND_STATUS BIT
              ,ORIGINAL_BATCH_ID VARCHAR(50)
              ,CREATED_DATE DATETIME NOT NULL
              ,MODIFIED_DATE DATETIME NOT NULL			
		      , ACTION_FLAG CHAR(1) NOT NULL
		      , ACTION_DATE DATETIME NOT NULL
		
		)
END
GO


----------------------- column addition --------------------

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'HIST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'UOM'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE HIST_ARP_OUTBOUND
        ADD UOM VARCHAR(50) NOT NULL
  END

GO


IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'HIST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'ACCOUNT_CATEGORY'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE HIST_ARP_OUTBOUND
        ADD ACCOUNT_CATEGORY VARCHAR(50)  NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'HIST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'ACCOUNT_GROUP'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE HIST_ARP_OUTBOUND
        ADD ACCOUNT_GROUP VARCHAR(50)  NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'HIST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'REBATE_PROGRAM_TYPE'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE HIST_ARP_OUTBOUND
        ADD REBATE_PROGRAM_TYPE VARCHAR(50)  NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'HIST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'RS_CATEGORY'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE HIST_ARP_OUTBOUND
        ADD RS_CATEGORY VARCHAR(50)  NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'HIST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'RS_TYPE'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE HIST_ARP_OUTBOUND
        ADD RS_TYPE VARCHAR(50)  NULL
  END

  GO
-------------DEFAULT CONSTRAINTS---------------------
IF NOT EXISTS (
		SELECT *
		FROM SYS.DEFAULT_CONSTRAINTS
		WHERE Object_name(PARENT_OBJECT_ID) = 'HIST_ARP_OUTBOUND'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'DF_HIST_ARP_OUTBOUND_ACTION_DATE'
		)
BEGIN
	ALTER TABLE HIST_ARP_OUTBOUND ADD CONSTRAINT DF_HIST_ARP_OUTBOUND_ACTION_DATE DEFAULT(Getdate())
	FOR ACTION_DATE
END

GO
----------------------------------HIST_ARP_OUTBOUND TRIGGER--------------------------------------
IF EXISTS (
		SELECT 'X'
		FROM SYS.TRIGGERS
		WHERE [Name] = N'TRG_ARP_OUTBOUND_UPD'
		)
BEGIN
	DROP TRIGGER dbo.TRG_ARP_OUTBOUND_UPD
END
GO

CREATE TRIGGER [dbo].[TRG_ARP_OUTBOUND_UPD] ON [dbo].[ARP_OUTBOUND]
AFTER UPDATE
AS
BEGIN
SET NOCOUNT ON
	IF EXISTS (
			SELECT *
			FROM INSERTED
			)
		AND EXISTS (
			SELECT *
			FROM DELETED
			)
		INSERT INTO HIST_ARP_OUTBOUND ( 
		PROJECTION_MASTER_SID
		,ARP_WORKFLOW_ID
		,COMPANY_MASTER_SID
		,ITEM_MASTER_SID
		,BRAND_MASTER_SID
		,RS_MODEL_SID
		,ACCOUNT
		,ACCOUNT_TYPE
		,YEAR
		,JAN
		,FEB
		,MAR
		,APR
		,MAY
		,JUN
		,JUL
		,AUG
		,SEP
		,OCT
		,NOV
		,DEC
		,ARP_CREATION_DATE
		,ARP_APPROVAL_DATE
		,OUTBOUND_STATUS
		,ORIGINAL_BATCH_ID
		,CREATED_DATE
		,MODIFIED_DATE
		,ACTION_FLAG
		,UOM
		,ACCOUNT_CATEGORY
		,ACCOUNT_GROUP
		,REBATE_PROGRAM_TYPE
		,RS_CATEGORY
		,RS_TYPE
			)
		SELECT PROJECTION_MASTER_SID
		,ARP_WORKFLOW_ID
		,COMPANY_MASTER_SID
		,ITEM_MASTER_SID
		,BRAND_MASTER_SID
		,RS_MODEL_SID
		,ACCOUNT
		,ACCOUNT_TYPE
		,YEAR
		,JAN
		,FEB
		,MAR
		,APR
		,MAY
		,JUN
		,JUL
		,AUG
		,SEP
		,OCT
		,NOV
		,DEC
		,ARP_CREATION_DATE
		,ARP_APPROVAL_DATE
		,OUTBOUND_STATUS
		,ORIGINAL_BATCH_ID
		,CREATED_DATE
		,MODIFIED_DATE
			,'C'
			,UOM
		,ACCOUNT_CATEGORY
		,ACCOUNT_GROUP
		,REBATE_PROGRAM_TYPE
		,RS_CATEGORY
		,RS_TYPE
		FROM INSERTED
END
GO

IF EXISTS (
		SELECT 'X'
		FROM SYS.TRIGGERS
		WHERE [Name] = N'TRG_ARP_OUTBOUND_INS'
		)
BEGIN
	DROP TRIGGER dbo.TRG_ARP_OUTBOUND_INS
END
GO

CREATE TRIGGER [dbo].[TRG_ARP_OUTBOUND_INS] ON [dbo].[ARP_OUTBOUND]
AFTER INSERT
AS
BEGIN
SET NOCOUNT ON
	IF EXISTS (
			SELECT *
			FROM INSERTED
			)
		INSERT INTO HIST_ARP_OUTBOUND ( 
		PROJECTION_MASTER_SID
		,ARP_WORKFLOW_ID
		,COMPANY_MASTER_SID
		,ITEM_MASTER_SID
		,BRAND_MASTER_SID
		,RS_MODEL_SID
		,ACCOUNT
		,ACCOUNT_TYPE
		,YEAR
		,JAN
		,FEB
		,MAR
		,APR
		,MAY
		,JUN
		,JUL
		,AUG
		,SEP
		,OCT
		,NOV
		,DEC
		,ARP_CREATION_DATE
		,ARP_APPROVAL_DATE
		,OUTBOUND_STATUS
		,ORIGINAL_BATCH_ID
		,CREATED_DATE
		,MODIFIED_DATE
		,ACTION_FLAG
		,UOM
		,ACCOUNT_CATEGORY
		,ACCOUNT_GROUP
		,REBATE_PROGRAM_TYPE
		,RS_CATEGORY
		,RS_TYPE
			)
		SELECT PROJECTION_MASTER_SID
		,ARP_WORKFLOW_ID
		,COMPANY_MASTER_SID
		,ITEM_MASTER_SID
		,BRAND_MASTER_SID
		,RS_MODEL_SID
		,ACCOUNT
		,ACCOUNT_TYPE
		,YEAR
		,JAN
		,FEB
		,MAR
		,APR
		,MAY
		,JUN
		,JUL
		,AUG
		,SEP
		,OCT
		,NOV
		,DEC
		,ARP_CREATION_DATE
		,ARP_APPROVAL_DATE
		,OUTBOUND_STATUS
		,ORIGINAL_BATCH_ID
		,CREATED_DATE
		,MODIFIED_DATE
			, 'A'
			,UOM
		,ACCOUNT_CATEGORY
		,ACCOUNT_GROUP
		,REBATE_PROGRAM_TYPE
		,RS_CATEGORY
		,RS_TYPE
			
		FROM INSERTED
END
GO

IF EXISTS (
		SELECT 'X'
		FROM SYS.TRIGGERS
		WHERE [Name] = N'TRG_ARP_OUTBOUND_DEL'
		)
BEGIN
	DROP TRIGGER dbo.TRG_ARP_OUTBOUND_DEL
END
GO

CREATE TRIGGER [dbo].[TRG_ARP_OUTBOUND_DEL] ON [dbo].[ARP_OUTBOUND]
AFTER DELETE
AS
BEGIN
SET NOCOUNT ON
	IF EXISTS (
			SELECT *
			FROM DELETED
			)
				INSERT INTO HIST_ARP_OUTBOUND ( 
		PROJECTION_MASTER_SID
		,ARP_WORKFLOW_ID
		,COMPANY_MASTER_SID
		,ITEM_MASTER_SID
		,BRAND_MASTER_SID
		,RS_MODEL_SID
		,ACCOUNT
		,ACCOUNT_TYPE
		,YEAR
		,JAN
		,FEB
		,MAR
		,APR
		,MAY
		,JUN
		,JUL
		,AUG
		,SEP
		,OCT
		,NOV
		,DEC
		,ARP_CREATION_DATE
		,ARP_APPROVAL_DATE
		,OUTBOUND_STATUS
		,ORIGINAL_BATCH_ID
		,CREATED_DATE
		,MODIFIED_DATE
		,ACTION_FLAG
		,UOM
		,ACCOUNT_CATEGORY
		,ACCOUNT_GROUP
		,REBATE_PROGRAM_TYPE
		,RS_CATEGORY
		,RS_TYPE
			)
		SELECT PROJECTION_MASTER_SID
		,ARP_WORKFLOW_ID
		,COMPANY_MASTER_SID
		,ITEM_MASTER_SID
		,BRAND_MASTER_SID
		,RS_MODEL_SID
		,ACCOUNT
		,ACCOUNT_TYPE
		,YEAR
		,JAN
		,FEB
		,MAR
		,APR
		,MAY
		,JUN
		,JUL
		,AUG
		,SEP
		,OCT
		,NOV
		,DEC
		,ARP_CREATION_DATE
		,ARP_APPROVAL_DATE
		,OUTBOUND_STATUS
		,ORIGINAL_BATCH_ID
		,CREATED_DATE
		,MODIFIED_DATE
			, 'D'
			,UOM
		,ACCOUNT_CATEGORY
		,ACCOUNT_GROUP
		,REBATE_PROGRAM_TYPE
		,RS_CATEGORY
		,RS_TYPE
			
		FROM DELETED
END
GO

----------------------------------------------ST_ARP_OUTBOUND_MASTER---------------------------------------------------------------------
IF NOT EXISTS (
              SELECT 'X'
              FROM INFORMATION_SCHEMA.TABLES
              WHERE TABLE_NAME = 'ST_ARP_OUTBOUND'
                     AND TABLE_SCHEMA = 'DBO'
              )
BEGIN
       CREATE TABLE ST_ARP_OUTBOUND (
              ARP_WORKFLOW_ID VARCHAR(50) NOT NULL
              ,ITEM_MASTER_SID INT NOT NULL
              ,RS_MODEL_SID INT  NULL
              ,ACCOUNT_TYPE VARCHAR(50) NOT NULL
              ,USER_ID INT NOT NULL
              ,SESSION_ID VARCHAR(100) NOT NULL
              ,CHECK_RECORD BIT NULL
              ,ETL_CHECK_RECORD BIT NULL
              ,LAST_MODIFIED_DATE DATETIME NOT NULL
              )
END
GO

------------------------- column addition --------------------------- 

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'ACCOUNT_CATEGORY'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_ARP_OUTBOUND
        ADD  ACCOUNT_CATEGORY VARCHAR(50)  NULL
  END
GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'ACCOUNT_GROUP'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_ARP_OUTBOUND
        ADD  ACCOUNT_GROUP VARCHAR(50)NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'ST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'REBATE_PROGRAM_TYPE'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_ARP_OUTBOUND
        ADD REBATE_PROGRAM_TYPE VARCHAR(50)  NULL
  END
 GO
 
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'ST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'RS_CATEGORY'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_ARP_OUTBOUND
        ADD RS_CATEGORY VARCHAR(50)  NULL
  END
 GO
 
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE TABLE_NAME = 'ST_ARP_OUTBOUND'
                      AND COLUMN_NAME = 'RS_TYPE'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_ARP_OUTBOUND
        ADD RS_TYPE VARCHAR(50)  NULL
  END
GO
---------------------UNIQUE KEY CONSTRAINT------------------------
IF EXISTS (SELECT 1
                     FROM   SYS.KEY_CONSTRAINTS
                     WHERE  TYPE_DESC = 'UNIQUE_CONSTRAINT'
                            AND PARENT_OBJECT_ID = OBJECT_ID('ST_ARP_OUTBOUND')
                            AND NAME = 'UQ_ST_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_ACCOUNT_TYPE_USER_ID_SESSION_ID')
        BEGIN
            ALTER TABLE ST_ARP_OUTBOUND
              DROP CONSTRAINT UQ_ST_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_ACCOUNT_TYPE_USER_ID_SESSION_ID
        END

IF EXISTS (SELECT NAME
           FROM   SYS.TABLES
           WHERE  NAME = 'ST_ARP_OUTBOUND')
  BEGIN
      IF NOT EXISTS (SELECT 1
                     FROM   SYS.KEY_CONSTRAINTS
                     WHERE  TYPE_DESC = 'UNIQUE_CONSTRAINT'
                            AND PARENT_OBJECT_ID = OBJECT_ID('ST_ARP_OUTBOUND')
                            AND NAME = 'UQ_ST_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_ACCOUNT_TYPE_ACC_CATEGORY_ACC_GROUP_USER_ID_SESSION_ID')
        BEGIN
            ALTER TABLE ST_ARP_OUTBOUND
              ADD CONSTRAINT UQ_ST_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_ACCOUNT_TYPE_ACC_CATEGORY_ACC_GROUP_USER_ID_SESSION_ID UNIQUE(ARP_WORKFLOW_ID,ITEM_MASTER_SID,RS_MODEL_SID,ACCOUNT_TYPE,ACCOUNT_CATEGORY,ACCOUNT_GROUP,USER_ID,SESSION_ID)
        END
  END

GO

IF EXISTS (SELECT 1
                     FROM   SYS.KEY_CONSTRAINTS
                     WHERE  TYPE_DESC = 'UNIQUE_CONSTRAINT'
                            AND PARENT_OBJECT_ID = OBJECT_ID('ST_ARP_OUTBOUND')
                            AND NAME = 'UQ_ST_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_ACCOUNT_TYPE_ACC_CATEGORY_ACC_GROUP_USER_ID_SESSION_ID')
        BEGIN
            ALTER TABLE ST_ARP_OUTBOUND
              DROP CONSTRAINT UQ_ST_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_ACCOUNT_TYPE_ACC_CATEGORY_ACC_GROUP_USER_ID_SESSION_ID
        END
  GO
IF EXISTS (SELECT NAME
           FROM   SYS.TABLES
           WHERE  NAME = 'ST_ARP_OUTBOUND')
  BEGIN
      IF NOT EXISTS (SELECT 1
                     FROM   SYS.KEY_CONSTRAINTS
                     WHERE  TYPE_DESC = 'UNIQUE_CONSTRAINT'
                            AND PARENT_OBJECT_ID = OBJECT_ID('ST_ARP_OUTBOUND')
                            AND NAME = 'UQ_ST_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_ACC_TYPE_ACC_CATEGORY_ACC_GROUP_RS_TYPE_RS_CAT_RP_TYPE_U_ID_S_ID')
        BEGIN
            ALTER TABLE ST_ARP_OUTBOUND
              ADD CONSTRAINT UQ_ST_ARP_OUTBOUND_ARP_WORKFLOW_ID_ITEM_MASTER_SID_RS_MODEL_SID_ACC_TYPE_ACC_CATEGORY_ACC_GROUP_RS_TYPE_RS_CAT_RP_TYPE_U_ID_S_ID UNIQUE(ARP_WORKFLOW_ID, ITEM_MASTER_SID, RS_MODEL_SID, ACCOUNT_TYPE, ACCOUNT_CATEGORY, ACCOUNT_GROUP, RS_TYPE, RS_CATEGORY, REBATE_PROGRAM_TYPE, USER_ID, SESSION_ID)
       END
  END
 
GO

--------------------------------------------default cons--------------------------------------------------
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ARP_OUTBOUND'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_ARP_OUTBOUND_LAST_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ST_ARP_OUTBOUND
        ADD CONSTRAINT DF_ST_ARP_OUTBOUND_LAST_MODIFIED_DATE DEFAULT (Getdate()) FOR LAST_MODIFIED_DATE
  END

GO



