--------------------------------------------------------F.K'S FOR ACCRUAL_PROJ_DETAILS-------------------------------------------------
--CCP_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_PROJ_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_PROJ_DETAILS_CCP_DETAILS_CCP_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_PROJ_DETAILS
        ADD CONSTRAINT FK_ACCRUAL_PROJ_DETAILS_CCP_DETAILS_CCP_DETAILS_SID FOREIGN KEY(CCP_DETAILS_SID) REFERENCES CCP_DETAILS(CCP_DETAILS_SID)
  END

GO

--RS_MODEL
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_PROJ_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_PROJ_DETAILS_RS_MODEL_RS_MODEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_PROJ_DETAILS
        ADD CONSTRAINT FK_ACCRUAL_PROJ_DETAILS_RS_MODEL_RS_MODEL_SID FOREIGN KEY(RS_MODEL_SID) REFERENCES RS_MODEL(RS_MODEL_SID)
  END

GO

--PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_PROJ_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_PROJ_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_PROJ_DETAILS
        ADD CONSTRAINT FK_ACCRUAL_PROJ_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

--------------------------------------------------------F.K'S FOR ACCRUAL_PROJ_SELECTION-------------------------------------------------
--PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_PROJ_SELECTION'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_PROJ_SELECTION_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_PROJ_SELECTION
        ADD CONSTRAINT FK_ACCRUAL_PROJ_SELECTION_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

--------------------------------------------------------F.K'S FOR ACCRUAL_SALES_ACTUALS-------------------------------------------------
--PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_SALES_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_SALES_ACTUALS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_SALES_ACTUALS
        ADD CONSTRAINT FK_ACCRUAL_SALES_ACTUALS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_SALES_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_SALES_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_SALES_ACTUALS
        ADD CONSTRAINT FK_ACCRUAL_SALES_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

--ITEM_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_SALES_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_SALES_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_SALES_ACTUALS
        ADD CONSTRAINT FK_ACCRUAL_SALES_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

--------------------------------------------------------F.K'S FOR ACCRUAL_SALES_ACTUALS-------------------------------------------------
--PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_SALES_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_SALES_ACTUALS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_ACCRUAL_SALES_ACTUALS
        ADD CONSTRAINT FK_ST_ACCRUAL_SALES_ACTUALS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_SALES_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_SALES_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_ACCRUAL_SALES_ACTUALS
        ADD CONSTRAINT FK_ST_ACCRUAL_SALES_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

--ITEM_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_SALES_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_SALES_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_ACCRUAL_SALES_ACTUALS
        ADD CONSTRAINT FK_ST_ACCRUAL_SALES_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

--------------------------------------------------------F.K'S FOR ACCRUAL_SALES_DETAILS-------------------------------------------------
--PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_SALES_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_SALES_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_SALES_DETAILS
        ADD CONSTRAINT FK_ACCRUAL_SALES_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_SALES_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_SALES_DETAILS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_SALES_DETAILS
        ADD CONSTRAINT FK_ACCRUAL_SALES_DETAILS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

--ITEM_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_SALES_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_SALES_DETAILS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_SALES_DETAILS
        ADD CONSTRAINT FK_ACCRUAL_SALES_DETAILS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

--------------------------------------------------------F.K'S FOR ACCRUAL_SALES_ACTUALS-------------------------------------------------
--PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_SALES_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_SALES_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_ACCRUAL_SALES_DETAILS
        ADD CONSTRAINT FK_ST_ACCRUAL_SALES_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_SALES_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_SALES_DETAILS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_ACCRUAL_SALES_DETAILS
        ADD CONSTRAINT FK_ST_ACCRUAL_SALES_DETAILS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

--ITEM_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_SALES_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_SALES_DETAILS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_ACCRUAL_SALES_DETAILS
        ADD CONSTRAINT FK_ST_ACCRUAL_SALES_DETAILS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

--------------------------------------------------------F.K'S FOR EXCLUSION_DETAILS-------------------------------------------------
--PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'EXCLUSION_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_EXCLUSION_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE EXCLUSION_DETAILS
        ADD CONSTRAINT FK_EXCLUSION_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

--COMPANY_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'EXCLUSION_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_EXCLUSION_DETAILS_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE EXCLUSION_DETAILS
        ADD CONSTRAINT FK_EXCLUSION_DETAILS_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO

--------------------------------------------------------F.K'S FOR ST_EXCLUSION_DETAILS-------------------------------------------------
--PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_EXCLUSION_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_EXCLUSION_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_EXCLUSION_DETAILS
        ADD CONSTRAINT FK_ST_EXCLUSION_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

--COMPANY_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_EXCLUSION_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_EXCLUSION_DETAILS_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_EXCLUSION_DETAILS
        ADD CONSTRAINT FK_ST_EXCLUSION_DETAILS_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO

---------------------------------FOREIGN KEY CONSTRAINTS
--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_RATE_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_RATE_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_RATE_ACTUALS
        ADD CONSTRAINT FK_ACCRUAL_RATE_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_RATE_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_RATE_ACTUALS_ACCRUAL_PROJ_DETAILS_ACCRUAL_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_RATE_ACTUALS
        ADD CONSTRAINT FK_ACCRUAL_RATE_ACTUALS_ACCRUAL_PROJ_DETAILS_ACCRUAL_PROJ_DETAILS_SID FOREIGN KEY(ACCRUAL_PROJ_DETAILS_SID) REFERENCES ACCRUAL_PROJ_DETAILS(ACCRUAL_PROJ_DETAILS_SID)
  END

GO

---------------------------------FOREIGN KEY CONSTRAINTS
--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_RATE_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_RATE_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_ACCRUAL_RATE_ACTUALS
        ADD CONSTRAINT FK_ST_ACCRUAL_RATE_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_RATE_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_RATE_ACTUALS_ACCRUAL_PROJ_DETAILS_ACCRUAL_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_ACCRUAL_RATE_ACTUALS
        ADD CONSTRAINT FK_ST_ACCRUAL_RATE_ACTUALS_ACCRUAL_PROJ_DETAILS_ACCRUAL_PROJ_DETAILS_SID FOREIGN KEY(ACCRUAL_PROJ_DETAILS_SID) REFERENCES ACCRUAL_PROJ_DETAILS(ACCRUAL_PROJ_DETAILS_SID)
  END

GO

---------------------------------FOREIGN KEY CONSTRAINTS
--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_RATE_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_RATE_DETAILS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_RATE_DETAILS
        ADD CONSTRAINT FK_ACCRUAL_RATE_DETAILS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_RATE_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_RATE_DETAILS_ACCRUAL_PROJ_DETAILS_ACCRUAL_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ACCRUAL_RATE_DETAILS
        ADD CONSTRAINT FK_ACCRUAL_RATE_DETAILS_ACCRUAL_PROJ_DETAILS_ACCRUAL_PROJ_DETAILS_SID FOREIGN KEY(ACCRUAL_PROJ_DETAILS_SID) REFERENCES ACCRUAL_PROJ_DETAILS(ACCRUAL_PROJ_DETAILS_SID)
  END

GO

---------------------------------FOREIGN KEY CONSTRAINTS
--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_RATE_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_RATE_DETAILS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_ACCRUAL_RATE_DETAILS
        ADD CONSTRAINT FK_ST_ACCRUAL_RATE_DETAILS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_RATE_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_RATE_DETAILS_ACCRUAL_PROJ_DETAILS_ACCRUAL_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_ACCRUAL_RATE_DETAILS
        ADD CONSTRAINT FK_ST_ACCRUAL_RATE_DETAILS_ACCRUAL_PROJ_DETAILS_ACCRUAL_PROJ_DETAILS_SID FOREIGN KEY(ACCRUAL_PROJ_DETAILS_SID) REFERENCES ACCRUAL_PROJ_DETAILS(ACCRUAL_PROJ_DETAILS_SID)
  END

GO 


------------------------------------------F.K'S for ACCRUAL_DETAILS_ACTUALS--------------------

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_DETAILS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_DETAILS_ACTUALS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ACCRUAL_DETAILS_ACTUALS]
        ADD CONSTRAINT FK_ACCRUAL_DETAILS_ACTUALS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER (PROJECTION_MASTER_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_DETAILS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_DETAILS_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ACCRUAL_DETAILS_ACTUALS]
        ADD CONSTRAINT FK_ACCRUAL_DETAILS_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER (ITEM_MASTER_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_DETAILS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_DETAILS_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ACCRUAL_DETAILS_ACTUALS]
        ADD CONSTRAINT FK_ACCRUAL_DETAILS_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD (PERIOD_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_DETAILS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_DETAILS_ACTUALS_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ACCRUAL_DETAILS_ACTUALS]
        ADD CONSTRAINT FK_ACCRUAL_DETAILS_ACTUALS_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER (COMPANY_MASTER_SID)
  END

GO
------------------------------------------F.K'S for ST_ACCRUAL_DETAILS_ACTUALS--------------------
-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_DETAILS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_DETAILS_ACTUALS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ST_ACCRUAL_DETAILS_ACTUALS]
        ADD CONSTRAINT FK_ST_ACCRUAL_DETAILS_ACTUALS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER (PROJECTION_MASTER_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_DETAILS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_DETAILS_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ST_ACCRUAL_DETAILS_ACTUALS]
        ADD CONSTRAINT FK_ST_ACCRUAL_DETAILS_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER (ITEM_MASTER_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_DETAILS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_DETAILS_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ST_ACCRUAL_DETAILS_ACTUALS]
        ADD CONSTRAINT FK_ST_ACCRUAL_DETAILS_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD (PERIOD_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_DETAILS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_DETAILS_ACTUALS_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ST_ACCRUAL_DETAILS_ACTUALS]
        ADD CONSTRAINT FK_ST_ACCRUAL_DETAILS_ACTUALS_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER (COMPANY_MASTER_SID)
  END

GO
--------------------------------F.K's for ACCRUAL_DETAILS_INFO-----------------------------------------------------------------
-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_DETAILS_INFO'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_DETAILS_INFO_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ACCRUAL_DETAILS_INFO]
        ADD CONSTRAINT FK_ACCRUAL_DETAILS_INFO_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER (PROJECTION_MASTER_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_DETAILS_INFO'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_DETAILS_INFO_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ACCRUAL_DETAILS_INFO]
        ADD CONSTRAINT FK_ACCRUAL_DETAILS_INFO_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER (ITEM_MASTER_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_DETAILS_INFO'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_DETAILS_INFO_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ACCRUAL_DETAILS_INFO]
        ADD CONSTRAINT FK_ACCRUAL_DETAILS_INFO_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD (PERIOD_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ACCRUAL_DETAILS_INFO'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ACCRUAL_DETAILS_INFO_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ACCRUAL_DETAILS_INFO]
        ADD CONSTRAINT FK_ACCRUAL_DETAILS_INFO_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER (COMPANY_MASTER_SID)
  END

GO
--------------------------------F.K's for ST_ACCRUAL_DETAILS_INFO-----------------------------------------------------------------
-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_DETAILS_INFO'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_DETAILS_INFO_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ST_ACCRUAL_DETAILS_INFO]
        ADD CONSTRAINT FK_ST_ACCRUAL_DETAILS_INFO_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER (PROJECTION_MASTER_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_DETAILS_INFO'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_DETAILS_INFO_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ST_ACCRUAL_DETAILS_INFO]
        ADD CONSTRAINT FK_ST_ACCRUAL_DETAILS_INFO_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER (ITEM_MASTER_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_DETAILS_INFO'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_DETAILS_INFO_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ST_ACCRUAL_DETAILS_INFO]
        ADD CONSTRAINT FK_ST_ACCRUAL_DETAILS_INFO_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD (PERIOD_SID)
  END

GO

-----------------------------------------------ADDING FOREIGNKEY----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_ACCRUAL_DETAILS_INFO'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_ACCRUAL_DETAILS_INFO_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ST_ACCRUAL_DETAILS_INFO]
        ADD CONSTRAINT FK_ST_ACCRUAL_DETAILS_INFO_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER (COMPANY_MASTER_SID)
  END

GO 
