IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE Object_name(PARENT_OBJECT_ID) = 'ARP_OUTBOUND'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_ARP_OUTBOUND_COMPANY_MASTER_COMPANY_MASTER_SID'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE ARP_OUTBOUND add CONSTRAINT FK_ARP_OUTBOUND_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY (COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER (COMPANY_MASTER_SID)
END
GO

IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE Object_name(PARENT_OBJECT_ID) = 'ARP_OUTBOUND'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_ARP_OUTBOUND_ITEM_MASTER_ITEM_MASTER_SID'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE ARP_OUTBOUND ADD CONSTRAINT FK_ARP_OUTBOUND_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY (ITEM_MASTER_SID) REFERENCES ITEM_MASTER (ITEM_MASTER_SID)
END
GO



IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE Object_name(PARENT_OBJECT_ID) = 'ARP_OUTBOUND'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_ARP_OUTBOUND_RS_MODEL_RS_MODEL_SID'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE ARP_OUTBOUND ADD CONSTRAINT FK_ARP_OUTBOUND_RS_MODEL_RS_MODEL_SID FOREIGN KEY (RS_MODEL_SID) REFERENCES RS_MODEL (RS_MODEL_SID)
END
GO




IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE Object_name(PARENT_OBJECT_ID) = 'ST_ARP_OUTBOUND'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_ST_ARP_OUTBOUND_ITEM_MASTER_ITEM_MASTER_SID'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE ST_ARP_OUTBOUND ADD CONSTRAINT FK_ST_ARP_OUTBOUND_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY (ITEM_MASTER_SID) REFERENCES ITEM_MASTER (ITEM_MASTER_SID)
END
GO


IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE Object_name(PARENT_OBJECT_ID) = 'ST_ARP_OUTBOUND'
			AND Schema_name(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_ST_ARP_OUTBOUND_RS_MODEL_RS_MODEL_SID'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE ST_ARP_OUTBOUND ADD CONSTRAINT FK_ST_ARP_OUTBOUND_RS_MODEL_RS_MODEL_SID FOREIGN KEY (RS_MODEL_SID) REFERENCES RS_MODEL (RS_MODEL_SID)
END
GO