----------------------------------------RETURNS_DETAILS-----------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_DETAILS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].RETURNS_DETAILS
        (
           RETURNS_DETAILS_SID   INT IDENTITY(1, 1) NOT NULL,
           PROJECTION_MASTER_SID INT NULL,
           ITEM_MASTER_SID       INT NULL
        )
  END

GO

-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_DETAILS_RETURNS_DETAILS_SID'
                     AND TABLE_NAME = 'RETURNS_DETAILS')

BEGIN
  ALTER TABLE RETURNS_DETAILS
    ADD CONSTRAINT PK_RETURNS_DETAILS_RETURNS_DETAILS_SID PRIMARY KEY(RETURNS_DETAILS_SID)
END

GO

---------UNIQUE KEY CONSTRAINTS--------------------
--IF NOT EXISTS (SELECT 'X'
--               FROM   SYS.KEY_CONSTRAINTS
--               WHERE  PARENT_OBJECT_ID = Object_id('DBO.RETURNS_DETAILS')
--                      AND NAME = 'UQ_RETURNS_DETAILS_RETURNS_DETAILS_SID_PROJECTION_MASTER_SID_ITEM_MASTER_SID'
--                      AND TYPE = 'UQ')
--  BEGIN
--      ALTER TABLE [DBO].[RETURNS_DETAILS]
--        ADD CONSTRAINT [UQ_RETURNS_DETAILS_RETURNS_DETAILS_SID_PROJECTION_MASTER_SID_ITEM_MASTER_SID] 
--		UNIQUE (RETURNS_DETAILS_SID, PROJECTION_MASTER_SID, ITEM_MASTER_SID)
--  END

--GO 

IF EXISTS(SELECT 'X'
               FROM   SYS.KEY_CONSTRAINTS
               WHERE  PARENT_OBJECT_ID = Object_id('DBO.RETURNS_DETAILS')
                      AND NAME = 'UQ_RETURNS_DETAILS_RETURNS_DETAILS_SID_PROJECTION_MASTER_SID_ITEM_MASTER_SID'
                      AND TYPE = 'UQ')
 BEGIN
      ALTER TABLE [DBO].[RETURNS_DETAILS]
        DROP CONSTRAINT [UQ_RETURNS_DETAILS_RETURNS_DETAILS_SID_PROJECTION_MASTER_SID_ITEM_MASTER_SID] 
END
GO

;WITH CTE 
     AS (SELECT *, 
                ROW_NUMBER() 
                  OVER( 
                    PARTITION BY PROJECTION_MASTER_SID, ITEM_MASTER_SID 
                    ORDER BY RETURNS_DETAILS_SID ) AS RN 
         FROM   RETURNS_DETAILS) 
DELETE FROM CTE 
WHERE  RN > 1 

---------UNIQUE KEY CONSTRAINTS--------------------
IF NOT EXISTS (SELECT 'X'
               FROM   SYS.KEY_CONSTRAINTS
               WHERE  PARENT_OBJECT_ID = Object_id('DBO.RETURNS_DETAILS')
                      AND NAME = 'UQ_RETURNS_DETAILS_PROJECTION_MASTER_SID_ITEM_MASTER_SID'
                      AND TYPE = 'UQ')
  BEGIN
      ALTER TABLE [DBO].[RETURNS_DETAILS]
        ADD CONSTRAINT [UQ_RETURNS_DETAILS_PROJECTION_MASTER_SID_ITEM_MASTER_SID] 
		UNIQUE ( PROJECTION_MASTER_SID, ITEM_MASTER_SID)
  END

GO  



----------------------------------------RETURNS_MAP-----------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_MAP'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].RETURNS_MAP
        (
           PROJECTION_MASTER_SID INT NOT NULL,
           HIERARCHY_NO          VARCHAR(50) NOT NULL,
           RETURNS_DETAILS_SID   VARCHAR(4000) NULL,
           LEVEL_NO              INT NOT NULL
        )
  END

GO

-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_MAP_PROJECTION_MASTER_SID_HIERARCHY_NO_LEVEL_NO'
                     AND TABLE_NAME = 'RETURNS_MAP')
  ALTER TABLE RETURNS_MAP
    ADD CONSTRAINT PK_RETURNS_MAP_PROJECTION_MASTER_SID_HIERARCHY_NO_LEVEL_NO PRIMARY KEY(PROJECTION_MASTER_SID, HIERARCHY_NO, LEVEL_NO)

GO 


IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_PROJECTION_SELECTION'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].RETURNS_PROJECTION_SELECTION
        (
           RETURNS_PROJ_SELECTION_SID INT IDENTITY(1, 1) NOT NULL,
           PROJECTION_MASTER_SID      INT,
           SCREEN_NAME                VARCHAR(50),
           FIELD_NAME                 VARCHAR(30),
           FIELD_VALUES               VARCHAR(4000)
        )
  END

GO

-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_PROJECTION_SELECTION_RETURNS_PROJ_SELECTION_SID'
                     AND TABLE_NAME = 'RETURNS_PROJECTION_SELECTION')
BEGIN
  ALTER TABLE RETURNS_PROJECTION_SELECTION
    ADD CONSTRAINT PK_RETURNS_PROJECTION_SELECTION_RETURNS_PROJ_SELECTION_SID PRIMARY KEY(RETURNS_PROJ_SELECTION_SID)
END

GO

------------------------------------RETURNS_PROJ_MASTER----------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_PROJ_MASTER'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].RETURNS_PROJ_MASTER
        (
           RETURNS_DETAILS_SID    INT NOT NULL,
           METHODOLOGY            VARCHAR(50) NULL,
           METHODOLOGY_START_DATE VARCHAR(50),
           METHODOLOGY_END_DATE   VARCHAR(50),
           CALCULATION_PERIODS    VARCHAR(4000),
           LAG                    INT,
           CLOSED_DATE            DATETIME,
           LOE_DATE               DATETIME,
           CHECK_RECORD           BIT NOT NULL
        )
  END

GO

-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_PROJ_MASTER_RETURNS_DETAILS_SID'
                     AND TABLE_NAME = 'RETURNS_PROJ_MASTER')
BEGIN
  ALTER TABLE RETURNS_PROJ_MASTER
    ADD CONSTRAINT PK_RETURNS_PROJ_MASTER_RETURNS_DETAILS_SID PRIMARY KEY(RETURNS_DETAILS_SID)
END

GO

-------------DEFAULT CONSTRAINTS---------------------
IF NOT EXISTS (SELECT 'X'
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  PARENT_OBJECT_ID = Object_id('DBO.RETURNS_PROJ_MASTER')
                      AND NAME = 'DF_RETURNS_PROJ_MASTER_CHECK_RECORD')
  BEGIN
      ALTER TABLE [DBO].RETURNS_PROJ_MASTER
        ADD CONSTRAINT DF_RETURNS_PROJ_MASTER_CHECK_RECORD DEFAULT (0) FOR CHECK_RECORD
  END

GO

----------------------------RETURNS_ACTUALS-----------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_ACTUALS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].RETURNS_ACTUALS
        (
           RETURNS_DETAILS_SID   INT NOT NULL,
           PERIOD_SID            INT NOT NULL,
           ACTUAL_RETURN_PERCENT NUMERIC(22, 6) NULL,
           ACTUAL_RPU            NUMERIC(22, 6) NULL,
           ACTUAL_RETURN_AMOUNT  NUMERIC(22, 6) NULL,
           ORIG_SALE_UNITS       NUMERIC(22, 6) NULL,
           ORIG_SALE_DOLLARS     NUMERIC(22, 6) NULL,
           CUM_RETURN_UNITS      NUMERIC(22, 6) NULL,
           EXPECTED_RETURN_RATE  NUMERIC(22, 6) NULL,
           ASP                   NUMERIC(22, 6) NULL
        )
  END

GO

-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_ACTUALS_RETURNS_DETAILS_SID_PERIOD_SID'
                     AND TABLE_NAME = 'RETURNS_ACTUALS')
BEGIN
  ALTER TABLE RETURNS_ACTUALS
    ADD CONSTRAINT PK_RETURNS_ACTUALS_RETURNS_DETAILS_SID_PERIOD_SID PRIMARY KEY(RETURNS_DETAILS_SID, PERIOD_SID)
END

GO

------------------------------------RETURNS_PROJ_DETAILS----------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_PROJ_DETAILS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].RETURNS_PROJ_DETAILS
        (
           RETURNS_DETAILS_SID           INT NOT NULL,
           PERIOD_SID                    INT NOT NULL,
           GROWTH_RATE                   NUMERIC(22, 6) NULL,
           PROJECTED_RETURN_PERCENT      NUMERIC(22, 6) NULL,
           PROJECTED_RPU                 NUMERIC(22, 6) NULL,
           PROJECTED_RETURN_AMOUNT       NUMERIC(22, 6) NULL,
           PROJECTED_RETURN_UNITS        NUMERIC(22, 6) NULL,
           ACTIVE_EXFACTORY_SALES_AMOUNT NUMERIC(22, 6) NULL,
           ACTIVE_EXFACTORY_SALES_UNITS  NUMERIC(22, 6) NULL,
           REFRESHED_NAME                VARCHAR(50) NULL
        )
  END

GO

-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_PROJ_DETAILS_RETURNS_DETAILS_SID_PERIOD_SID'
                     AND TABLE_NAME = 'RETURNS_PROJ_DETAILS')
BEGIN
  ALTER TABLE RETURNS_PROJ_DETAILS
    ADD CONSTRAINT PK_RETURNS_PROJ_DETAILS_RETURNS_DETAILS_SID_PERIOD_SID PRIMARY KEY(RETURNS_DETAILS_SID, PERIOD_SID)
END

GO

------------------------------------ST_RETURNS_PROJ_MASTER----------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_RETURNS_PROJ_MASTER'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].ST_RETURNS_PROJ_MASTER
        (
           RETURNS_DETAILS_SID    INT NOT NULL,
           METHODOLOGY            VARCHAR(50) NULL,
           METHODOLOGY_START_DATE VARCHAR(50),
           METHODOLOGY_END_DATE   VARCHAR(50),
           CALCULATION_PERIODS    VARCHAR(4000),
           LAG                    INT,
           CLOSED_DATE            DATETIME,
           LOE_DATE               DATETIME,
           CHECK_RECORD           BIT NOT NULL,
           USER_ID                INT NOT NULL,
           SESSION_ID             INT NOT NULL
        )
  END

GO

-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_ST_RETURNS_PROJ_MASTER_RETURNS_DETAILS_SID_USER_ID_SESSION_ID'
                     AND TABLE_NAME = 'ST_RETURNS_PROJ_MASTER')
BEGIN
  ALTER TABLE ST_RETURNS_PROJ_MASTER
    ADD CONSTRAINT PK_ST_RETURNS_PROJ_MASTER_RETURNS_DETAILS_SID_USER_ID_SESSION_ID PRIMARY KEY(RETURNS_DETAILS_SID, USER_ID, SESSION_ID)
END

GO

-------------DEFAULT CONSTRAINTS---------------------
IF NOT EXISTS (SELECT 'X'
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  PARENT_OBJECT_ID = Object_id('DBO.ST_RETURNS_PROJ_MASTER')
                      AND NAME = 'DF_ST_RETURNS_PROJ_MASTER_CHECK_RECORD')
  BEGIN
      ALTER TABLE [DBO].ST_RETURNS_PROJ_MASTER
        ADD CONSTRAINT DF_ST_RETURNS_PROJ_MASTER_CHECK_RECORD DEFAULT (0) FOR CHECK_RECORD
  END

GO

----------------------------ST_RETURNS_ACTUALS-----------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_RETURNS_ACTUALS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].ST_RETURNS_ACTUALS
        (
           RETURNS_DETAILS_SID   INT NOT NULL,
           PERIOD_SID            INT NOT NULL,
           ACTUAL_RETURN_PERCENT NUMERIC(22, 6) NULL,
           ACTUAL_RPU            NUMERIC(22, 6) NULL,
           ACTUAL_RETURN_AMOUNT  NUMERIC(22, 6) NULL,
           ORIG_SALE_UNITS       NUMERIC(22, 6) NULL,
           ORIG_SALE_DOLLARS     NUMERIC(22, 6) NULL,
           CUM_RETURN_UNITS      NUMERIC(22, 6) NULL,
           EXPECTED_RETURN_RATE  NUMERIC(22, 6) NULL,
           ASP                   NUMERIC(22, 6) NULL,
           USER_ID               INT NOT NULL,
           SESSION_ID            INT NOT NULL
        )
  END

GO

-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_ST_RETURNS_ACTUALS_RETURNS_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID'
                     AND TABLE_NAME = 'ST_RETURNS_ACTUALS')
BEGIN
  ALTER TABLE ST_RETURNS_ACTUALS
    ADD CONSTRAINT PK_ST_RETURNS_ACTUALS_RETURNS_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID PRIMARY KEY(RETURNS_DETAILS_SID, PERIOD_SID, USER_ID, SESSION_ID)
END

GO

------------------------------------ST_RETURNS_PROJ_DETAILS----------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_RETURNS_PROJ_DETAILS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].ST_RETURNS_PROJ_DETAILS
        (
           RETURNS_DETAILS_SID           INT NOT NULL,
           PERIOD_SID                    INT NOT NULL,
           GROWTH_RATE                   NUMERIC(22, 6) NULL,
           PROJECTED_RETURN_PERCENT      NUMERIC(22, 6) NULL,
           PROJECTED_RPU                 NUMERIC(22, 6) NULL,
           PROJECTED_RETURN_AMOUNT       NUMERIC(22, 6) NULL,
           PROJECTED_RETURN_UNITS        NUMERIC(22, 6) NULL,
           ACTIVE_EXFACTORY_SALES_AMOUNT NUMERIC(22, 6) NULL,
           ACTIVE_EXFACTORY_SALES_UNITS  NUMERIC(22, 6) NULL,
           REFRESHED_NAME                VARCHAR(50) NULL,
           USER_ID                       INT NOT NULL,
           SESSION_ID                    INT NOT NULL
        )
  END

GO

-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_ST_RETURNS_PROJ_DETAILS_RETURNS_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID'
                     AND TABLE_NAME = 'ST_RETURNS_PROJ_DETAILS')
BEGIN
  ALTER TABLE ST_RETURNS_PROJ_DETAILS
    ADD CONSTRAINT PK_ST_RETURNS_PROJ_DETAILS_RETURNS_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID PRIMARY KEY(RETURNS_DETAILS_SID, PERIOD_SID, USER_ID, SESSION_ID)
END

GO 
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_PROJ_MASTER_TEST'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[RETURNS_PROJ_MASTER_TEST]
        (
           [PROJECTION_MASTER_SID]  [INT] NOT NULL,
           [ITEM_MASTER_SID]        [INT] NOT NULL,
           [METHODOLOGY]            [VARCHAR](50) NULL,
           [METHODOLOGY_START_DATE] [VARCHAR](50) NULL,
           [METHODOLOGY_END_DATE]   [VARCHAR](50) NULL,
           [CALCULATION_PERIODS]    [VARCHAR](4000) NULL,
           [LAG]                    [INT] NULL,
           [CLOSED_DATE]            [DATETIME] NULL,
           [LOE_DATE]               [DATETIME] NULL,
           [CHECK_RECORD]           [BIT] NOT NULL
        )
  END 


-------------PRIMARY KEYS--------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_PROJ_MASTER_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID'
                     AND TABLE_NAME = 'RETURNS_PROJ_MASTER_TEST')
BEGIN
  ALTER TABLE RETURNS_PROJ_MASTER_TEST
    ADD CONSTRAINT PK_RETURNS_PROJ_MASTER_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID PRIMARY KEY(PROJECTION_MASTER_SID, ITEM_MASTER_SID)
END

GO

-------------DEFAULT CONSTRAINTS---------------------
IF NOT EXISTS (SELECT 'X'
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  PARENT_OBJECT_ID = Object_id('DBO.RETURNS_PROJ_MASTER_TEST')
                      AND NAME = 'DF_RETURNS_PROJ_MASTER_CHECK_RECORD_TEST')
  BEGIN
      ALTER TABLE [DBO].RETURNS_PROJ_MASTER_TEST
        ADD CONSTRAINT DF_RETURNS_PROJ_MASTER_CHECK_RECORD_TEST DEFAULT (0) FOR CHECK_RECORD
  END

GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_PROJ_DETAILS_TEST'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [dbo].[RETURNS_PROJ_DETAILS_TEST]
        (
           [PROJECTION_MASTER_SID]         [INT] NOT NULL,
           [ITEM_MASTER_SID]               [INT] NOT NULL,
           [PERIOD_SID]                    [INT] NOT NULL,
           [GROWTH_RATE]                   [NUMERIC](22, 6) NULL,
           [PROJECTED_RETURN_PERCENT]      [NUMERIC](22, 6) NULL,
           [PROJECTED_RPU]                 [NUMERIC](22, 6) NULL,
           [PROJECTED_RETURN_AMOUNT]       [NUMERIC](22, 6) NULL,
           [PROJECTED_RETURN_UNITS]        [NUMERIC](22, 6) NULL,
           [ACTIVE_EXFACTORY_SALES_AMOUNT] [NUMERIC](22, 6) NULL,
           [ACTIVE_EXFACTORY_SALES_UNITS]  [NUMERIC](22, 6) NULL,
           [REFRESHED_NAME]                [VARCHAR](50) NULL,
        )
  END 


IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_PROJ_DETAILS_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID'
                     AND TABLE_NAME = 'RETURNS_PROJ_DETAILS_TEST')
  BEGIN
      ALTER TABLE RETURNS_PROJ_DETAILS_TEST
        ADD CONSTRAINT PK_RETURNS_PROJ_DETAILS_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID PRIMARY KEY(PROJECTION_MASTER_SID, ITEM_MASTER_SID, PERIOD_SID)
  END

GO 
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'RETURNS_ACTUALS_TEST'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [dbo].[RETURNS_ACTUALS_TEST]
        (
           [PROJECTION_MASTER_SID] [INT] NOT NULL,
           [ITEM_MASTER_SID]       [INT] NOT NULL,
           [PERIOD_SID]            [INT] NOT NULL,
           [ACTUAL_RETURN_PERCENT] [NUMERIC](22, 6) NULL,
           [ACTUAL_RPU]            [NUMERIC](22, 6) NULL,
           [ACTUAL_RETURN_AMOUNT]  [NUMERIC](22, 6) NULL,
           [ORIG_SALE_UNITS]       [NUMERIC](22, 6) NULL,
           [ORIG_SALE_DOLLARS]     [NUMERIC](22, 6) NULL,
           [CUM_RETURN_UNITS]      [NUMERIC](22, 6) NULL,
           [EXPECTED_RETURN_RATE]  [NUMERIC](22, 6) NULL
        )
  END 
GO

IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_RETURNS_ACTUALS_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID'
                     AND TABLE_NAME = 'RETURNS_ACTUALS_TEST')
  BEGIN
      ALTER TABLE RETURNS_ACTUALS_TEST
        ADD CONSTRAINT PK_RETURNS_ACTUALS_TEST_PROJECTION_MASTER_SID_ITEM_MASTER_SID_PERIOD_SID PRIMARY KEY(PROJECTION_MASTER_SID, ITEM_MASTER_SID, PERIOD_SID)
  END

GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.COLUMNS
              WHERE  NAME = 'ASP' AND object_id = Object_id('RETURNS_ACTUALS_TEST'))
  BEGIN
      ALTER TABLE RETURNS_ACTUALS_TEST ADD ASP NUMERIC(22, 6)
  END 
GO
