----------------------------------------RETURNS_DETAILS-------------------------------------------------
--F.K'S
----PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RETURNS_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RETURNS_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RETURNS_DETAILS
        ADD CONSTRAINT FK_RETURNS_DETAILS_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

----ITEM_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RETURNS_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RETURNS_DETAILS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RETURNS_DETAILS
        ADD CONSTRAINT FK_RETURNS_DETAILS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

----------------------------------------RETURNS_MAP-------------------------------------------------
--F.K'S
----PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RETURNS_MAP'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RETURNS_MAP_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RETURNS_MAP
        ADD CONSTRAINT FK_RETURNS_MAP_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO

----------------------------------------RETURNS_PROJECTION_SELECTION-----------------------------------------------
--F.K'S
----PROJECTION_MASTER
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RETURNS_PROJECTION_SELECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RETURNS_PROJECTION_SELECTION_PROJECTION_MASTER_PROJECTION_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RETURNS_PROJECTION_SELECTION
        ADD CONSTRAINT FK_RETURNS_PROJECTION_SELECTION_PROJECTION_MASTER_PROJECTION_MASTER_SID FOREIGN KEY(PROJECTION_MASTER_SID) REFERENCES PROJECTION_MASTER(PROJECTION_MASTER_SID)
  END

GO


------------------------------------RETURNS_PROJ_MASTER----------------------------------------
-----FK'S
----RETURNS_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RETURNS_PROJ_MASTER'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RETURNS_PROJ_MASTER_RETURNS_DETAILS_RETURNS_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RETURNS_PROJ_MASTER
        ADD CONSTRAINT FK_RETURNS_PROJ_MASTER_RETURNS_DETAILS_RETURNS_DETAILS_SID FOREIGN KEY(RETURNS_DETAILS_SID) REFERENCES RETURNS_DETAILS(RETURNS_DETAILS_SID)
  END

GO

----------------------------RETURNS_ACTUALS-----------------------------
--F.K'S
----RETURNS_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RETURNS_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RETURNS_ACTUALS_RETURNS_DETAILS_RETURNS_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RETURNS_ACTUALS
        ADD CONSTRAINT FK_RETURNS_ACTUALS_RETURNS_DETAILS_RETURNS_DETAILS_SID FOREIGN KEY(RETURNS_DETAILS_SID) REFERENCES RETURNS_DETAILS(RETURNS_DETAILS_SID)
  END

GO

--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RETURNS_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RETURNS_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RETURNS_ACTUALS
        ADD CONSTRAINT FK_RETURNS_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

------------------------------------RETURNS_PROJ_DETAILS----------------------------------------
--F.K'S
----RETURNS_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RETURNS_PROJ_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RETURNS_PROJ_DETAILS_RETURNS_DETAILS_RETURNS_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RETURNS_PROJ_DETAILS
        ADD CONSTRAINT FK_RETURNS_PROJ_DETAILS_RETURNS_DETAILS_RETURNS_DETAILS_SID FOREIGN KEY(RETURNS_DETAILS_SID) REFERENCES RETURNS_DETAILS(RETURNS_DETAILS_SID)
  END

GO

--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RETURNS_PROJ_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RETURNS_PROJ_DETAILS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RETURNS_PROJ_DETAILS
        ADD CONSTRAINT FK_RETURNS_PROJ_DETAILS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

------------------------------------ST_RETURNS_PROJ_MASTER----------------------------------------
-----FK'S
----RETURNS_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_RETURNS_PROJ_MASTER'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_RETURNS_PROJ_MASTER_RETURNS_DETAILS_RETURNS_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_RETURNS_PROJ_MASTER
        ADD CONSTRAINT FK_ST_RETURNS_PROJ_MASTER_RETURNS_DETAILS_RETURNS_DETAILS_SID FOREIGN KEY(RETURNS_DETAILS_SID) REFERENCES RETURNS_DETAILS(RETURNS_DETAILS_SID)
  END

GO

----------------------------ST_RETURNS_ACTUALS-----------------------------
--F.K'S
----RETURNS_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_RETURNS_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_RETURNS_ACTUALS_RETURNS_DETAILS_RETURNS_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_RETURNS_ACTUALS
        ADD CONSTRAINT FK_ST_RETURNS_ACTUALS_RETURNS_DETAILS_RETURNS_DETAILS_SID FOREIGN KEY(RETURNS_DETAILS_SID) REFERENCES RETURNS_DETAILS(RETURNS_DETAILS_SID)
  END

GO

--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_RETURNS_ACTUALS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_RETURNS_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_RETURNS_ACTUALS
        ADD CONSTRAINT FK_ST_RETURNS_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

------------------------------------ST_RETURNS_PROJ_DETAILS----------------------------------------
--F.K'S
----RETURNS_DETAILS
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_RETURNS_PROJ_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_RETURNS_PROJ_DETAILS_RETURNS_DETAILS_RETURNS_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_RETURNS_PROJ_DETAILS
        ADD CONSTRAINT FK_ST_RETURNS_PROJ_DETAILS_RETURNS_DETAILS_RETURNS_DETAILS_SID FOREIGN KEY(RETURNS_DETAILS_SID) REFERENCES RETURNS_DETAILS(RETURNS_DETAILS_SID)
  END

GO

--PERIOD
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_RETURNS_PROJ_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_RETURNS_PROJ_DETAILS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_RETURNS_PROJ_DETAILS
        ADD CONSTRAINT FK_ST_RETURNS_PROJ_DETAILS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO 
