----------------------------------------------- NM_DISCOUNT_PROJ_MASTER ---------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[NM_DISCOUNT_PROJ_MASTER]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           RS_MODEL_SID           INT NOT NULL,
           METHODOLOGY            VARCHAR(50) NULL,
           PRICE_GROUP_TYPE       VARCHAR(50) NULL,
           NET_FLAG               CHAR(1) NULL,
           USER_GROUP             VARCHAR(50) NULL,
           CHECK_RECORD           BIT NOT NULL,
           BASELINE_PERIODS       VARCHAR(500) NULL,
           SELECTED_PERIODS       VARCHAR(500) NULL
        )
  END

GO
---------------------------- column addition ----------------------
IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                 AND COLUMN_NAME = 'BASELINE_PERIODS'
                 AND DATA_TYPE = 'VARCHAR'
                 AND CHARACTER_OCTET_LENGTH = 500)
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ALTER COLUMN BASELINE_PERIODS VARCHAR(4000)
  END

GO

IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                 AND COLUMN_NAME = 'SELECTED_PERIODS'
                 AND DATA_TYPE = 'VARCHAR'
                 AND CHARACTER_OCTET_LENGTH = 500)
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ALTER COLUMN SELECTED_PERIODS VARCHAR(4000)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'CALCULATION_PERIODS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD CALCULATION_PERIODS VARCHAR(1000)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'CALCULATION_BASED'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD CALCULATION_BASED VARCHAR(100)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'FORECAST_START_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD FORECAST_START_PERIOD_SID INT
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'FORECAST_END_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD FORECAST_END_PERIOD_SID INT
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'EFFECTIVE_START_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD EFFECTIVE_START_PERIOD_SID INT NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'EFFECTIVE_END_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD EFFECTIVE_END_PERIOD_SID INT NULL
  END

GO
  
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'FREQ_CAL_START_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD FREQ_CAL_START_PERIOD_SID INT
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'FREQ_CAL_END_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD FREQ_CAL_END_PERIOD_SID INT
  END 

GO


IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'EFFECTIVE_START_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        DROP COLUMN EFFECTIVE_START_PERIOD_SID  
  END

GO

IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'EFFECTIVE_END_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        DROP COLUMN EFFECTIVE_END_PERIOD_SID  
  END

GO


IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'FREQ_CAL_START_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        DROP COLUMN FREQ_CAL_START_PERIOD_SID 
  END

GO

IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'FREQ_CAL_END_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        DROP COLUMN FREQ_CAL_END_PERIOD_SID 
  END 

GO
--------------------------------------------------- 1163

IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                 AND COLUMN_NAME = 'RS_CONTRACT_SID'
                 AND DATA_TYPE = 'INT')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD RS_CONTRACT_SID INT
  END

GO

IF OBJECT_ID('TEMPDB..#TEMP_DISCOUNT_MASTER') IS NOT NULL 
  BEGIN
  DROP TABLE #TEMP_DISCOUNT_MASTER 
    END
  GO

IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                 AND COLUMN_NAME = 'RS_CONTRACT_SID'
                 AND DATA_TYPE = 'INT')
  BEGIN
     
	 SELECT A.*, 
       G.RS_MODEL_SID, 
       G.RS_CONTRACT_SID 
	 INTO #TEMP_DISCOUNT_MASTER
	 FROM   PROJECTION_DETAILS A 
       JOIN CCP_DETAILS B 
         ON B.CCP_DETAILS_SID = A.CCP_DETAILS_SID 
       JOIN CFP_CONTRACT C 
         ON C.CONTRACT_MASTER_SID = B.CONTRACT_MASTER_SID 
       JOIN CFP_CONTRACT_DETAILS D  
		ON D.CFP_CONTRACT_SID = C.CFP_CONTRACT_SID 
            AND D.COMPANY_MASTER_SID = B.COMPANY_MASTER_SID 
	   JOIN IFP_CONTRACT E 
         ON E.CONTRACT_MASTER_SID = B.CONTRACT_MASTER_SID 
            AND E.CFP_CONTRACT_SID = C.CFP_CONTRACT_SID 
       JOIN IFP_CONTRACT_DETAILS F 
         ON F.IFP_CONTRACT_SID = E.IFP_CONTRACT_SID 
            AND F.ITEM_MASTER_SID = B.ITEM_MASTER_SID 
	   JOIN RS_CONTRACT G 
         ON G.CONTRACT_MASTER_SID = B.CONTRACT_MASTER_SID 
            AND G.CFP_CONTRACT_SID = C.CFP_CONTRACT_SID 
            AND G.IFP_CONTRACT_SID = E.IFP_CONTRACT_SID 
	  JOIN RS_CONTRACT_DETAILS H 
         ON H.RS_CONTRACT_SID = G.RS_CONTRACT_SID 
            AND H.ITEM_MASTER_SID = B.ITEM_MASTER_SID 
     END

GO

 IF EXISTS (SELECT 1)
BEGIN

       
	UPDATE A
	SET A.RS_CONTRACT_SID=B.RS_CONTRACT_SID
	FROM NM_DISCOUNT_PROJ_MASTER A
	JOIN #TEMP_DISCOUNT_MASTER b 
		ON A.PROJECTION_DETAILS_SID=B.PROJECTION_DETAILS_SID
		  AND A.RS_MODEL_SID=B.RS_MODEL_SID
	WHERE A.RS_CONTRACT_SID IS NULL

END
GO



IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                 AND COLUMN_NAME = 'RS_CONTRACT_SID'
                 AND DATA_TYPE = 'INT')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ALTER COLUMN RS_CONTRACT_SID INT NOT NULL
  END

GO
------------------ PRIMARY KEY -----------------------------------------
--IF NOT EXISTS(SELECT 'X'
--              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
--              WHERE  CONSTRAINT_NAME = 'PK_NM_DISCOUNT_PROJ_MASTER_PROJECTION_DETAILS_SID_RS_MODEL_SID'
--                     AND TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER')
--BEGIN
--  ALTER TABLE NM_DISCOUNT_PROJ_MASTER
--    ADD CONSTRAINT PK_NM_DISCOUNT_PROJ_MASTER_PROJECTION_DETAILS_SID_RS_MODEL_SID PRIMARY KEY(PROJECTION_DETAILS_SID, RS_MODEL_SID)
--END

--GO

IF EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_NM_DISCOUNT_PROJ_MASTER_PROJECTION_DETAILS_SID_RS_MODEL_SID'
                     AND TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER')
BEGIN
  ALTER TABLE NM_DISCOUNT_PROJ_MASTER
    DROP CONSTRAINT PK_NM_DISCOUNT_PROJ_MASTER_PROJECTION_DETAILS_SID_RS_MODEL_SID 
END

GO

--IF NOT EXISTS(SELECT 'X'
--              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
--              WHERE  CONSTRAINT_NAME = 'PK_NM_DISCOUNT_PROJ_MASTER_PROJECTION_DETAILS_SID_RS_CONTRACT_SID'
--                     AND TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER')
--BEGIN
--  ALTER TABLE NM_DISCOUNT_PROJ_MASTER
--    ADD CONSTRAINT PK_NM_DISCOUNT_PROJ_MASTER_PROJECTION_DETAILS_SID_RS_CONTRACT_SID PRIMARY KEY(PROJECTION_DETAILS_SID, RS_CONTRACT_SID)
--END
--
--GO
IF EXISTS (SELECT 1
           FROM   SYS.KEY_CONSTRAINTS
           WHERE  Object_name(PARENT_OBJECT_ID) = 'NM_DISCOUNT_PROJ_MASTER'
                  AND Schema_name(SCHEMA_ID) = 'DBO'
                  AND NAME = 'PK_NM_DISCOUNT_PROJ_MASTER_PROJECTION_DETAILS_SID_RS_CONTRACT_SID'
                  AND TYPE = 'PK')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        DROP CONSTRAINT PK_NM_DISCOUNT_PROJ_MASTER_PROJECTION_DETAILS_SID_RS_CONTRACT_SID
  END

GO

--------------adding columns 
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'PROJECTION_MASTER_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD PROJECTION_MASTER_SID INT NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'CCP_DETAILS_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD CCP_DETAILS_SID INT NULL
  END

GO 


----------------------------
IF EXISTS(SELECT 1
          FROM   NM_DISCOUNT_PROJ_MASTER
          WHERE  ( CCP_DETAILS_SID IS NULL
                    OR PROJECTION_MASTER_SID IS NULL ))
  BEGIN
      UPDATE TARGET
      SET    TARGET.PROJECTION_MASTER_SID = PD.PROJECTION_MASTER_SID,
             TARGET.CCP_DETAILS_SID = PD.CCP_DETAILS_SID
      FROM   NM_DISCOUNT_PROJ_MASTER TARGET
             JOIN PROJECTION_DETAILS PD
               ON PD.PROJECTION_DETAILS_SID = TARGET.PROJECTION_DETAILS_SID
      WHERE  ( TARGET.CCP_DETAILS_SID IS NULL
                OR TARGET.PROJECTION_MASTER_SID IS NULL )
  END

GO

------------------altering to not null
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                  AND COLUMN_NAME = 'PROJECTION_MASTER_SID'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ALTER COLUMN PROJECTION_MASTER_SID INT NOT NULL
  END

GO

IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER'
                  AND COLUMN_NAME = 'CCP_DETAILS_SID'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ALTER COLUMN CCP_DETAILS_SID INT NOT NULL
  END

GO

------------create pk
IF NOT EXISTS (SELECT 1
               FROM   SYS.KEY_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'NM_DISCOUNT_PROJ_MASTER'
                      AND Schema_name(SCHEMA_ID) = 'DBO'
                      AND NAME = 'PK_NM_DISCOUNT_PROJ_MASTER_PROJECTION_MASTER_SID_CCP_DETAILS_SID_RS_CONTRACT_SID'
                      AND TYPE = 'PK')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        ADD CONSTRAINT PK_NM_DISCOUNT_PROJ_MASTER_PROJECTION_MASTER_SID_CCP_DETAILS_SID_RS_CONTRACT_SID PRIMARY KEY ( PROJECTION_MASTER_SID, CCP_DETAILS_SID, RS_CONTRACT_SID )
  END

GO 

------------------------------------------------- ST_NM_DISCOUNT_PROJ_MASTER ------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJ_MASTER'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[ST_NM_DISCOUNT_PROJ_MASTER]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           RS_MODEL_SID           INT NOT NULL,
           METHODOLOGY            VARCHAR(50) NULL,
           PRICE_GROUP_TYPE       VARCHAR(50) NULL,
           NET_FLAG               CHAR(1) NULL,
           USER_GROUP             VARCHAR(50) NULL,
           CHECK_RECORD           BIT NOT NULL,
           BASELINE_PERIODS       VARCHAR(500) NULL,
           SELECTED_PERIODS       VARCHAR(500) NULL,
           [USER_ID]              INT NOT NULL,
           SESSION_ID             INT NOT NULL,
           LAST_MODIFIED_DATE     DATETIME NOT NULL
        )
  END

GO

------------------------- column addition ----------------------------------
IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJ_MASTER'
                 AND COLUMN_NAME = 'BASELINE_PERIODS'
                 AND DATA_TYPE = 'VARCHAR'
                 AND CHARACTER_OCTET_LENGTH = 500)
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJ_MASTER
        ALTER COLUMN BASELINE_PERIODS VARCHAR(4000)
  END

GO

IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJ_MASTER'
                 AND COLUMN_NAME = 'SELECTED_PERIODS'
                 AND DATA_TYPE = 'VARCHAR'
                 AND CHARACTER_OCTET_LENGTH = 500)
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJ_MASTER
        ALTER COLUMN SELECTED_PERIODS VARCHAR(4000)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'CALCULATION_PERIODS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJ_MASTER
        ADD CALCULATION_PERIODS VARCHAR(1000)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'CALCULATION_BASED'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJ_MASTER
        ADD CALCULATION_BASED VARCHAR(100)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'FORECAST_START_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJ_MASTER
        ADD FORECAST_START_PERIOD_SID INT
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJ_MASTER'
                      AND COLUMN_NAME = 'FORECAST_END_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJ_MASTER
        ADD FORECAST_END_PERIOD_SID INT
  END

GO

------------------ PRIMARY KEY -----------------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_ST_NM_DISCOUNT_PROJ_MASTER_PROJECTION_DETAILS_SID_RS_MODEL_SID_USER_ID_SESSION_ID'
                     AND TABLE_NAME = 'ST_NM_DISCOUNT_PROJ_MASTER')
BEGIN
  ALTER TABLE ST_NM_DISCOUNT_PROJ_MASTER
    ADD CONSTRAINT PK_ST_NM_DISCOUNT_PROJ_MASTER_PROJECTION_DETAILS_SID_RS_MODEL_SID_USER_ID_SESSION_ID PRIMARY KEY(PROJECTION_DETAILS_SID, RS_MODEL_SID, [USER_ID], SESSION_ID)
END

GO

--Default Constraints
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_NM_DISCOUNT_PROJ_MASTER'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_NM_DISCOUNT_PROJ_MASTER_LAST_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJ_MASTER
        ADD CONSTRAINT DF_ST_NM_DISCOUNT_PROJ_MASTER_LAST_MODIFIED_DATE DEFAULT (Getdate()) FOR LAST_MODIFIED_DATE
  END

GO

------------------------------------------------------ NM_ACTUAL_DISCOUNT -------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[NM_ACTUAL_DISCOUNT]
        (
           PROJECTION_DETAILS_SID  INT NOT NULL,
           RS_MODEL_SID            INT NOT NULL,
           PERIOD_SID              INT NOT NULL,
           ACTUAL_SALES            NUMERIC(22, 6) NULL,
           ACTUAL_RATE             NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_SALES NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_RATE  NUMERIC(22, 6) NULL
        )
  END

GO

------------------ PRIMARY KEY DROP DUE TO RS_CONTRACT_SID COLUMN -----------------------------------------
--IF NOT EXISTS(SELECT 'X'
--              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
--              WHERE  CONSTRAINT_NAME = 'PK_NM_ACTUAL_DISCOUNT_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID'
--                     AND TABLE_NAME = 'NM_ACTUAL_DISCOUNT')
--BEGIN
--  ALTER TABLE NM_ACTUAL_DISCOUNT
--    ADD CONSTRAINT PK_NM_ACTUAL_DISCOUNT_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID PRIMARY KEY(PROJECTION_DETAILS_SID, RS_MODEL_SID, PERIOD_SID)
--END

--GO

IF EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_NM_ACTUAL_DISCOUNT_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID'
                     AND TABLE_NAME = 'NM_ACTUAL_DISCOUNT')
BEGIN
  ALTER TABLE NM_ACTUAL_DISCOUNT
    DROP CONSTRAINT PK_NM_ACTUAL_DISCOUNT_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID
END

GO

------------------------- column addition ----------------------------------
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                      AND COLUMN_NAME = 'ACTUAL_RPU'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_ACTUAL_DISCOUNT
        ADD ACTUAL_RPU NUMERIC(22, 6)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                      AND COLUMN_NAME = 'ACTUAL_PROJECTION_RPU'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_ACTUAL_DISCOUNT
        ADD ACTUAL_PROJECTION_RPU NUMERIC(22, 6)
  END
GO

----------------------------------------------------------- 1163

IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                 AND COLUMN_NAME = 'RS_CONTRACT_SID'
                 AND DATA_TYPE = 'INT')
  BEGIN
      ALTER TABLE NM_ACTUAL_DISCOUNT
        ADD RS_CONTRACT_SID INT
  END

GO

IF OBJECT_ID('TEMPDB..#TEMP_ACTUAL_DISCOUNT') IS NOT NULL 
BEGIN
  DROP TABLE #TEMP_ACTUAL_DISCOUNT 
END
GO

IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                 AND COLUMN_NAME = 'RS_CONTRACT_SID'
                 AND DATA_TYPE = 'INT')
  BEGIN

  SELECT A.*, 
       G.RS_MODEL_SID, 
       G.RS_CONTRACT_SID 
  INTO #TEMP_ACTUAL_DISCOUNT
  FROM   PROJECTION_DETAILS A 
       JOIN CCP_DETAILS B 
         ON B.CCP_DETAILS_SID = A.CCP_DETAILS_SID 
       JOIN CFP_CONTRACT C 
         ON C.CONTRACT_MASTER_SID = B.CONTRACT_MASTER_SID 
       JOIN CFP_CONTRACT_DETAILS D  
		ON D.CFP_CONTRACT_SID = C.CFP_CONTRACT_SID 
            AND D.COMPANY_MASTER_SID = B.COMPANY_MASTER_SID 
	   JOIN IFP_CONTRACT E 
         ON E.CONTRACT_MASTER_SID = B.CONTRACT_MASTER_SID 
            AND E.CFP_CONTRACT_SID = C.CFP_CONTRACT_SID 
       JOIN IFP_CONTRACT_DETAILS F 
         ON F.IFP_CONTRACT_SID = E.IFP_CONTRACT_SID 
            AND F.ITEM_MASTER_SID = B.ITEM_MASTER_SID 
	   JOIN RS_CONTRACT G 
         ON G.CONTRACT_MASTER_SID = B.CONTRACT_MASTER_SID 
            AND G.CFP_CONTRACT_SID = C.CFP_CONTRACT_SID 
            AND G.IFP_CONTRACT_SID = E.IFP_CONTRACT_SID 
	  JOIN RS_CONTRACT_DETAILS H 
         ON H.RS_CONTRACT_SID = G.RS_CONTRACT_SID 
            AND H.ITEM_MASTER_SID = B.ITEM_MASTER_SID 

  END

GO



 IF EXISTS (SELECT 1)
BEGIN

           
	UPDATE A
	SET A.RS_CONTRACT_SID=B.RS_CONTRACT_SID
	FROM NM_ACTUAL_DISCOUNT A
	JOIN #TEMP_ACTUAL_DISCOUNT B 
	  ON A.PROJECTION_DETAILS_SID=B.PROJECTION_DETAILS_SID
		AND A.RS_MODEL_SID=B.RS_MODEL_SID
	WHERE A.RS_CONTRACT_SID IS NULL

END
GO



IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                 AND COLUMN_NAME = 'RS_CONTRACT_SID'
                 AND DATA_TYPE = 'INT')
  BEGIN

      ALTER TABLE NM_ACTUAL_DISCOUNT
        ALTER COLUMN RS_CONTRACT_SID INT NOT NULL
  END

GO

-------------------------------- PRIMARY KEY ------------------------------------

--IF NOT EXISTS(SELECT 'X'
--              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
--              WHERE  CONSTRAINT_NAME = 'PK_NM_ACTUAL_DISCOUNT_PROJECTION_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID'
--                     AND TABLE_NAME = 'NM_ACTUAL_DISCOUNT')
--BEGIN
--  ALTER TABLE NM_ACTUAL_DISCOUNT
--    ADD CONSTRAINT PK_NM_ACTUAL_DISCOUNT_PROJECTION_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID PRIMARY KEY(PROJECTION_DETAILS_SID, RS_CONTRACT_SID, PERIOD_SID)
--END
--
--GO
--------------------drop  pk actuals------------------------ 
IF EXISTS (SELECT 1
           FROM   SYS.KEY_CONSTRAINTS
           WHERE  Object_name(PARENT_OBJECT_ID) = 'NM_ACTUAL_DISCOUNT'
                  AND Schema_name(SCHEMA_ID) = 'DBO'
                  AND NAME = 'PK_NM_ACTUAL_DISCOUNT_PROJECTION_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID'
                  AND TYPE = 'PK')
  BEGIN
      ALTER TABLE NM_ACTUAL_DISCOUNT
        DROP CONSTRAINT PK_NM_ACTUAL_DISCOUNT_PROJECTION_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID
  END

GO

------------------------------------------
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                      AND COLUMN_NAME = 'PROJECTION_MASTER_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_ACTUAL_DISCOUNT
        ADD PROJECTION_MASTER_SID INT NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                      AND COLUMN_NAME = 'CCP_DETAILS_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_ACTUAL_DISCOUNT
        ADD CCP_DETAILS_SID INT NULL
  END

GO

IF EXISTS(SELECT 1
          FROM   NM_ACTUAL_DISCOUNT
          WHERE  ( CCP_DETAILS_SID IS NULL
                    OR PROJECTION_MASTER_SID IS NULL ))
  BEGIN
      UPDATE TARGET
      SET    TARGET.PROJECTION_MASTER_SID = PD.PROJECTION_MASTER_SID,
             TARGET.CCP_DETAILS_SID = PD.CCP_DETAILS_SID
      FROM   NM_ACTUAL_DISCOUNT TARGET
             JOIN PROJECTION_DETAILS PD
               ON PD.PROJECTION_DETAILS_SID = TARGET.PROJECTION_DETAILS_SID
      WHERE  ( TARGET.CCP_DETAILS_SID IS NULL
                OR TARGET.PROJECTION_MASTER_SID IS NULL )
  END

GO

---------------------------
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                  AND COLUMN_NAME = 'PROJECTION_MASTER_SID'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_ACTUAL_DISCOUNT
        ALTER COLUMN PROJECTION_MASTER_SID INT NOT NULL
  END

GO

IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                  AND COLUMN_NAME = 'CCP_DETAILS_SID'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_ACTUAL_DISCOUNT
        ALTER COLUMN CCP_DETAILS_SID INT NOT NULL
  END

GO

------------------------CREATE PK-------------------------
IF NOT EXISTS (SELECT 1
               FROM   SYS.KEY_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'NM_ACTUAL_DISCOUNT'
                      AND Schema_name(SCHEMA_ID) = 'DBO'
                      AND NAME = 'PK_NM_ACTUAL_DISCOUNT_PROJECTION_MASTER_SID_CCP_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID'
                      AND TYPE = 'PK')
  BEGIN
      ALTER TABLE NM_ACTUAL_DISCOUNT
        ADD CONSTRAINT PK_NM_ACTUAL_DISCOUNT_PROJECTION_MASTER_SID_CCP_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID PRIMARY KEY ( PROJECTION_MASTER_SID, CCP_DETAILS_SID, RS_CONTRACT_SID, PERIOD_SID )
  END

GO
------------------------------------------------------- ST_NM_ACTUAL_DISCOUNT ----------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_NM_ACTUAL_DISCOUNT'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[ST_NM_ACTUAL_DISCOUNT]
        (
           PROJECTION_DETAILS_SID  INT NOT NULL,
           RS_MODEL_SID            INT NOT NULL,
           PERIOD_SID              INT NOT NULL,
           ACTUAL_SALES            NUMERIC(22, 6) NULL,
           ACTUAL_RATE             NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_SALES NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_RATE  NUMERIC(22, 6) NULL,
           [USER_ID]               INT NOT NULL,
           SESSION_ID              INT NOT NULL,
           LAST_MODIFIED_DATE      DATETIME NOT NULL
        )
  END

GO

------------------ PRIMARY KEY -----------------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_ST_NM_ACTUAL_DISCOUNT_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID_USER_ID_SESSION_ID'
                     AND TABLE_NAME = 'ST_NM_ACTUAL_DISCOUNT')
BEGIN
  ALTER TABLE ST_NM_ACTUAL_DISCOUNT
    ADD CONSTRAINT PK_ST_NM_ACTUAL_DISCOUNT_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID_USER_ID_SESSION_ID PRIMARY KEY(PROJECTION_DETAILS_SID, RS_MODEL_SID, PERIOD_SID, [USER_ID], SESSION_ID)
END

GO

--Default Constraints
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_NM_ACTUAL_DISCOUNT'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_NM_ACTUAL_DISCOUNT_LAST_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ST_NM_ACTUAL_DISCOUNT
        ADD CONSTRAINT DF_ST_NM_ACTUAL_DISCOUNT_LAST_MODIFIED_DATE DEFAULT (Getdate()) FOR LAST_MODIFIED_DATE
  END

GO

------------------------- column addition ----------------------------------
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_NM_ACTUAL_DISCOUNT'
                      AND COLUMN_NAME = 'ACTUAL_RPU'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_NM_ACTUAL_DISCOUNT
        ADD ACTUAL_RPU NUMERIC(22, 6)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_NM_ACTUAL_DISCOUNT'
                      AND COLUMN_NAME = 'ACTUAL_PROJECTION_RPU'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_NM_ACTUAL_DISCOUNT
        ADD ACTUAL_PROJECTION_RPU NUMERIC(22, 6)
  END

GO

------------------------------------------------------ NM_DISCOUNT_PROJECTION -------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[NM_DISCOUNT_PROJECTION]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           RS_MODEL_SID           INT NOT NULL,
           DISCOUNT_RATE          NUMERIC(22, 6) NULL,
           PERIOD_SID             INT NOT NULL,
           PROJECTION_SALES       NUMERIC(22, 6) NULL,
           PROJECTION_RATE        NUMERIC(22, 6) NULL,
           ADJUSTMENT_TYPE        VARCHAR(20) NULL,
           ADJUSTMENT_BASIS       VARCHAR(20) NULL,
           ADJUSTMENT_VALUE       NUMERIC(22, 6) NULL,
           ADJUSTMENT_METHODOLOGY VARCHAR(50) NULL
        )
  END

GO

------------------ PRIMARY KEY DROP SCRIPT DUE TO ADDITION OF RS_CONTRACT_SID-----------------------------------------
--IF NOT EXISTS(SELECT 'X'
--              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
--              WHERE  CONSTRAINT_NAME = 'PK_NM_DISCOUNT_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID'
--                     AND TABLE_NAME = 'NM_DISCOUNT_PROJECTION')
--BEGIN
--  ALTER TABLE NM_DISCOUNT_PROJECTION
--    ADD CONSTRAINT PK_NM_DISCOUNT_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID PRIMARY KEY(PROJECTION_DETAILS_SID, RS_MODEL_SID, PERIOD_SID)
--END

--GO

IF EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_NM_DISCOUNT_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID'
                     AND TABLE_NAME = 'NM_DISCOUNT_PROJECTION')
BEGIN
  ALTER TABLE NM_DISCOUNT_PROJECTION
    DROP CONSTRAINT PK_NM_DISCOUNT_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID 
END

GO

------------------ DEFAULT CONSTRAINT -----------------------------------------
/*IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'NM_DISCOUNT_PROJECTION'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_NM_DISCOUNT_PROJECTION_DISCOUNT_RATE')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ADD CONSTRAINT DF_NM_DISCOUNT_PROJECTION_DISCOUNT_RATE DEFAULT (0) FOR DISCOUNT_RATE
  END

GO
*/
------------------------- column addition ----------------------------------
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                      AND COLUMN_NAME = 'PROJECTION_RPU'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ADD PROJECTION_RPU NUMERIC(22, 6)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                      AND COLUMN_NAME = 'GROWTH'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ADD GROWTH NUMERIC(22, 6)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                      AND COLUMN_NAME = 'REFRESHED_NAME'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ADD REFRESHED_NAME VARCHAR(10)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                      AND COLUMN_NAME = 'REFRESHED_VALUE'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ADD REFRESHED_VALUE NUMERIC(22, 6)
  END

GO

----------------------------------------------------------------- 1163

IF NOT EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                 AND COLUMN_NAME = 'RS_CONTRACT_SID'
                 AND DATA_TYPE = 'INT')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ADD RS_CONTRACT_SID INT
  END

GO

IF OBJECT_ID('TEMPDB..#TEMP_DISCOUNT_PROJECTION') IS NOT NULL 
  DROP TABLE #TEMP_DISCOUNT_PROJECTION 

IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                 AND COLUMN_NAME = 'RS_CONTRACT_SID'
                 AND DATA_TYPE = 'INT')
  BEGIN

  SELECT A.*, 
       G.RS_MODEL_SID, 
       G.RS_CONTRACT_SID 
  INTO #TEMP_DISCOUNT_PROJECTION
  FROM   PROJECTION_DETAILS A 
       JOIN CCP_DETAILS B 
         ON B.CCP_DETAILS_SID = A.CCP_DETAILS_SID 
       JOIN CFP_CONTRACT C 
         ON C.CONTRACT_MASTER_SID = B.CONTRACT_MASTER_SID 
       JOIN CFP_CONTRACT_DETAILS D  
		ON D.CFP_CONTRACT_SID = C.CFP_CONTRACT_SID 
            AND D.COMPANY_MASTER_SID = B.COMPANY_MASTER_SID 
	   JOIN IFP_CONTRACT E 
         ON E.CONTRACT_MASTER_SID = B.CONTRACT_MASTER_SID 
            AND E.CFP_CONTRACT_SID = C.CFP_CONTRACT_SID 
       JOIN IFP_CONTRACT_DETAILS F 
         ON F.IFP_CONTRACT_SID = E.IFP_CONTRACT_SID 
            AND F.ITEM_MASTER_SID = B.ITEM_MASTER_SID 
	   JOIN RS_CONTRACT G 
         ON G.CONTRACT_MASTER_SID = B.CONTRACT_MASTER_SID 
            AND G.CFP_CONTRACT_SID = C.CFP_CONTRACT_SID 
            AND G.IFP_CONTRACT_SID = E.IFP_CONTRACT_SID 
	  JOIN RS_CONTRACT_DETAILS H 
         ON H.RS_CONTRACT_SID = G.RS_CONTRACT_SID 
            AND H.ITEM_MASTER_SID = B.ITEM_MASTER_SID 

  END

GO



 IF EXISTS (SELECT 1)
BEGIN

           
           
  UPDATE A
  SET A.RS_CONTRACT_SID=B.RS_CONTRACT_SID
  FROM NM_DISCOUNT_PROJECTION A
  JOIN #TEMP_DISCOUNT_PROJECTION B 
	ON A.PROJECTION_DETAILS_SID=B.PROJECTION_DETAILS_SID
	 AND A.RS_MODEL_SID=B.RS_MODEL_SID
  WHERE A.RS_CONTRACT_SID IS NULL

END
GO

IF EXISTS(SELECT 1
          FROM   INFORMATION_SCHEMA.COLUMNS
          WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                 AND COLUMN_NAME = 'RS_CONTRACT_SID'
                 AND DATA_TYPE = 'INT')
  BEGIN

      ALTER TABLE NM_DISCOUNT_PROJECTION
        ALTER COLUMN RS_CONTRACT_SID INT NOT NULL
  END

GO

----------------------------------------- PRIMARY KEY -----------------------------------------

--IF NOT EXISTS(SELECT 'X'
--              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
--              WHERE  CONSTRAINT_NAME = 'PK_NM_DISCOUNT_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID'
--                     AND TABLE_NAME = 'NM_DISCOUNT_PROJECTION')
--BEGIN
--  ALTER TABLE NM_DISCOUNT_PROJECTION
--    ADD CONSTRAINT PK_NM_DISCOUNT_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID PRIMARY KEY(PROJECTION_DETAILS_SID, RS_CONTRACT_SID, PERIOD_SID)
--END
--
--GO
IF EXISTS (SELECT 1
           FROM   SYS.KEY_CONSTRAINTS
           WHERE  Object_name(PARENT_OBJECT_ID) = 'NM_DISCOUNT_PROJECTION'
                  AND Schema_name(SCHEMA_ID) = 'DBO'
                  AND NAME = 'PK_NM_DISCOUNT_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID'
                  AND TYPE = 'PK')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        DROP CONSTRAINT PK_NM_DISCOUNT_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID
  END

GO

-----------ADDING NEW COLUMNS
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                      AND COLUMN_NAME = 'PROJECTION_MASTER_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ADD PROJECTION_MASTER_SID INT
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                      AND COLUMN_NAME = 'CCP_DETAILS_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ADD CCP_DETAILS_SID INT
  END

GO

----------------------------
IF EXISTS(SELECT 1
          FROM   NM_DISCOUNT_PROJECTION
          WHERE  ( CCP_DETAILS_SID IS NULL
                    OR PROJECTION_MASTER_SID IS NULL ))
  BEGIN
      UPDATE TARGET
      SET    TARGET.PROJECTION_MASTER_SID = PD.PROJECTION_MASTER_SID,
             TARGET.CCP_DETAILS_SID = PD.CCP_DETAILS_SID
      FROM   NM_DISCOUNT_PROJECTION TARGET
             JOIN PROJECTION_DETAILS PD
               ON PD.PROJECTION_DETAILS_SID = TARGET.PROJECTION_DETAILS_SID
      WHERE  ( TARGET.CCP_DETAILS_SID IS NULL
                OR TARGET.PROJECTION_MASTER_SID IS NULL )
  END

GO

----ALTERING COLUMNS TO NOT NULL
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                  AND COLUMN_NAME = 'PROJECTION_MASTER_SID'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ALTER COLUMN PROJECTION_MASTER_SID INT NOT NULL
  END

GO

IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                  AND COLUMN_NAME = 'CCP_DETAILS_SID'
                  AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ALTER COLUMN CCP_DETAILS_SID INT NOT NULL
  END

GO

----------CREATING  NEW PK--------------------
IF NOT EXISTS (SELECT 1
               FROM   SYS.KEY_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'NM_DISCOUNT_PROJECTION'
                      AND Schema_name(SCHEMA_ID) = 'DBO'
                      AND NAME = 'PK_NM_DISCOUNT_PROJECTION_PROJECTION_MASTER_SID_CCP_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID'
                      AND TYPE = 'PK')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        ADD CONSTRAINT PK_NM_DISCOUNT_PROJECTION_PROJECTION_MASTER_SID_CCP_DETAILS_SID_PERIOD_SID_RS_CONTRACT_SID PRIMARY KEY ( PROJECTION_MASTER_SID, CCP_DETAILS_SID, RS_CONTRACT_SID, PERIOD_SID )
  END

GO


------------------------------------------------------ ST_NM_DISCOUNT_PROJECTION ----------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJECTION'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[ST_NM_DISCOUNT_PROJECTION]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           RS_MODEL_SID           INT NOT NULL,
           DISCOUNT_RATE          NUMERIC(22, 6) NULL,
           PERIOD_SID             INT NOT NULL,
           PROJECTION_SALES       NUMERIC(22, 6) NULL,
           PROJECTION_RATE        NUMERIC(22, 6) NULL,
           ADJUSTMENT_TYPE        VARCHAR(20) NULL,
           ADJUSTMENT_BASIS       VARCHAR(20) NULL,
           ADJUSTMENT_VALUE       NUMERIC(22, 6) NULL,
           ADJUSTMENT_METHODOLOGY VARCHAR(50) NULL,
           [USER_ID]              INT NOT NULL,
           SESSION_ID             INT NOT NULL,
           LAST_MODIFIED_DATE     DATETIME NOT NULL
        )
  END

GO

------------------ PRIMARY KEY -----------------------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_ST_NM_DISCOUNT_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID_USER_ID_SESSION_ID'
                     AND TABLE_NAME = 'ST_NM_DISCOUNT_PROJECTION')
BEGIN
  ALTER TABLE ST_NM_DISCOUNT_PROJECTION
    ADD CONSTRAINT PK_ST_NM_DISCOUNT_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_RS_MODEL_SID_USER_ID_SESSION_ID PRIMARY KEY(PROJECTION_DETAILS_SID, RS_MODEL_SID, PERIOD_SID, [USER_ID], SESSION_ID)
END

GO

------------------ DEFAULT CONSTRAINT -----------------------------------------
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_NM_DISCOUNT_PROJECTION'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_NM_DISCOUNT_PROJECTION_DISCOUNT_RATE')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJECTION
        ADD CONSTRAINT DF_ST_NM_DISCOUNT_PROJECTION_DISCOUNT_RATE DEFAULT (0) FOR DISCOUNT_RATE
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_NM_DISCOUNT_PROJECTION'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_NM_DISCOUNT_PROJECTION_LAST_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJECTION
        ADD CONSTRAINT DF_ST_NM_DISCOUNT_PROJECTION_LAST_MODIFIED_DATE DEFAULT (Getdate()) FOR LAST_MODIFIED_DATE
  END

GO

------------------------- column addition ----------------------------------
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJECTION'
                      AND COLUMN_NAME = 'PROJECTION_RPU'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJECTION
        ADD PROJECTION_RPU NUMERIC(22, 6)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJECTION'
                      AND COLUMN_NAME = 'GROWTH'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJECTION
        ADD GROWTH NUMERIC(22, 6)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJECTION'
                      AND COLUMN_NAME = 'REFRESHED_NAME'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJECTION
        ADD REFRESHED_NAME VARCHAR(10)
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_NM_DISCOUNT_PROJECTION'
                      AND COLUMN_NAME = 'REFRESHED_VALUE'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_NM_DISCOUNT_PROJECTION
        ADD REFRESHED_VALUE NUMERIC(22, 6)
  END

GO 

-------------------------------------------DISCOUNT ALTERNATE HISTORY TABLE SCRIPT START HERE---------------------------------------------------------------------------------



-------------------------------------------ST_DISC_CCP_ACTUAL_DETAILS---------------------------------------------------------------------------------

IF NOT EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'ST_DISC_CCP_ACTUAL_DETAILS'
                  AND TABLE_SCHEMA = 'DBO')

BEGIN

CREATE TABLE [DBO].[ST_DISC_CCP_ACTUAL_DETAILS](
	[CCP_DETAILS_SID] [INT] NOT NULL,
	[PERIOD_SID] [INT] NOT NULL,
	[ACTUAL_AMOUNT] [NUMERIC](22, 6) NULL,
	[PROJECTION_AMOUNT] [NUMERIC](22, 6) NULL,
	[USER_ID] [INT] NOT NULL,
	[SESSION_ID] [VARCHAR](100) NOT NULL
)

END

GO
---------------------PRIMARY KEY CONSTRAINT------------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_ST_DISC_CCP_ACTUAL_DETAILS_CCP_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID'
                     AND TABLE_NAME = 'ST_DISC_CCP_ACTUAL_DETAILS')
  BEGIN
      ALTER TABLE [DBO].[ST_DISC_CCP_ACTUAL_DETAILS]
        ADD CONSTRAINT PK_ST_DISC_CCP_ACTUAL_DETAILS_CCP_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID PRIMARY KEY(CCP_DETAILS_SID, PERIOD_SID, USER_ID, SESSION_ID)
  END

GO


-------------------------------------------ST_DISC_CCP_ACTUAL_DETAILS END---------------------------------------------------------------------------------


-------------------------------------------ST_DISC_ALTERNATE_HIST_ALLOCATION START---------------------------------------------------------------------------------

IF NOT EXISTS (SELECT 1
           FROM   information_schema.columns
           WHERE  table_name = 'ST_DISC_ALTERNATE_HIST_ALLOCATION'
                  AND table_schema = 'DBO')

BEGIN

CREATE TABLE [DBO].[ST_DISC_ALTERNATE_HIST_ALLOCATION](
	[PROJECTION_DETAILS_SID] [INT] NOT NULL,
	[RS_MODEL_SID] [INT] NOT NULL,
	[PERIOD_SID] [INT] NOT NULL,
	[ACTUAL_AMOUNT] [NUMERIC](22, 6) NULL,
	[PROJECTION_AMOUNT] [NUMERIC](22, 6) NULL,
	[ACTUAL_ALLOCATION_PERCENT] [NUMERIC](22, 6) NULL,
	[PROJECTION_ALLOCATION_PERCENT] [NUMERIC](22, 6) NULL,
	[TOTAL_ACTUAL_AMOUNT] [NUMERIC](22, 6) NULL,
	[TOTAL_PROJECTION_AMOUNT] [NUMERIC](22, 6) NULL,
	[CHECK_RECORD] [BIT] NULL,
	[FLAG] [CHAR](1) NULL,
	[USER_ID] [INT] NOT NULL,
	[SESSION_ID] [VARCHAR](100) NOT NULL
) 
END

GO
---------------------PRIMARY KEY CONSTRAINT------------------------
IF NOT EXISTS (SELECT 1
               FROM   SYS.KEY_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_DISC_ALTERNATE_HIST_ALLOCATION'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'ST_DISC_ALTERNATE_HIST_ALLOCATION_PROJECTION_DETAILS_SID_RS_MODEL_SID_PERIOD_SID_USER_ID_SESSION_ID'
                      AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [dbo].ST_DISC_ALTERNATE_HIST_ALLOCATION
        ADD CONSTRAINT ST_DISC_ALTERNATE_HIST_ALLOCATION_PROJECTION_DETAILS_SID_RS_MODEL_SID_PERIOD_SID_USER_ID_SESSION_ID PRIMARY KEY ( PROJECTION_DETAILS_SID, RS_MODEL_SID, PERIOD_SID, USER_ID, SESSION_ID )
  END

GO

----------------------------------------------------------------ST_DISC_ALTERNATE_HIST_ALLOCATION END-------------------------------------------------------------------


----------------------------------------------------------------------------DISCOUNT ALTERNATE HISTORY TABLE SCRIPT END HERE-------------------------------------------




IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'DISC_ALTERNATE_HIST_ALLOCATION'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [dbo].[DISC_ALTERNATE_HIST_ALLOCATION]
        (
           [PROJECTION_DETAILS_SID]        [INT] NOT NULL,
           [RS_MODEL_SID]                  [INT] NOT NULL,
           [PERIOD_SID]                    [INT] NOT NULL,
           [ACTUAL_AMOUNT]                 [NUMERIC](22, 6) NULL,
           [PROJECTION_AMOUNT]             [NUMERIC](22, 6) NULL,
           [ACTUAL_ALLOCATION_PERCENT]     [NUMERIC](22, 6) NULL,
           [PROJECTION_ALLOCATION_PERCENT] [NUMERIC](22, 6) NULL,
           [TOTAL_ACTUAL_AMOUNT]           [NUMERIC](22, 6) NULL,
           [TOTAL_PROJECTION_AMOUNT]       [NUMERIC](22, 6) NULL,
           [CHECK_RECORD]                  [BIT] NULL,
           [FLAG]                          [CHAR](1) NULL,
           [AVAILABLE_CHECKBOX]            [BIT] NULL,
           [SELECTED_CHECKBOX]             [BIT] NULL
        )
  END
GO

---------------------PRIMARY KEY CONSTRAINT------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'DISC_ALTERNATE_HIST_ALLOCATION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_DISC_ALTERNATE_HIST_ALLOCATION_PROJECTION_DETAILS_SID_RS_MODEL_SID_PERIOD_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].[DISC_ALTERNATE_HIST_ALLOCATION]
        ADD CONSTRAINT [PK_DISC_ALTERNATE_HIST_ALLOCATION_PROJECTION_DETAILS_SID_RS_MODEL_SID_PERIOD_SID] PRIMARY KEY CLUSTERED ( [PROJECTION_DETAILS_SID] ASC, [RS_MODEL_SID] ASC, [PERIOD_SID] ASC )
  END

GO





IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'DISC_CCP_ACTUAL_DETAILS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [dbo].[DISC_CCP_ACTUAL_DETAILS]
        (
           [CCP_DETAILS_SID]   [INT] NOT NULL,
           [PERIOD_SID]        [INT] NOT NULL,
           [ACTUAL_AMOUNT]     [NUMERIC](22, 6) NULL,
           [PROJECTION_AMOUNT] [NUMERIC](22, 6) NULL
        )
  END
GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'DISC_CCP_ACTUAL_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_DISC_CCP_ACTUAL_DETAILS_CCP_DETAILS_SID_PERIOD_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [DBO].DISC_CCP_ACTUAL_DETAILS
        ADD CONSTRAINT [PK_DISC_CCP_ACTUAL_DETAILS_CCP_DETAILS_SID_PERIOD_SID] PRIMARY KEY CLUSTERED ( [CCP_DETAILS_SID] ASC, [PERIOD_SID] ASC )
  END

GO



IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  COLUMN_NAME = 'BASELINE_PERIODS'
                  AND TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        DROP COLUMN BASELINE_PERIODS
  END
  GO

IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  COLUMN_NAME = 'SELECTED_PERIODS'
                  AND TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        DROP COLUMN SELECTED_PERIODS
  END 
  GO




IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  COLUMN_NAME = 'FORECAST_START_PERIOD_SID'
                  AND TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER')
BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        DROP COLUMN FORECAST_START_PERIOD_SID

END 
GO

IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  COLUMN_NAME = 'FORECAST_END_PERIOD_SID'
                  AND TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER')
BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        DROP COLUMN FORECAST_END_PERIOD_SID

END 
GO



IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  COLUMN_NAME = 'CALCULATION_BASED'
                  AND TABLE_NAME = 'NM_DISCOUNT_PROJ_MASTER')
BEGIN
      ALTER TABLE NM_DISCOUNT_PROJ_MASTER
        DROP COLUMN CALCULATION_BASED
END 
GO





------------------------------------ACTUAL DISCOUNT--------------------  

IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  COLUMN_NAME = 'ACTUAL_PROJECTION_SALES'
                  AND TABLE_NAME = 'NM_ACTUAL_DISCOUNT')
  BEGIN
      ALTER TABLE NM_ACTUAL_DISCOUNT
        DROP COLUMN ACTUAL_PROJECTION_SALES
  END
  GO


IF EXISTS (SELECT 1
         FROM   INFORMATION_SCHEMA.COLUMNS
         WHERE  COLUMN_NAME = 'ACTUAL_PROJECTION_RATE'
                AND TABLE_NAME = 'NM_ACTUAL_DISCOUNT')
BEGIN
    ALTER TABLE NM_ACTUAL_DISCOUNT
      DROP COLUMN ACTUAL_PROJECTION_RATE
END
GO


IF EXISTS (SELECT 1
         FROM   INFORMATION_SCHEMA.COLUMNS
         WHERE  COLUMN_NAME = 'ACTUAL_PROJECTION_RPU'
                AND TABLE_NAME = 'NM_ACTUAL_DISCOUNT')
BEGIN
    ALTER TABLE NM_ACTUAL_DISCOUNT
      DROP COLUMN ACTUAL_PROJECTION_RPU
END
GO


------------------------------------NM_DISCOUNT_PROJECTION REMOVAL

IF EXISTS (SELECT 1
           FROM   SYS.DEFAULT_CONSTRAINTS
           WHERE  NAME = 'DF_NM_DISCOUNT_PROJECTION_DISCOUNT_RATE')
  BEGIN
      ALTER TABLE NM_DISCOUNT_PROJECTION
        DROP CONSTRAINT DF_NM_DISCOUNT_PROJECTION_DISCOUNT_RATE
  END 
GO


IF EXISTS (SELECT 1
         FROM   INFORMATION_SCHEMA.COLUMNS
         WHERE  COLUMN_NAME = 'DISCOUNT_RATE'
                AND TABLE_NAME = 'NM_DISCOUNT_PROJECTION')
BEGIN
    ALTER TABLE NM_DISCOUNT_PROJECTION
      DROP COLUMN DISCOUNT_RATE
END
GO
IF EXISTS (SELECT 1
         FROM   INFORMATION_SCHEMA.COLUMNS
         WHERE  COLUMN_NAME = 'ADJUSTMENT_TYPE'
                AND TABLE_NAME = 'NM_DISCOUNT_PROJECTION')
BEGIN
    ALTER TABLE NM_DISCOUNT_PROJECTION
      DROP COLUMN ADJUSTMENT_TYPE
END
GO
IF EXISTS (SELECT 1
         FROM   INFORMATION_SCHEMA.COLUMNS
         WHERE  COLUMN_NAME = 'ADJUSTMENT_BASIS'
                AND TABLE_NAME = 'NM_DISCOUNT_PROJECTION')
BEGIN
    ALTER TABLE NM_DISCOUNT_PROJECTION
      DROP COLUMN ADJUSTMENT_BASIS
END

GO
IF EXISTS (SELECT 1
         FROM   INFORMATION_SCHEMA.COLUMNS
         WHERE  COLUMN_NAME = 'ADJUSTMENT_VALUE'
                AND TABLE_NAME = 'NM_DISCOUNT_PROJECTION')
BEGIN
    ALTER TABLE NM_DISCOUNT_PROJECTION
      DROP COLUMN ADJUSTMENT_VALUE
END
GO

IF EXISTS (SELECT 1
         FROM   INFORMATION_SCHEMA.COLUMNS
         WHERE  COLUMN_NAME = 'ADJUSTMENT_METHODOLOGY'
                AND TABLE_NAME = 'NM_DISCOUNT_PROJECTION')
BEGIN
    ALTER TABLE NM_DISCOUNT_PROJECTION
      DROP COLUMN ADJUSTMENT_METHODOLOGY
END

GO




--------------------------------
SET NUMERIC_ROUNDABORT OFF;
INSERT INTO NM_PROJECTION_SELECTION (
       PROJECTION_MASTER_SID
       ,SCREEN_NAME
       ,FIELD_NAME
       ,FIELD_VALUES
       )
SELECT DISTINCT pd.PROJECTION_MASTER_SID
       , 'Discount Projection'
       , 'DeductionLevelValue' FIELD_NAME
       ,STUFF((
                                  SELECT DISTINCT ', ' + CONVERT(VARCHAR(max), RS_CATEGORY)
                                  FROM RS_CONTRACT RC
                                  WHERE RC.RS_CONTRACT_SID = NDP.RS_CONTRACT_SID
                                  FOR XML PATH('')
                                         ,TYPE
                                  ).value('.', 'NVARCHAR(MAX)'), 1, 2, '')
              FIELD_VALUES
FROM PROJECTION_DETAILS PD
JOIN NM_DISCOUNT_PROJ_MASTER NDP ON NDP.PROJECTION_DETAILS_SID = PD.PROJECTION_DETAILS_SID
WHERE not EXISTS(SELECT 1 FROM  NM_PROJECTION_SELECTION NPS
              WHERE  NPS.PROJECTION_MASTER_SID = PD.PROJECTION_MASTER_SID
                     AND NPS.SCREEN_NAME = 'DISCOUNT PROJECTION'
                     AND NPS.FIELD_NAME = 'DEDUCTIONLEVELVALUE')
					 

GO
              

INSERT INTO NM_PROJECTION_SELECTION (
       PROJECTION_MASTER_SID
       ,SCREEN_NAME
       ,FIELD_NAME
       ,FIELD_VALUES
       )
SELECT DISTINCT pd.PROJECTION_MASTER_SID
       , 'Discount Projection'
       , 'DeductionLevel' FIELD_NAME
       ,1 as FIELD_VALUES
FROM PROJECTION_DETAILS PD
JOIN NM_DISCOUNT_PROJ_MASTER NDP ON NDP.PROJECTION_DETAILS_SID = PD.PROJECTION_DETAILS_SID
WHERE not EXISTS(SELECT 1 FROM  NM_PROJECTION_SELECTION NPS
              WHERE  NPS.PROJECTION_MASTER_SID = PD.PROJECTION_MASTER_SID
                     AND NPS.SCREEN_NAME = 'DISCOUNT PROJECTION'
                     AND NPS.FIELD_NAME = 'DeductionLevel' )

GO
SET NUMERIC_ROUNDABORT ON;
----------------------------------------------------------
-------------------------------Rate and Rpu Changes
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                  AND COLUMN_NAME = 'PROJECTION_RATE')
  BEGIN
 ALTER TABLE NM_DISCOUNT_PROJECTION DROP COLUMN PROJECTION_RATE
  END

GO

IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'NM_DISCOUNT_PROJECTION'
                  AND COLUMN_NAME = 'PROJECTION_RPU')
  BEGIN
 ALTER TABLE NM_DISCOUNT_PROJECTION DROP COLUMN PROJECTION_RPU
  END

GO


IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                  AND COLUMN_NAME = 'ACTUAL_RATE')
  BEGIN
 ALTER TABLE NM_ACTUAL_DISCOUNT DROP COLUMN ACTUAL_RATE
  END

GO
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'NM_ACTUAL_DISCOUNT'
                  AND COLUMN_NAME = 'ACTUAL_RPU')
  BEGIN
 ALTER TABLE NM_ACTUAL_DISCOUNT DROP COLUMN ACTUAL_RPU
  END

GO
-----------------------pv table_name
  IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME ='CCP_PV_FILTERS'
                      AND TABLE_SCHEMA = 'DBO')
					  BEGIN
			  CREATE TABLE CCP_PV_FILTERS
                   (
				   CCP_DETAILS_SID     INT,
				   RS_CONTRACT_SID     INT,
				   PV_FILTERS		   BIT

				   )
       END
          GO