package com.stpl.app.model.impl;

import com.stpl.app.model.ChActualSales;
import com.stpl.app.service.ChActualSalesLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ChActualSales service. Represents a row in the &quot;CH_ACTUAL_SALES&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChActualSalesImpl}.
 * </p>
 *
 * @author
 * @see ChActualSalesImpl
 * @see com.stpl.app.model.ChActualSales
 * @generated
 */
public abstract class ChActualSalesBaseImpl extends ChActualSalesModelImpl
    implements ChActualSales {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a ch actual sales model instance should use the {@link ChActualSales} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ChActualSalesLocalServiceUtil.addChActualSales(this);
        } else {
            ChActualSalesLocalServiceUtil.updateChActualSales(this);
        }
    }
}
