package com.stpl.app.model.impl;

import com.stpl.app.model.CompanyQualifier;
import com.stpl.app.service.CompanyQualifierLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the CompanyQualifier service. Represents a row in the &quot;COMPANY_QUALIFIER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CompanyQualifierImpl}.
 * </p>
 *
 * @author
 * @see CompanyQualifierImpl
 * @see com.stpl.app.model.CompanyQualifier
 * @generated
 */
public abstract class CompanyQualifierBaseImpl extends CompanyQualifierModelImpl
    implements CompanyQualifier {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a company qualifier model instance should use the {@link CompanyQualifier} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CompanyQualifierLocalServiceUtil.addCompanyQualifier(this);
        } else {
            CompanyQualifierLocalServiceUtil.updateCompanyQualifier(this);
        }
    }
}
