package com.stpl.app.model.impl;

import com.stpl.app.model.CompanyGroup;
import com.stpl.app.service.CompanyGroupLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the CompanyGroup service. Represents a row in the &quot;COMPANY_GROUP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CompanyGroupImpl}.
 * </p>
 *
 * @author
 * @see CompanyGroupImpl
 * @see com.stpl.app.model.CompanyGroup
 * @generated
 */
public abstract class CompanyGroupBaseImpl extends CompanyGroupModelImpl
    implements CompanyGroup {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a company group model instance should use the {@link CompanyGroup} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CompanyGroupLocalServiceUtil.addCompanyGroup(this);
        } else {
            CompanyGroupLocalServiceUtil.updateCompanyGroup(this);
        }
    }
}
