package com.stpl.app.model.impl;

import com.stpl.app.model.FcpActuals;
import com.stpl.app.service.FcpActualsLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the FcpActuals service. Represents a row in the &quot;FCP_ACTUALS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FcpActualsImpl}.
 * </p>
 *
 * @author
 * @see FcpActualsImpl
 * @see com.stpl.app.model.FcpActuals
 * @generated
 */
public abstract class FcpActualsBaseImpl extends FcpActualsModelImpl
    implements FcpActuals {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a fcp actuals model instance should use the {@link FcpActuals} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            FcpActualsLocalServiceUtil.addFcpActuals(this);
        } else {
            FcpActualsLocalServiceUtil.updateFcpActuals(this);
        }
    }
}
