package com.stpl.app.model.impl;

import com.stpl.app.model.ForecastingViewMaster;
import com.stpl.app.service.ForecastingViewMasterLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ForecastingViewMaster service. Represents a row in the &quot;FORECASTING_VIEW_MASTER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ForecastingViewMasterImpl}.
 * </p>
 *
 * @author
 * @see ForecastingViewMasterImpl
 * @see com.stpl.app.model.ForecastingViewMaster
 * @generated
 */
public abstract class ForecastingViewMasterBaseImpl
    extends ForecastingViewMasterModelImpl implements ForecastingViewMaster {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a forecasting view master model instance should use the {@link ForecastingViewMaster} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ForecastingViewMasterLocalServiceUtil.addForecastingViewMaster(this);
        } else {
            ForecastingViewMasterLocalServiceUtil.updateForecastingViewMaster(this);
        }
    }
}
