package com.stpl.app.model.impl;

import com.stpl.app.model.SalesBasisDetails;
import com.stpl.app.service.SalesBasisDetailsLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the SalesBasisDetails service. Represents a row in the &quot;SALES_BASIS_DETAILS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SalesBasisDetailsImpl}.
 * </p>
 *
 * @author
 * @see SalesBasisDetailsImpl
 * @see com.stpl.app.model.SalesBasisDetails
 * @generated
 */
public abstract class SalesBasisDetailsBaseImpl
    extends SalesBasisDetailsModelImpl implements SalesBasisDetails {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a sales basis details model instance should use the {@link SalesBasisDetails} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SalesBasisDetailsLocalServiceUtil.addSalesBasisDetails(this);
        } else {
            SalesBasisDetailsLocalServiceUtil.updateSalesBasisDetails(this);
        }
    }
}
