select
	LEVEL_NO,
	LEVEl_NAME
from
	HIERARCHY_DEFINITION HD
join HIERARCHY_LEVEL_DEFINITION HLD on
	HD.HIERARCHY_DEFINITION_SID = HLD.HIERARCHY_DEFINITION_SID
where
	HD.HIERARCHY_DEFINITION_SID = 1
	and LEVEL_NO >= 3
	
	select * from HIERARCHY_DEFINITION
	select
	TOP 1 HIERARCHY_DEFINITION_SID
from
	dbo.HIERARCHY_DEFINITION HD
join dbo.HELPER_TABLE HT on
	HT.HELPER_TABLE_SID = HD.HIERARCHY_CATEGORY
	where HT.DESCRIPTION like '%product%'
	ORDER BY NEWID()
	
	
	select * from dbo.ErrorInfo