package com.stpl.gtn.gtn2o.ws.module.rebateschedule.constants;

public class GtnWsRsQueryConstants {

	private GtnWsRsQueryConstants() {

	}

	public static final String GTN_RS_COUNT_QUERY = "   from dbo.RS_MODEL RSM "
			+ "LEFT JOIN dbo.HELPER_TABLE RS_TYPE ON  RSM.RS_TYPE=RS_TYPE.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE RS_STATUS ON  RSM.RS_STATUS=RS_STATUS.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE REBATE_PROGRAM_TYPE ON  RSM.REBATE_PROGRAM_TYPE=REBATE_PROGRAM_TYPE.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE RS_CATEGORY ON  RSM.RS_CATEGORY=RS_CATEGORY.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE RS_TRADE_CLASS ON  RSM.RS_TRADE_CLASS=RS_TRADE_CLASS.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE REBATE_FREQUENCY ON  RSM.REBATE_FREQUENCY=REBATE_FREQUENCY.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE RS_CALENDAR ON  RSM.RS_CALENDAR=RS_CALENDAR.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE CALCULATION_TYPE ON  RSM.CALCULATION_TYPE=CALCULATION_TYPE.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE CALCULATION_LEVEL ON  RSM.CALCULATION_LEVEL=CALCULATION_LEVEL.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE REBATE_RULE_TYPE ON  RSM.REBATE_RULE_TYPE=REBATE_RULE_TYPE.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE REBATE_RULE_ASSOCIATION ON  RSM.REBATE_RULE_ASSOCIATION=REBATE_RULE_ASSOCIATION.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE PAYMENT_LEVEL ON  RSM.PAYMENT_LEVEL=PAYMENT_LEVEL.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE INTEREST_BEARING_INDICATOR ON  RSM.INTEREST_BEARING_INDICATOR=INTEREST_BEARING_INDICATOR.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE INTEREST_BEARING_BASIS ON  RSM.INTEREST_BEARING_BASIS=INTEREST_BEARING_BASIS.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE RS_DESIGNATION ON  RSM.RS_DESIGNATION=RS_DESIGNATION.HELPER_TABLE_SID "
			+ "LEFT JOIN dbo.UDCS  UDCS ON UDCS.MASTER_SID=RSM.RS_MODEL_SID AND UDCS.MASTER_TYPE='RS_MODEL' ";

	public static final String GTN_RS_SEARCH_QUERY = "  from dbo.RS_MODEL RSM "
			+ "LEFT JOIN dbo.HELPER_TABLE RS_TYPE ON  RSM.RS_TYPE=RS_TYPE.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE RS_STATUS ON  RSM.RS_STATUS=RS_STATUS.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE REBATE_PROGRAM_TYPE ON  RSM.REBATE_PROGRAM_TYPE=REBATE_PROGRAM_TYPE.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE RS_CATEGORY ON  RSM.RS_CATEGORY=RS_CATEGORY.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE RS_TRADE_CLASS ON  RSM.RS_TRADE_CLASS=RS_TRADE_CLASS.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE REBATE_FREQUENCY ON  RSM.REBATE_FREQUENCY=REBATE_FREQUENCY.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE RS_CALENDAR ON  RSM.RS_CALENDAR=RS_CALENDAR.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE CALCULATION_TYPE ON  RSM.CALCULATION_TYPE=CALCULATION_TYPE.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE CALCULATION_LEVEL ON  RSM.CALCULATION_LEVEL=CALCULATION_LEVEL.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE REBATE_RULE_TYPE ON  RSM.REBATE_RULE_TYPE=REBATE_RULE_TYPE.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE REBATE_RULE_ASSOCIATION ON  RSM.REBATE_RULE_ASSOCIATION=REBATE_RULE_ASSOCIATION.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE PAYMENT_LEVEL ON  RSM.PAYMENT_LEVEL=PAYMENT_LEVEL.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE INTEREST_BEARING_INDICATOR ON  RSM.INTEREST_BEARING_INDICATOR=INTEREST_BEARING_INDICATOR.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE INTEREST_BEARING_BASIS ON  RSM.INTEREST_BEARING_BASIS=INTEREST_BEARING_BASIS.HELPER_TABLE_SID\n"
			+ "LEFT JOIN dbo.HELPER_TABLE RS_DESIGNATION ON  RSM.RS_DESIGNATION=RS_DESIGNATION.HELPER_TABLE_SID "
			+ "LEFT JOIN dbo.UDCS  UDCS ON UDCS.MASTER_SID=RSM.RS_MODEL_SID AND UDCS.MASTER_TYPE='RS_MODEL' ";

	public static final String GTN_RS_DEFAULT_WHERE_CLAUSE = " RSM.INBOUND_STATUS <> 'D' ";

}
