package com.stpl.app.model;

import com.stpl.portal.kernel.bean.AutoEscape;
import com.stpl.portal.model.BaseModel;
import com.stpl.portal.model.CacheModel;
import com.stpl.portal.service.ServiceContext;

import com.stpl.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CdrModel service. Represents a row in the &quot;CDR_MODEL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stpl.app.model.impl.CdrModelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stpl.app.model.impl.CdrModelImpl}.
 * </p>
 *
 * @author
 * @see CdrModel
 * @see com.stpl.app.model.impl.CdrModelImpl
 * @see com.stpl.app.model.impl.CdrModelModelImpl
 * @generated
 */
public interface CdrModelModel extends BaseModel<CdrModel> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a cdr model model instance should use the {@link CdrModel} interface instead.
     */

    /**
     * Returns the primary key of this cdr model.
     *
     * @return the primary key of this cdr model
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this cdr model.
     *
     * @param primaryKey the primary key of this cdr model
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the created by of this cdr model.
     *
     * @return the created by of this cdr model
     */
    public int getCreatedBy();

    /**
     * Sets the created by of this cdr model.
     *
     * @param createdBy the created by of this cdr model
     */
    public void setCreatedBy(int createdBy);

    /**
     * Returns the rule category of this cdr model.
     *
     * @return the rule category of this cdr model
     */
    public int getRuleCategory();

    /**
     * Sets the rule category of this cdr model.
     *
     * @param ruleCategory the rule category of this cdr model
     */
    public void setRuleCategory(int ruleCategory);

    /**
     * Returns the rule type of this cdr model.
     *
     * @return the rule type of this cdr model
     */
    public int getRuleType();

    /**
     * Sets the rule type of this cdr model.
     *
     * @param ruleType the rule type of this cdr model
     */
    public void setRuleType(int ruleType);

    /**
     * Returns the modified by of this cdr model.
     *
     * @return the modified by of this cdr model
     */
    public int getModifiedBy();

    /**
     * Sets the modified by of this cdr model.
     *
     * @param modifiedBy the modified by of this cdr model
     */
    public void setModifiedBy(int modifiedBy);

    /**
     * Returns the internal notes of this cdr model.
     *
     * @return the internal notes of this cdr model
     */
    @AutoEscape
    public String getInternalNotes();

    /**
     * Sets the internal notes of this cdr model.
     *
     * @param internalNotes the internal notes of this cdr model
     */
    public void setInternalNotes(String internalNotes);

    /**
     * Returns the created date of this cdr model.
     *
     * @return the created date of this cdr model
     */
    public Date getCreatedDate();

    /**
     * Sets the created date of this cdr model.
     *
     * @param createdDate the created date of this cdr model
     */
    public void setCreatedDate(Date createdDate);

    /**
     * Returns the rule name of this cdr model.
     *
     * @return the rule name of this cdr model
     */
    @AutoEscape
    public String getRuleName();

    /**
     * Sets the rule name of this cdr model.
     *
     * @param ruleName the rule name of this cdr model
     */
    public void setRuleName(String ruleName);

    /**
     * Returns the cdr model sid of this cdr model.
     *
     * @return the cdr model sid of this cdr model
     */
    public int getCdrModelSid();

    /**
     * Sets the cdr model sid of this cdr model.
     *
     * @param cdrModelSid the cdr model sid of this cdr model
     */
    public void setCdrModelSid(int cdrModelSid);

    /**
     * Returns the rule no of this cdr model.
     *
     * @return the rule no of this cdr model
     */
    @AutoEscape
    public String getRuleNo();

    /**
     * Sets the rule no of this cdr model.
     *
     * @param ruleNo the rule no of this cdr model
     */
    public void setRuleNo(String ruleNo);

    /**
     * Returns the modified date of this cdr model.
     *
     * @return the modified date of this cdr model
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this cdr model.
     *
     * @param modifiedDate the modified date of this cdr model
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(CdrModel cdrModel);

    @Override
    public int hashCode();

    @Override
    public CacheModel<CdrModel> toCacheModel();

    @Override
    public CdrModel toEscapedModel();

    @Override
    public CdrModel toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
