package com.stpl.app.model;

import com.stpl.portal.kernel.bean.AutoEscape;
import com.stpl.portal.model.BaseModel;
import com.stpl.portal.model.CacheModel;
import com.stpl.portal.service.ServiceContext;

import com.stpl.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorkflowMaster service. Represents a row in the &quot;WORKFLOW_MASTER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stpl.app.model.impl.WorkflowMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stpl.app.model.impl.WorkflowMasterImpl}.
 * </p>
 *
 * @author
 * @see WorkflowMaster
 * @see com.stpl.app.model.impl.WorkflowMasterImpl
 * @see com.stpl.app.model.impl.WorkflowMasterModelImpl
 * @generated
 */
public interface WorkflowMasterModel extends BaseModel<WorkflowMaster> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a workflow master model instance should use the {@link WorkflowMaster} interface instead.
     */

    /**
     * Returns the primary key of this workflow master.
     *
     * @return the primary key of this workflow master
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this workflow master.
     *
     * @param primaryKey the primary key of this workflow master
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the created by of this workflow master.
     *
     * @return the created by of this workflow master
     */
    public int getCreatedBy();

    /**
     * Sets the created by of this workflow master.
     *
     * @param createdBy the created by of this workflow master
     */
    public void setCreatedBy(int createdBy);

    /**
     * Returns the file size of this workflow master.
     *
     * @return the file size of this workflow master
     */
    @AutoEscape
    public String getFileSize();

    /**
     * Sets the file size of this workflow master.
     *
     * @param fileSize the file size of this workflow master
     */
    public void setFileSize(String fileSize);

    /**
     * Returns the workflow status ID of this workflow master.
     *
     * @return the workflow status ID of this workflow master
     */
    public int getWorkflowStatusId();

    /**
     * Sets the workflow status ID of this workflow master.
     *
     * @param workflowStatusId the workflow status ID of this workflow master
     */
    public void setWorkflowStatusId(int workflowStatusId);

    /**
     * Returns the modified by of this workflow master.
     *
     * @return the modified by of this workflow master
     */
    public int getModifiedBy();

    /**
     * Sets the modified by of this workflow master.
     *
     * @param modifiedBy the modified by of this workflow master
     */
    public void setModifiedBy(int modifiedBy);

    /**
     * Returns the created date of this workflow master.
     *
     * @return the created date of this workflow master
     */
    public Date getCreatedDate();

    /**
     * Sets the created date of this workflow master.
     *
     * @param createdDate the created date of this workflow master
     */
    public void setCreatedDate(Date createdDate);

    /**
     * Returns the approval level of this workflow master.
     *
     * @return the approval level of this workflow master
     */
    public int getApprovalLevel();

    /**
     * Sets the approval level of this workflow master.
     *
     * @param approvalLevel the approval level of this workflow master
     */
    public void setApprovalLevel(int approvalLevel);

    /**
     * Returns the no of approval of this workflow master.
     *
     * @return the no of approval of this workflow master
     */
    public int getNoOfApproval();

    /**
     * Sets the no of approval of this workflow master.
     *
     * @param noOfApproval the no of approval of this workflow master
     */
    public void setNoOfApproval(int noOfApproval);

    /**
     * Returns the file name of this workflow master.
     *
     * @return the file name of this workflow master
     */
    @AutoEscape
    public String getFileName();

    /**
     * Sets the file name of this workflow master.
     *
     * @param fileName the file name of this workflow master
     */
    public void setFileName(String fileName);

    /**
     * Returns the uploaded by of this workflow master.
     *
     * @return the uploaded by of this workflow master
     */
    @AutoEscape
    public String getUploadedBy();

    /**
     * Sets the uploaded by of this workflow master.
     *
     * @param uploadedBy the uploaded by of this workflow master
     */
    public void setUploadedBy(String uploadedBy);

    /**
     * Returns the modified date of this workflow master.
     *
     * @return the modified date of this workflow master
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this workflow master.
     *
     * @param modifiedDate the modified date of this workflow master
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the acc closure master sid of this workflow master.
     *
     * @return the acc closure master sid of this workflow master
     */
    public int getAccClosureMasterSid();

    /**
     * Sets the acc closure master sid of this workflow master.
     *
     * @param accClosureMasterSid the acc closure master sid of this workflow master
     */
    public void setAccClosureMasterSid(int accClosureMasterSid);

    /**
     * Returns the notes of this workflow master.
     *
     * @return the notes of this workflow master
     */
    @AutoEscape
    public String getNotes();

    /**
     * Sets the notes of this workflow master.
     *
     * @param notes the notes of this workflow master
     */
    public void setNotes(String notes);

    /**
     * Returns the workflow master sid of this workflow master.
     *
     * @return the workflow master sid of this workflow master
     */
    public int getWorkflowMasterSid();

    /**
     * Sets the workflow master sid of this workflow master.
     *
     * @param workflowMasterSid the workflow master sid of this workflow master
     */
    public void setWorkflowMasterSid(int workflowMasterSid);

    /**
     * Returns the workflow ID of this workflow master.
     *
     * @return the workflow ID of this workflow master
     */
    @AutoEscape
    public String getWorkflowId();

    /**
     * Sets the workflow ID of this workflow master.
     *
     * @param workflowId the workflow ID of this workflow master
     */
    public void setWorkflowId(String workflowId);

    /**
     * Returns the projection master sid of this workflow master.
     *
     * @return the projection master sid of this workflow master
     */
    public int getProjectionMasterSid();

    /**
     * Sets the projection master sid of this workflow master.
     *
     * @param projectionMasterSid the projection master sid of this workflow master
     */
    public void setProjectionMasterSid(int projectionMasterSid);

    /**
     * Returns the uploaded date of this workflow master.
     *
     * @return the uploaded date of this workflow master
     */
    public Date getUploadedDate();

    /**
     * Sets the uploaded date of this workflow master.
     *
     * @param uploadedDate the uploaded date of this workflow master
     */
    public void setUploadedDate(Date uploadedDate);

    /**
     * Returns the file type of this workflow master.
     *
     * @return the file type of this workflow master
     */
    @AutoEscape
    public String getFileType();

    /**
     * Sets the file type of this workflow master.
     *
     * @param fileType the file type of this workflow master
     */
    public void setFileType(String fileType);

    /**
     * Returns the approved by of this workflow master.
     *
     * @return the approved by of this workflow master
     */
    public int getApprovedBy();

    /**
     * Sets the approved by of this workflow master.
     *
     * @param approvedBy the approved by of this workflow master
     */
    public void setApprovedBy(int approvedBy);

    /**
     * Returns the workflow descrption of this workflow master.
     *
     * @return the workflow descrption of this workflow master
     */
    @AutoEscape
    public String getWorkflowDescrption();

    /**
     * Sets the workflow descrption of this workflow master.
     *
     * @param workflowDescrption the workflow descrption of this workflow master
     */
    public void setWorkflowDescrption(String workflowDescrption);

    /**
     * Returns the approved date of this workflow master.
     *
     * @return the approved date of this workflow master
     */
    public Date getApprovedDate();

    /**
     * Sets the approved date of this workflow master.
     *
     * @param approvedDate the approved date of this workflow master
     */
    public void setApprovedDate(Date approvedDate);

    /**
     * Returns the contract master sid of this workflow master.
     *
     * @return the contract master sid of this workflow master
     */
    public int getContractMasterSid();

    /**
     * Sets the contract master sid of this workflow master.
     *
     * @param contractMasterSid the contract master sid of this workflow master
     */
    public void setContractMasterSid(int contractMasterSid);

    /**
     * Returns the contract structure of this workflow master.
     *
     * @return the contract structure of this workflow master
     */
    @AutoEscape
    public String getContractStructure();

    /**
     * Sets the contract structure of this workflow master.
     *
     * @param contractStructure the contract structure of this workflow master
     */
    public void setContractStructure(String contractStructure);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(WorkflowMaster workflowMaster);

    @Override
    public int hashCode();

    @Override
    public CacheModel<WorkflowMaster> toCacheModel();

    @Override
    public WorkflowMaster toEscapedModel();

    @Override
    public WorkflowMaster toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
