------------------------------------------- M_SALES_PROJECTION_MASTER -------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'M_SALES_PROJECTION_MASTER'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[M_SALES_PROJECTION_MASTER]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           METHODOLOGY            VARCHAR(20) NULL,
           CALCULATION_PERIODS    VARCHAR(4000) NULL,
           CALCULATION_BASED      VARCHAR(100) NULL,
           CHECK_RECORD           BIT NOT NULL
        )
  END
GO

---------------------PRIMARY KEY CONSTRAINT------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SALES_PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [dbo].[M_SALES_PROJECTION_MASTER]
        ADD CONSTRAINT PK_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_SID PRIMARY KEY(PROJECTION_DETAILS_SID)
  END

GO

-------------------------- column addition ----------------------------------
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'M_SALES_PROJECTION_MASTER'
                      AND COLUMN_NAME = 'FORECAST_START_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION_MASTER
        ADD FORECAST_START_PERIOD_SID INT
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'M_SALES_PROJECTION_MASTER'
                      AND COLUMN_NAME = 'FORECAST_END_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION_MASTER
        ADD FORECAST_END_PERIOD_SID INT
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'M_SALES_PROJECTION_MASTER'
                      AND COLUMN_NAME = 'ALLOCATION_BASIS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION_MASTER
        ADD ALLOCATION_BASIS VARCHAR(50)
  END

GO

IF EXISTS (SELECT *
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  COLUMN_NAME = 'METHODOLOGY'
                  AND TABLE_NAME = 'M_SALES_PROJECTION_MASTER'
                  AND DATA_TYPE = 'VARCHAR'
                  AND CHARACTER_MAXIMUM_LENGTH = 20)
  BEGIN
      ALTER TABLE M_SALES_PROJECTION_MASTER
        ALTER COLUMN METHODOLOGY VARCHAR(50)
  END

GO
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'M_SALES_PROJECTION_MASTER'
                      AND COLUMN_NAME = 'EFFECTIVE_START_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION_MASTER
        ADD EFFECTIVE_START_PERIOD_SID INT NULL
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'M_SALES_PROJECTION_MASTER'
                      AND COLUMN_NAME = 'EFFECTIVE_END_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION_MASTER
        ADD EFFECTIVE_END_PERIOD_SID INT NULL
  END
  GO
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'M_SALES_PROJECTION_MASTER'
                      AND COLUMN_NAME = 'FREQ_CAL_START_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION_MASTER
        ADD FREQ_CAL_START_PERIOD_SID INT
  END
  GO
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'M_SALES_PROJECTION_MASTER'
                      AND COLUMN_NAME = 'FREQ_CAL_END_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION_MASTER
        ADD FREQ_CAL_END_PERIOD_SID INT
  END 
  GO

------------------------------------------- ST_M_SALES_PROJECTION_MASTER ----------------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_M_SALES_PROJECTION_MASTER'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[ST_M_SALES_PROJECTION_MASTER]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           METHODOLOGY            VARCHAR(20) NULL,
           CALCULATION_PERIODS    VARCHAR(4000) NULL,
           CALCULATION_BASED      VARCHAR(100) NULL,
           CHECK_RECORD           BIT NOT NULL,
           [USER_ID]              INT NOT NULL,
           SESSION_ID             INT NOT NULL,
           LAST_MODIFIED_DATE     DATETIME NOT NULL
        )
  END
GO

---------------------PRIMARY KEY CONSTRAINT------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SALES_PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ST_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_SID_USER_ID_SESSION_ID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [dbo].[ST_M_SALES_PROJECTION_MASTER]
        ADD CONSTRAINT PK_ST_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_SID_USER_ID_SESSION_ID PRIMARY KEY(PROJECTION_DETAILS_SID, [USER_ID], SESSION_ID)
  END

GO

---------------------DEFAULT_CONSTRAINTS------------------------
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SALES_PROJECTION_MASTER'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_M_SALES_PROJECTION_MASTER_LAST_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ST_M_SALES_PROJECTION_MASTER
        ADD CONSTRAINT DF_ST_M_SALES_PROJECTION_MASTER_LAST_MODIFIED_DATE DEFAULT (Getdate()) FOR LAST_MODIFIED_DATE
  END

GO

---------------------------------- column addition --------------------------------
IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_M_SALES_PROJECTION_MASTER'
                      AND COLUMN_NAME = 'FORECAST_START_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_M_SALES_PROJECTION_MASTER
        ADD FORECAST_START_PERIOD_SID INT
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_M_SALES_PROJECTION_MASTER'
                      AND COLUMN_NAME = 'FORECAST_END_PERIOD_SID'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_M_SALES_PROJECTION_MASTER
        ADD FORECAST_END_PERIOD_SID INT
  END

GO

IF NOT EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ST_M_SALES_PROJECTION_MASTER'
                      AND COLUMN_NAME = 'ALLOCATION_BASIS'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      ALTER TABLE ST_M_SALES_PROJECTION_MASTER
        ADD ALLOCATION_BASIS VARCHAR(50)
  END

GO

IF EXISTS (SELECT *
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  COLUMN_NAME = 'METHODOLOGY'
                  AND TABLE_NAME = 'ST_M_SALES_PROJECTION_MASTER'
                  AND DATA_TYPE = 'VARCHAR'
                  AND CHARACTER_MAXIMUM_LENGTH = 20)
  BEGIN
      ALTER TABLE ST_M_SALES_PROJECTION_MASTER
        ALTER COLUMN METHODOLOGY VARCHAR(50)
  END

GO

------------------------------------------- M_ACTUAL_SALES -----------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'M_ACTUAL_SALES'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[M_ACTUAL_SALES]
        (
           PROJECTION_DETAILS_SID  INT NOT NULL,
           PERIOD_SID              INT NOT NULL,
           ACTUAL_SALES            NUMERIC(22, 6) NULL,
           ACTUAL_UNITS            NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_SALES NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_UNITS NUMERIC(22, 6) NULL
        )
  END
GO

---------------------PRIMARY KEY CONSTRAINT------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ACTUAL_SALES'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_M_ACTUAL_SALES_PROJECTION_DETAILS_SID_PERIOD_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [dbo].[M_ACTUAL_SALES]
        ADD CONSTRAINT PK_M_ACTUAL_SALES_PROJECTION_DETAILS_SID_PERIOD_SID PRIMARY KEY(PROJECTION_DETAILS_SID, PERIOD_SID)
  END

GO

-------------------------------------------------- ST_M_ACTUAL_SALES -------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_M_ACTUAL_SALES'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[ST_M_ACTUAL_SALES]
        (
           PROJECTION_DETAILS_SID  INT NOT NULL,
           PERIOD_SID              INT NOT NULL,
           ACTUAL_SALES            NUMERIC(22, 6) NULL,
           ACTUAL_UNITS            NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_SALES NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_UNITS NUMERIC(22, 6) NULL,
           [USER_ID]               INT NOT NULL,
           SESSION_ID              INT NOT NULL,
           LAST_MODIFIED_DATE      DATETIME NOT NULL
        )
  END
GO

---------------------PRIMARY KEY CONSTRAINT------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_ACTUAL_SALES'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ST_M_ACTUAL_SALES_PROJECTION_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [dbo].[ST_M_ACTUAL_SALES]
        ADD CONSTRAINT PK_ST_M_ACTUAL_SALES_PROJECTION_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID PRIMARY KEY(PROJECTION_DETAILS_SID, PERIOD_SID, [USER_ID], SESSION_ID)
  END

GO

---------------------DEFAULT_CONSTRAINTS------------------------
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_ACTUAL_SALES'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_M_ACTUAL_SALES_LAST_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ST_M_ACTUAL_SALES
        ADD CONSTRAINT DF_ST_M_ACTUAL_SALES_LAST_MODIFIED_DATE DEFAULT (Getdate()) FOR LAST_MODIFIED_DATE
  END

GO

------------------------------------------------------ M_SALES_PROJECTION ------------------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'M_SALES_PROJECTION'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[M_SALES_PROJECTION]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           ACCOUNT_GROWTH         NUMERIC(22, 6) NULL,
           PRODUCT_GROWTH         NUMERIC(22, 6) NULL,
           PROJECTION_SALES       NUMERIC(22, 6) NULL,
           PROJECTION_UNITS       NUMERIC(22, 6) NULL,
           PERIOD_SID             INT NOT NULL,
           ADJUSTMENT_TYPE        VARCHAR(20) NULL,
           ADJUSTMENT_BASIS       VARCHAR(20) NULL,
           ADJUSTMENT_VARIABLE    BIT NULL,
           ADJUSTMENT_METHODOLOGY VARCHAR(50) NULL,
           ADJUSTMENT_VALUES      NUMERIC(22, 6) NULL
        )
  END
GO

---------------------PRIMARY KEY CONSTRAINT------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SALES_PROJECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_M_SALES_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [dbo].[M_SALES_PROJECTION]
        ADD CONSTRAINT PK_M_SALES_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID PRIMARY KEY(PROJECTION_DETAILS_SID, PERIOD_SID)
  END

GO

------------------------------------------- ST_M_SALES_PROJECTION ------------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_M_SALES_PROJECTION'
                      AND TABLE_SCHEMA = 'DBO')
  BEGIN
      CREATE TABLE [DBO].[ST_M_SALES_PROJECTION]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           ACCOUNT_GROWTH         NUMERIC(22, 6) NULL,
           PRODUCT_GROWTH         NUMERIC(22, 6) NULL,
           PROJECTION_SALES       NUMERIC(22, 6) NULL,
           PROJECTION_UNITS       NUMERIC(22, 6) NULL,
           PERIOD_SID             INT NOT NULL,
           ADJUSTMENT_TYPE        VARCHAR(20) NULL,
           ADJUSTMENT_BASIS       VARCHAR(20) NULL,
           ADJUSTMENT_VARIABLE    BIT NULL,
           ADJUSTMENT_METHODOLOGY VARCHAR(50) NULL,
           ADJUSTMENT_VALUES      NUMERIC(22, 6) NULL,
           [USER_ID]              INT NOT NULL,
           SESSION_ID             INT NOT NULL,
           LAST_MODIFIED_DATE     DATETIME NOT NULL
        )
  END
GO

---------------------PRIMARY KEY CONSTRAINT------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.KEY_CONSTRAINTS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SALES_PROJECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'PK_ST_M_SALES_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID'
                     AND TYPE = 'PK')
  BEGIN
      ALTER TABLE [dbo].[ST_M_SALES_PROJECTION]
        ADD CONSTRAINT PK_ST_M_SALES_PROJECTION_PROJECTION_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID PRIMARY KEY(PROJECTION_DETAILS_SID, PERIOD_SID, [USER_ID], SESSION_ID)
  END

GO

---------------------DEFAULT_CONSTRAINTS------------------------
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SALES_PROJECTION'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_M_SALES_PROJECTION_LAST_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ST_M_SALES_PROJECTION
        ADD CONSTRAINT DF_ST_M_SALES_PROJECTION_LAST_MODIFIED_DATE DEFAULT (Getdate()) FOR LAST_MODIFIED_DATE
  END

GO 
