----------------------------------------------------------------------M_SUPPLEMENTAL_DISC_MASTER---------------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'M_SUPPLEMENTAL_DISC_MASTER'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[M_SUPPLEMENTAL_DISC_MASTER]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           MARKET_TYPE            VARCHAR(50) NOT NULL,
           ACTUAL_DISCOUNT        NUMERIC(22, 6) NULL,
           CASH_PAID_DATE         VARCHAR(10) NULL,
           ACTUAL_METHODOLOGY     VARCHAR(50) NULL,
           ACTUAL_CONTRACT_PRICE  NUMERIC(22, 6) NULL,
           ACTUAL_DISCOUNT_RATE1  NUMERIC(22, 6) NULL,
           ACTUAL_DISCOUNT_RATE2  NUMERIC(22, 6) NULL,
           CONTRACT_END_DATE      DATETIME NULL,
           CHECK_RECORD           INT NULL
        )
  END

GO

--PRIMARY KEY 
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_SID'
                     AND TABLE_NAME = 'M_SUPPLEMENTAL_DISC_MASTER')
  ALTER TABLE M_SUPPLEMENTAL_DISC_MASTER
    ADD CONSTRAINT PK_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_SID PRIMARY KEY(PROJECTION_DETAILS_SID)

GO

----------------------------------------------------------------------M_SUPPLEMENTAL_DISC_ACTUALS---------------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'M_SUPPLEMENTAL_DISC_ACTUALS'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[M_SUPPLEMENTAL_DISC_ACTUALS]
        (
           PROJECTION_DETAILS_SID  INT NOT NULL,
           PERIOD_SID              INT NOT NULL,
           ACTUAL_SALES            NUMERIC(22, 6) NULL,
           ACTUAL_RATE             NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_SALES NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_RATE  NUMERIC(22, 6) NULL,
		   ACTUAL_RPU  			   NUMERIC(22,6)
        )
  END

GO

--PRIMARY KEY
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_SID_PERIOD_SID'
                     AND TABLE_NAME = 'M_SUPPLEMENTAL_DISC_ACTUALS')
  ALTER TABLE M_SUPPLEMENTAL_DISC_ACTUALS
    ADD CONSTRAINT PK_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_SID_PERIOD_SID PRIMARY KEY(PROJECTION_DETAILS_SID, PERIOD_SID)

GO
IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'M_SUPPLEMENTAL_DISC_ACTUALS'
			AND COLUMN_NAME = 'ACTUAL_RPU'
		)
BEGIN
	ALTER TABLE M_SUPPLEMENTAL_DISC_ACTUALS ADD ACTUAL_RPU  NUMERIC(22,6)
END
GO

-------------------------------------------------------------------M_SUPPLEMENTAL_DISC_PROJ-----------------------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'M_SUPPLEMENTAL_DISC_PROJ'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[M_SUPPLEMENTAL_DISC_PROJ]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           PERIOD_SID             INT NOT NULL,
           METHODOLOGY            VARCHAR(50) NULL,
           CONTRACT_PRICE         NUMERIC(22, 6) NULL,
           DISCOUNT_RATE_1        NUMERIC(22, 6) NULL,
           DISCOUNT_RATE_2        NUMERIC(22, 6) NULL,
           ACCESS                 VARCHAR(5) NULL,
           PARITY                 BIT NULL,
           PARITY_REFERENCE       VARCHAR(10) NULL,
           PARITY_DISCOUNT        NUMERIC(22, 6) NULL,
           PROJECTION_RATE        NUMERIC(22, 6) NULL,
           PROJECTION_SALES       NUMERIC(22, 6) NULL,
		   PROJECTION_RPU  		  NUMERIC(22,6)
        )
  END

GO

--PRIMARY KEY
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_SID_PERIOD_SID'
                     AND TABLE_NAME = 'M_SUPPLEMENTAL_DISC_PROJ')
  ALTER TABLE M_SUPPLEMENTAL_DISC_PROJ
    ADD CONSTRAINT PK_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_SID_PERIOD_SID PRIMARY KEY(PROJECTION_DETAILS_SID, PERIOD_SID)

GO
IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'M_SUPPLEMENTAL_DISC_PROJ'
			AND COLUMN_NAME = 'PROJECTION_RPU'
		)
BEGIN
	ALTER TABLE M_SUPPLEMENTAL_DISC_PROJ ADD PROJECTION_RPU  NUMERIC(22,6)
END
GO
-----------------------------------------------------------ST_M_SUPPLEMENTAL_DISC_MASTER----------------------------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_M_SUPPLEMENTAL_DISC_MASTER'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[ST_M_SUPPLEMENTAL_DISC_MASTER]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           MARKET_TYPE            VARCHAR(50) NOT NULL,
           ACTUAL_DISCOUNT        NUMERIC(22, 6) NULL,
		   CASH_PAID_DATE         VARCHAR(10) NULL,
           ACTUAL_METHODOLOGY     VARCHAR(50) NULL,
           ACTUAL_CONTRACT_PRICE  NUMERIC(22, 6) NULL,
           ACTUAL_DISCOUNT_RATE1  NUMERIC(22, 6) NULL,
           ACTUAL_DISCOUNT_RATE2  NUMERIC(22, 6) NULL,
           CONTRACT_END_DATE      DATETIME NULL,
           CHECK_RECORD           INT NULL,
           [USER_ID]              INT NOT NULL,
           SESSION_ID             INT NOT NULL,
           LAST_MODIFIED_DATE     DATETIME NOT NULL
        )
  END

GO

--PRIMARY KEY
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_ST_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_SID_USER_ID_SESSION_ID'
                     AND TABLE_NAME = 'ST_M_SUPPLEMENTAL_DISC_MASTER')
  ALTER TABLE ST_M_SUPPLEMENTAL_DISC_MASTER
    ADD CONSTRAINT PK_ST_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_SID_USER_ID_SESSION_ID PRIMARY KEY(PROJECTION_DETAILS_SID, [USER_ID], SESSION_ID)

GO

--DEFAULT_CONSTRAINTS
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SUPPLEMENTAL_DISC_MASTER'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_M_SUPPLEMENTAL_DISC_MASTER_LAST_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ST_M_SUPPLEMENTAL_DISC_MASTER
        ADD CONSTRAINT DF_ST_M_SUPPLEMENTAL_DISC_MASTER_LAST_MODIFIED_DATE DEFAULT (Getdate()) FOR LAST_MODIFIED_DATE
  END

GO

-----------------------------------------------------------ST_M_SUPPLEMENTAL_DISC_ACTUALS----------------------------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_M_SUPPLEMENTAL_DISC_ACTUALS'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[ST_M_SUPPLEMENTAL_DISC_ACTUALS]
        (
           PROJECTION_DETAILS_SID  INT NOT NULL,
           PERIOD_SID              INT NOT NULL,
           ACTUAL_SALES            NUMERIC(22, 6) NULL,
           ACTUAL_RATE             NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_SALES NUMERIC(22, 6) NULL,
           ACTUAL_PROJECTION_RATE  NUMERIC(22, 6) NULL,
		   ACTUAL_RPU  			   NUMERIC(22,6),
           [USER_ID]               INT NOT NULL,
           SESSION_ID              INT NOT NULL,
           LAST_MODIFIED_DATE      DATETIME NOT NULL
        )
  END

GO

--PRIMARY KEY
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_ST_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID'
                     AND TABLE_NAME = 'ST_M_SUPPLEMENTAL_DISC_ACTUALS')
  ALTER TABLE ST_M_SUPPLEMENTAL_DISC_ACTUALS
    ADD CONSTRAINT PK_ST_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID PRIMARY KEY(PROJECTION_DETAILS_SID, PERIOD_SID, [USER_ID], SESSION_ID)

GO
IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'ST_M_SUPPLEMENTAL_DISC_ACTUALS'
			AND COLUMN_NAME = 'ACTUAL_RPU'
		)
BEGIN
	ALTER TABLE ST_M_SUPPLEMENTAL_DISC_ACTUALS ADD ACTUAL_RPU  NUMERIC(22,6)
END
GO
--DEFAULT_CONSTRAINTS
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SUPPLEMENTAL_DISC_ACTUALS'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_M_SUPPLEMENTAL_DISC_ACTUALS_LAST_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ST_M_SUPPLEMENTAL_DISC_ACTUALS
        ADD CONSTRAINT DF_ST_M_SUPPLEMENTAL_DISC_ACTUALS_LAST_MODIFIED_DATE DEFAULT (Getdate()) FOR LAST_MODIFIED_DATE
  END

GO

---------------------------------------------------------------ST_M_SUPPLEMENTAL_DISC_PROJ----------------------------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ST_M_SUPPLEMENTAL_DISC_PROJ'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[ST_M_SUPPLEMENTAL_DISC_PROJ]
        (
           PROJECTION_DETAILS_SID INT NOT NULL,
           PERIOD_SID             INT NOT NULL,
           METHODOLOGY            VARCHAR(50) NULL,
           CONTRACT_PRICE         NUMERIC(22, 6) NULL,
           DISCOUNT_RATE_1        NUMERIC(22, 6) NULL,
           DISCOUNT_RATE_2        NUMERIC(22, 6) NULL,
           ACCESS                 VARCHAR(5) NULL,
           PARITY                 BIT NULL,
           PARITY_REFERENCE       VARCHAR(10) NULL,
           PARITY_DISCOUNT        NUMERIC(22, 6) NULL,
           PROJECTION_RATE        NUMERIC(22, 6) NULL,
           PROJECTION_SALES       NUMERIC(22, 6) NULL,
		   PROJECTION_RPU  		  NUMERIC(22,6),
           [USER_ID]              INT NOT NULL,
           SESSION_ID             INT NOT NULL,
           LAST_MODIFIED_DATE     DATETIME NOT NULL
        )
  END

GO

--PRIMARY KEY
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_ST_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID'
                     AND TABLE_NAME = 'ST_M_SUPPLEMENTAL_DISC_PROJ')
  ALTER TABLE ST_M_SUPPLEMENTAL_DISC_PROJ
    ADD CONSTRAINT PK_ST_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_SID_PERIOD_SID_USER_ID_SESSION_ID PRIMARY KEY(PROJECTION_DETAILS_SID, PERIOD_SID, [USER_ID], SESSION_ID)

GO
IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'ST_M_SUPPLEMENTAL_DISC_PROJ'
			AND COLUMN_NAME = 'PROJECTION_RPU'
		)
BEGIN
	ALTER TABLE ST_M_SUPPLEMENTAL_DISC_PROJ ADD PROJECTION_RPU  NUMERIC(22,6)
END
GO

--DEFAULT_CONSTRAINTS
IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SUPPLEMENTAL_DISC_PROJ'
                      AND Schema_name(SCHEMA_ID) = 'dbo'
                      AND NAME = 'DF_ST_M_SUPPLEMENTAL_DISC_PROJ_LAST_MODIFIED_DATE')
  BEGIN
      ALTER TABLE ST_M_SUPPLEMENTAL_DISC_PROJ
        ADD CONSTRAINT DF_ST_M_SUPPLEMENTAL_DISC_PROJ_LAST_MODIFIED_DATE DEFAULT (Getdate()) FOR LAST_MODIFIED_DATE
  END

GO 
---------------------------------------------M_SUPPLEMENTAL_FORMULA_DETAILS-----------------------------------------------------------

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'M_SUPPLEMENTAL_FORMULA_DETAILS'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [M_SUPPLEMENTAL_FORMULA_DETAILS]
        (
           [SUPP_FORMULA_DETAILS_SID] [INT] IDENTITY(1, 1) NOT NULL,
           [FORMULA_NO]               [VARCHAR](50) NOT NULL,
           [FORMULA_DESC]             [VARCHAR](50) NOT NULL,
           [FORMULA]                  [VARCHAR](4000) NOT NULL,
           [CREATED_DATE]             [DATETIME] NOT NULL CONSTRAINT DF_M_SUPPLEMENTAL_FORMULA_DETAILS_CREATED_DATE DEFAULT Getdate(),
           [MODIFIED_DATE]            [DATETIME] NOT NULL CONSTRAINT DF_M_SUPPLEMENTAL_FORMULA_DETAILS_MODIFIED_DATE DEFAULT Getdate(),
           [IS_ACTIVE]                [BIT] NOT NULL CONSTRAINT DF_M_SUPPLEMENTAL_FORMULA_DETAILS_IS_ACTIVE DEFAULT 1
        )
  END

GO 
--------------------------------------------M_PARITY_LOOKUP--------------------------------------------------------------------------
IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'M_PARITY_LOOKUP'
                      AND TABLE_SCHEMA = 'dbo')
  BEGIN
      CREATE TABLE [dbo].[M_PARITY_LOOKUP]
        (
           M_PARITY_LOOKUP_SID    INT IDENTITY(1, 1) NOT NULL,
           CONTRACT_MASTER_SID    INT NOT NULL,
           ITEM_MASTER_SID        INT NOT NULL,
           QUARTER                INT NOT NULL,
           YEAR                   INT NOT NULL,
           METHODOLOGY            VARCHAR(50) NOT NULL,
           CONTRACT_PRICE         NUMERIC(22, 6) NULL,
           DISCOUNT_RATE_1        NUMERIC(22, 6) NULL,
           DISCOUNT_RATE_2        NUMERIC(22, 6) NULL,
           PROJECTION_DETAILS_SID INT NOT NULL
        )
  END

GO

---------------------PRIMARY KEY CONSTRAINT-----------------------
IF NOT EXISTS(SELECT 'X'
              FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
              WHERE  CONSTRAINT_NAME = 'PK_M_PARITY_LOOKUP_M_PARITY_LOOKUP_SID'
                     AND TABLE_NAME = 'M_PARITY_LOOKUP')
BEGIN
  ALTER TABLE M_PARITY_LOOKUP
    ADD CONSTRAINT PK_M_PARITY_LOOKUP_M_PARITY_LOOKUP_SID PRIMARY KEY(M_PARITY_LOOKUP_SID)
END

GO
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.TABLE_CONSTRAINTS
           WHERE  TABLE_NAME = 'M_PARITY_LOOKUP'
                  AND CONSTRAINT_NAME = 'FK_M_PARITY_LOOKUP_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                  AND CONSTRAINT_TYPE = 'FOREIGN KEY')
  BEGIN
      ALTER TABLE M_PARITY_LOOKUP
        DROP CONSTRAINT FK_M_PARITY_LOOKUP_PROJECTION_DETAILS_PROJECTION_DETAILS_SID
  END
  GO
IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'M_PARITY_LOOKUP'
                  AND COLUMN_NAME = 'PROJECTION_DETAILS_SID')
  BEGIN
      EXEC SP_RENAME 'M_PARITY_LOOKUP.PROJECTION_DETAILS_SID', 'CCP_DETAILS_SID','COLUMN'
  END 

 GO