--------------------------NATIONAL ASSUMPTIONS DATA SELECTION FOREIGN KEYS------------------------------------

------------------------NA_PROJ_MASTER FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'NA_PROJ_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NA_PROJ_MASTER_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE NA_PROJ_MASTER
        ADD CONSTRAINT FK_NA_PROJ_MASTER_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END

GO

--IF NOT EXISTS(SELECT 1
--              FROM   SYS.FOREIGN_KEYS
--              WHERE  Object_name(PARENT_OBJECT_ID) = 'NA_PROJ_MASTER'
--                     AND Schema_name(SCHEMA_ID) = 'DBO'
--                     AND NAME = 'FK_NA_PROJ_MASTER_ITEM_GROUP_ITEM_GROUP_SID'
--                     AND TYPE = 'F')
--  BEGIN
--      ALTER TABLE NA_PROJ_MASTER
--        ADD CONSTRAINT FK_NA_PROJ_MASTER_ITEM_GROUP_ITEM_GROUP_SID FOREIGN KEY(ITEM_GROUP_SID) REFERENCES ITEM_GROUP(ITEM_GROUP_SID)
--  END
--
--GO

IF NOT EXISTS (
              SELECT 1
              FROM SYS.FOREIGN_KEYS
              WHERE Object_name(PARENT_OBJECT_ID) = 'NA_PROJ_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NA_PROJ_MASTER_COMPANY_MASTER_BUSINESS_UNIT'
                     AND TYPE = 'F'
              )
BEGIN
       ALTER TABLE NA_PROJ_MASTER add CONSTRAINT FK_NA_PROJ_MASTER_COMPANY_MASTER_BUSINESS_UNIT FOREIGN KEY (BUSINESS_UNIT) REFERENCES COMPANY_MASTER (COMPANY_MASTER_SID)
END
GO

-------------------------------NA_PROJ_DETAILS FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'NA_PROJ_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NA_PROJ_DETAILS_NA_PROJ_MASTER_NA_PROJ_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE NA_PROJ_DETAILS
        ADD CONSTRAINT FK_NA_PROJ_DETAILS_NA_PROJ_MASTER_NA_PROJ_MASTER_SID FOREIGN KEY(NA_PROJ_MASTER_SID) REFERENCES NA_PROJ_MASTER(NA_PROJ_MASTER_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'NA_PROJ_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NA_PROJ_DETAILS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE NA_PROJ_DETAILS
        ADD CONSTRAINT FK_NA_PROJ_DETAILS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

----------------------------NATIONAL_ASSUMPTIONS FORECASTING TABLES FOREIGN KEY CONSTRAINT-----------------------------

-------------------------------NATIONAL_ASSUMPTIONS FOREIGN KEY CONSTRAINT-------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'NATIONAL_ASSUMPTIONS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NATIONAL_ASSUMPTIONS_NA_PROJ_MASTER_NA_PROJ_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE NATIONAL_ASSUMPTIONS
        ADD CONSTRAINT FK_NATIONAL_ASSUMPTIONS_NA_PROJ_MASTER_NA_PROJ_MASTER_SID FOREIGN KEY(NA_PROJ_MASTER_SID) REFERENCES NA_PROJ_MASTER(NA_PROJ_MASTER_SID)
  END

GO

-------------------------------ST_NATIONAL_ASSUMPTIONS FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_NATIONAL_ASSUMPTIONS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_NATIONAL_ASSUMPTIONS_NA_PROJ_MASTER_NA_PROJ_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_NATIONAL_ASSUMPTIONS
        ADD CONSTRAINT FK_ST_NATIONAL_ASSUMPTIONS_NA_PROJ_MASTER_NA_PROJ_MASTER_SID FOREIGN KEY(NA_PROJ_MASTER_SID) REFERENCES NA_PROJ_MASTER(NA_PROJ_MASTER_SID)
  END

GO


-------------------------------NATIONAL_ASSUMPTIONS_ACTUALS FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'NATIONAL_ASSUMPTIONS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NATIONAL_ASSUMPTIONS_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE NATIONAL_ASSUMPTIONS_ACTUALS
        ADD CONSTRAINT FK_NATIONAL_ASSUMPTIONS_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'NATIONAL_ASSUMPTIONS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NATIONAL_ASSUMPTIONS_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE NATIONAL_ASSUMPTIONS_ACTUALS
        ADD CONSTRAINT FK_NATIONAL_ASSUMPTIONS_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

-------------------------------ST_NATIONAL_ASSUMPTIONS_ACTUALS FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_NATIONAL_ASSUMPTIONS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_NATIONAL_ASSUMPTIONS_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_NATIONAL_ASSUMPTIONS_ACTUALS
        ADD CONSTRAINT FK_ST_NATIONAL_ASSUMPTIONS_ACTUALS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO


IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_NATIONAL_ASSUMPTIONS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_NATIONAL_ASSUMPTIONS_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_NATIONAL_ASSUMPTIONS_ACTUALS
        ADD CONSTRAINT FK_ST_NATIONAL_ASSUMPTIONS_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO


-------------------------------NATIONAL_ASSUMPTIONS_PROJ FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'NATIONAL_ASSUMPTIONS_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NATIONAL_ASSUMPTIONS_PROJ_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE NATIONAL_ASSUMPTIONS_PROJ
        ADD CONSTRAINT FK_NATIONAL_ASSUMPTIONS_PROJ_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'NATIONAL_ASSUMPTIONS_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NATIONAL_ASSUMPTIONS_PROJ_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE NATIONAL_ASSUMPTIONS_PROJ
        ADD CONSTRAINT FK_NATIONAL_ASSUMPTIONS_PROJ_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

-------------------------------ST_NATIONAL_ASSUMPTIONS_PROJ FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_NATIONAL_ASSUMPTIONS_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_NATIONAL_ASSUMPTIONS_PROJ_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_NATIONAL_ASSUMPTIONS_PROJ
        ADD CONSTRAINT FK_ST_NATIONAL_ASSUMPTIONS_PROJ_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_NATIONAL_ASSUMPTIONS_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_NATIONAL_ASSUMPTIONS_PROJ_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_NATIONAL_ASSUMPTIONS_PROJ
        ADD CONSTRAINT FK_ST_NATIONAL_ASSUMPTIONS_PROJ_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

------------------------------------------------------------NEW NDC-----------------------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'ST_FEDERAL_NEW_NDC'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_FEDERAL_NEW_NDC_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[ST_FEDERAL_NEW_NDC]
        ADD CONSTRAINT [FK_ST_FEDERAL_NEW_NDC_ITEM_MASTER_SID] FOREIGN KEY([ITEM_MASTER_SID]) REFERENCES [DBO].[ITEM_MASTER] ([ITEM_MASTER_SID])
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'FEDERAL_NEW_NDC'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FEDERAL_NEW_NDC_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[FEDERAL_NEW_NDC]
        ADD CONSTRAINT [FK_FEDERAL_NEW_NDC_ITEM_MASTER_SID] FOREIGN KEY([ITEM_MASTER_SID]) REFERENCES [DBO].[ITEM_MASTER] ([ITEM_MASTER_SID])
  END

GO 

------------------------------------------------------------NEW NDC-----------------------------------------------------------

-------------------------------NATIONAL ASSUMPTIONS WORKSHEETS FOREIGN KEY----------------------------------------

-------------------------------MEDICAID_URA_PROJ FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'MEDICAID_URA_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_MEDICAID_URA_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE MEDICAID_URA_PROJ
        ADD CONSTRAINT FK_MEDICAID_URA_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'MEDICAID_URA_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_MEDICAID_URA_PROJ_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE MEDICAID_URA_PROJ
        ADD CONSTRAINT FK_MEDICAID_URA_PROJ_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO


-------------------------------ST_MEDICAID_URA_PROJ FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_MEDICAID_URA_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_MEDICAID_URA_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_MEDICAID_URA_PROJ
        ADD CONSTRAINT FK_ST_MEDICAID_URA_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_MEDICAID_URA_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_MEDICAID_URA_PROJ_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_MEDICAID_URA_PROJ
        ADD CONSTRAINT FK_ST_MEDICAID_URA_PROJ_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

-------------------------------MEDICAID_URA_ACTUALS FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'MEDICAID_URA_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_MEDICAID_URA_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE MEDICAID_URA_ACTUALS
        ADD CONSTRAINT FK_MEDICAID_URA_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'MEDICAID_URA_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_MEDICAID_URA_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE MEDICAID_URA_ACTUALS
        ADD CONSTRAINT FK_MEDICAID_URA_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO


-------------------------------ST_MEDICAID_URA_ACTUALS FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_MEDICAID_URA_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_MEDICAID_URA_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_MEDICAID_URA_ACTUALS
        ADD CONSTRAINT FK_ST_MEDICAID_URA_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_MEDICAID_URA_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_MEDICAID_URA_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_MEDICAID_URA_ACTUALS
        ADD CONSTRAINT FK_ST_MEDICAID_URA_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO


-------------------------------FCP_ACTUALS FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'FCP_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FCP_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE FCP_ACTUALS
        ADD CONSTRAINT FK_FCP_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'FCP_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FCP_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE FCP_ACTUALS
        ADD CONSTRAINT FK_FCP_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO


-------------------------------ST_FCP_ACTUALS FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_FCP_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_FCP_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_FCP_ACTUALS
        ADD CONSTRAINT FK_ST_FCP_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_FCP_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_FCP_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_FCP_ACTUALS
        ADD CONSTRAINT FK_ST_FCP_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

-------------------------------FCP_PROJ FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'FCP_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FCP_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE FCP_PROJ
        ADD CONSTRAINT FK_FCP_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'FCP_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_FCP_PROJ_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE FCP_PROJ
        ADD CONSTRAINT FK_FCP_PROJ_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO

-------------------------------PHS_PROJ FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PHS_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PHS_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PHS_PROJ
        ADD CONSTRAINT FK_PHS_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PHS_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PHS_PROJ_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PHS_PROJ
        ADD CONSTRAINT FK_PHS_PROJ_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO 


-------------------------------ST_PHS_PROJ FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_PHS_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_PHS_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_PHS_PROJ
        ADD CONSTRAINT FK_ST_PHS_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_PHS_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_PHS_PROJ_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_PHS_PROJ
        ADD CONSTRAINT FK_ST_PHS_PROJ_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO 




-------------------------------ST_FCP_PROJ FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_FCP_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_FCP_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_FCP_PROJ
        ADD CONSTRAINT FK_ST_FCP_PROJ_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_FCP_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_FCP_PROJ_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_FCP_PROJ
        ADD CONSTRAINT FK_ST_FCP_PROJ_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO


-------------------------------PHS_ACTUALS FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PHS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PHS_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PHS_ACTUALS
        ADD CONSTRAINT FK_PHS_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PHS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PHS_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PHS_ACTUALS
        ADD CONSTRAINT FK_PHS_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO 


-------------------------------ST_PHS_ACTUALS FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_PHS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_PHS_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_PHS_ACTUALS
        ADD CONSTRAINT FK_ST_PHS_ACTUALS_NA_PROJ_DETAILS_NA_PROJ_DETAILS_SID FOREIGN KEY(NA_PROJ_DETAILS_SID) REFERENCES NA_PROJ_DETAILS(NA_PROJ_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_PHS_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_PHS_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_PHS_ACTUALS
        ADD CONSTRAINT FK_ST_PHS_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO 

-------------------------------NA_PROJECTION_SELECTION FOREIGN KEY CONSTRAINT----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'NA_PROJECTION_SELECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_NA_PROJECTION_SELECTION_NA_PROJ_MASTER_NA_PROJ_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [NA_PROJECTION_SELECTION]
        ADD CONSTRAINT [FK_NA_PROJECTION_SELECTION_NA_PROJ_MASTER_NA_PROJ_MASTER_SID] FOREIGN KEY([NA_PROJ_MASTER_SID]) REFERENCES [NA_PROJ_MASTER]([NA_PROJ_MASTER_SID])
  END

GO 



----------------------------------------------------- M_SALES_PROJECTION_MASTER -----------------------------------------

-------------------------------- PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS TABLE -------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SALES_PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION_MASTER
        ADD CONSTRAINT FK_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END 
GO

----------------------------------------------------- ST_M_SALES_PROJECTION_MASTER -----------------------------------------

-------------------------------- PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SALES_PROJECTION_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_SALES_PROJECTION_MASTER
        ADD CONSTRAINT FK_ST_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END 
GO

--------------------- M_ACTUAL_SALES ------------------------------------------------------------------------------------------------

------------------------------------------------- PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS TABLE ------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ACTUAL_SALES'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_ACTUAL_SALES_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_ACTUAL_SALES
        ADD CONSTRAINT FK_M_ACTUAL_SALES_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END
GO

------------------------------------------------- PERIOD_SID REFERENCE FROM PERIOD_SID --------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ACTUAL_SALES'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_ACTUAL_SALES_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_ACTUAL_SALES
        ADD CONSTRAINT FK_M_ACTUAL_SALES_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END
GO


------------------------------- ST_M_ACTUAL_SALES -----------------------------------------------------------------------------

------------------------------------------------- PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS TABLE ------------------------------------------------------                            
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_ACTUAL_SALES'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_ACTUAL_SALES_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_ACTUAL_SALES
        ADD CONSTRAINT FK_ST_M_ACTUAL_SALES_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END
GO

------------------------------------------------- PERIOD_SID REFERENCE FROM PERIOD_SID --------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_ACTUAL_SALES'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_ACTUAL_SALES_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_ACTUAL_SALES
        ADD CONSTRAINT FK_ST_M_ACTUAL_SALES_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END
GO 


-------------------------------- NM SALES PROJECTION ----------------------------------

-------------------------------- PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SALES_PROJECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_SALES_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION
        ADD CONSTRAINT FK_M_SALES_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END
GO

-------------------------------- PERIOD_SID REFERENCE FROM PERIOD TABLE -----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SALES_PROJECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_SALES_PROJECTION_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION
        ADD CONSTRAINT FK_M_SALES_PROJECTION_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END
GO 

--------------------------------ST_M_SALES_PROJECTION ----------------------------------

-------------------------------- PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SALES_PROJECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_SALES_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_SALES_PROJECTION
        ADD CONSTRAINT FK_ST_M_SALES_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END
GO

-------------------------------- PERIOD_SID REFERENCE FROM PERIOD TABLE -----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SALES_PROJECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_SALES_PROJECTION_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_SALES_PROJECTION
        ADD CONSTRAINT FK_ST_M_SALES_PROJECTION_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END
GO 

----------------------------------------------------- M_ASSUMPTIONS -------------------------------------
------------------------------------------------------ PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS ------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ASSUMPTIONS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_ASSUMPTIONS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_ASSUMPTIONS
        ADD CONSTRAINT FK_M_ASSUMPTIONS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END 
GO
----------------------------------------------------- ST_M_ASSUMPTIONS -------------------------------------

------------------------------------------------------ PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS ------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_ASSUMPTIONS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_ASSUMPTIONS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_ASSUMPTIONS
        ADD CONSTRAINT FK_ST_M_ASSUMPTIONS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END
GO

----------------------------------------------------- M_DISCOUNT_PROJECTION -----------------------------------------

-------------------------------- PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS TABLE -------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_DISCOUNT_PROJECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_DISCOUNT_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_DISCOUNT_PROJECTION
        ADD CONSTRAINT FK_M_DISCOUNT_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END 
GO

------------------------------------------------- PERIOD_SID REFERENCE FROM PERIOD_SID --------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_DISCOUNT_PROJECTION'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_DISCOUNT_PROJECTION_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_DISCOUNT_PROJECTION
        ADD CONSTRAINT FK_M_DISCOUNT_PROJECTION_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END
GO

----------------------------------------------------- M_ACTUAL_DISCOUNT -----------------------------------------

------------------------------------------------- PROJECTION_DETAILS_SID REFERENCE FROM PROJECTION_DETAILS TABLE ------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ACTUAL_DISCOUNT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_ACTUAL_DISCOUNT_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_ACTUAL_DISCOUNT
        ADD CONSTRAINT FK_M_ACTUAL_DISCOUNT_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END
GO

------------------------------------------------- PERIOD_SID REFERENCE FROM PERIOD_SID --------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ACTUAL_DISCOUNT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_ACTUAL_DISCOUNT_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_ACTUAL_DISCOUNT
        ADD CONSTRAINT FK_M_ACTUAL_DISCOUNT_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END
GO

----------------------------------------------------------------------M_SUPPLEMENTAL_DISC_MASTER---------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_SUPPLEMENTAL_DISC_MASTER
        ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END

GO

----------------------------------------------------------------------M_SUPPLEMENTAL_DISC_ACTUALS---------------------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_SUPPLEMENTAL_DISC_ACTUALS
        ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END

GO


IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_SUPPLEMENTAL_DISC_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_SUPPLEMENTAL_DISC_ACTUALS
        ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO
-------------------------------------------------------------------M_SUPPLEMENTAL_DISC_PROJ-----------------------------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_SUPPLEMENTAL_DISC_PROJ
        ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_SUPPLEMENTAL_DISC_PROJ_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_SUPPLEMENTAL_DISC_PROJ
        ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_PROJ_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO 
-----------------------------------------------------------ST_M_SUPPLEMENTAL_DISC_MASTER----------------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SUPPLEMENTAL_DISC_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_SUPPLEMENTAL_DISC_MASTER
        ADD CONSTRAINT FK_ST_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END

GO

-----------------------------------------------------------ST_M_SUPPLEMENTAL_DISC_ACTUALS----------------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SUPPLEMENTAL_DISC_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_SUPPLEMENTAL_DISC_ACTUALS
        ADD CONSTRAINT FK_ST_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SUPPLEMENTAL_DISC_ACTUALS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_SUPPLEMENTAL_DISC_ACTUALS_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_SUPPLEMENTAL_DISC_ACTUALS
        ADD CONSTRAINT FK_ST_M_SUPPLEMENTAL_DISC_ACTUALS_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO
---------------------------------------------------------------ST_M_SUPPLEMENTAL_DISC_PROJ----------------------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SUPPLEMENTAL_DISC_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_SUPPLEMENTAL_DISC_PROJ
        ADD CONSTRAINT FK_ST_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY(PROJECTION_DETAILS_SID) REFERENCES PROJECTION_DETAILS(PROJECTION_DETAILS_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'ST_M_SUPPLEMENTAL_DISC_PROJ'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_ST_M_SUPPLEMENTAL_DISC_PROJ_PERIOD_PERIOD_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE ST_M_SUPPLEMENTAL_DISC_PROJ
        ADD CONSTRAINT FK_ST_M_SUPPLEMENTAL_DISC_PROJ_PERIOD_PERIOD_SID FOREIGN KEY(PERIOD_SID) REFERENCES PERIOD(PERIOD_SID)
  END

GO 

---------------------------------------------------------------M_PARITY_LOOKUP-----------------------------------------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_PARITY_LOOKUP'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_PARITY_LOOKUP_CONTRACT_MASTER_CONTRACT_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_PARITY_LOOKUP
        ADD CONSTRAINT FK_M_PARITY_LOOKUP_CONTRACT_MASTER_CONTRACT_MASTER_SID FOREIGN KEY(CONTRACT_MASTER_SID) REFERENCES CONTRACT_MASTER(CONTRACT_MASTER_SID)
  END

GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'M_PARITY_LOOKUP'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_PARITY_LOOKUP_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE M_PARITY_LOOKUP
        ADD CONSTRAINT FK_M_PARITY_LOOKUP_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO 



IF NOT EXISTS(
SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'M_PARITY_LOOKUP'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_M_PARITY_LOOKUP_CCP_DETAILS_CCP_DETAILS_SID'
                     AND TYPE = 'F')
BEGIN

ALTER TABLE M_PARITY_LOOKUP ADD CONSTRAINT FK_M_PARITY_LOOKUP_CCP_DETAILS_CCP_DETAILS_SID FOREIGN KEY(CCP_DETAILS_SID) REFERENCES CCP_DETAILS(CCP_DETAILS_SID)
END
GO


----------------------CASCADE DELETE-----------------------------

IF EXISTS(SELECT 1
          FROM   SYS.FOREIGN_KEYS
          WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SALES_PROJECTION_MASTER'
                 AND Schema_name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                 AND TYPE = 'F'
                 AND delete_referential_action_desc <> 'CASCADE')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION_MASTER
        DROP CONSTRAINT FK_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID

      ALTER TABLE [M_SALES_PROJECTION_MASTER]
        ADD CONSTRAINT FK_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END

ELSE
  BEGIN
      IF NOT EXISTS(SELECT 1
                    FROM   SYS.FOREIGN_KEYS
                    WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SALES_PROJECTION_MASTER'
                           AND Schema_name(SCHEMA_ID) = 'DBO'
                           AND NAME = 'FK_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                           AND TYPE = 'F')
        ALTER TABLE [M_SALES_PROJECTION_MASTER]
          ADD CONSTRAINT FK_M_SALES_PROJECTION_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
  GO

IF EXISTS(SELECT 1
          FROM   SYS.FOREIGN_KEYS
          WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ACTUAL_SALES'
                 AND Schema_name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_M_ACTUAL_SALES_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                 AND TYPE = 'F'
                 AND delete_referential_action_desc <> 'CASCADE')
  BEGIN
      ALTER TABLE M_ACTUAL_SALES
        DROP CONSTRAINT FK_M_ACTUAL_SALES_PROJECTION_DETAILS_PROJECTION_DETAILS_SID

      ALTER TABLE [M_ACTUAL_SALES]
        ADD CONSTRAINT FK_M_ACTUAL_SALES_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
ELSE
  BEGIN
      IF NOT EXISTS(SELECT 1
                    FROM   SYS.FOREIGN_KEYS
                    WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ACTUAL_SALES'
                           AND Schema_name(SCHEMA_ID) = 'DBO'
                           AND NAME = 'FK_M_ACTUAL_SALES_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                           AND TYPE = 'F')
        ALTER TABLE [M_ACTUAL_SALES]
          ADD CONSTRAINT FK_M_ACTUAL_SALES_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
  GO

IF EXISTS(SELECT 1
          FROM   SYS.FOREIGN_KEYS
          WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SALES_PROJECTION'
                 AND Schema_name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_M_SALES_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                 AND TYPE = 'F'
                 AND delete_referential_action_desc <> 'CASCADE')
  BEGIN
      ALTER TABLE M_SALES_PROJECTION
        DROP CONSTRAINT FK_M_SALES_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID

      ALTER TABLE [M_SALES_PROJECTION]
        ADD CONSTRAINT FK_M_SALES_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
ELSE
  BEGIN
      IF NOT EXISTS(SELECT 1
                    FROM   SYS.FOREIGN_KEYS
                    WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SALES_PROJECTION'
                           AND Schema_name(SCHEMA_ID) = 'DBO'
                           AND NAME = 'FK_M_SALES_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                           AND TYPE = 'F')
        ALTER TABLE [M_SALES_PROJECTION]
          ADD CONSTRAINT FK_M_SALES_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
  GO

IF EXISTS(SELECT 1
          FROM   SYS.FOREIGN_KEYS
          WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ASSUMPTIONS'
                 AND Schema_name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_M_ASSUMPTIONS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                 AND TYPE = 'F'
                 AND delete_referential_action_desc <> 'CASCADE')
  BEGIN
      ALTER TABLE M_ASSUMPTIONS
        DROP CONSTRAINT FK_M_ASSUMPTIONS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID

      ALTER TABLE [M_ASSUMPTIONS]
        ADD CONSTRAINT FK_M_ASSUMPTIONS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
ELSE
  BEGIN
      IF NOT EXISTS(SELECT 1
                    FROM   SYS.FOREIGN_KEYS
                    WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ASSUMPTIONS'
                           AND Schema_name(SCHEMA_ID) = 'DBO'
                           AND NAME = 'FK_M_ASSUMPTIONS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                           AND TYPE = 'F')
        ALTER TABLE [M_ASSUMPTIONS]
          ADD CONSTRAINT FK_M_ASSUMPTIONS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
  GO

IF EXISTS(SELECT 1
          FROM   SYS.FOREIGN_KEYS
          WHERE  Object_name(PARENT_OBJECT_ID) = 'M_DISCOUNT_PROJECTION'
                 AND Schema_name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_M_DISCOUNT_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                 AND TYPE = 'F'
                 AND delete_referential_action_desc <> 'CASCADE')
  BEGIN
      ALTER TABLE M_DISCOUNT_PROJECTION
        DROP CONSTRAINT FK_M_DISCOUNT_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID

      ALTER TABLE [M_DISCOUNT_PROJECTION]
        ADD CONSTRAINT FK_M_DISCOUNT_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
ELSE
  BEGIN
      IF NOT EXISTS(SELECT 1
                    FROM   SYS.FOREIGN_KEYS
                    WHERE  Object_name(PARENT_OBJECT_ID) = 'M_DISCOUNT_PROJECTION'
                           AND Schema_name(SCHEMA_ID) = 'DBO'
                           AND NAME = 'FK_M_DISCOUNT_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                           AND TYPE = 'F')
        ALTER TABLE [M_DISCOUNT_PROJECTION]
          ADD CONSTRAINT FK_M_DISCOUNT_PROJECTION_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
  GO

IF EXISTS(SELECT 1
          FROM   SYS.FOREIGN_KEYS
          WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ACTUAL_DISCOUNT'
                 AND Schema_name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_M_ACTUAL_DISCOUNT_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                 AND TYPE = 'F'
                 AND delete_referential_action_desc <> 'CASCADE')
  BEGIN
      ALTER TABLE M_ACTUAL_DISCOUNT
        DROP CONSTRAINT FK_M_ACTUAL_DISCOUNT_PROJECTION_DETAILS_PROJECTION_DETAILS_SID

      ALTER TABLE [M_ACTUAL_DISCOUNT]
        ADD CONSTRAINT FK_M_ACTUAL_DISCOUNT_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
ELSE
  BEGIN
      IF NOT EXISTS(SELECT 1
                    FROM   SYS.FOREIGN_KEYS
                    WHERE  Object_name(PARENT_OBJECT_ID) = 'M_ACTUAL_DISCOUNT'
                           AND Schema_name(SCHEMA_ID) = 'DBO'
                           AND NAME = 'FK_M_ACTUAL_DISCOUNT_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                           AND TYPE = 'F')
        ALTER TABLE [M_ACTUAL_DISCOUNT]
          ADD CONSTRAINT FK_M_ACTUAL_DISCOUNT_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
  GO

IF EXISTS(SELECT 1
          FROM   SYS.FOREIGN_KEYS
          WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_MASTER'
                 AND Schema_name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                 AND TYPE = 'F'
                 AND delete_referential_action_desc <> 'CASCADE')
  BEGIN
      ALTER TABLE M_SUPPLEMENTAL_DISC_MASTER
        DROP CONSTRAINT FK_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID

      ALTER TABLE [M_SUPPLEMENTAL_DISC_MASTER]
        ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
ELSE
  BEGIN
      IF NOT EXISTS(SELECT 1
                    FROM   SYS.FOREIGN_KEYS
                    WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_MASTER'
                           AND Schema_name(SCHEMA_ID) = 'DBO'
                           AND NAME = 'FK_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                           AND TYPE = 'F')
        ALTER TABLE [M_SUPPLEMENTAL_DISC_MASTER]
          ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_MASTER_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
  GO

IF EXISTS(SELECT 1
          FROM   SYS.FOREIGN_KEYS
          WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_ACTUALS'
                 AND Schema_name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                 AND TYPE = 'F'
                 AND delete_referential_action_desc <> 'CASCADE')
  BEGIN
      ALTER TABLE M_SUPPLEMENTAL_DISC_ACTUALS
        DROP CONSTRAINT FK_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID

      ALTER TABLE [M_SUPPLEMENTAL_DISC_ACTUALS]
        ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
ELSE
  BEGIN
      IF NOT EXISTS(SELECT 1
                    FROM   SYS.FOREIGN_KEYS
                    WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_ACTUALS'
                           AND Schema_name(SCHEMA_ID) = 'DBO'
                           AND NAME = 'FK_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                           AND TYPE = 'F')
        ALTER TABLE [M_SUPPLEMENTAL_DISC_ACTUALS]
          ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_ACTUALS_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
  GO

IF EXISTS(SELECT 1
          FROM   SYS.FOREIGN_KEYS
          WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_PROJ'
                 AND Schema_name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                 AND TYPE = 'F'
                 AND delete_referential_action_desc <> 'CASCADE')
  BEGIN
      ALTER TABLE M_SUPPLEMENTAL_DISC_PROJ
        DROP CONSTRAINT FK_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_PROJECTION_DETAILS_SID

      ALTER TABLE [M_SUPPLEMENTAL_DISC_PROJ]
        ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
ELSE
  BEGIN
      IF NOT EXISTS(SELECT 1
                    FROM   SYS.FOREIGN_KEYS
                    WHERE  Object_name(PARENT_OBJECT_ID) = 'M_SUPPLEMENTAL_DISC_PROJ'
                           AND Schema_name(SCHEMA_ID) = 'DBO'
                           AND NAME = 'FK_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
                           AND TYPE = 'F')
        ALTER TABLE [M_SUPPLEMENTAL_DISC_PROJ]
          ADD CONSTRAINT FK_M_SUPPLEMENTAL_DISC_PROJ_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
  END
  GO

--IF EXISTS(SELECT 1
--          FROM   SYS.FOREIGN_KEYS
--          WHERE  Object_name(PARENT_OBJECT_ID) = 'M_PARITY_LOOKUP'
--                 AND Schema_name(SCHEMA_ID) = 'DBO'
--                 AND NAME = 'FK_M_PARITY_LOOKUP_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
--                 AND TYPE = 'F'
--                 AND delete_referential_action_desc <> 'CASCADE')
--  BEGIN
--      ALTER TABLE M_PARITY_LOOKUP
--        DROP CONSTRAINT FK_M_PARITY_LOOKUP_PROJECTION_DETAILS_PROJECTION_DETAILS_SID

--      ALTER TABLE [M_PARITY_LOOKUP]
--        ADD CONSTRAINT FK_M_PARITY_LOOKUP_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
--  END
--ELSE
--  BEGIN
--      IF NOT EXISTS(SELECT 1
--                    FROM   SYS.FOREIGN_KEYS
--                    WHERE  Object_name(PARENT_OBJECT_ID) = 'M_PARITY_LOOKUP'
--                           AND Schema_name(SCHEMA_ID) = 'DBO'
--                           AND NAME = 'FK_M_PARITY_LOOKUP_PROJECTION_DETAILS_PROJECTION_DETAILS_SID'
--                           AND TYPE = 'F')
--        ALTER TABLE [M_PARITY_LOOKUP]
--          ADD CONSTRAINT FK_M_PARITY_LOOKUP_PROJECTION_DETAILS_PROJECTION_DETAILS_SID FOREIGN KEY([PROJECTION_DETAILS_SID]) REFERENCES PROJECTION_DETAILS([PROJECTION_DETAILS_SID]) ON DELETE CASCADE
--  END
--  GO
