IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO')		
  BEGIN      
       CREATE TABLE [dbo].[ACCRUAL_INBOUND_INTERFACE]
        (
           [ACCRUAL_INBOUND_INTERFACE_ID] [INT] NOT NULL,
           [ACCRUAL_ID]                   [VARCHAR](50) NOT NULL,
           [SALES_MASTER_ID]              [VARCHAR](50) NULL,
           [GL_ACCOUNT]                   [VARCHAR](50) NOT NULL,
           [COMPANY_ID]                   [VARCHAR](50) NOT NULL,
           [COMPANY_NO]                   [VARCHAR](50) NOT NULL,
           [COMP_IDENT_CODE_QUALIFIER]    [VARCHAR](50) NULL,
           [COMPANY_COST_CENTER]          [VARCHAR](50) NOT NULL,
           [ACCOUNT_ID]                   [VARCHAR](50) NOT NULL,
           [ACCOUNT_NO]                   [VARCHAR](50) NULL,
           [ACCOUNT_NAME]                 [VARCHAR](100) NULL,
           [ACCT_IDENT_CODE_QUALIFIER]    [VARCHAR](50) NULL,
           [ITEM_ID]                      [VARCHAR](50) NOT NULL,
           [ITEM_NO]                      [VARCHAR](50) NULL,
           [ITEM_IDENT_CODE_QUALIFIER]    [VARCHAR](50) NULL,
           [CONTRACT_ID]                  [VARCHAR](50) NOT NULL,
           [CONTRACT_NO]                  [VARCHAR](50) NULL,
           [CONTRACT_NAME]                [VARCHAR](100) NULL,
           [BRAND_ID]                     [VARCHAR](50) NULL,
           [CATEGORY_ID]                  [VARCHAR](50) NULL,
           [PROVISION_ID]                 [VARCHAR](50) NOT NULL,
           [ACCRUAL_TYPE]                 [VARCHAR](50) NULL,
           [ACCRUAL_PERIOD_START_DATE]    [DATETIME] NOT NULL,
           [ACCRUAL_PERIOD_END_DATE]      [DATETIME] NOT NULL,
           [AMOUNT]                       [NUMERIC](22, 6) NOT NULL,
           [SUB_LEDGER]                   [VARCHAR](50) NOT NULL,
           [SUB_LEDGER_TYPE]              [VARCHAR](50) NOT NULL,
           [DOCUMENT_TYPE]                [VARCHAR](50) NOT NULL,
           [POSTING_DATE]                 [DATETIME] NULL,
           [GL_DATE]                      [DATETIME] NULL,
           [RECORD_CREATED_DATE]          [DATETIME] NULL,
           [BATCH_ID]                     [VARCHAR](50) NOT NULL,
           [SOURCE]                       [VARCHAR](50) NULL,
           [CREATED_BY]                   [VARCHAR](50) NULL,
           [CREATED_DATE]                 [DATETIME] NULL,
           [MODIFIED_BY]                  [VARCHAR](50) NULL,
           [MODIFIED_DATE]                [DATETIME] NULL,
           [ADD_CHG_DEL_INDICATOR]        [VARCHAR](10) NOT NULL
        )
  END

GO

IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'COMPANY_NAME' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD COMPANY_NAME VARCHAR(100)
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'BUSINESS_UNIT_ID' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD BUSINESS_UNIT_ID VARCHAR(50) NOT NULL
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'BUSINESS_UNIT_NO' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD BUSINESS_UNIT_NO VARCHAR(50) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'BU_IDENT_CODE_QUALIFIER' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD BU_IDENT_CODE_QUALIFIER VARCHAR(50) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'BUSINESS_UNIT_NAME' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD BUSINESS_UNIT_NAME VARCHAR(100) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'ITEM_NAME' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD ITEM_NAME VARCHAR(100) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'BRAND_NAME' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD BRAND_NAME VARCHAR(30) 
  END
GO
IF EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'AMOUNT' AND TABLE_SCHEMA = 'DBO')
    BEGIN
     exec sp_RENAME 'ACCRUAL_INBOUND_INTERFACE.AMOUNT', 'DEDUCTION_AMOUNT' , 'COLUMN';
  END
GO

IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'ACCRUAL_SCHEDULE_TYPE' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD ACCRUAL_SCHEDULE_TYPE VARCHAR(25) 
  END
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'ACCRUAL_PROGRAM_TYPE' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE 
        ADD ACCRUAL_PROGRAM_TYPE VARCHAR(25) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'SALES_AMOUNT' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD SALES_AMOUNT NUMERIC(22,6) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'QUANTITY' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD QUANTITY NUMERIC(22,6) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'ACCRUAL_UDC1' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD ACCRUAL_UDC1 VARCHAR(100) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'ACCRUAL_UDC2' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD ACCRUAL_UDC2 VARCHAR(100) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'ACCRUAL_UDC3' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD ACCRUAL_UDC3 VARCHAR(100) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'ACCRUAL_UDC4' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD ACCRUAL_UDC4 VARCHAR(100) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'ACCRUAL_UDC5' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD ACCRUAL_UDC5 VARCHAR(100) 
  END
GO
IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'ACCRUAL_UDC6' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD ACCRUAL_UDC6 VARCHAR(100) 
  END
GO

IF NOT EXISTS(
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
      WHERE TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE' AND COLUMN_NAME  = 'ACCRUAL_CATEGORY' AND TABLE_SCHEMA = 'DBO')
    BEGIN
                
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ADD ACCRUAL_CATEGORY VARCHAR(25) 
  END
GO


IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                      AND COLUMN_NAME = 'PROVISION_ID'
                      AND TABLE_SCHEMA = 'DBO' )
  BEGIN
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ALTER COLUMN  PROVISION_ID VARCHAR(50) NULL
  END
GO

IF  EXISTS (SELECT 1
               FROM   INFORMATION_SCHEMA.COLUMNS
               WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                      AND COLUMN_NAME = 'ITEM_ID'
                      AND TABLE_SCHEMA = 'DBO' )
  BEGIN
      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ALTER COLUMN  ITEM_ID VARCHAR(50) NULL
  END
GO

----------------------- FOR AGN-801 -------------------
  IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                  AND COLUMN_NAME = 'GL_ACCOUNT' AND IS_NULLABLE = 'NO')
  BEGIN

      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ALTER COLUMN GL_ACCOUNT VARCHAR(50) NULL
  END 
    GO
    
  IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                  AND COLUMN_NAME = 'COMPANY_NO' AND IS_NULLABLE = 'NO')
  BEGIN

      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ALTER COLUMN COMPANY_NO VARCHAR(50) NULL
  END 
    GO
   
  IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                  AND COLUMN_NAME = 'COMPANY_COST_CENTER' AND IS_NULLABLE = 'NO')
  BEGIN

      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ALTER COLUMN COMPANY_COST_CENTER VARCHAR(50) NULL
  END 
    GO
	
	

  IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                  AND COLUMN_NAME = 'CONTRACT_ID' AND IS_NULLABLE = 'NO')
  BEGIN

      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ALTER COLUMN CONTRACT_ID VARCHAR(50) NULL
  END 
    GO
	


  IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                  AND COLUMN_NAME = 'ACCOUNT_ID' AND IS_NULLABLE = 'NO')
  BEGIN

      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ALTER COLUMN ACCOUNT_ID VARCHAR(50) NULL
  END 
    GO
    
  IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                  AND COLUMN_NAME = 'SUB_LEDGER' AND IS_NULLABLE = 'NO')
  BEGIN

      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ALTER COLUMN SUB_LEDGER VARCHAR(50) NULL
  END 
    GO
   

  IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                  AND COLUMN_NAME = 'SUB_LEDGER_TYPE' AND IS_NULLABLE = 'NO')
  BEGIN

      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ALTER COLUMN SUB_LEDGER_TYPE VARCHAR(50) NULL
  END 
    GO
    
  
  IF EXISTS (SELECT 1
           FROM   INFORMATION_SCHEMA.COLUMNS
           WHERE  TABLE_NAME = 'ACCRUAL_INBOUND_INTERFACE'
                  AND COLUMN_NAME = 'DOCUMENT_TYPE' AND IS_NULLABLE = 'NO')
  BEGIN

      ALTER TABLE ACCRUAL_INBOUND_INTERFACE
        ALTER COLUMN DOCUMENT_TYPE VARCHAR(50) NULL
  END 
    GO
