IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'PSTG_UOM_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
BEGIN
	CREATE TABLE [DBO].[PSTG_UOM_INTERFACE](
		[PSTG_UOM_INTERFACE_SID] [BIGINT] IDENTITY(1,1) NOT NULL,
		[FLE_RCR_NMB] [BIGINT] NULL,
		[ITEM_ID] [NVARCHAR](1000) NULL,
		[ITEM_NO] [NVARCHAR](1000) NULL,
		[ITEM_NAME] [NVARCHAR](1000) NULL,
		[PRI_UOM_FCT] [NVARCHAR](1000) NULL,
		[PRI_UOM_CDE] [NVARCHAR](1000) NULL,
		[PRI_UOM_NAME] [NVARCHAR](1000) NULL,
		[SEC_UOM_FCT] [NVARCHAR](1000) NULL,
		[SEC_UOM_CDE] [NVARCHAR](1000) NULL,
		[SEC_UOM_NAME] [NVARCHAR](1000) NULL,
		[CNV_STATUS] [NVARCHAR](1000) NULL,
		[FLE_NME] [NVARCHAR](200) NULL,
		[CREATED_DATE] [DATETIME] NOT NULL,
		[CREATED_BY] [NVARCHAR](50) NOT NULL
	) ON [PRIMARY]
END

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PSTG_UOM_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_PSTG_UOM_INTERFACE_CREATED_DATE')
	BEGIN
		ALTER TABLE [DBO].[PSTG_UOM_INTERFACE] ADD  CONSTRAINT [DF_PSTG_UOM_INTERFACE_CREATED_DATE]  DEFAULT (GETDATE()) FOR [CREATED_DATE]
	END	
GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PSTG_UOM_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_PSTG_UOM_INTERFACE_CREATED_BY')
	BEGIN
		ALTER TABLE [DBO].[PSTG_UOM_INTERFACE] ADD  CONSTRAINT [DF_PSTG_UOM_INTERFACE_CREATED_BY]  DEFAULT ('AGN') FOR [CREATED_BY]
	END
GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'IVLD_PSTG_UOM_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
	BEGIN
		CREATE TABLE [DBO].[IVLD_PSTG_UOM_INTERFACE](
			[IVLD_PSTG_UOM_INTERFACE_SID] [BIGINT] IDENTITY(1,1) NOT NULL,
			[FLE_RCR_NMB] [BIGINT] NULL,
			[ITEM_ID] [NVARCHAR](1000) NULL,
			[ITEM_NO] [NVARCHAR](1000) NULL,
			[ITEM_NAME] [NVARCHAR](1000) NULL,
			[PRI_UOM_FCT] [NVARCHAR](1000) NULL,
			[PRI_UOM_CDE] [NVARCHAR](1000) NULL,
			[PRI_UOM_NAME] [NVARCHAR](1000) NULL,
			[SEC_UOM_FCT] [NVARCHAR](1000) NULL,
			[SEC_UOM_CDE] [NVARCHAR](1000) NULL,
			[SEC_UOM_NAME] [NVARCHAR](1000) NULL,
			[CNV_STATUS] [NVARCHAR](1000) NULL,
			[FLE_NME] [NVARCHAR](200) NULL,
			[PSTG_UOM_INTERFACE_SID] [BIGINT] NULL,
			[CREATED_DATE] [DATETIME] NULL,
			[CREATED_BY] [NVARCHAR](50) NULL,
			[REASON_FOR_FAILURE] [NVARCHAR](1000) NULL,
			[ERROR_CODE] [VARCHAR](10) NULL,
			[ERROR_FIELD] [NVARCHAR](1000) NULL,
			[BATCH_ID] [NVARCHAR](100) NOT NULL,
			[IVLD_INTERFACE_DATE] [DATETIME] NOT NULL
		) ON [PRIMARY]
	END
GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'IVLD_PSTG_UOM_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_IVLD_PSTG_UOM_INTERFACE_IVLD_INTERFACE_DATE')
	BEGIN
		ALTER TABLE [DBO].[IVLD_PSTG_UOM_INTERFACE] ADD  CONSTRAINT [DF_IVLD_PSTG_UOM_INTERFACE_IVLD_INTERFACE_DATE] DEFAULT (GETDATE()) FOR [IVLD_INTERFACE_DATE]
	END
	
GO


IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VLD_PSTG_UOM_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
BEGIN
	CREATE TABLE [DBO].[VLD_PSTG_UOM_INTERFACE](
		[ITEM_UOM_CONVERSION_ID] [NUMERIC](38, 0) NOT NULL,
		[ITEM_ID] [VARCHAR](38) NOT NULL,
		[ITEM_NO] [VARCHAR](50) NULL,
		[ITEM_NAME] [VARCHAR](100) NULL,
		[PRIMARY_UOM_BASELINE_FACTOR] [NUMERIC](22, 6) NOT NULL,
		[PRIMARY_UOM_CODE] [VARCHAR](20) NOT NULL,
		[PRIMARY_UOM_NAME] [VARCHAR](20) NOT NULL,
		[SECONDARY_UOM_CONVERSION_FACTOR] [NUMERIC](22, 6) NOT NULL,
		[SECONDARY_UOM_CODE] [VARCHAR](20) NOT NULL,
		[SECONDARY_UOM_NAME] [VARCHAR](20) NOT NULL,
		[STATUS] [VARCHAR](20) NOT NULL,
		[UPLOAD_DATE] [DATETIME] NOT NULL,
		[MODIFIED_BY] [VARCHAR](50) NULL,
		[MODIFIED_DATE] [DATETIME] NULL,
		[CREATED_BY] [VARCHAR](38) NULL,
		[CREATED_DATE] [DATETIME] NULL,
		[ADD_CHG_DEL_INDICATOR] [VARCHAR](10) NOT NULL,
		[BATCH_ID] [VARCHAR](38) NOT NULL,
		[SOURCE] [VARCHAR](50) NULL,
		[IS_COMPLETE] [CHAR](1) NOT NULL
	) ON [PRIMARY]

END

GO

IF EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VW_UOM_TGT'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
  BEGIN
		DROP TABLE VW_UOM_TGT
  END

GO

IF EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VW_UOM_TGT'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='VIEW')
  BEGIN

		DROP VIEW VW_UOM_TGT
  END

GO

	CREATE VIEW [dbo].[VW_UOM_TGT]
		AS
		SELECT ITEM_UOM_CONVERSION_ID,
		ITEM_ID,
		ITEM_NO,
		ITEM_NAME,
		PRIMARY_UOM_BASELINE_FACTOR,
		PRIMARY_UOM_CODE,
		PRIMARY_UOM_NAME,
		SECONDARY_UOM_CONVERSION_FACTOR,
		SECONDARY_UOM_CODE,
		SECONDARY_UOM_NAME,
		STATUS,
		UPLOAD_DATE,
		MODIFIED_BY,
		MODIFIED_DATE,
		CREATED_BY,
		CREATED_DATE,
		ADD_CHG_DEL_INDICATOR,
		BATCH_ID,
		SOURCE
		FROM VLD_PSTG_UOM_INTERFACE WHERE IS_COMPLETE='Y'

GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'PSTG_CPI_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
BEGIN
	CREATE TABLE [DBO].[PSTG_CPI_INTERFACE](
		[PSTG_CPI_INTERFACE_SID] [BIGINT] IDENTITY(1,1) NOT NULL,
		[INFLATION_NUM] [NVARCHAR](2000) NULL,
		[USERID] [NVARCHAR](2000) NULL,
		[LASTMOD] [NVARCHAR](2000) NULL,
		[FLG_NOTE] [NVARCHAR](2000) NULL,
		[INDTYP_CD] [NVARCHAR](2000) NULL,
		[INFLATION_DT_EFF] [NVARCHAR](2000) NULL,
		[INFLATION_VAL] [NVARCHAR](2000) NULL,
		[INFLATION_FLG_CHG] [NVARCHAR](2000) NULL,
		[STATUS_NUM] [NVARCHAR](2000) NULL,
		[INFLATION_NUM_PRIOR] [NVARCHAR](2000) NULL,
		[REVISION] [NVARCHAR](2000) NULL,
		[INFLATION_FLG_LOCK] [NVARCHAR](2000) NULL,
		[CREATED_DATE] [DATETIME] NOT NULL,
		[CREATED_BY] [NVARCHAR](50) NOT NULL
	) ON [PRIMARY]
END

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PSTG_CPI_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_PSTG_CPI_INTERFACE_CREATED_DATE')
	BEGIN
		ALTER TABLE [DBO].[PSTG_CPI_INTERFACE] ADD  CONSTRAINT [DF_PSTG_CPI_INTERFACE_CREATED_DATE]  DEFAULT (GETDATE()) FOR [CREATED_DATE]
	END	
GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PSTG_CPI_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_PSTG_CPI_INTERFACE_CREATED_BY')
	BEGIN
		ALTER TABLE [DBO].[PSTG_CPI_INTERFACE] ADD  CONSTRAINT [DF_PSTG_CPI_INTERFACE_CREATED_BY]  DEFAULT ('AGN') FOR [CREATED_BY]
	END
GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'IVLD_PSTG_CPI_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
	BEGIN
		CREATE TABLE [DBO].[IVLD_PSTG_CPI_INTERFACE](
			[IVLD_PSTG_CPI_INTERFACE_SID] [BIGINT] IDENTITY(1,1) NOT NULL,
			[INFLATION_NUM] [NVARCHAR](2000) NULL,
			[USERID] [NVARCHAR](2000) NULL,
			[LASTMOD] [NVARCHAR](2000) NULL,
			[FLG_NOTE] [NVARCHAR](2000) NULL,
			[INDTYP_CD] [NVARCHAR](2000) NULL,
			[INFLATION_DT_EFF] [NVARCHAR](2000) NULL,
			[INFLATION_VAL] [NVARCHAR](2000) NULL,
			[INFLATION_FLG_CHG] [NVARCHAR](2000) NULL,
			[STATUS_NUM] [NVARCHAR](2000) NULL,
			[INFLATION_NUM_PRIOR] [NVARCHAR](2000) NULL,
			[REVISION] [NVARCHAR](2000) NULL,
			[INFLATION_FLG_LOCK] [NVARCHAR](2000) NULL,
			[PSTG_CPI_INTERFACE_SID] [BIGINT] NULL,
			[CREATED_DATE] [DATETIME] NULL,
			[CREATED_BY] [NVARCHAR](50) NULL,
			[REASON_FOR_FAILURE] [NVARCHAR](1000) NULL,
			[ERROR_CODE] [VARCHAR](10) NULL,
			[ERROR_FIELD] [NVARCHAR](1000) NULL,
			[BATCH_ID] [NVARCHAR](100) NOT NULL,
			[IVLD_INTERFACE_DATE] [DATETIME] NOT NULL
		) ON [PRIMARY]
	END
GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'IVLD_PSTG_CPI_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_IVLD_PSTG_CPI_INTERFACE_IVLD_INTERFACE_DATE')
	BEGIN
		ALTER TABLE [DBO].[IVLD_PSTG_CPI_INTERFACE] ADD  CONSTRAINT [DF_IVLD_PSTG_CPI_INTERFACE_IVLD_INTERFACE_DATE] DEFAULT (GETDATE()) FOR [IVLD_INTERFACE_DATE]
	END
	
GO


IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VLD_PSTG_CPI_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
BEGIN
	CREATE TABLE [DBO].[VLD_PSTG_CPI_INTERFACE](
		[CPI_INTERFACE_ID] [NUMERIC](38, 0) NOT NULL,
		[INDEX_ID] [NUMERIC](22, 0) NULL,
		[STATUS] [VARCHAR](20) NULL,
		[INDEX_TYPE] [VARCHAR](50) NULL,
		[EFFECTIVE_DATE] [DATE] NULL,
		[INDEX_VALUE] [NUMERIC](22, 6) NULL,
		[SOURCE] [VARCHAR](50) NULL,
		[CREATED_BY] [VARCHAR](50) NULL,
		[CREATED_DATE] [DATE] NULL,
		[MODIFIED_BY] [VARCHAR](50) NULL,
		[MODIFIED_DATE] [DATE] NULL,
		[ADD_CHG_DEL_INDICATOR] [VARCHAR](10) NOT NULL,
		[BATCH_ID] [VARCHAR](38) NOT NULL,
		[IS_COMPLETE] [CHAR](1) NOT NULL
	) ON [PRIMARY]

END

GO

IF EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VW_CPI_TGT'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
  BEGIN
		DROP TABLE VW_CPI_TGT
  END

GO

IF EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VW_CPI_TGT'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='VIEW')
  BEGIN

		DROP VIEW VW_CPI_TGT
  END

GO

	CREATE VIEW [dbo].[VW_CPI_TGT]
		AS
		SELECT  CPI_INTERFACE_ID,
				INDEX_ID,
				STATUS,
				INDEX_TYPE,
				EFFECTIVE_DATE,
				INDEX_VALUE,
				SOURCE,
				CREATED_BY,
				CREATED_DATE,
				MODIFIED_BY,
				MODIFIED_DATE,
				ADD_CHG_DEL_INDICATOR,
				BATCH_ID
		FROM VLD_PSTG_CPI_INTERFACE WHERE IS_COMPLETE='Y'

GO


IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'PSTG_RETURN_RATE_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
BEGIN
	CREATE TABLE [DBO].[PSTG_RETURN_RATE_INTERFACE](
		[PSTG_RETURN_RATE_INTERFACE_SID] [BIGINT] IDENTITY(1,1) NOT NULL,
		[ITEM_ID] [NVARCHAR](1000) NULL,
		[ITEM_NO] [NVARCHAR](1000) NULL,
		[ITEM_NAME] [NVARCHAR](1000) NULL,
		[FORECAST_YEAR] [NVARCHAR](1000) NULL,
		[FORECAST_MONTH] [NVARCHAR](1000) NULL,
		[RATE] [NVARCHAR](1000) NULL,
		[FORECAST_NAME] [NVARCHAR](1000) NULL,
		[FORECAST_VER] [NVARCHAR](1000) NULL,
		[CREATED_DATE] [DATETIME] NOT NULL,
		[CREATED_BY] [NVARCHAR](50) NOT NULL
	) ON [PRIMARY]
END

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PSTG_RETURN_RATE_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_PSTG_RETURN_RATE_INTERFACE_CREATED_DATE')
	BEGIN
		ALTER TABLE [DBO].[PSTG_RETURN_RATE_INTERFACE] ADD  CONSTRAINT [DF_PSTG_RETURN_RATE_INTERFACE_CREATED_DATE]  DEFAULT (GETDATE()) FOR [CREATED_DATE]
	END	
GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PSTG_RETURN_RATE_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_PSTG_RETURN_RATE_INTERFACE_CREATED_BY')
	BEGIN
		ALTER TABLE [DBO].[PSTG_RETURN_RATE_INTERFACE] ADD  CONSTRAINT [DF_PSTG_RETURN_RATE_INTERFACE_CREATED_BY]  DEFAULT ('AGN') FOR [CREATED_BY]
	END
GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'IVLD_PSTG_RETURN_RATE_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
	BEGIN
		CREATE TABLE [DBO].[IVLD_PSTG_RETURN_RATE_INTERFACE](
			[IVLD_PSTG_RETURN_RATE_INTERFACE_SID] [BIGINT] IDENTITY(1,1) NOT NULL,
			[ITEM_ID] [nvarchar](1000) NULL,
			[ITEM_NO] [NVARCHAR](1000) NULL,
			[ITEM_NAME] [NVARCHAR](1000) NULL,
			[FORECAST_YEAR] [NVARCHAR](1000) NULL,
			[FORECAST_MONTH] [NVARCHAR](1000) NULL,
			[RATE] [NVARCHAR](1000) NULL,
			[FORECAST_NAME] [NVARCHAR](1000) NULL,
			[FORECAST_VER] [NVARCHAR](1000) NULL,
			[PSTG_RETURN_RATE_INTERFACE_SID] [BIGINT] NULL,
			[CREATED_DATE] [DATETIME] NULL,
			[CREATED_BY] [NVARCHAR](50) NULL,
			[REASON_FOR_FAILURE] [NVARCHAR](1000) NULL,
			[ERROR_CODE] [VARCHAR](10) NULL,
			[ERROR_FIELD] [NVARCHAR](1000) NULL,
			[BATCH_ID] [NVARCHAR](100) NOT NULL,
			[IVLD_INTERFACE_DATE] [DATETIME] NOT NULL
		) ON [PRIMARY]
	END
GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'IVLD_PSTG_RETURN_RATE_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_IVLD_PSTG_RETURN_RATE_INTERFACE_IVLD_INTERFACE_DATE')
	BEGIN
		ALTER TABLE [DBO].[IVLD_PSTG_RETURN_RATE_INTERFACE] ADD  CONSTRAINT [DF_IVLD_PSTG_RETURN_RATE_INTERFACE_IVLD_INTERFACE_DATE] DEFAULT (GETDATE()) FOR [IVLD_INTERFACE_DATE]
	END
	
GO


IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VLD_PSTG_RETURN_RATE_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
BEGIN
	CREATE TABLE [DBO].[VLD_PSTG_RETURN_RATE_INTERFACE](
		[RETURN_RATE_FORECAST_INTERFACE_ID] [numeric](38, 0) NOT NULL,
		[ITEM_ID] [varchar](38) NOT NULL,
		[ITEM_NO] [varchar](50) NULL,
		[ITEM_NAME] [varchar](100) NULL,
		[FORECAST_YEAR] [varchar](5) NULL,
		[FORECAST_MONTH] [varchar](25) NULL,
		[RATE] [numeric](22, 6) NULL,
		[FORECAST_NAME] [varchar](100) NULL,
		[FORECAST_VER] [varchar](15) NULL,
		[CREATED_BY] [varchar](50) NULL,
		[CREATED_DATE] [datetime] NULL,
		[MODIFIED_BY] [varchar](50) NULL,
		[MODIFIED_DATE] [datetime] NULL,
		[ADD_CHG_DEL_INDICATOR] [varchar](10) NOT NULL,
		[BATCH_ID] [varchar](38) NOT NULL,
		[SOURCE] [varchar](50) NULL,
		[IS_COMPLETE] [char](1) NOT NULL
	) ON [PRIMARY]

END

GO

IF EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VW_RRT_TGT'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
  BEGIN
		DROP TABLE VW_RRT_TGT
  END

GO

IF EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VW_RRT_TGT'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='VIEW')
  BEGIN

		DROP VIEW VW_RRT_TGT
  END

GO

	CREATE VIEW [dbo].[VW_RRT_TGT]
		AS
		SELECT  RETURN_RATE_FORECAST_INTERFACE_ID,
				ITEM_ID,
				ITEM_NO,
				ITEM_NAME,
				FORECAST_YEAR,
				FORECAST_MONTH,
				RATE,
				FORECAST_NAME,
				FORECAST_VER,
				CREATED_BY,
				CREATED_DATE,
				MODIFIED_BY,
				MODIFIED_DATE,
				ADD_CHG_DEL_INDICATOR,
				BATCH_ID,
				SOURCE
		FROM DBO.VLD_PSTG_RETURN_RATE_INTERFACE WHERE IS_COMPLETE='Y'

GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'PSTG_ITEM_PRICING_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
BEGIN
	CREATE TABLE [DBO].[PSTG_ITEM_PRICING_INTERFACE](
		[PSTG_ITEM_PRICING_INTERFACE_SID] [BIGINT] IDENTITY(1,1) NOT NULL,
		[PRICING_TYPE_NUM] [NVARCHAR](1000) NULL,
		[PRICING_TYPE] [NVARCHAR](1000) NULL,
		[PRODUCT_ID] [NVARCHAR](1000) NULL,
		[PROD_DESC] [NVARCHAR](1000) NULL,
		[PROD_UOM_NUM] [NVARCHAR](1000) NULL,
		[PROD_UOM_NAME] [NVARCHAR](1000) NULL,
		[PRICE] [NVARCHAR](1000) NULL,
		[EFFECTIVE_START_DATE] [NVARCHAR](1000) NULL,
		[EFFECTIVE_END_DATE] [NVARCHAR](1000) NULL,
		[PRODUCTION_DATE] [NVARCHAR](1000) NULL,
		[STATUS] [NVARCHAR](1000) NULL,
		[CNV_STATUS_NUM] [NVARCHAR](1000) NULL,
		[PROD_PKG_SIZE] [NVARCHAR](1000) NULL,
		[PROD_UNIT_TYPE] [NVARCHAR](1000) NULL,
		[PROD_UNIT_SIZE] [NVARCHAR](1000) NULL,
		[LAST_MODIFIED_DATE] [NVARCHAR](1000) NULL,
		[GLX_ITM_NO] [NVARCHAR](1000) NULL,
		[CREATED_DATE] [DATETIME] NOT NULL,
		[CREATED_BY] [NVARCHAR](50) NOT NULL
	) ON [PRIMARY]
END

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PSTG_ITEM_PRICING_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_PSTG_ITEM_PRICING_INTERFACE_CREATED_DATE')
	BEGIN
		ALTER TABLE [DBO].[PSTG_ITEM_PRICING_INTERFACE] ADD  CONSTRAINT [DF_PSTG_ITEM_PRICING_INTERFACE_CREATED_DATE]  DEFAULT (GETDATE()) FOR [CREATED_DATE]
	END	
GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PSTG_ITEM_PRICING_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_PSTG_ITEM_PRICING_INTERFACE_CREATED_BY')
	BEGIN
		ALTER TABLE [DBO].[PSTG_ITEM_PRICING_INTERFACE] ADD  CONSTRAINT [DF_PSTG_ITEM_PRICING_INTERFACE_CREATED_BY]  DEFAULT ('AGN') FOR [CREATED_BY]
	END
GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'IVLD_PSTG_ITEM_PRICING_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
	BEGIN
		CREATE TABLE [DBO].[IVLD_PSTG_ITEM_PRICING_INTERFACE](
			[IVLD_PSTG_ITEM_PRICING_INTERFACE_SID] [BIGINT] IDENTITY(1,1) NOT NULL,
			[PRICING_TYPE_NUM] [NVARCHAR](1000) NULL,
			[PRICING_TYPE] [NVARCHAR](1000) NULL,
			[PRODUCT_ID] [NVARCHAR](1000) NULL,
			[PROD_DESC] [NVARCHAR](1000) NULL,
			[PROD_UOM_NUM] [NVARCHAR](1000) NULL,
			[PROD_UOM_NAME] [NVARCHAR](1000) NULL,
			[PRICE] [NVARCHAR](1000) NULL,
			[EFFECTIVE_START_DATE] [NVARCHAR](1000) NULL,
			[EFFECTIVE_END_DATE] [NVARCHAR](1000) NULL,
			[PRODUCTION_DATE] [NVARCHAR](1000) NULL,
			[STATUS] [NVARCHAR](1000) NULL,
			[CNV_STATUS_NUM] [NVARCHAR](1000) NULL,
			[PROD_PKG_SIZE] [NVARCHAR](1000) NULL,
			[PROD_UNIT_TYPE] [NVARCHAR](1000) NULL,
			[PROD_UNIT_SIZE] [NVARCHAR](1000) NULL,
			[LAST_MODIFIED_DATE] [NVARCHAR](1000) NULL,
			[GLX_ITM_NO] [NVARCHAR](1000) NULL,
			[PSTG_ITEM_PRICING_INTERFACE_SID] [BIGINT] NULL,
			[CREATED_DATE] [DATETIME] NULL,
			[CREATED_BY] [NVARCHAR](50) NULL,
			[REASON_FOR_FAILURE] [NVARCHAR](1000) NULL,
			[ERROR_CODE] [VARCHAR](10) NULL,
			[ERROR_FIELD] [NVARCHAR](1000) NULL,
			[BATCH_ID] [NVARCHAR](100) NOT NULL,
			[IVLD_INTERFACE_DATE] [DATETIME] NOT NULL
		) ON [PRIMARY]
	END
GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'IVLD_PSTG_ITEM_PRICING_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_IVLD_PSTG_ITEM_PRICING_INTERFACE_IVLD_INTERFACE_DATE')
	BEGIN
		ALTER TABLE [DBO].[IVLD_PSTG_ITEM_PRICING_INTERFACE] ADD  CONSTRAINT [DF_IVLD_PSTG_ITEM_PRICING_INTERFACE_IVLD_INTERFACE_DATE] DEFAULT (GETDATE()) FOR [IVLD_INTERFACE_DATE]
	END
	
GO


IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VLD_PSTG_ITEM_PRICING_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
BEGIN
	CREATE TABLE [DBO].[VLD_PSTG_ITEM_PRICING_INTERFACE](
		[ITEM_PRICING_INTERFACE_ID] [numeric](38, 0) NOT NULL,
		[ITEM_ID] [varchar](38) NOT NULL,
		[ITEM_NO] [varchar](50) NOT NULL,
		[ITEM_NAME] [varchar](100) NULL,
		[ITEM_UOM] [varchar](20) NOT NULL,
		[PRICING_CODE_QUALIFIER] [varchar](25) NOT NULL,
		[PRICING_CODE_QUALIFIER_NAME] [varchar](100) NULL,
		[ITEM_PRICE] [numeric](20, 6) NOT NULL,
		[PRICING_CODE_STATUS] [varchar](20) NOT NULL,
		[START_DATE] [datetime] NOT NULL,
		[END_DATE] [datetime] NULL,
		[ENTITY_CODE] [varchar](30) NULL,
		[CREATED_BY] [varchar](50) NULL,
		[CREATED_DATE] [datetime] NULL,
		[MODIFIED_BY] [varchar](50) NULL,
		[MODIFIED_DATE] [datetime] NULL,
		[ADD_CHG_DEL_INDICATOR] [varchar](10) NOT NULL,
		[BATCH_ID] [varchar](38) NOT NULL,
		[SOURCE] [varchar](50) NULL,
		[IS_COMPLETE] [char](1) NOT NULL
	) ON [PRIMARY]

END

GO

IF EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VW_PRC_TGT'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
  BEGIN
		DROP TABLE VW_PRC_TGT
  END

GO

IF EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VW_PRC_TGT'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='VIEW')
  BEGIN

		DROP VIEW VW_PRC_TGT
  END

GO

	CREATE VIEW [dbo].[VW_PRC_TGT]
		AS
		SELECT  ITEM_PRICING_INTERFACE_ID,
				ITEM_ID,
				ITEM_NO,
				ITEM_NAME,
				ITEM_UOM,
				PRICING_CODE_QUALIFIER,
				PRICING_CODE_QUALIFIER_NAME,
				ITEM_PRICE,
				PRICING_CODE_STATUS,
				START_DATE,
				END_DATE,
				ENTITY_CODE,
				CREATED_BY,
				CREATED_DATE,
				MODIFIED_BY,
				MODIFIED_DATE,
				ADD_CHG_DEL_INDICATOR,
				BATCH_ID,
				SOURCE
		FROM DBO.VLD_PSTG_ITEM_PRICING_INTERFACE WHERE IS_COMPLETE='Y'

GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'PSTG_ACCRUAL_ACTUAL_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
BEGIN
	CREATE TABLE [DBO].[PSTG_ACCRUAL_ACTUAL_INTERFACE](
		[PSTG_ACCRUAL_ACTUAL_INTERFACE_SID] [BIGINT] IDENTITY(1,1) NOT NULL,
		[ACCRUAL_ID] [NVARCHAR](1000) NULL,
		[SALES_MASTER_ID] [NVARCHAR](1000) NULL,
		[GL_ACCOUNT] [NVARCHAR](1000) NULL,
		[COMPANY_ID] [NVARCHAR](1000) NULL,
		[COMPANY_NO] [NVARCHAR](1000) NULL,
		[COMP_IDENT_CODE_QUALIFIER] [NVARCHAR](1000) NULL,
		[COMPANY_NAME] [NVARCHAR](1000) NULL,
		[BUSINESS_UNIT_ID] [NVARCHAR](1000) NULL,
		[BUSINESS_UNIT_NO] [NVARCHAR](1000) NULL,
		[BU_IDENT_CODE_QUALIFIER] [NVARCHAR](1000) NULL,
		[BUSINESS_UNIT_NAME] [NVARCHAR](1000) NULL,
		[COMPANY_COST_CENTER] [NVARCHAR](1000) NULL,
		[ACCOUNT_ID] [NVARCHAR](1000) NULL,
		[ACCOUNT_NO] [NVARCHAR](1000) NULL,
		[ACCOUNT_NAME] [NVARCHAR](1000) NULL,
		[ACCT_IDENT_CODE_QUALIFIER] [NVARCHAR](1000) NULL,
		[ITEM_ID] [NVARCHAR](1000) NULL,
		[ITEM_NO] [NVARCHAR](1000) NULL,
		[ITEM_IDENT_CODE_QUALIFIER] [NVARCHAR](1000) NULL,
		[ITEM_NAME] [NVARCHAR](1000) NULL,
		[CONTRACT_ID] [NVARCHAR](1000) NULL,
		[CONTRACT_NO] [NVARCHAR](1000) NULL,
		[CONTRACT_NAME] [NVARCHAR](1000) NULL,
		[BRAND_ID] [NVARCHAR](1000) NULL,
		[BRAND_NAME] [NVARCHAR](1000) NULL,
		[CATEGORY_ID] [NVARCHAR](1000) NULL,
		[PROVISION_ID] [NVARCHAR](1000) NULL,
		[ACCRUAL_TYPE] [NVARCHAR](1000) NULL,
		[ACCRUAL_PERIOD_START_DATE] [NVARCHAR](1000) NULL,
		[ACCRUAL_PERIOD_END_DATE] [NVARCHAR](1000) NULL,
		[DEDUCTION_AMOUNT] [NVARCHAR](1000) NULL,
		[SUB_LEDGER] [NVARCHAR](1000) NULL,
		[SUB_LEDGER_TYPE] [NVARCHAR](1000) NULL,
		[DOCUMENT_TYPE] [NVARCHAR](1000) NULL,
		[POSTING_DATE] [NVARCHAR](1000) NULL,
		[GL_DATE] [NVARCHAR](1000) NULL,
		[RECORD_CREATED_DATE] [NVARCHAR](1000) NULL,
		[BATCH_ID] [NVARCHAR](1000) NULL,
		[SOURCE] [NVARCHAR](1000) NULL,
		[CREATED_BY] [NVARCHAR](1000) NULL,
		[CREATED_DATE] [NVARCHAR](1000) NULL,
		[MODIFIED_BY] [NVARCHAR](1000) NULL,
		[MODIFIED_DATE] [NVARCHAR](1000) NULL,
		[ADD_CHG_DEL_INDICATOR] [NVARCHAR](1000) NULL,
		[ACCRUAL_CATEGORY] [NVARCHAR](1000) NULL,
		[ACCRUAL_SCHEDULE_TYPE] [NVARCHAR](1000) NULL,
		[ACCRUAL_PROGRAM_TYPE] [NVARCHAR](1000) NULL,
		[SALES_AMOUNT] [NVARCHAR](1000) NULL,
		[QUANTITY] [NVARCHAR](1000) NULL,
		[ACCRUAL_UDC1] [NVARCHAR](1000) NULL,
		[ACCRUAL_UDC2] [NVARCHAR](1000) NULL,
		[ACCRUAL_UDC3] [NVARCHAR](1000) NULL,
		[ACCRUAL_UDC4] [NVARCHAR](1000) NULL,
		[ACCRUAL_UDC5] [NVARCHAR](1000) NULL,
		[ACCRUAL_UDC6] [NVARCHAR](1000) NULL
	) ON [PRIMARY]
END

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PSTG_ACCRUAL_ACTUAL_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_PSTG_ACCRUAL_ACTUAL_INTERFACE_CREATED_DATE')
	BEGIN
		ALTER TABLE [DBO].[PSTG_ACCRUAL_ACTUAL_INTERFACE] ADD  CONSTRAINT [DF_PSTG_ACCRUAL_ACTUAL_INTERFACE_CREATED_DATE]  DEFAULT (GETDATE()) FOR [CREATED_DATE]
	END	
GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PSTG_ACCRUAL_ACTUAL_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_PSTG_ACCRUAL_ACTUAL_INTERFACE_CREATED_BY')
	BEGIN
		ALTER TABLE [DBO].[PSTG_ACCRUAL_ACTUAL_INTERFACE] ADD  CONSTRAINT [DF_PSTG_ACCRUAL_ACTUAL_INTERFACE_CREATED_BY]  DEFAULT ('AGN') FOR [CREATED_BY]
	END
GO

IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'IVLD_PSTG_ACCRUAL_ACTUAL_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
	BEGIN
		CREATE TABLE [DBO].[IVLD_PSTG_ACCRUAL_ACTUAL_INTERFACE](
			[IVLD_PSTG_ACCRUAL_ACTUAL_INTERFACE_SID] [bigint] IDENTITY(1,1) NOT NULL,
			[ACCRUAL_ID] [nvarchar](1000) NULL,
			[SALES_MASTER_ID] [nvarchar](1000) NULL,
			[GL_ACCOUNT] [nvarchar](1000) NULL,
			[COMPANY_ID] [nvarchar](1000) NULL,
			[COMPANY_NO] [nvarchar](1000) NULL,
			[COMP_IDENT_CODE_QUALIFIER] [nvarchar](1000) NULL,
			[COMPANY_NAME] [nvarchar](1000) NULL,
			[BUSINESS_UNIT_ID] [nvarchar](1000) NULL,
			[BUSINESS_UNIT_NO] [nvarchar](1000) NULL,
			[BU_IDENT_CODE_QUALIFIER] [nvarchar](1000) NULL,
			[BUSINESS_UNIT_NAME] [nvarchar](1000) NULL,
			[COMPANY_COST_CENTER] [nvarchar](1000) NULL,
			[ACCOUNT_ID] [nvarchar](1000) NULL,
			[ACCOUNT_NO] [nvarchar](1000) NULL,
			[ACCOUNT_NAME] [nvarchar](1000) NULL,
			[ACCT_IDENT_CODE_QUALIFIER] [nvarchar](1000) NULL,
			[ITEM_ID] [nvarchar](1000) NULL,
			[ITEM_NO] [nvarchar](1000) NULL,
			[ITEM_IDENT_CODE_QUALIFIER] [nvarchar](1000) NULL,
			[ITEM_NAME] [nvarchar](1000) NULL,
			[CONTRACT_ID] [nvarchar](1000) NULL,
			[CONTRACT_NO] [nvarchar](1000) NULL,
			[CONTRACT_NAME] [nvarchar](1000) NULL,
			[BRAND_ID] [nvarchar](1000) NULL,
			[BRAND_NAME] [nvarchar](1000) NULL,
			[CATEGORY_ID] [nvarchar](1000) NULL,
			[PROVISION_ID] [nvarchar](1000) NULL,
			[ACCRUAL_TYPE] [nvarchar](1000) NULL,
			[ACCRUAL_PERIOD_START_DATE] [nvarchar](1000) NULL,
			[ACCRUAL_PERIOD_END_DATE] [nvarchar](1000) NULL,
			[DEDUCTION_AMOUNT] [nvarchar](1000) NULL,
			[SUB_LEDGER] [nvarchar](1000) NULL,
			[SUB_LEDGER_TYPE] [nvarchar](1000) NULL,
			[DOCUMENT_TYPE] [nvarchar](1000) NULL,
			[POSTING_DATE] [nvarchar](1000) NULL,
			[GL_DATE] [nvarchar](1000) NULL,
			[RECORD_CREATED_DATE] [nvarchar](1000) NULL,
			[SOURCE] [nvarchar](1000) NULL,
			[CREATED_BY] [nvarchar](1000) NULL,
			[CREATED_DATE] [nvarchar](1000) NULL,
			[MODIFIED_BY] [nvarchar](1000) NULL,
			[MODIFIED_DATE] [nvarchar](1000) NULL,
			[ADD_CHG_DEL_INDICATOR] [nvarchar](1000) NULL,
			[ACCRUAL_CATEGORY] [nvarchar](1000) NULL,
			[ACCRUAL_SCHEDULE_TYPE] [nvarchar](1000) NULL,
			[ACCRUAL_PROGRAM_TYPE] [nvarchar](1000) NULL,
			[SALES_AMOUNT] [nvarchar](1000) NULL,
			[QUANTITY] [nvarchar](1000) NULL,
			[ACCRUAL_UDC1] [nvarchar](1000) NULL,
			[ACCRUAL_UDC2] [nvarchar](1000) NULL,
			[ACCRUAL_UDC3] [nvarchar](1000) NULL,
			[ACCRUAL_UDC4] [nvarchar](1000) NULL,
			[ACCRUAL_UDC5] [nvarchar](1000) NULL,
			[ACCRUAL_UDC6] [nvarchar](1000) NULL,
			[PSTG_ACCRUAL_ACTUAL_INTERFACE_SID] [BIGINT] NULL,
			[REASON_FOR_FAILURE] [NVARCHAR](1000) NULL,
			[ERROR_CODE] [VARCHAR](10) NULL,
			[ERROR_FIELD] [NVARCHAR](1000) NULL,
			[BATCH_ID] [NVARCHAR](100) NOT NULL,
			[IVLD_INTERFACE_DATE] [DATETIME] NOT NULL
		) ON [PRIMARY]
	END
GO

IF NOT EXISTS (SELECT 1
               FROM   SYS.DEFAULT_CONSTRAINTS
               WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'IVLD_PSTG_ACCRUAL_ACTUAL_INTERFACE'
                      AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                      AND NAME = 'DF_IVLD_PSTG_ACCRUAL_ACTUAL_INTERFACE_IVLD_INTERFACE_DATE')
	BEGIN
		ALTER TABLE [DBO].[IVLD_PSTG_ACCRUAL_ACTUAL_INTERFACE] ADD  CONSTRAINT [DF_IVLD_PSTG_ACCRUAL_ACTUAL_INTERFACE_IVLD_INTERFACE_DATE] DEFAULT (GETDATE()) FOR [IVLD_INTERFACE_DATE]
	END
	
GO


IF NOT EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VLD_PSTG_ACCRUAL_ACTUAL_INTERFACE'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
BEGIN
	CREATE TABLE [DBO].[VLD_PSTG_ACCRUAL_ACTUAL_INTERFACE](
		[ACCRUAL_INBOUND_INTERFACE_ID] [int] NOT NULL,
		[ACCRUAL_ID] [varchar](50) NOT NULL,
		[SALES_MASTER_ID] [varchar](50) NULL,
		[GL_ACCOUNT] [varchar](50) NULL,
		[COMPANY_ID] [varchar](50) NOT NULL,
		[COMPANY_NO] [varchar](50) NULL,
		[COMP_IDENT_CODE_QUALIFIER] [varchar](50) NULL,
		[COMPANY_COST_CENTER] [varchar](50) NULL,
		[ACCOUNT_ID] [varchar](50) NULL,
		[ACCOUNT_NO] [varchar](50) NULL,
		[ACCOUNT_NAME] [varchar](100) NULL,
		[ACCT_IDENT_CODE_QUALIFIER] [varchar](50) NULL,
		[ITEM_ID] [varchar](50) NULL,
		[ITEM_NO] [varchar](50) NULL,
		[ITEM_IDENT_CODE_QUALIFIER] [varchar](50) NULL,
		[CONTRACT_ID] [varchar](50) NULL,
		[CONTRACT_NO] [varchar](50) NULL,
		[CONTRACT_NAME] [varchar](100) NULL,
		[BRAND_ID] [varchar](50) NULL,
		[CATEGORY_ID] [varchar](50) NULL,
		[PROVISION_ID] [varchar](50) NULL,
		[ACCRUAL_TYPE] [varchar](50) NULL,
		[ACCRUAL_PERIOD_START_DATE] [datetime] NOT NULL,
		[ACCRUAL_PERIOD_END_DATE] [datetime] NOT NULL,
		[DEDUCTION_AMOUNT] [numeric](22, 6) NOT NULL,
		[SUB_LEDGER] [varchar](50) NULL,
		[SUB_LEDGER_TYPE] [varchar](50) NULL,
		[DOCUMENT_TYPE] [varchar](50) NULL,
		[POSTING_DATE] [datetime] NULL,
		[GL_DATE] [datetime] NULL,
		[RECORD_CREATED_DATE] [datetime] NULL,
		[BATCH_ID] [varchar](50) NOT NULL,
		[SOURCE] [varchar](50) NULL,
		[CREATED_BY] [varchar](50) NULL,
		[CREATED_DATE] [datetime] NULL,
		[MODIFIED_BY] [varchar](50) NULL,
		[MODIFIED_DATE] [datetime] NULL,
		[ADD_CHG_DEL_INDICATOR] [varchar](10) NOT NULL,
		[COMPANY_NAME] [varchar](100) NULL,
		[BUSINESS_UNIT_ID] [varchar](50) NOT NULL,
		[BUSINESS_UNIT_NO] [varchar](50) NULL,
		[BU_IDENT_CODE_QUALIFIER] [varchar](50) NULL,
		[BUSINESS_UNIT_NAME] [varchar](100) NULL,
		[ITEM_NAME] [varchar](100) NULL,
		[BRAND_NAME] [varchar](30) NULL,
		[ACCRUAL_SCHEDULE_TYPE] [varchar](25) NULL,
		[ACCRUAL_PROGRAM_TYPE] [varchar](25) NULL,
		[SALES_AMOUNT] [numeric](22, 6) NULL,
		[QUANTITY] [numeric](22, 6) NULL,
		[ACCRUAL_UDC1] [varchar](100) NULL,
		[ACCRUAL_UDC2] [varchar](100) NULL,
		[ACCRUAL_UDC3] [varchar](100) NULL,
		[ACCRUAL_UDC4] [varchar](100) NULL,
		[ACCRUAL_UDC5] [varchar](100) NULL,
		[ACCRUAL_UDC6] [varchar](100) NULL,
		[ACCRUAL_CATEGORY] [varchar](25) NULL,
		[IS_COMPLETE] [char](1) NOT NULL
	) ON [PRIMARY]

END

GO

IF EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VW_ACR_ACT_TGT'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='BASE TABLE')
  BEGIN
		DROP TABLE VW_ACR_ACT_TGT
  END

GO

IF EXISTS (SELECT 'X'
               FROM   INFORMATION_SCHEMA.TABLES
               WHERE  TABLE_NAME = 'VW_ACR_ACT_TGT'
                      AND TABLE_SCHEMA = 'DBO'
					  AND TABLE_TYPE='VIEW')
  BEGIN

		DROP VIEW VW_ACR_ACT_TGT
  END

GO

	CREATE VIEW [dbo].[VW_ACR_ACT_TGT]
		AS
		SELECT  ACCRUAL_INBOUND_INTERFACE_ID,
				ACCRUAL_ID,
				SALES_MASTER_ID,
				GL_ACCOUNT,
				COMPANY_ID,
				COMPANY_NO,
				COMP_IDENT_CODE_QUALIFIER,
				COMPANY_COST_CENTER,
				ACCOUNT_ID,
				ACCOUNT_NO,
				ACCOUNT_NAME,
				ACCT_IDENT_CODE_QUALIFIER,
				ITEM_ID,
				ITEM_NO,
				ITEM_IDENT_CODE_QUALIFIER,
				CONTRACT_ID,
				CONTRACT_NO,
				CONTRACT_NAME,
				BRAND_ID,
				CATEGORY_ID,
				PROVISION_ID,
				ACCRUAL_TYPE,
				ACCRUAL_PERIOD_START_DATE,
				ACCRUAL_PERIOD_END_DATE,
				DEDUCTION_AMOUNT,
				SUB_LEDGER,
				SUB_LEDGER_TYPE,
				DOCUMENT_TYPE,
				POSTING_DATE,
				GL_DATE,
				RECORD_CREATED_DATE,
				BATCH_ID,
				SOURCE,
				CREATED_BY,
				CREATED_DATE,
				MODIFIED_BY,
				MODIFIED_DATE,
				ADD_CHG_DEL_INDICATOR,
				COMPANY_NAME,
				BUSINESS_UNIT_ID,
				BUSINESS_UNIT_NO,
				BU_IDENT_CODE_QUALIFIER,
				BUSINESS_UNIT_NAME,
				ITEM_NAME,
				BRAND_NAME,
				ACCRUAL_SCHEDULE_TYPE,
				ACCRUAL_PROGRAM_TYPE,
				SALES_AMOUNT,
				QUANTITY,
				ACCRUAL_UDC1,
				ACCRUAL_UDC2,
				ACCRUAL_UDC3,
				ACCRUAL_UDC4,
				ACCRUAL_UDC5,
				ACCRUAL_UDC6,
				ACCRUAL_CATEGORY
		FROM DBO.VLD_PSTG_ACCRUAL_ACTUAL_INTERFACE WHERE IS_COMPLETE='Y'

GO