/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.stpl.app.parttwo.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VwIvldAdjDemandForeActual service. Represents a row in the &quot;VW_IVLD_ADJ_DEMAND_FORE_ACTUAL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stpl.app.parttwo.model.impl.VwIvldAdjDemandForeActualModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stpl.app.parttwo.model.impl.VwIvldAdjDemandForeActualImpl}.
 * </p>
 *
 * @author
 * @see VwIvldAdjDemandForeActual
 * @see com.stpl.app.parttwo.model.impl.VwIvldAdjDemandForeActualImpl
 * @see com.stpl.app.parttwo.model.impl.VwIvldAdjDemandForeActualModelImpl
 * @generated
 */
@ProviderType
public interface VwIvldAdjDemandForeActualModel extends BaseModel<VwIvldAdjDemandForeActual> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vw ivld adj demand fore actual model instance should use the {@link VwIvldAdjDemandForeActual} interface instead.
	 */

	/**
	 * Returns the primary key of this vw ivld adj demand fore actual.
	 *
	 * @return the primary key of this vw ivld adj demand fore actual
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this vw ivld adj demand fore actual.
	 *
	 * @param primaryKey the primary key of this vw ivld adj demand fore actual
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the forecast version of this vw ivld adj demand fore actual.
	 *
	 * @return the forecast version of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getForecastVersion();

	/**
	 * Sets the forecast version of this vw ivld adj demand fore actual.
	 *
	 * @param forecastVersion the forecast version of this vw ivld adj demand fore actual
	 */
	public void setForecastVersion(String forecastVersion);

	/**
	 * Returns the gross units of this vw ivld adj demand fore actual.
	 *
	 * @return the gross units of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getGrossUnits();

	/**
	 * Sets the gross units of this vw ivld adj demand fore actual.
	 *
	 * @param grossUnits the gross units of this vw ivld adj demand fore actual
	 */
	public void setGrossUnits(String grossUnits);

	/**
	 * Returns the business unit no of this vw ivld adj demand fore actual.
	 *
	 * @return the business unit no of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getBusinessUnitNo();

	/**
	 * Sets the business unit no of this vw ivld adj demand fore actual.
	 *
	 * @param businessUnitNo the business unit no of this vw ivld adj demand fore actual
	 */
	public void setBusinessUnitNo(String businessUnitNo);

	/**
	 * Returns the year of this vw ivld adj demand fore actual.
	 *
	 * @return the year of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getYear();

	/**
	 * Sets the year of this vw ivld adj demand fore actual.
	 *
	 * @param year the year of this vw ivld adj demand fore actual
	 */
	public void setYear(String year);

	/**
	 * Returns the item ID of this vw ivld adj demand fore actual.
	 *
	 * @return the item ID of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getItemId();

	/**
	 * Sets the item ID of this vw ivld adj demand fore actual.
	 *
	 * @param itemId the item ID of this vw ivld adj demand fore actual
	 */
	public void setItemId(String itemId);

	/**
	 * Returns the brand name of this vw ivld adj demand fore actual.
	 *
	 * @return the brand name of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getBrandName();

	/**
	 * Sets the brand name of this vw ivld adj demand fore actual.
	 *
	 * @param brandName the brand name of this vw ivld adj demand fore actual
	 */
	public void setBrandName(String brandName);

	/**
	 * Returns the modified date of this vw ivld adj demand fore actual.
	 *
	 * @return the modified date of this vw ivld adj demand fore actual
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vw ivld adj demand fore actual.
	 *
	 * @param modifiedDate the modified date of this vw ivld adj demand fore actual
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the organization key of this vw ivld adj demand fore actual.
	 *
	 * @return the organization key of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getOrganizationKey();

	/**
	 * Sets the organization key of this vw ivld adj demand fore actual.
	 *
	 * @param organizationKey the organization key of this vw ivld adj demand fore actual
	 */
	public void setOrganizationKey(String organizationKey);

	/**
	 * Returns the created date of this vw ivld adj demand fore actual.
	 *
	 * @return the created date of this vw ivld adj demand fore actual
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vw ivld adj demand fore actual.
	 *
	 * @param createdDate the created date of this vw ivld adj demand fore actual
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this vw ivld adj demand fore actual.
	 *
	 * @return the created by of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this vw ivld adj demand fore actual.
	 *
	 * @param createdBy the created by of this vw ivld adj demand fore actual
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the source of this vw ivld adj demand fore actual.
	 *
	 * @return the source of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getSource();

	/**
	 * Sets the source of this vw ivld adj demand fore actual.
	 *
	 * @param source the source of this vw ivld adj demand fore actual
	 */
	public void setSource(String source);

	/**
	 * Returns the market share ratio of this vw ivld adj demand fore actual.
	 *
	 * @return the market share ratio of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getMarketShareRatio();

	/**
	 * Sets the market share ratio of this vw ivld adj demand fore actual.
	 *
	 * @param marketShareRatio the market share ratio of this vw ivld adj demand fore actual
	 */
	public void setMarketShareRatio(String marketShareRatio);

	/**
	 * Returns the business unit name of this vw ivld adj demand fore actual.
	 *
	 * @return the business unit name of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getBusinessUnitName();

	/**
	 * Sets the business unit name of this vw ivld adj demand fore actual.
	 *
	 * @param businessUnitName the business unit name of this vw ivld adj demand fore actual
	 */
	public void setBusinessUnitName(String businessUnitName);

	/**
	 * Returns the add chg del indicator of this vw ivld adj demand fore actual.
	 *
	 * @return the add chg del indicator of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getAddChgDelIndicator();

	/**
	 * Sets the add chg del indicator of this vw ivld adj demand fore actual.
	 *
	 * @param addChgDelIndicator the add chg del indicator of this vw ivld adj demand fore actual
	 */
	public void setAddChgDelIndicator(String addChgDelIndicator);

	/**
	 * Returns the item identifier of this vw ivld adj demand fore actual.
	 *
	 * @return the item identifier of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getItemIdentifier();

	/**
	 * Sets the item identifier of this vw ivld adj demand fore actual.
	 *
	 * @param itemIdentifier the item identifier of this vw ivld adj demand fore actual
	 */
	public void setItemIdentifier(String itemIdentifier);

	/**
	 * Returns the error code of this vw ivld adj demand fore actual.
	 *
	 * @return the error code of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getErrorCode();

	/**
	 * Sets the error code of this vw ivld adj demand fore actual.
	 *
	 * @param errorCode the error code of this vw ivld adj demand fore actual
	 */
	public void setErrorCode(String errorCode);

	/**
	 * Returns the modified by of this vw ivld adj demand fore actual.
	 *
	 * @return the modified by of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this vw ivld adj demand fore actual.
	 *
	 * @param modifiedBy the modified by of this vw ivld adj demand fore actual
	 */
	public void setModifiedBy(String modifiedBy);

	/**
	 * Returns the market share units of this vw ivld adj demand fore actual.
	 *
	 * @return the market share units of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getMarketShareUnits();

	/**
	 * Sets the market share units of this vw ivld adj demand fore actual.
	 *
	 * @param marketShareUnits the market share units of this vw ivld adj demand fore actual
	 */
	public void setMarketShareUnits(String marketShareUnits);

	/**
	 * Returns the month of this vw ivld adj demand fore actual.
	 *
	 * @return the month of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getMonth();

	/**
	 * Sets the month of this vw ivld adj demand fore actual.
	 *
	 * @param month the month of this vw ivld adj demand fore actual
	 */
	public void setMonth(String month);

	/**
	 * Returns the inventory unit change of this vw ivld adj demand fore actual.
	 *
	 * @return the inventory unit change of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getInventoryUnitChange();

	/**
	 * Sets the inventory unit change of this vw ivld adj demand fore actual.
	 *
	 * @param inventoryUnitChange the inventory unit change of this vw ivld adj demand fore actual
	 */
	public void setInventoryUnitChange(String inventoryUnitChange);

	/**
	 * Returns the reprocessed flag of this vw ivld adj demand fore actual.
	 *
	 * @return the reprocessed flag of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getReprocessedFlag();

	/**
	 * Sets the reprocessed flag of this vw ivld adj demand fore actual.
	 *
	 * @param reprocessedFlag the reprocessed flag of this vw ivld adj demand fore actual
	 */
	public void setReprocessedFlag(String reprocessedFlag);

	/**
	 * Returns the uncaptured units ratio of this vw ivld adj demand fore actual.
	 *
	 * @return the uncaptured units ratio of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getUncapturedUnitsRatio();

	/**
	 * Sets the uncaptured units ratio of this vw ivld adj demand fore actual.
	 *
	 * @param uncapturedUnitsRatio the uncaptured units ratio of this vw ivld adj demand fore actual
	 */
	public void setUncapturedUnitsRatio(String uncapturedUnitsRatio);

	/**
	 * Returns the reason for failure of this vw ivld adj demand fore actual.
	 *
	 * @return the reason for failure of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getReasonForFailure();

	/**
	 * Sets the reason for failure of this vw ivld adj demand fore actual.
	 *
	 * @param reasonForFailure the reason for failure of this vw ivld adj demand fore actual
	 */
	public void setReasonForFailure(String reasonForFailure);

	/**
	 * Returns the adjusted demand forecast intf ID of this vw ivld adj demand fore actual.
	 *
	 * @return the adjusted demand forecast intf ID of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getAdjustedDemandForecastIntfId();

	/**
	 * Sets the adjusted demand forecast intf ID of this vw ivld adj demand fore actual.
	 *
	 * @param adjustedDemandForecastIntfId the adjusted demand forecast intf ID of this vw ivld adj demand fore actual
	 */
	public void setAdjustedDemandForecastIntfId(
		String adjustedDemandForecastIntfId);

	/**
	 * Returns the country of this vw ivld adj demand fore actual.
	 *
	 * @return the country of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this vw ivld adj demand fore actual.
	 *
	 * @param country the country of this vw ivld adj demand fore actual
	 */
	public void setCountry(String country);

	/**
	 * Returns the forecast type of this vw ivld adj demand fore actual.
	 *
	 * @return the forecast type of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getForecastType();

	/**
	 * Sets the forecast type of this vw ivld adj demand fore actual.
	 *
	 * @param forecastType the forecast type of this vw ivld adj demand fore actual
	 */
	public void setForecastType(String forecastType);

	/**
	 * Returns the total adjusted demand units of this vw ivld adj demand fore actual.
	 *
	 * @return the total adjusted demand units of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getTotalAdjustedDemandUnits();

	/**
	 * Sets the total adjusted demand units of this vw ivld adj demand fore actual.
	 *
	 * @param totalAdjustedDemandUnits the total adjusted demand units of this vw ivld adj demand fore actual
	 */
	public void setTotalAdjustedDemandUnits(String totalAdjustedDemandUnits);

	/**
	 * Returns the brand ID of this vw ivld adj demand fore actual.
	 *
	 * @return the brand ID of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getBrandId();

	/**
	 * Sets the brand ID of this vw ivld adj demand fore actual.
	 *
	 * @param brandId the brand ID of this vw ivld adj demand fore actual
	 */
	public void setBrandId(String brandId);

	/**
	 * Returns the is forecast of this vw ivld adj demand fore actual.
	 *
	 * @return the is forecast of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getIsForecast();

	/**
	 * Sets the is forecast of this vw ivld adj demand fore actual.
	 *
	 * @param isForecast the is forecast of this vw ivld adj demand fore actual
	 */
	public void setIsForecast(String isForecast);

	/**
	 * Returns the total adjusted demand amount of this vw ivld adj demand fore actual.
	 *
	 * @return the total adjusted demand amount of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getTotalAdjustedDemandAmount();

	/**
	 * Sets the total adjusted demand amount of this vw ivld adj demand fore actual.
	 *
	 * @param totalAdjustedDemandAmount the total adjusted demand amount of this vw ivld adj demand fore actual
	 */
	public void setTotalAdjustedDemandAmount(String totalAdjustedDemandAmount);

	/**
	 * Returns the uncaptured units of this vw ivld adj demand fore actual.
	 *
	 * @return the uncaptured units of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getUncapturedUnits();

	/**
	 * Sets the uncaptured units of this vw ivld adj demand fore actual.
	 *
	 * @param uncapturedUnits the uncaptured units of this vw ivld adj demand fore actual
	 */
	public void setUncapturedUnits(String uncapturedUnits);

	/**
	 * Returns the gross price of this vw ivld adj demand fore actual.
	 *
	 * @return the gross price of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getGrossPrice();

	/**
	 * Sets the gross price of this vw ivld adj demand fore actual.
	 *
	 * @param grossPrice the gross price of this vw ivld adj demand fore actual
	 */
	public void setGrossPrice(String grossPrice);

	/**
	 * Returns the gross amount of this vw ivld adj demand fore actual.
	 *
	 * @return the gross amount of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getGrossAmount();

	/**
	 * Sets the gross amount of this vw ivld adj demand fore actual.
	 *
	 * @param grossAmount the gross amount of this vw ivld adj demand fore actual
	 */
	public void setGrossAmount(String grossAmount);

	/**
	 * Returns the item identifier code qualifier of this vw ivld adj demand fore actual.
	 *
	 * @return the item identifier code qualifier of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getItemIdentifierCodeQualifier();

	/**
	 * Sets the item identifier code qualifier of this vw ivld adj demand fore actual.
	 *
	 * @param itemIdentifierCodeQualifier the item identifier code qualifier of this vw ivld adj demand fore actual
	 */
	public void setItemIdentifierCodeQualifier(
		String itemIdentifierCodeQualifier);

	/**
	 * Returns the batch ID of this vw ivld adj demand fore actual.
	 *
	 * @return the batch ID of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getBatchId();

	/**
	 * Sets the batch ID of this vw ivld adj demand fore actual.
	 *
	 * @param batchId the batch ID of this vw ivld adj demand fore actual
	 */
	public void setBatchId(String batchId);

	/**
	 * Returns the item name of this vw ivld adj demand fore actual.
	 *
	 * @return the item name of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getItemName();

	/**
	 * Sets the item name of this vw ivld adj demand fore actual.
	 *
	 * @param itemName the item name of this vw ivld adj demand fore actual
	 */
	public void setItemName(String itemName);

	/**
	 * Returns the error field of this vw ivld adj demand fore actual.
	 *
	 * @return the error field of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getErrorField();

	/**
	 * Sets the error field of this vw ivld adj demand fore actual.
	 *
	 * @param errorField the error field of this vw ivld adj demand fore actual
	 */
	public void setErrorField(String errorField);

	/**
	 * Returns the net sales price of this vw ivld adj demand fore actual.
	 *
	 * @return the net sales price of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getNetSalesPrice();

	/**
	 * Sets the net sales price of this vw ivld adj demand fore actual.
	 *
	 * @param netSalesPrice the net sales price of this vw ivld adj demand fore actual
	 */
	public void setNetSalesPrice(String netSalesPrice);

	/**
	 * Returns the net sales amount of this vw ivld adj demand fore actual.
	 *
	 * @return the net sales amount of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getNetSalesAmount();

	/**
	 * Sets the net sales amount of this vw ivld adj demand fore actual.
	 *
	 * @param netSalesAmount the net sales amount of this vw ivld adj demand fore actual
	 */
	public void setNetSalesAmount(String netSalesAmount);

	/**
	 * Returns the segment of this vw ivld adj demand fore actual.
	 *
	 * @return the segment of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getSegment();

	/**
	 * Sets the segment of this vw ivld adj demand fore actual.
	 *
	 * @param segment the segment of this vw ivld adj demand fore actual
	 */
	public void setSegment(String segment);

	/**
	 * Returns the forecast name of this vw ivld adj demand fore actual.
	 *
	 * @return the forecast name of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getForecastName();

	/**
	 * Sets the forecast name of this vw ivld adj demand fore actual.
	 *
	 * @param forecastName the forecast name of this vw ivld adj demand fore actual
	 */
	public void setForecastName(String forecastName);

	/**
	 * Returns the ivld adjusted demand forecast sid of this vw ivld adj demand fore actual.
	 *
	 * @return the ivld adjusted demand forecast sid of this vw ivld adj demand fore actual
	 */
	public int getIvldAdjustedDemandForecastSid();

	/**
	 * Sets the ivld adjusted demand forecast sid of this vw ivld adj demand fore actual.
	 *
	 * @param ivldAdjustedDemandForecastSid the ivld adjusted demand forecast sid of this vw ivld adj demand fore actual
	 */
	public void setIvldAdjustedDemandForecastSid(
		int ivldAdjustedDemandForecastSid);

	/**
	 * Returns the market size units of this vw ivld adj demand fore actual.
	 *
	 * @return the market size units of this vw ivld adj demand fore actual
	 */
	@AutoEscape
	public String getMarketSizeUnits();

	/**
	 * Sets the market size units of this vw ivld adj demand fore actual.
	 *
	 * @param marketSizeUnits the market size units of this vw ivld adj demand fore actual
	 */
	public void setMarketSizeUnits(String marketSizeUnits);

	/**
	 * Returns the check record of this vw ivld adj demand fore actual.
	 *
	 * @return the check record of this vw ivld adj demand fore actual
	 */
	public boolean getCheckRecord();

	/**
	 * Returns <code>true</code> if this vw ivld adj demand fore actual is check record.
	 *
	 * @return <code>true</code> if this vw ivld adj demand fore actual is check record; <code>false</code> otherwise
	 */
	public boolean isCheckRecord();

	/**
	 * Sets whether this vw ivld adj demand fore actual is check record.
	 *
	 * @param checkRecord the check record of this vw ivld adj demand fore actual
	 */
	public void setCheckRecord(boolean checkRecord);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VwIvldAdjDemandForeActual vwIvldAdjDemandForeActual);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VwIvldAdjDemandForeActual> toCacheModel();

	@Override
	public VwIvldAdjDemandForeActual toEscapedModel();

	@Override
	public VwIvldAdjDemandForeActual toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}