/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stpl.gtn.gtn2o.ws.util;

/**
 *
 * @author Mahesh.James
 */
public class GtnWsQueryConstants {
	private GtnWsQueryConstants() {
		/**
		 * empty constructor
		 */
	}

	public static final String NOTES_INSERT = " INSERT INTO MASTER_DATA_FILES (MASTER_TABLE_SID, MASTER_TABLE_NAME, FILE_PATH, CREATED_DATE, CREATED_BY) VALUES (?,?,?,GetDate(),?)";
	public static final String CDR_DETAILS_INSERT = " INSERT INTO CDR_DETAILS (CDR_MODEL_SID, LINE_TYPE, ITEM_GROUP_MS_ASSOCIATION, KEYWORD, OPERATOR, VALUE,COMPARISON, LOGICAL_OPERATOR, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY) VALUES ";
	public static final String CDR_NOTES_DELETE1 = " DELETE FROM MASTER_DATA_FILES WHERE MASTER_TABLE_SID= ";
	public static final String CDR_NOTES_DELETE2 = " AND MASTER_TABLE_NAME='CDR_MODEL' ";
	public static final String CDR_DETAILS_DELETE = " DELETE FROM CDR_DETAILS WHERE CDR_MODEL_SID=";
	public static final String CDR_MODEL_DELETE = " DELETE FROM CDR_MODEL WHERE CDR_MODEL_SID=";
	public static final String CDR_NOTES_SELECT = " Select MASTER_TABLE_NAME,FILE_PATH,CREATED_DATE,CREATED_BY,MASTER_DATA_FILES_SID from MASTER_DATA_FILES  where MASTER_TABLE_NAME='CDR_MODEL' AND MASTER_TABLE_SID=";

	public static final String CDR_SELECT_INFO = "Select RULE_TYPE, RULE_NO, RULE_NAME, RULE_CATEGORY,INTERNAL_NOTES FROM CDR_MODEL where CDR_MODEL_SID=";
	public static final String CDR_RULE_EXIST = "Select COUNT(1) FROM CDR_MODEL where RULE_NAME=";
	public static final String CDR_DETAILS_SELECT = "select LINE_TYPE_HT.DESCRIPTION  as LINE_TYPEDESC,\n"
			+ "ITEM_GROUP_MS_ASSOCIATION_HT.DESCRIPTION as ITEM_GROUP_MS_ASSOCIATIONDESC,\n"
			+ "KEYWORD_HT.DESCRIPTION as KEYWORDDESC,OPERATOR_HT.DESCRIPTION as OPERATORDESC,\"VALUE\" as VALUEDESC,COMPARISON_HT.DESCRIPTION as COMPARISONDESC,\n"
			+ "LOGICAL_OPERATOR_HT.DESCRIPTION as LOGICAL_OPERATORDESC,LINE_TYPE,ITEM_GROUP_MS_ASSOCIATION,KEYWORD,OPERATOR,\"VALUE\",COMPARISON,LOGICAL_OPERATOR\n"
			+ "from dbo.CDR_DETAILS CDR_D\n"
			+ "JOIN HELPER_TABLE LINE_TYPE_HT ON LINE_TYPE_HT.HELPER_TABLE_SID=CDR_D.LINE_TYPE\n"
			+ "JOIN HELPER_TABLE ITEM_GROUP_MS_ASSOCIATION_HT ON ITEM_GROUP_MS_ASSOCIATION_HT.HELPER_TABLE_SID=CDR_D.ITEM_GROUP_MS_ASSOCIATION\n"
			+ "JOIN HELPER_TABLE KEYWORD_HT ON KEYWORD_HT.HELPER_TABLE_SID=CDR_D.KEYWORD\n"
			+ "JOIN HELPER_TABLE OPERATOR_HT ON OPERATOR_HT.HELPER_TABLE_SID=CDR_D.OPERATOR\n"
			+ "JOIN HELPER_TABLE COMPARISON_HT ON COMPARISON_HT.HELPER_TABLE_SID=CDR_D.COMPARISON\n"
			+ "JOIN HELPER_TABLE LOGICAL_OPERATOR_HT ON LOGICAL_OPERATOR_HT.HELPER_TABLE_SID=CDR_D.LOGICAL_OPERATOR\n"
			+ "WHERE CDR_D.CDR_MODEL_SID=";

	public static final String RP_NOTES_DELETE = "DELETE FROM MASTER_DATA_FILES WHERE MASTER_TABLE_NAME='REBATE_PLAN_MASTER' AND MASTER_TABLE_SID=";
	public static final String RP_NOTES_SELECT = " Select MASTER_TABLE_NAME,FILE_PATH,CREATED_DATE,CREATED_BY,MASTER_DATA_FILES_SID from MASTER_DATA_FILES where MASTER_TABLE_NAME='REBATE_PLAN_MASTER'  AND MASTER_TABLE_SID= ";
	public static final String NOTES_ATTACH_INSERT = "INSERT INTO ATTACHMENT (ATTACHMENT_TABLE_SID,FILE_NAME, FILE_DATA, MASTER_TABLE_NAME, CREATED_DATE, CREATED_BY) VALUES (?,?,?,?,GetDate(),?)";
	public static final String NOTE_TAB_ATTACHMENT_DELETE = "DELETE FROM ATTACHMENT WHERE ATTACHMENT_TABLE_SID=";
	public static final String NOTE_TAB_ATTACHMENT_SELECT = "Select MASTER_TABLE_NAME,FILE_NAME, CREATED_DATE, CREATED_BY ,ID,FILE_DATA from ATTACHMENT where ATTACHMENT_TABLE_SID= ";


}
