package com.stpl.gtn.gtn2o.ws.entity.transaction;
// Generated Mar 20, 2017 8:45:04 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * IvldItemPricing generated by hbm2java
 */
@SuppressWarnings("serial")
public class IvldItemPricing implements java.io.Serializable {

	private int ivldItemPricingSid;
	private String itemPricingIntfid;
	private String itemUom;
	private String itemPrice;
	private String pricingCodeStatus;
	private String entityCode;
	private String startDate;
	private String endDate;
	private String batchId;
	private String source;
	private String createdBy;
	private Date createdDate;
	private String modifiedBy;
	private Date modifiedDate;
	private String itemId;
	private String itemName;
	private String itemNo;
	private String pricingCodeQualifier;
	private String pricingCodeQualifierName;
	private String addChgDelIndicator;
	private String reasonForFailure;
    private Date intfInsertedDate;
    private String errorCode;
    private String errorField;
    private String reprocessedFlag;
    private boolean checkRecord;

	public IvldItemPricing() {
	}

	public IvldItemPricing(int ivldItemPricingSid, String itemPricingIntfid) {
		this.ivldItemPricingSid = ivldItemPricingSid;
		this.itemPricingIntfid = itemPricingIntfid;
	}

	
	public int getIvldItemPricingSid() {
		return ivldItemPricingSid;
	}

	public void setIvldItemPricingSid(int ivldItemPricingSid) {
		this.ivldItemPricingSid = ivldItemPricingSid;
	}

	public String getItemPricingIntfid() {
		return itemPricingIntfid;
	}

	public void setItemPricingIntfid(String itemPricingIntfid) {
		this.itemPricingIntfid = itemPricingIntfid;
	}

	public String getItemUom() {
		return this.itemUom;
	}

	public void setItemUom(String itemUom) {
		this.itemUom = itemUom;
	}

	public String getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(String itemPrice) {
		this.itemPrice = itemPrice;
	}

	public String getPricingCodeStatus() {
		return this.pricingCodeStatus;
	}

	public void setPricingCodeStatus(String pricingCodeStatus) {
		this.pricingCodeStatus = pricingCodeStatus;
	}

	public String getEntityCode() {
		return this.entityCode;
	}

	public void setEntityCode(String entityCode) {
		this.entityCode = entityCode;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getBatchId() {
		return this.batchId;
	}

	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getItemId() {
		return itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getItemNo() {
		return itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	public String getPricingCodeQualifier() {
		return pricingCodeQualifier;
	}

	public void setPricingCodeQualifier(String pricingCodeQualifier) {
		this.pricingCodeQualifier = pricingCodeQualifier;
	}

	public String getPricingCodeQualifierName() {
		return pricingCodeQualifierName;
	}

	public void setPricingCodeQualifierName(String pricingCodeQualifierName) {
		this.pricingCodeQualifierName = pricingCodeQualifierName;
	}

	public String getAddChgDelIndicator() {
		return addChgDelIndicator;
	}

	public void setAddChgDelIndicator(String addChgDelIndicator) {
		this.addChgDelIndicator = addChgDelIndicator;
	}

	public String getReasonForFailure() {
		return reasonForFailure;
	}

	public void setReasonForFailure(String reasonForFailure) {
		this.reasonForFailure = reasonForFailure;
	}

	public Date getIntfInsertedDate() {
		return intfInsertedDate;
	}

	public void setIntfInsertedDate(Date intfInsertedDate) {
		this.intfInsertedDate = intfInsertedDate;
	}

	public String getErrorCode() {
		return errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	public String getErrorField() {
		return errorField;
	}

	public void setErrorField(String errorField) {
		this.errorField = errorField;
	}

	public String getReprocessedFlag() {
		return reprocessedFlag;
	}

	public void setReprocessedFlag(String reprocessedFlag) {
		this.reprocessedFlag = reprocessedFlag;
	}

	public boolean isCheckRecord() {
		return checkRecord;
	}

	public void setCheckRecord(boolean checkRecord) {
		this.checkRecord = checkRecord;
	}
 
}
