package com.stpl.gtn.gtn2o.ws.entity.transaction;
// Generated May 17, 2017 7:42:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StagAverageShelfLife generated by hbm2java
 */
@SuppressWarnings("serial")
public class StagAverageShelfLife  implements java.io.Serializable {


     private int stagAverageShelfLifeSid;
     private String averageShelfLifeIntfid;
     private String itemIdType;
     private String itemId;
     private String avgShelfLife;
     private String createdBy;
     private Date createdDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String batchId;
     private String source;
     private String addChgDelIndicator;

    public StagAverageShelfLife() {
    }

	
    public StagAverageShelfLife(int stagAverageShelfLifeSid, String averageShelfLifeIntfid, String itemIdType, String itemId, String avgShelfLife, String batchId, String addChgDelIndicator) {
        this.stagAverageShelfLifeSid = stagAverageShelfLifeSid;
        this.averageShelfLifeIntfid = averageShelfLifeIntfid;
        this.itemIdType = itemIdType;
        this.itemId = itemId;
        this.avgShelfLife = avgShelfLife;
        this.batchId = batchId;
        this.addChgDelIndicator = addChgDelIndicator;
    }
    public StagAverageShelfLife(int stagAverageShelfLifeSid, String averageShelfLifeIntfid, String itemIdType, String itemId, String avgShelfLife, String createdBy, Date createdDate, String modifiedBy, Date modifiedDate, String batchId, String source, String addChgDelIndicator) {
       this.stagAverageShelfLifeSid = stagAverageShelfLifeSid;
       this.averageShelfLifeIntfid = averageShelfLifeIntfid;
       this.itemIdType = itemIdType;
       this.itemId = itemId;
       this.avgShelfLife = avgShelfLife;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.batchId = batchId;
       this.source = source;
       this.addChgDelIndicator = addChgDelIndicator;
    }
   
    public int getStagAverageShelfLifeSid() {
        return this.stagAverageShelfLifeSid;
    }
    
    public void setStagAverageShelfLifeSid(int stagAverageShelfLifeSid) {
        this.stagAverageShelfLifeSid = stagAverageShelfLifeSid;
    }
    public String getAverageShelfLifeIntfid() {
        return this.averageShelfLifeIntfid;
    }
    
    public void setAverageShelfLifeIntfid(String averageShelfLifeIntfid) {
        this.averageShelfLifeIntfid = averageShelfLifeIntfid;
    }
    public String getItemIdType() {
        return this.itemIdType;
    }
    
    public void setItemIdType(String itemIdType) {
        this.itemIdType = itemIdType;
    }
    public String getItemId() {
        return this.itemId;
    }
    
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }
    public String getAvgShelfLife() {
        return this.avgShelfLife;
    }
    
    public void setAvgShelfLife(String avgShelfLife) {
        this.avgShelfLife = avgShelfLife;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    public String getBatchId() {
		return batchId;
	}


	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}


	public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getAddChgDelIndicator() {
        return this.addChgDelIndicator;
    }
    
    public void setAddChgDelIndicator(String addChgDelIndicator) {
        this.addChgDelIndicator = addChgDelIndicator;
    }




}


