package com.stpl.gtn.gtn2o.ws.entity.transaction;
// Generated May 17, 2017 7:42:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StagCustomerGtsActual generated by hbm2java
 */
@SuppressWarnings("serial")
public class StagCustomerGtsActual  implements java.io.Serializable {


     private int stagCustomerGtsActualSid;
     private String customerGtsActualIntfId;
     private String salesId;
     private String organizationKey;
     private String itemId;
     private String itemUom;
     private String orderNumber;
     private String invoiceNumber;
     private String invoiceLineNumber;
     private Date invoiceDate;
     private String quantity;
     private String lotNo;
     private String amount;
     private String contractId;
     private String accountId;
     private Date orderReceivedDate;
     private String batchId;
     private String source;
     private String createdBy;
     private String createdDate;
     private String modifiedBy;
     private Date modifiedDate;
     private String addChgDelIndicator;
     private String parentAccountId;

    public StagCustomerGtsActual() {
    }

	
    public StagCustomerGtsActual(int stagCustomerGtsActualSid, String customerGtsActualIntfId, String salesId, String organizationKey, String itemId, String itemUom, String orderNumber, String invoiceNumber, String invoiceLineNumber, Date invoiceDate, String quantity, String amount, String accountId, String batchId, String source, String createdBy, String createdDate, String modifiedBy, Date modifiedDate, String addChgDelIndicator) {
        this.stagCustomerGtsActualSid = stagCustomerGtsActualSid;
        this.customerGtsActualIntfId = customerGtsActualIntfId;
        this.salesId = salesId;
        this.organizationKey = organizationKey;
        this.itemId = itemId;
        this.itemUom = itemUom;
        this.orderNumber = orderNumber;
        this.invoiceNumber = invoiceNumber;
        this.invoiceLineNumber = invoiceLineNumber;
        this.invoiceDate = invoiceDate;
        this.quantity = quantity;
        this.amount = amount;
        this.accountId = accountId;
        this.batchId = batchId;
        this.source = source;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.addChgDelIndicator = addChgDelIndicator;
    }
    public StagCustomerGtsActual(int stagCustomerGtsActualSid, String customerGtsActualIntfId, String salesId, String organizationKey, String itemId, String itemUom, String orderNumber, String invoiceNumber, String invoiceLineNumber, Date invoiceDate, String quantity, String lotNo, String amount, String contractId, String accountId, Date orderReceivedDate, String batchId, String source, String createdBy, String createdDate, String modifiedBy, Date modifiedDate, String addChgDelIndicator, String parentAccountId) {
       this.stagCustomerGtsActualSid = stagCustomerGtsActualSid;
       this.customerGtsActualIntfId = customerGtsActualIntfId;
       this.salesId = salesId;
       this.organizationKey = organizationKey;
       this.itemId = itemId;
       this.itemUom = itemUom;
       this.orderNumber = orderNumber;
       this.invoiceNumber = invoiceNumber;
       this.invoiceLineNumber = invoiceLineNumber;
       this.invoiceDate = invoiceDate;
       this.quantity = quantity;
       this.lotNo = lotNo;
       this.amount = amount;
       this.contractId = contractId;
       this.accountId = accountId;
       this.orderReceivedDate = orderReceivedDate;
       this.batchId = batchId;
       this.source = source;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.addChgDelIndicator = addChgDelIndicator;
       this.parentAccountId = parentAccountId;
    }
   
    public int getStagCustomerGtsActualSid() {
        return this.stagCustomerGtsActualSid;
    }
    
    public void setStagCustomerGtsActualSid(int stagCustomerGtsActualSid) {
        this.stagCustomerGtsActualSid = stagCustomerGtsActualSid;
    }
    public String getCustomerGtsActualIntfId() {
        return this.customerGtsActualIntfId;
    }
    
    public void setCustomerGtsActualIntfId(String customerGtsActualIntfId) {
        this.customerGtsActualIntfId = customerGtsActualIntfId;
    }
    public String getSalesId() {
        return this.salesId;
    }
    
    public void setSalesId(String salesId) {
        this.salesId = salesId;
    }
    public String getOrganizationKey() {
        return this.organizationKey;
    }
    
    public void setOrganizationKey(String organizationKey) {
        this.organizationKey = organizationKey;
    }
    public String getItemId() {
        return this.itemId;
    }
    
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }
    public String getItemUom() {
        return this.itemUom;
    }
    
    public void setItemUom(String itemUom) {
        this.itemUom = itemUom;
    }
    public String getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }
    public String getInvoiceNumber() {
        return this.invoiceNumber;
    }
    
    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }
    public String getInvoiceLineNumber() {
        return this.invoiceLineNumber;
    }
    
    public void setInvoiceLineNumber(String invoiceLineNumber) {
        this.invoiceLineNumber = invoiceLineNumber;
    }
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    public String getLotNo() {
        return this.lotNo;
    }
    
    public void setLotNo(String lotNo) {
        this.lotNo = lotNo;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getContractId() {
        return this.contractId;
    }
    
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }
    public String getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }
    public Date getOrderReceivedDate() {
        return this.orderReceivedDate;
    }
    
    public void setOrderReceivedDate(Date orderReceivedDate) {
        this.orderReceivedDate = orderReceivedDate;
    }
    public String getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
   
    public String getCreatedDate() {
		return createdDate;
	}


	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}


	public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getAddChgDelIndicator() {
        return this.addChgDelIndicator;
    }
    
    public void setAddChgDelIndicator(String addChgDelIndicator) {
        this.addChgDelIndicator = addChgDelIndicator;
    }
    public String getParentAccountId() {
        return this.parentAccountId;
    }
    
    public void setParentAccountId(String parentAccountId) {
        this.parentAccountId = parentAccountId;
    }




}


