package com.stpl.app.model.impl;

import com.stpl.app.model.MSalesProjectionMaster;
import com.stpl.app.service.MSalesProjectionMasterLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the MSalesProjectionMaster service. Represents a row in the &quot;M_SALES_PROJECTION_MASTER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MSalesProjectionMasterImpl}.
 * </p>
 *
 * @author
 * @see MSalesProjectionMasterImpl
 * @see com.stpl.app.model.MSalesProjectionMaster
 * @generated
 */
public abstract class MSalesProjectionMasterBaseImpl
    extends MSalesProjectionMasterModelImpl implements MSalesProjectionMaster {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a m sales projection master model instance should use the {@link MSalesProjectionMaster} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MSalesProjectionMasterLocalServiceUtil.addMSalesProjectionMaster(this);
        } else {
            MSalesProjectionMasterLocalServiceUtil.updateMSalesProjectionMaster(this);
        }
    }
}
