package com.stpl.app.model.impl;

import com.stpl.app.model.RebateTierFormula;
import com.stpl.app.service.RebateTierFormulaLocalServiceUtil;

import com.stpl.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the RebateTierFormula service. Represents a row in the &quot;REBATE_TIER_FORMULA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RebateTierFormulaImpl}.
 * </p>
 *
 * @author
 * @see RebateTierFormulaImpl
 * @see com.stpl.app.model.RebateTierFormula
 * @generated
 */
public abstract class RebateTierFormulaBaseImpl
    extends RebateTierFormulaModelImpl implements RebateTierFormula {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a rebate tier formula model instance should use the {@link RebateTierFormula} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RebateTierFormulaLocalServiceUtil.addRebateTierFormula(this);
        } else {
            RebateTierFormulaLocalServiceUtil.updateRebateTierFormula(this);
        }
    }
}
