/*Start of Contract Header Foreign Key Information*/

-------------------------------------------- CONTRACT MASTER -----------------------------------------

------------------------------- MANF_COMPANY_MASTER_SID REFERENCE FROM COMPANY_MASTER TABLE --------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_COMPANY_MASTER_MANF_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        ADD CONSTRAINT FK_CONTRACT_MASTER_COMPANY_MASTER_MANF_COMPANY_MASTER_SID FOREIGN KEY(MANF_COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END
GO

------------------------------- BUNIT_COMPANY_MASTER_SID REFERENCE FROM COMPANY_MASTER TABLE --------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_COMPANY_MASTER_BUNIT_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        ADD CONSTRAINT FK_CONTRACT_MASTER_COMPANY_MASTER_BUNIT_COMPANY_MASTER_SID FOREIGN KEY(BUNIT_COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END
GO

------------------------------- CONT_HOLD_COMPANY_MASTER_SID REFERENCE FROM COMPANY_MASTER TABLE --------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_COMPANY_MASTER_CONT_HOLD_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        ADD CONSTRAINT FK_CONTRACT_MASTER_COMPANY_MASTER_CONT_HOLD_COMPANY_MASTER_SID FOREIGN KEY(CONT_HOLD_COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END
GO

------------------------------- CONTRACT_TYPE REFERENCE FROM HELPER TABLE --------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_HELPER_TABLE_CONTRACT_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        ADD CONSTRAINT FK_CONTRACT_MASTER_HELPER_TABLE_CONTRACT_TYPE FOREIGN KEY(CONTRACT_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------- DOCUMENT_TYPE REFERENCE FROM HELPER TABLE --------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_HELPER_TABLE_DOCUMENT_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        ADD CONSTRAINT FK_CONTRACT_MASTER_HELPER_TABLE_DOCUMENT_TYPE FOREIGN KEY(DOCUMENT_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------- AWARD_STATUS REFERENCE FROM HELPER TABLE --------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_HELPER_TABLE_AWARD_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        ADD CONSTRAINT FK_CONTRACT_MASTER_HELPER_TABLE_AWARD_STATUS FOREIGN KEY(AWARD_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------- CONTRACT_STATUS REFERENCE FROM HELPER TABLE --------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_HELPER_TABLE_CONTRACT_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        ADD CONSTRAINT FK_CONTRACT_MASTER_HELPER_TABLE_CONTRACT_STATUS FOREIGN KEY(CONTRACT_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------- PAYMENT_TERMS REFERENCE FROM HELPER TABLE --------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_HELPER_TABLE_PAYMENT_TERMS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        ADD CONSTRAINT FK_CONTRACT_MASTER_HELPER_TABLE_PAYMENT_TERMS FOREIGN KEY(PAYMENT_TERMS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------- CONTRACT_TRADE_CLASS REFERENCE FROM HELPER TABLE --------------------------
IF EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_HELPER_TABLE_TRADE_CLASS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        DROP CONSTRAINT FK_CONTRACT_MASTER_HELPER_TABLE_TRADE_CLASS
  END
GO
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_HELPER_TABLE_CONTRACT_TRADE_CLASS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        ADD CONSTRAINT FK_CONTRACT_MASTER_HELPER_TABLE_CONTRACT_TRADE_CLASS FOREIGN KEY(CONTRACT_TRADE_CLASS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------- DOCUMENT_CLASS REFERENCE FROM HELPER TABLE --------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_MASTER_HELPER_TABLE_DOCUMENT_CLASS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_MASTER
        ADD CONSTRAINT FK_CONTRACT_MASTER_HELPER_TABLE_DOCUMENT_CLASS FOREIGN KEY(DOCUMENT_CLASS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END 

GO
------------------------------------- CONTRACT ALIAS MASTER -----------------------------------

--------------------------------- CONTRACT_MASTER_SID REFERENCE FROM CONTRACT_MASTER TABLE -----------------------------------------
  IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_ALIAS_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_ALIAS_MASTER_CONTRACT_MASTER_CONTRACT_MASTER_SID'
                     AND [TYPE] = 'F')
  BEGIN
      ALTER TABLE CONTRACT_ALIAS_MASTER
        ADD CONSTRAINT FK_CONTRACT_ALIAS_MASTER_CONTRACT_MASTER_CONTRACT_MASTER_SID FOREIGN KEY(CONTRACT_MASTER_SID) REFERENCES CONTRACT_MASTER(CONTRACT_MASTER_SID)
  END
GO

--------------------------------- CONTRACT_ALIAS_TYPE REFERENCE FROM HELPER TABLE -----------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CONTRACT_ALIAS_MASTER'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CONTRACT_ALIAS_MASTER_HELPER_TABLE_CONTRACT_ALIAS_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CONTRACT_ALIAS_MASTER
        ADD CONSTRAINT FK_CONTRACT_ALIAS_MASTER_HELPER_TABLE_CONTRACT_ALIAS_TYPE FOREIGN KEY(CONTRACT_ALIAS_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO 

/*End of Contract Header Foreign Key Information*/

/*Start of Company Family Plan Contract Foreign Key Information*/

-------------------------------- CFP_CONTRACT ------------------------------------------------------
-------------------------------- CONTRACT_MASTER_SID REFERENCE FROM CONTRACT_MASTER TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_CONTRACT_MASTER_CONTRACT_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT
        ADD CONSTRAINT FK_CFP_CONTRACT_CONTRACT_MASTER_CONTRACT_MASTER_SID FOREIGN KEY(CONTRACT_MASTER_SID) REFERENCES CONTRACT_MASTER(CONTRACT_MASTER_SID)
  END
GO

-------------------------------- CFP_MODEL_SID REFERENCE FROM CFP_MODEL TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_CFP_MODEL_CFP_MODEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT
        ADD CONSTRAINT FK_CFP_CONTRACT_CFP_MODEL_CFP_MODEL_SID FOREIGN KEY(CFP_MODEL_SID) REFERENCES CFP_MODEL(CFP_MODEL_SID)
  END
GO

-------------------------------- CFP_TYPE REFERENCE FROM HELPER TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_HELPER_TABLE_CFP_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT
        ADD CONSTRAINT FK_CFP_CONTRACT_HELPER_TABLE_CFP_TYPE FOREIGN KEY(CFP_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

-------------------------------- CFP_CONTRACT_ATTACHED_STATUS REFERENCE FROM HELPER TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_HELPER_TABLE_CFP_CONTRACT_ATTACHED_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT
        ADD CONSTRAINT FK_CFP_CONTRACT_HELPER_TABLE_CFP_CONTRACT_ATTACHED_STATUS FOREIGN KEY(CFP_CONTRACT_ATTACHED_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

-------------------------------- CFP_STATUS REFERENCE FROM HELPER TABLE ---------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_HELPER_TABLE_CFP_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT
        ADD CONSTRAINT FK_CFP_CONTRACT_HELPER_TABLE_CFP_STATUS FOREIGN KEY(CFP_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

-------------------------------- CFP_CATEGORY REFERENCE FROM HELPER TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_HELPER_TABLE_CFP_CATEGORY'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT
        ADD CONSTRAINT FK_CFP_CONTRACT_HELPER_TABLE_CFP_CATEGORY FOREIGN KEY(CFP_CATEGORY) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

-------------------------------- CFP_TRADE_CLASS REFERENCE FROM HELPER_TABLE TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_HELPER_TABLE_CFP_TRADE_CLASS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT
        ADD CONSTRAINT FK_CFP_CONTRACT_HELPER_TABLE_CFP_TRADE_CLASS FOREIGN KEY(CFP_TRADE_CLASS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO 


--------------------------------------- CFP CONTRACT DETAILS -----------------------------------------------------

-------------------------------- CFP_CONTRACT_SID REFERENCE FROM CFP_CONTRACT TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_DETAILS_CFP_CONTRACT_CFP_CONTRACT_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT_DETAILS
        ADD CONSTRAINT FK_CFP_CONTRACT_DETAILS_CFP_CONTRACT_CFP_CONTRACT_SID FOREIGN KEY(CFP_CONTRACT_SID) REFERENCES CFP_CONTRACT(CFP_CONTRACT_SID)
  END
GO

-------------------------------- COMPANY_MASTER_SID REFERENCE FROM COMPANY_MASTER TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_DETAILS_COMPANY_MASTER_COMPANY_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT_DETAILS
        ADD CONSTRAINT FK_CFP_CONTRACT_DETAILS_COMPANY_MASTER_COMPANY_MASTER_SID FOREIGN KEY(COMPANY_MASTER_SID) REFERENCES COMPANY_MASTER(COMPANY_MASTER_SID)
  END
GO

-------------------------------- TRADE_CLASS REFERENCE FROM HELPER TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_DETAILS_HELPER_TABLE_TRADE_CLASS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT_DETAILS
        ADD CONSTRAINT FK_CFP_CONTRACT_DETAILS_HELPER_TABLE_TRADE_CLASS FOREIGN KEY(TRADE_CLASS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

-------------------------------- CFP_CONTRACT_ATTACHED_STATUS REFERENCE FROM HELPER TABLE --------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'CFP_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_CFP_CONTRACT_DETAILS_HELPER_TABLE_CFP_CONTRACT_ATTACHED_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE CFP_CONTRACT_DETAILS
        ADD CONSTRAINT FK_CFP_CONTRACT_DETAILS_HELPER_TABLE_CFP_CONTRACT_ATTACHED_STATUS FOREIGN KEY(CFP_CONTRACT_ATTACHED_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO 



/*End of Company Family Plan Contract Foreign Key Information*/


/*Start of Item Family Plan Contract Foreign Key Information*/

------------------------------------ IFP CONTRACT ----------------------------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IMTD_IFP_DETAILS_PENDING'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IMTD_IFP_DETAILS_PENDING_IFP_CONTRACT_IFP_CONTRACT_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].IMTD_IFP_DETAILS_PENDING
        ADD CONSTRAINT FK_IMTD_IFP_DETAILS_PENDING_IFP_CONTRACT_IFP_CONTRACT_SID FOREIGN KEY(IFP_CONTRACT_SID) REFERENCES IFP_CONTRACT ( IFP_CONTRACT_SID)
  END

GO 


------------------------------------- CFP_CONTRACT_SID REFERENCE FROM CFP_CONTRACT TABLE -------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_CFP_CONTRACT_CFP_CONTRACT_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [dbo].[IFP_CONTRACT]
        ADD CONSTRAINT FK_IFP_CONTRACT_CFP_CONTRACT_CFP_CONTRACT_SID FOREIGN KEY(CFP_CONTRACT_SID) REFERENCES CFP_CONTRACT(CFP_CONTRACT_SID)
  END
GO

------------------------------------- CONTRACT_MASTER_SID REFERENCE FROM CONTRACT_MASTER TABLE -------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_CONTRACT_MASTER_CONTRACT_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [dbo].[IFP_CONTRACT]
        ADD CONSTRAINT FK_IFP_CONTRACT_CONTRACT_MASTER_CONTRACT_MASTER_SID FOREIGN KEY(CONTRACT_MASTER_SID) REFERENCES CONTRACT_MASTER(CONTRACT_MASTER_SID)
  END
GO

------------------------------------- IFP_MODEL_SID REFERENCE FROM IFP_MODEL TABLE -------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_IFP_MODEL_IFP_MODEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE IFP_CONTRACT
        ADD CONSTRAINT FK_IFP_CONTRACT_IFP_MODEL_IFP_MODEL_SID FOREIGN KEY(IFP_MODEL_SID) REFERENCES IFP_MODEL(IFP_MODEL_SID)
  END
GO

------------------------------------- IFP_TYPE REFERENCE FROM HELPER TABLE -------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_HELPER_TABLE_IFP_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE IFP_CONTRACT
        ADD CONSTRAINT FK_IFP_CONTRACT_HELPER_TABLE_IFP_TYPE FOREIGN KEY(IFP_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------- IFP_CONTRACT_ATTACHED_STATUS REFERENCE FROM HELPER TABLE -------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_HELPER_TABLE_IFP_CONTRACT_ATTACHED_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE IFP_CONTRACT
        ADD CONSTRAINT FK_IFP_CONTRACT_HELPER_TABLE_IFP_CONTRACT_ATTACHED_STATUS FOREIGN KEY(IFP_CONTRACT_ATTACHED_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------- IFP_STATUS REFERENCE FROM HELPER TABLE ----------------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_HELPER_TABLE_IFP_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE IFP_CONTRACT
        ADD CONSTRAINT FK_IFP_CONTRACT_HELPER_TABLE_IFP_STATUS FOREIGN KEY(IFP_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO

------------------------------------- IFP_DESIGNATION REFERENCE FROM HELPER TABLE ----------------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_HELPER_TABLE_IFP_DESIGNATION'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE IFP_CONTRACT
        ADD CONSTRAINT FK_IFP_CONTRACT_HELPER_TABLE_IFP_DESIGNATION  FOREIGN KEY(IFP_DESIGNATION) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO


------------------------------------- IFP_CATEGORY REFERENCE FROM HELPER TABLE ----------------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_HELPER_TABLE_IFP_CATEGORY'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE IFP_CONTRACT
        ADD CONSTRAINT FK_IFP_CONTRACT_HELPER_TABLE_IFP_CATEGORY FOREIGN KEY(IFP_CATEGORY) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END 
GO

-------------------------------------- IFP CONTRACT DETAILS -----------------------------------------------------------------------------------------

-------------------------------------- IFP_CONTRACT_SID REFERENCE FROM IFP_CONTRACT TABLE -----------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_DETAILS_IFP_CONTRACT_IFP_CONTRACT_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [dbo].[IFP_CONTRACT_DETAILS]
        ADD CONSTRAINT FK_IFP_CONTRACT_DETAILS_IFP_CONTRACT_IFP_CONTRACT_SID FOREIGN KEY(IFP_CONTRACT_SID) REFERENCES IFP_CONTRACT(IFP_CONTRACT_SID)
  END
GO

-------------------------------------- ITEM_MASTER_SID REFERENCE FROM ITEM_MASTER TABLE ------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_DETAILS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [dbo].[IFP_CONTRACT_DETAILS]
        ADD CONSTRAINT FK_IFP_CONTRACT_DETAILS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

-------------------------------------- IFP_CONTRACT_ATTACHED_STATUS REFERENCE FROM HELPER TABLE ------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_DETAILS_HELPER_TABLE_IFP_CONTRACT_ATTACHED_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE IFP_CONTRACT_DETAILS
        ADD CONSTRAINT FK_IFP_CONTRACT_DETAILS_HELPER_TABLE_IFP_CONTRACT_ATTACHED_STATUS FOREIGN KEY(IFP_CONTRACT_ATTACHED_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO


------------------FK_IFP_CONTRACT_DETAILS_HELPER_TABLE_ITEM_STATUS----------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'IFP_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_IFP_CONTRACT_DETAILS_HELPER_TABLE_ITEM_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[IFP_CONTRACT_DETAILS]
         ADD CONSTRAINT FK_IFP_CONTRACT_DETAILS_HELPER_TABLE_ITEM_STATUS FOREIGN KEY(ITEM_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO 


/*End of Item Family Plan Contract Foreign Key Information*/


/*Start of Price Schedule Contract Foreign Key Information*/

---------------------------------------------- PS CONTRACT ------------------------------------------------------------------------

-------------------------------------------- CONTRACT_MASTER_SID REFERENCE FROM CONTRACT_MASTER TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_CONTRACT_MASTER_CONTRACT_MASTER_SID'
                     AND TYPE = 'F')
BEGIN
  ALTER TABLE [dbo].[PS_CONTRACT]
    ADD CONSTRAINT FK_PS_CONTRACT_CONTRACT_MASTER_CONTRACT_MASTER_SID FOREIGN KEY(CONTRACT_MASTER_SID) REFERENCES CONTRACT_MASTER(CONTRACT_MASTER_SID)
END

GO

-------------------------------------------- CFP_CONTRACT_SID REFERENCE FROM CFP_CONTRACT TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_CFP_CONTRACT_CFP_CONTRACT_SID'
                     AND TYPE = 'F')
BEGIN
  ALTER TABLE [dbo].[PS_CONTRACT]
    ADD CONSTRAINT FK_PS_CONTRACT_CFP_CONTRACT_CFP_CONTRACT_SID FOREIGN KEY(CFP_CONTRACT_SID) REFERENCES CFP_CONTRACT(CFP_CONTRACT_SID)
END

GO

-------------------------------------------- IFP_CONTRACT_SID REFERENCE FROM IFP_CONTRACT TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_IFP_CONTRACT_IFP_CONTRACT_SID'
                     AND TYPE = 'F')
BEGIN 
  ALTER TABLE [dbo].[PS_CONTRACT]
    ADD CONSTRAINT FK_PS_CONTRACT_IFP_CONTRACT_IFP_CONTRACT_SID FOREIGN KEY(IFP_CONTRACT_SID) REFERENCES IFP_CONTRACT(IFP_CONTRACT_SID)
END

GO

-------------------------------------------- PS_MODEL_SID REFERENCE FROM PS_MODEL TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_PS_MODEL_PS_MODEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT
        ADD CONSTRAINT FK_PS_CONTRACT_PS_MODEL_PS_MODEL_SID FOREIGN KEY(PS_MODEL_SID) REFERENCES PS_MODEL(PS_MODEL_SID)
  END

GO

-------------------------------------------- PS_TYPE REFERENCE FROM HELPER TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_HELPER_TABLE_PS_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT
        ADD CONSTRAINT FK_PS_CONTRACT_HELPER_TABLE_PS_TYPE FOREIGN KEY(PS_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO

-------------------------------------------- PS_CONTRACT_ATTACHED_STATUS REFERENCE FROM CONTRACT_MASTER TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_HELPER_TABLE_PS_CONTRACT_ATTACHED_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT
        ADD CONSTRAINT FK_PS_CONTRACT_HELPER_TABLE_PS_CONTRACT_ATTACHED_STATUS FOREIGN KEY(PS_CONTRACT_ATTACHED_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO

-------------------------------------------- PS_STATUS REFERENCE FROM CONTRACT_MASTER TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_HELPER_TABLE_PS_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT
        ADD CONSTRAINT FK_PS_CONTRACT_HELPER_TABLE_PS_STATUS FOREIGN KEY(PS_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO

-------------------------------------------- PS_CATEGORY REFERENCE FROM HELPER_TABLE TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_HELPER_TABLE_PS_CATEGORY'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT
        ADD CONSTRAINT FK_PS_CONTRACT_HELPER_TABLE_PS_CATEGORY FOREIGN KEY(PS_CATEGORY) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END 

GO

--------------------------------------------- PS_DESIGNATION REFERENCE FROM HELPER_TABLE TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_HELPER_TABLE_PS_DESIGNATION'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT
        ADD CONSTRAINT FK_PS_CONTRACT_HELPER_TABLE_PS_DESIGNATION  FOREIGN KEY(PS_DESIGNATION) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO


--------------------------------------------- PS CONTRACT DETAILS ------------------------------------------------------------------

--------------------------------------------- PS_CONTRACT_SID REFERENCE FROM PS_CONTRACT TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_PS_CONTRACT_PS_CONTRACT_SID'
                     AND TYPE = 'F')
BEGIN  
  ALTER TABLE [dbo].[PS_CONTRACT_DETAILS]
    ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_PS_CONTRACT_PS_CONTRACT_SID FOREIGN KEY(PS_CONTRACT_SID) REFERENCES PS_CONTRACT(PS_CONTRACT_SID)
END

GO

--------------------------------------------- PRICE_TOLERANCE_INTERVAL REFERENCE FROM PS_CONTRACT TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PRICE_TOLERANCE_INTERVAL'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT_DETAILS
        ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PRICE_TOLERANCE_INTERVAL  FOREIGN KEY(PRICE_TOLERANCE_INTERVAL) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO

--------------------------------------------- ITEM_MASTER_SID REFERENCE FROM ITEM_MASTER TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
BEGIN
  ALTER TABLE [dbo].[PS_CONTRACT_DETAILS]
    ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
END

GO

--------------------------------------------- ITEM_PRICING_QUALIFIER_SID REFERENCE FROM ITEM_PRICING_QUALIFIER TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_ITEM_PRICING_QUALIFIER_ITEM_PRICING_QUALIFIER_SID'
                     AND TYPE = 'F')
BEGIN
  ALTER TABLE [dbo].[PS_CONTRACT_DETAILS]
    ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_ITEM_PRICING_QUALIFIER_ITEM_PRICING_QUALIFIER_SID FOREIGN KEY(ITEM_PRICING_QUALIFIER_SID) REFERENCES ITEM_PRICING_QUALIFIER(ITEM_PRICING_QUALIFIER_SID)
END

GO

--------------------------------------------- PRICE_TOLERANCE_TYPE REFERENCE FROM HELPER_TABLE TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PRICE_TOLERANCE_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT_DETAILS
        ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PRICE_TOLERANCE_TYPE FOREIGN KEY(PRICE_TOLERANCE_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO

--------------------------------------------- PRICE_TOLERANCE_FREQUENCY REFERENCE FROM HELPER_TABLE TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PRICE_TOLERANCE_FREQUENCY'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT_DETAILS
        ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PRICE_TOLERANCE_FREQUENCY FOREIGN KEY(PRICE_TOLERANCE_FREQUENCY) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END 

GO

--------------------------------------------- PS_CONTRACT_ATTACHED_STATUS REFERENCE FROM HELPER_TABLE TABLE -------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PS_CONTRACT_ATTACHED_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT_DETAILS
        ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PS_CONTRACT_ATTACHED_STATUS FOREIGN KEY(PS_CONTRACT_ATTACHED_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO
-----------------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_BRAND_MASTER_BRAND_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[PS_CONTRACT_DETAILS]
        ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_BRAND_MASTER_BRAND_MASTER_SID FOREIGN KEY(BRAND_MASTER_SID) REFERENCES BRAND_MASTER ( BRAND_MASTER_SID)
  END

GO 
IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE OBJECT_NAME(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
			AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_NET_BASE_PRICE'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE PS_CONTRACT_DETAILS ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_NET_BASE_PRICE FOREIGN KEY (NET_BASE_PRICE) REFERENCES HELPER_TABLE (HELPER_TABLE_SID)
END

GO

IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE OBJECT_NAME(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
			AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_NET_SUBSEQUENT_PERIOD_PRICE'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE PS_CONTRACT_DETAILS ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_NET_SUBSEQUENT_PERIOD_PRICE FOREIGN KEY (NET_SUBSEQUENT_PERIOD_PRICE) REFERENCES HELPER_TABLE (HELPER_TABLE_SID)
END

GO

IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE OBJECT_NAME(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
			AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_NET_RESET_PRICE_TYPE'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE PS_CONTRACT_DETAILS ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_NET_RESET_PRICE_TYPE FOREIGN KEY (NET_RESET_PRICE_TYPE) REFERENCES HELPER_TABLE (HELPER_TABLE_SID)
END

GO

IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE OBJECT_NAME(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
			AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PRICE_TOLERANCE_FREQUENCY'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE PS_CONTRACT_DETAILS ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PRICE_TOLERANCE_FREQUENCY FOREIGN KEY (PRICE_TOLERANCE_FREQUENCY) REFERENCES HELPER_TABLE (HELPER_TABLE_SID)
END

GO

IF NOT EXISTS (
		SELECT 1
		FROM SYS.FOREIGN_KEYS
		WHERE OBJECT_NAME(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
			AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
			AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PRICE_TOLERANCE_TYPE'
			AND TYPE = 'F'
		)
BEGIN
	ALTER TABLE PS_CONTRACT_DETAILS ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_PRICE_TOLERANCE_TYPE FOREIGN KEY (PRICE_TOLERANCE_TYPE) REFERENCES HELPER_TABLE (HELPER_TABLE_SID)
END

GO


/*End of Price Schedule Contract Foreign Key Information*/


/*Start of Rebate Schedule Contract Foreign Key Information*/

------------------------------------------------- RS CONTRACT --------------------------------------------------------------------
--------------------------------CONTRACT_MASTER_SID REFERENCE FROM CONTRACT_MASTER TABLE -----------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_CONTRACT_MASTER_CONTRACT_MASTER_SID'
                     AND TYPE = 'F')
BEGIN
  ALTER TABLE [dbo].[RS_CONTRACT]
    ADD CONSTRAINT FK_RS_CONTRACT_CONTRACT_MASTER_CONTRACT_MASTER_SID FOREIGN KEY(CONTRACT_MASTER_SID) REFERENCES CONTRACT_MASTER(CONTRACT_MASTER_SID)
END

GO


------------------------------------------------- CFP_CONTRACT_SID REFERENCE FROM CFP_CONTRACT TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_CFP_CONTRACT_CFP_CONTRACT_SID'
                     AND TYPE = 'F')
BEGIN
  ALTER TABLE [dbo].[RS_CONTRACT]
    ADD CONSTRAINT FK_RS_CONTRACT_CFP_CONTRACT_CFP_CONTRACT_SID FOREIGN KEY(CFP_CONTRACT_SID) REFERENCES CFP_CONTRACT(CFP_CONTRACT_SID)
END

GO

------------------------------------------------- IFP_CONTRACT_SID REFERENCE FROM IFP_CONTRACT TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_IFP_CONTRACT_IFP_CONTRACT_SID'
                     AND TYPE = 'F')
BEGIN
  ALTER TABLE [dbo].[RS_CONTRACT]
    ADD CONSTRAINT FK_RS_CONTRACT_IFP_CONTRACT_IFP_CONTRACT_SID FOREIGN KEY(IFP_CONTRACT_SID) REFERENCES IFP_CONTRACT(IFP_CONTRACT_SID)
END

GO

------------------------------------------------- PS_CONTRACT_SID REFERENCE FROM PS_CONTRACT TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_PS_CONTRACT_PS_CONTRACT_SID'
                     AND TYPE = 'F')
BEGIN
  ALTER TABLE [dbo].[RS_CONTRACT]
    ADD CONSTRAINT FK_RS_CONTRACT_PS_CONTRACT_PS_CONTRACT_SID FOREIGN KEY(PS_CONTRACT_SID) REFERENCES PS_CONTRACT(PS_CONTRACT_SID)
END

GO

------------------------------------------------- RS_MODEL_SID REFERENCE FROM RS_MODEL TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_RS_MODEL_RS_MODEL_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_RS_MODEL_RS_MODEL_SID FOREIGN KEY(RS_MODEL_SID) REFERENCES RS_MODEL(RS_MODEL_SID)
  END

GO
------------------------------------------------- REBATE_PROCESSING_TYPE REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_HELPER_TABLE_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_HELPER_TABLE_SID FOREIGN KEY(REBATE_PROCESSING_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

--------------------------------REBATE_PLAN_LEVEL REFERENCE FROM HELPER TABLE -----------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_REBATE_PLAN_LEVEL'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_REBATE_PLAN_LEVEL  FOREIGN KEY(REBATE_PLAN_LEVEL) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO


------------------------------------------------- REBATE_PROGRAM_TYPE REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_REBATE_PROGRAM_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_REBATE_PROGRAM_TYPE FOREIGN KEY(REBATE_PROGRAM_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- REBATE_RULE_TYPE REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_REBATE_RULE_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_REBATE_RULE_TYPE FOREIGN KEY(REBATE_RULE_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- RS_TYPE REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_RS_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_RS_TYPE FOREIGN KEY(RS_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- RS_CONTRACT_ATTACHED_STATUS REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_RS_CONTRACT_ATTACHED_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_RS_CONTRACT_ATTACHED_STATUS FOREIGN KEY(RS_CONTRACT_ATTACHED_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- RS_STATUS REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_RS_STATUS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_RS_STATUS FOREIGN KEY(RS_STATUS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- PAYMENT_FREQUENCY REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_PAYMENT_FREQUENCY'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_PAYMENT_FREQUENCY FOREIGN KEY(PAYMENT_FREQUENCY) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- PAYMENT_METHOD REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_PAYMENT_METHOD'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_PAYMENT_METHOD FOREIGN KEY(PAYMENT_METHOD) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- PAYMENT_TERMS REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_PAYMENT_TERMS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_PAYMENT_TERMS FOREIGN KEY(PAYMENT_TERMS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- RS_CATEGORY REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_RS_CATEGORY'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_RS_CATEGORY FOREIGN KEY(RS_CATEGORY) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- STATE REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_STATE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_STATE FOREIGN KEY(STATE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- RS_TRADE_CLASS REFERENCE FROM HELPER TABLE -----------------------------
IF EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_TRADE_CLASS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        DROP CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_TRADE_CLASS 
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_RS_TRADE_CLASS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_RS_TRADE_CLASS  FOREIGN KEY(RS_TRADE_CLASS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO
------------------------------------------------- RS_CALENDAR REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_RS_CALENDAR'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_RS_CALENDAR  FOREIGN KEY(RS_CALENDAR) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO
------------------------------------------------- RS_DESIGNATION REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_RS_DESIGNATION'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_RS_DESIGNATION  FOREIGN KEY(RS_DESIGNATION) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO

------------------------------------------------- REBATE_FREQUENCY REFERENCE FROM HELPER TABLE -----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_REBATE_FREQUENCY'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_REBATE_FREQUENCY FOREIGN KEY(REBATE_FREQUENCY) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO

------------------------------------------------- RS_VALIDATION_PROFILE REFERENCE FROM HELPER TABLE -----------------------------
IF EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_VALIDATION_PROFILE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        DROP CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_VALIDATION_PROFILE 
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_RS_VALIDATION_PROFILE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_RS_VALIDATION_PROFILE  FOREIGN KEY(RS_VALIDATION_PROFILE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_INTEREST_BEARING_INDICATOR'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_INTEREST_BEARING_INDICATOR FOREIGN KEY(INTEREST_BEARING_INDICATOR) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_HELPER_TABLE_INTEREST_BEARING_BASIS'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE RS_CONTRACT
        ADD CONSTRAINT FK_RS_CONTRACT_HELPER_TABLE_INTEREST_BEARING_BASIS FOREIGN KEY(INTEREST_BEARING_BASIS) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END

GO
-------------------------------------------------- RS CONTRACT DETAILS ---------------------------------------------------------

-------------------------------------------------- RS_CONTRACT_SID REFERENCE FROM RS_CONTRACT TABLE ----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_Name(PARENT_OBJECT_ID) = 'RS_CONTRACT_DETAILS'
                 AND scHema_Name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_RS_CONTRACT_DETAILS_RS_CONTRACT_RS_CONTRACT_SID'
                 AND TYPE = 'F')
BEGIN  
  ALTER TABLE [dbo].[RS_CONTRACT_DETAILS]
    ADD CONSTRAINT FK_RS_CONTRACT_DETAILS_RS_CONTRACT_RS_CONTRACT_SID FOREIGN KEY(RS_CONTRACT_SID)
	REFERENCES RS_CONTRACT(RS_CONTRACT_SID)
END
GO

-------------------------------------------------- ITEM_MASTER_SID REFERENCE FROM ITEM_MASTER TABLE ----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_Name(PARENT_OBJECT_ID) = 'RS_CONTRACT_DETAILS'
                 AND scHema_Name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_RS_CONTRACT_DETAILS_ITEM_MASTER_ITEM_MASTER_SID'
                 AND TYPE = 'F')
BEGIN
  ALTER TABLE [dbo].[RS_CONTRACT_DETAILS]
    ADD CONSTRAINT FK_RS_CONTRACT_DETAILS_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID)
	REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
END
GO

-------------------------------------------------- REBATE_PLAN_MASTER_SID REFERENCE FROM REBATE_PLAN_MASTER TABLE ----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_Name(PARENT_OBJECT_ID) = 'RS_CONTRACT_DETAILS'
                 AND scHema_Name(SCHEMA_ID) = 'DBO'
                 AND NAME = 'FK_RS_CONTRACT_DETAILS_REBATE_PLAN_MASTER_REBATE_PLAN_MASTER_SID'
                 AND TYPE = 'F')
  ALTER TABLE [dbo].[RS_CONTRACT_DETAILS]
    ADD CONSTRAINT FK_RS_CONTRACT_DETAILS_REBATE_PLAN_MASTER_REBATE_PLAN_MASTER_SID FOREIGN KEY(REBATE_PLAN_MASTER_SID)
	REFERENCES REBATE_PLAN_MASTER(REBATE_PLAN_MASTER_SID)

GO

-------------------------------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_DETAILS_DEDUCTION_CALENDAR_MASTER_DEDUCTION_CALENDAR_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[RS_CONTRACT_DETAILS]
        ADD CONSTRAINT FK_RS_CONTRACT_DETAILS_DEDUCTION_CALENDAR_MASTER_DEDUCTION_CALENDAR_MASTER_SID FOREIGN KEY(DEDUCTION_CALENDAR_MASTER_SID) REFERENCES DEDUCTION_CALENDAR_MASTER ( DEDUCTION_CALENDAR_MASTER_SID)
  END

GO

-------------------------------------------------------------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT_DETAILS'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_DETAILS_NET_SALES_FORMULA_MASTER_NET_SALES_FORMULA_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [DBO].[RS_CONTRACT_DETAILS]
        ADD CONSTRAINT FK_RS_CONTRACT_DETAILS_NET_SALES_FORMULA_MASTER_NET_SALES_FORMULA_MASTER_SID FOREIGN KEY(NET_SALES_FORMULA_MASTER_SID) REFERENCES NET_SALES_FORMULA_MASTER (NET_SALES_FORMULA_MASTER_SID)
  END

GO 



/*End of Rebate Schedule Contract Foreign Key Information*/
---------------------------------------------******-----------------------Foreign Key----------------------------*****----------
-------------------------------------------------- RS_CONTRACT_DETAILS_SID REFERENCE FROM RS_CONTRACT_DETAILS TABLE ----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT_DETAILS_FR'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_DETAILS_FR_RS_CONTRACT_DETAILS_RS_CONTRACT_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [dbo].[RS_CONTRACT_DETAILS_FR]
        ADD CONSTRAINT FK_RS_CONTRACT_DETAILS_FR_RS_CONTRACT_DETAILS_RS_CONTRACT_DETAILS_SID FOREIGN KEY(RS_CONTRACT_DETAILS_SID) REFERENCES RS_CONTRACT_DETAILS(RS_CONTRACT_DETAILS_SID)
  END

GO

-------------------------------------------------- ITEM_MASTER_SID REFERENCE FROM ITEM_MASTER TABLE ----------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  Object_name(PARENT_OBJECT_ID) = 'RS_CONTRACT_DETAILS_FR'
                     AND Schema_name(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_RS_CONTRACT_DETAILS_FR_ITEM_MASTER_ITEM_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE [dbo].[RS_CONTRACT_DETAILS_FR]
        ADD CONSTRAINT FK_RS_CONTRACT_DETAILS_FR_ITEM_MASTER_ITEM_MASTER_SID FOREIGN KEY(ITEM_MASTER_SID) REFERENCES ITEM_MASTER(ITEM_MASTER_SID)
  END

GO

------------------------------------------------------------- DEDUCTION_DETAILS ------------------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'DEDUCTION_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_DEDUCTION_DETAILS_CONTRACT_MASTER_CONTRACT_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE DEDUCTION_DETAILS
        ADD CONSTRAINT FK_DEDUCTION_DETAILS_CONTRACT_MASTER_CONTRACT_MASTER_SID FOREIGN KEY(CONTRACT_MASTER_SID) REFERENCES CONTRACT_MASTER(CONTRACT_MASTER_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'DEDUCTION_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_DEDUCTION_DETAILS_RS_CONTRACT_RS_CONTRACT_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE DEDUCTION_DETAILS
        ADD CONSTRAINT FK_DEDUCTION_DETAILS_RS_CONTRACT_RS_CONTRACT_SID FOREIGN KEY(RS_CONTRACT_SID) REFERENCES RS_CONTRACT(RS_CONTRACT_SID)
  END

GO

------------------------------------------------------------- SALES_BASIS_DETAILS ------------------------------------------------
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'SALES_BASIS_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_SALES_BASIS_DETAILS_CONTRACT_MASTER_CONTRACT_MASTER_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE SALES_BASIS_DETAILS
        ADD CONSTRAINT FK_SALES_BASIS_DETAILS_CONTRACT_MASTER_CONTRACT_MASTER_SID FOREIGN KEY(CONTRACT_MASTER_SID) REFERENCES CONTRACT_MASTER(CONTRACT_MASTER_SID)
  END

GO

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'SALES_BASIS_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_SALES_BASIS_DETAILS_CFP_CONTRACT_DETAILS_CFP_CONTRACT_DETAILS_SID'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE SALES_BASIS_DETAILS
        ADD CONSTRAINT FK_SALES_BASIS_DETAILS_CFP_CONTRACT_DETAILS_CFP_CONTRACT_DETAILS_SID FOREIGN KEY(CFP_CONTRACT_DETAILS_SID) REFERENCES CFP_CONTRACT_DETAILS(CFP_CONTRACT_DETAILS_SID)
  END

GO

----PS_CONTRACT_DETAILS----------------

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_BASE_PRICE_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT_DETAILS
        ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_BASE_PRICE_TYPE FOREIGN KEY(BASE_PRICE_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO 

IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_RESET_ELIGIBLE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT_DETAILS
        ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_RESET_ELIGIBLE FOREIGN KEY(RESET_ELIGIBLE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO 
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_NET_SALES_FORMULA_MASTER_NET_PRICE_TYPE_FORMULA'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT_DETAILS
        ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_NET_SALES_FORMULA_MASTER_NET_PRICE_TYPE_FORMULA FOREIGN KEY(NET_PRICE_TYPE_FORMULA) REFERENCES NET_SALES_FORMULA_MASTER(NET_SALES_FORMULA_MASTER_SID)
  END
GO 
IF NOT EXISTS(SELECT 1
              FROM   SYS.FOREIGN_KEYS
              WHERE  OBJECT_NAME(PARENT_OBJECT_ID) = 'PS_CONTRACT_DETAILS'
                     AND SCHEMA_NAME(SCHEMA_ID) = 'DBO'
                     AND NAME = 'FK_PS_CONTRACT_DETAILS_HELPER_TABLE_NET_PRICE_TYPE'
                     AND TYPE = 'F')
  BEGIN
      ALTER TABLE PS_CONTRACT_DETAILS
        ADD CONSTRAINT FK_PS_CONTRACT_DETAILS_HELPER_TABLE_NET_PRICE_TYPE FOREIGN KEY(NET_PRICE_TYPE) REFERENCES HELPER_TABLE(HELPER_TABLE_SID)
  END
GO