base_path=$1
mkdir -p $base_path/File_Process
mkdir -p $base_path/staging/Outbound
mkdir -p $base_path/staging/Outbound/Accrual\ Rate\ Projection
mkdir -p $base_path/staging/Outbound/Accrual\ Rate\ Projection/Output
mkdir -p $base_path/staging/Outbound/Processed
mkdir -p $base_path/staging/Outbound/Relationship_Builder
mkdir -p $base_path/staging/Outbound/Hierarchy_Definition
mkdir -p $base_path/staging/Outbound/Cff_Outbound
mkdir -p $base_path/staging/Outbound/ADJUSTMENT_DETAILS_RESERVE
mkdir -p $base_path/staging/Outbound/ADJUSTMENT_DETAILS_GTN
mkdir -p $base_path/staging/Inbound
mkdir -p $base_path/staging/Inbound/RETURNS_INTERFACE
mkdir -p $base_path/staging/Inbound/RETURNS_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/RETURNS_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/RETURNS_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/GL_POSTING_INTERFACE
mkdir -p $base_path/staging/Inbound/GL_POSTING_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/GL_POSTING_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/GL_POSTING_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/GL_BALANCE_INTERFACE
mkdir -p $base_path/staging/Inbound/GL_BALANCE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/GL_BALANCE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/GL_BALANCE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/REBATE_SCHEDULE_INTERFACE
mkdir -p $base_path/staging/Inbound/REBATE_SCHEDULE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/REBATE_SCHEDULE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/REBATE_SCHEDULE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ITEM_PRICING_INTERFACE
mkdir -p $base_path/staging/Inbound/ITEM_PRICING_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ITEM_PRICING_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ITEM_PRICING_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/REBATE_PLAN_INTERFACE
mkdir -p $base_path/staging/Inbound/REBATE_PLAN_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/REBATE_PLAN_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/REBATE_PLAN_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DEMAND_ACTUAL_INTERFACE
mkdir -p $base_path/staging/Inbound/DEMAND_ACTUAL_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DEMAND_ACTUAL_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DEMAND_ACTUAL_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/FORMULA_DETAILS_INTERFACE
mkdir -p $base_path/staging/Inbound/FORMULA_DETAILS_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/FORMULA_DETAILS_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/FORMULA_DETAILS_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ITEM_IDENTIFIER_INTERFACE
mkdir -p $base_path/staging/Inbound/ITEM_IDENTIFIER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ITEM_IDENTIFIER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ITEM_IDENTIFIER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ADJUSTED_DEMAND_FORECAST_INTERFACE
mkdir -p $base_path/staging/Inbound/ADJUSTED_DEMAND_FORECAST_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ADJUSTED_DEMAND_FORECAST_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ADJUSTED_DEMAND_FORECAST_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CUSTOMER_GTS_FORECAST_INTERFACE
mkdir -p $base_path/staging/Inbound/CUSTOMER_GTS_FORECAST_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CUSTOMER_GTS_FORECAST_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CUSTOMER_GTS_FORECAST_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PRICE_SCHEDULE_INTERFACE
mkdir -p $base_path/staging/Inbound/PRICE_SCHEDULE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PRICE_SCHEDULE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PRICE_SCHEDULE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CPI_INTERFACE
mkdir -p $base_path/staging/Inbound/CPI_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CPI_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CPI_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/COMPANY_IDENTIFIER_INTERFACE
mkdir -p $base_path/staging/Inbound/COMPANY_IDENTIFIER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/COMPANY_IDENTIFIER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/COMPANY_IDENTIFIER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/FORECAST_SALES_INTERFACE
mkdir -p $base_path/staging/Inbound/FORECAST_SALES_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/FORECAST_SALES_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/FORECAST_SALES_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ITEM_MASTER_INTERFACE
mkdir -p $base_path/staging/Inbound/ITEM_MASTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ITEM_MASTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ITEM_MASTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CONTRACT_HEADER_INTERFACE
mkdir -p $base_path/staging/Inbound/CONTRACT_HEADER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CONTRACT_HEADER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CONTRACT_HEADER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DEMAND_FORECAST_INTERFACE
mkdir -p $base_path/staging/Inbound/DEMAND_FORECAST_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DEMAND_FORECAST_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DEMAND_FORECAST_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/BEST_PRICE_INTERFACE
mkdir -p $base_path/staging/Inbound/BEST_PRICE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/BEST_PRICE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/BEST_PRICE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/COMPANY_TRADE_CLASS_INTERFACE
mkdir -p $base_path/staging/Inbound/COMPANY_TRADE_CLASS_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/COMPANY_TRADE_CLASS_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/COMPANY_TRADE_CLASS_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/COMPANY_PARENT_INTERFACE
mkdir -p $base_path/staging/Inbound/COMPANY_PARENT_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/COMPANY_PARENT_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/COMPANY_PARENT_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ADJUSTED_DEMAND_ACTUAL_INTERFACE
mkdir -p $base_path/staging/Inbound/ADJUSTED_DEMAND_ACTUAL_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ADJUSTED_DEMAND_ACTUAL_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ADJUSTED_DEMAND_ACTUAL_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/AVERAGE_SHELF_LIFE_INTERFACE
mkdir -p $base_path/staging/Inbound/AVERAGE_SHELF_LIFE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/AVERAGE_SHELF_LIFE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/AVERAGE_SHELF_LIFE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CUSTOMER_GTS_ACTUAL_INTERFACE
mkdir -p $base_path/staging/Inbound/CUSTOMER_GTS_ACTUAL_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CUSTOMER_GTS_ACTUAL_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CUSTOMER_GTS_ACTUAL_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ACCRUAL_INBOUND_INTERFACE
mkdir -p $base_path/staging/Inbound/ACCRUAL_INBOUND_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ACCRUAL_INBOUND_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ACCRUAL_INBOUND_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/SALES_MASTER_INTERFACE
mkdir -p $base_path/staging/Inbound/SALES_MASTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/SALES_MASTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/SALES_MASTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ACTUAL_MASTER_INTERFACE
mkdir -p $base_path/staging/Inbound/ACTUAL_MASTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ACTUAL_MASTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ACTUAL_MASTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/LOT_MASTER_INTERFACE
mkdir -p $base_path/staging/Inbound/LOT_MASTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/LOT_MASTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/LOT_MASTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/COMPANY_MASTER_INTERFACE
mkdir -p $base_path/staging/Inbound/COMPANY_MASTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/COMPANY_MASTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/COMPANY_MASTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ITEM_HIERARCHY_INTERFACE
mkdir -p $base_path/staging/Inbound/ITEM_HIERARCHY_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ITEM_HIERARCHY_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ITEM_HIERARCHY_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/MASTER_DATA_ATTRIBUTE_INTERFACE
mkdir -p $base_path/staging/Inbound/MASTER_DATA_ATTRIBUTE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/MASTER_DATA_ATTRIBUTE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/MASTER_DATA_ATTRIBUTE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ITEM_FAMILY_PLAN_INTERFACE
mkdir -p $base_path/staging/Inbound/ITEM_FAMILY_PLAN_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ITEM_FAMILY_PLAN_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ITEM_FAMILY_PLAN_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ITEM_HIERARCHY_DEFINATION_INTERFACE
mkdir -p $base_path/staging/Inbound/ITEM_HIERARCHY_DEFINATION_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ITEM_HIERARCHY_DEFINATION_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ITEM_HIERARCHY_DEFINATION_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/COMPANY_FAMILY_PLAN_INTERFACE
mkdir -p $base_path/staging/Inbound/COMPANY_FAMILY_PLAN_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/COMPANY_FAMILY_PLAN_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/COMPANY_FAMILY_PLAN_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/GL_COST_CENTER_INTERFACE
mkdir -p $base_path/staging/Inbound/GL_COST_CENTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/GL_COST_CENTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/GL_COST_CENTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/RETURN_RATE_FORECAST_INTERFACE
mkdir -p $base_path/staging/Inbound/RETURN_RATE_FORECAST_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/RETURN_RATE_FORECAST_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/RETURN_RATE_FORECAST_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ITEM_UOM_INTERFACE
mkdir -p $base_path/staging/Inbound/ITEM_UOM_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ITEM_UOM_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ITEM_UOM_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_MASTER_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_MASTER_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_MASTER_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_MASTER_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_IDENTIFIER_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_IDENTIFIER_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_IDENTIFIER_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_IDENTIFIER_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_TRADE_CLASS_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_TRADE_CLASS_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_TRADE_CLASS_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_TRADE_CLASS_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_IDENTIFIER_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_IDENTIFIER_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_IDENTIFIER_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_IDENTIFIER_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_MASTER_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_MASTER_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_MASTER_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_MASTER_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_PRICING_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_PRICING_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_PRICING_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_PRICING_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_CONTRACT_HEADER_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_CONTRACT_HEADER_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_CONTRACT_HEADER_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_CONTRACT_HEADER_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_FAMILY_PLAN_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_FAMILY_PLAN_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_FAMILY_PLAN_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_COMPANY_FAMILY_PLAN_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_FAMILY_PLAN_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_FAMILY_PLAN_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_FAMILY_PLAN_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_FAMILY_PLAN_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_REBATE_PLAN_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_REBATE_PLAN_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_REBATE_PLAN_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_REBATE_PLAN_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_PRICE_SCHEDULE_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_PRICE_SCHEDULE_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_PRICE_SCHEDULE_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_PRICE_SCHEDULE_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_REBATE_SCHEDULE_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_REBATE_SCHEDULE_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_REBATE_SCHEDULE_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_REBATE_SCHEDULE_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_SALES_MASTER_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_SALES_MASTER_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_SALES_MASTER_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_SALES_MASTER_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_CUSTOMER_GTS_ACTUAL_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_CUSTOMER_GTS_ACTUAL_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_CUSTOMER_GTS_ACTUAL_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_CUSTOMER_GTS_ACTUAL_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_CUSTOMER_GTS_FORECAST_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_CUSTOMER_GTS_FORECAST_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_CUSTOMER_GTS_FORECAST_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_CUSTOMER_GTS_FORECAST_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_RETURNS_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_RETURNS_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_RETURNS_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_RETURNS_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_CPI_INDEX_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_CPI_INDEX_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_CPI_INDEX_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_CPI_INDEX_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_GL_COST_CENTER_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_GL_COST_CENTER_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_GL_COST_CENTER_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_GL_COST_CENTER_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_UOM_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_UOM_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_UOM_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_UOM_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ACCRUAL_INBOUND_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ACCRUAL_INBOUND_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ACCRUAL_INBOUND_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ACCRUAL_INBOUND_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_FORECASTING_MASTER_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_FORECASTING_MASTER_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_FORECASTING_MASTER_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_FORECASTING_MASTER_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_CHARGEBACK_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_CHARGEBACK_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_CHARGEBACK_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_CHARGEBACK_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_MEDICAID_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_MEDICAID_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_MEDICAID_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_MEDICAID_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_REBATE_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_REBATE_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_REBATE_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_REBATE_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_COUPON_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_COUPON_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_COUPON_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ACTUAL_MASTER_COUPON_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_HIERARCHY_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_HIERARCHY_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_HIERARCHY_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_HIERARCHY_INTERFACE/Input
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_BUSINESS_WAREHOUSE_INTERFACE
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_BUSINESS_WAREHOUSE_INTERFACE/Error
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_BUSINESS_WAREHOUSE_INTERFACE/Processed
rm -rf $base_path/staging/Inbound/ADROIT_ITEM_BUSINESS_WAREHOUSE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ACTUALS_CHARGEBACK_INTERFACE
mkdir -p $base_path/staging/Inbound/ACTUALS_CHARGEBACK_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ACTUALS_CHARGEBACK_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ACTUALS_CHARGEBACK_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ACTUALS_MEDICAID_INTERFACE
mkdir -p $base_path/staging/Inbound/ACTUALS_MEDICAID_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ACTUALS_MEDICAID_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ACTUALS_MEDICAID_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ACTUALS_REBATE_INTERFACE
mkdir -p $base_path/staging/Inbound/ACTUALS_REBATE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ACTUALS_REBATE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ACTUALS_REBATE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ACTUALS_COUPON_INTERFACE
mkdir -p $base_path/staging/Inbound/ACTUALS_COUPON_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ACTUALS_COUPON_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ACTUALS_COUPON_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_HIERARCHY_INTERFACE
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_HIERARCHY_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_HIERARCHY_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_HIERARCHY_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_BW_INTERFACE
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_BW_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_BW_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_BW_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/COMPANY_BUNIT_INTERFACE
mkdir -p $base_path/staging/Inbound/COMPANY_BUNIT_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/COMPANY_BUNIT_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/COMPANY_BUNIT_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/COMPANY_BUID_INTERFACE
mkdir -p $base_path/staging/Inbound/COMPANY_BUID_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/COMPANY_BUID_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/COMPANY_BUID_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/COMPANY_BUTYPE_INTERFACE
mkdir -p $base_path/staging/Inbound/COMPANY_BUTYPE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/COMPANY_BUTYPE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/COMPANY_BUTYPE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PRODUCT_PRODID_INTERFACE
mkdir -p $base_path/staging/Inbound/PRODUCT_PRODID_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PRODUCT_PRODID_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PRODUCT_PRODID_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_INTERFACE
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PRODUCT_PROD_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PRICING_INTERFACE
mkdir -p $base_path/staging/Inbound/PRICING_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PRICING_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PRICING_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CONTRACT_CONT_INTERFACE
mkdir -p $base_path/staging/Inbound/CONTRACT_CONT_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CONTRACT_CONT_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CONTRACT_CONT_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CONTRACT_CPGRP_INTERFACE
mkdir -p $base_path/staging/Inbound/CONTRACT_CPGRP_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CONTRACT_CPGRP_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CONTRACT_CPGRP_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CONTRACT_CPPPO_INTERFACE
mkdir -p $base_path/staging/Inbound/CONTRACT_CPPPO_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CONTRACT_CPPPO_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CONTRACT_CPPPO_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CONTRACT_CPPT_INTERFACE
mkdir -p $base_path/staging/Inbound/CONTRACT_CPPT_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CONTRACT_CPPT_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CONTRACT_CPPT_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CONTRACT_CPGRP_PGMMKT_INTERFACE
mkdir -p $base_path/staging/Inbound/CONTRACT_CPGRP_PGMMKT_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CONTRACT_CPGRP_PGMMKT_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CONTRACT_CPGRP_PGMMKT_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CONTRACT_PRGMMKT_INTERFACE
mkdir -p $base_path/staging/Inbound/CONTRACT_PRGMMKT_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CONTRACT_PRGMMKT_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CONTRACT_PRGMMKT_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PSTG_SALES_MASTER_INTERFACE
mkdir -p $base_path/staging/Inbound/PSTG_SALES_MASTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PSTG_SALES_MASTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PSTG_SALES_MASTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PSTG_CUSTOMER_GTS_ACTUAL_INTERFACE
mkdir -p $base_path/staging/Inbound/PSTG_CUSTOMER_GTS_ACTUAL_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PSTG_CUSTOMER_GTS_ACTUAL_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PSTG_CUSTOMER_GTS_ACTUAL_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PSTG_CUSTOMER_GTS_FORECAST_INTERFACE
mkdir -p $base_path/staging/Inbound/PSTG_CUSTOMER_GTS_FORECAST_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PSTG_CUSTOMER_GTS_FORECAST_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PSTG_CUSTOMER_GTS_FORECAST_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PSTG_RETURNS_INTERFACE
mkdir -p $base_path/staging/Inbound/PSTG_RETURNS_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PSTG_RETURNS_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PSTG_RETURNS_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CONSUMER_PRICE_INDEX_INTERFACE
mkdir -p $base_path/staging/Inbound/CONSUMER_PRICE_INDEX_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CONSUMER_PRICE_INDEX_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CONSUMER_PRICE_INDEX_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PSTG_GL_COST_CENTER_INTERFACE
mkdir -p $base_path/staging/Inbound/PSTG_GL_COST_CENTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PSTG_GL_COST_CENTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PSTG_GL_COST_CENTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/UNIT_OF_MEASURE_INTERFACE
mkdir -p $base_path/staging/Inbound/UNIT_OF_MEASURE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/UNIT_OF_MEASURE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/UNIT_OF_MEASURE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ACCRUALS_INTERFACE
mkdir -p $base_path/staging/Inbound/ACCRUALS_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ACCRUALS_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ACCRUALS_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PSTG_SALES_FORECAST_INTERFACE
mkdir -p $base_path/staging/Inbound/PSTG_SALES_FORECAST_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PSTG_SALES_FORECAST_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PSTG_SALES_FORECAST_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/CONTRACT_CFP_MBR_INTERFACE
mkdir -p $base_path/staging/Inbound/CONTRACT_CFP_MBR_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/CONTRACT_CFP_MBR_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/CONTRACT_CFP_MBR_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PSTG_GCC_PROD_HIERARCHY_INTERFACE
mkdir -p $base_path/staging/Inbound/PSTG_GCC_PROD_HIERARCHY_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PSTG_GCC_PROD_HIERARCHY_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PSTG_GCC_PROD_HIERARCHY_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/PSTG_FORECAST_SALES_WAC_INTERFACE
mkdir -p $base_path/staging/Inbound/PSTG_FORECAST_SALES_WAC_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/PSTG_FORECAST_SALES_WAC_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/PSTG_FORECAST_SALES_WAC_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_UOM_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_UOM_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_UOM_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_UOM_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CPI_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CPI_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CPI_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CPI_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_RETURN_RATE_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_RETURN_RATE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_RETURN_RATE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_RETURN_RATE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_ITEM_PRICING_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_ITEM_PRICING_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_ITEM_PRICING_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_ITEM_PRICING_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_ACCRUAL_ACTUAL_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_ACCRUAL_ACTUAL_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_ACCRUAL_ACTUAL_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_ACCRUAL_ACTUAL_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_ITEM_MASTER_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_ITEM_MASTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_ITEM_MASTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_ITEM_MASTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_ITEM_IDENTIFIER_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_ITEM_IDENTIFIER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_ITEM_IDENTIFIER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_ITEM_IDENTIFIER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CUSTOMER_GTS_ACTUAL_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CUSTOMER_GTS_ACTUAL_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CUSTOMER_GTS_ACTUAL_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CUSTOMER_GTS_ACTUAL_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CUSTOMER_GTS_FORECAST_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CUSTOMER_GTS_FORECAST_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CUSTOMER_GTS_FORECAST_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CUSTOMER_GTS_FORECAST_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_MASTER_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_MASTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_MASTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_MASTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_TRADE_CLASS_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_TRADE_CLASS_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_TRADE_CLASS_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_TRADE_CLASS_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/ARM_LOAD_INTERFACE
mkdir -p $base_path/staging/Inbound/ARM_LOAD_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/ARM_LOAD_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/ARM_LOAD_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_IDENTIFIER_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_IDENTIFIER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_IDENTIFIER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_COMPANY_IDENTIFIER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CFP_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CFP_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CFP_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CFP_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_HEADER_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_HEADER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_HEADER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_HEADER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_FORECAST_SALES_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_FORECAST_SALES_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_FORECAST_SALES_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_FORECAST_SALES_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_FORECAST_SALES_WAC_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_FORECAST_SALES_WAC_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_FORECAST_SALES_WAC_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_FORECAST_SALES_WAC_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_IFP_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_IFP_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_IFP_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_IFP_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPGRP_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPGRP_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPGRP_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPGRP_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_PRICE_PLAN_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_PRICE_PLAN_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_PRICE_PLAN_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_PRICE_PLAN_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPPPO_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPPPO_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPPPO_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPPPO_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPGRP_PGM_MKT_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPGRP_PGM_MKT_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPGRP_PGM_MKT_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CPGRP_PGM_MKT_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_PRICE_SCHEDULE_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_PRICE_SCHEDULE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_PRICE_SCHEDULE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_PRICE_SCHEDULE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CONT_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CONT_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CONT_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_CONT_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_REBATE_PLAN_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_REBATE_PLAN_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_REBATE_PLAN_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_REBATE_PLAN_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_REBATE_SCHEDULE_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_REBATE_SCHEDULE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_REBATE_SCHEDULE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_CONTRACT_REBATE_SCHEDULE_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_GL_COST_CENTER_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_GL_COST_CENTER_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_GL_COST_CENTER_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_GL_COST_CENTER_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_ACTUAL_MASTER_COUPON_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_ACTUAL_MASTER_COUPON_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_ACTUAL_MASTER_COUPON_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_ACTUAL_MASTER_COUPON_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_ACTUAL_MASTER_MEDICAID_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_ACTUAL_MASTER_MEDICAID_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_ACTUAL_MASTER_MEDICAID_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_ACTUAL_MASTER_MEDICAID_INTERFACE/Input
mkdir -p $base_path/staging/Inbound/DTX_ACTUALS_MASTER_REBATE_INTERFACE
mkdir -p $base_path/staging/Inbound/DTX_ACTUALS_MASTER_REBATE_INTERFACE/Error
mkdir -p $base_path/staging/Inbound/DTX_ACTUALS_MASTER_REBATE_INTERFACE/Processed
mkdir -p $base_path/staging/Inbound/DTX_ACTUALS_MASTER_REBATE_INTERFACE/Input