mkdir -p ./File_Process
mkdir -p ./staging/Outbound
mkdir -p ./staging/Outbound/Accrual\ Rate\ Projection
mkdir -p ./staging/Outbound/Accrual\ Rate\ Projection/Output
mkdir -p ./staging/Outbound/Processed
mkdir -p ./staging/Outbound/Relationship_Builder
mkdir -p ./staging/Outbound/Hierarchy_Definition
mkdir -p ./staging/Outbound/Cff_Outbound
mkdir -p ./staging/Outbound/ADJUSTMENT_DETAILS_RESERVE
mkdir -p ./staging/Outbound/ADJUSTMENT_DETAILS_GTN
mkdir -p ./staging/Inbound
mkdir -p ./staging/Inbound/RETURNS_INTERFACE
mkdir -p ./staging/Inbound/RETURNS_INTERFACE/Error
mkdir -p ./staging/Inbound/RETURNS_INTERFACE/Processed
mkdir -p ./staging/Inbound/RETURNS_INTERFACE/Input
mkdir -p ./staging/Inbound/GL_POSTING_INTERFACE
mkdir -p ./staging/Inbound/GL_POSTING_INTERFACE/Error
mkdir -p ./staging/Inbound/GL_POSTING_INTERFACE/Processed
mkdir -p ./staging/Inbound/GL_POSTING_INTERFACE/Input
mkdir -p ./staging/Inbound/GL_BALANCE_INTERFACE
mkdir -p ./staging/Inbound/GL_BALANCE_INTERFACE/Error
mkdir -p ./staging/Inbound/GL_BALANCE_INTERFACE/Processed
mkdir -p ./staging/Inbound/GL_BALANCE_INTERFACE/Input
mkdir -p ./staging/Inbound/REBATE_SCHEDULE_INTERFACE
mkdir -p ./staging/Inbound/REBATE_SCHEDULE_INTERFACE/Error
mkdir -p ./staging/Inbound/REBATE_SCHEDULE_INTERFACE/Processed
mkdir -p ./staging/Inbound/REBATE_SCHEDULE_INTERFACE/Input
mkdir -p ./staging/Inbound/ITEM_PRICING_INTERFACE
mkdir -p ./staging/Inbound/ITEM_PRICING_INTERFACE/Error
mkdir -p ./staging/Inbound/ITEM_PRICING_INTERFACE/Processed
mkdir -p ./staging/Inbound/ITEM_PRICING_INTERFACE/Input
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE/Error
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE/Processed
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_SUMMARY_INTERFACE/Input
mkdir -p ./staging/Inbound/REBATE_PLAN_INTERFACE
mkdir -p ./staging/Inbound/REBATE_PLAN_INTERFACE/Error
mkdir -p ./staging/Inbound/REBATE_PLAN_INTERFACE/Processed
mkdir -p ./staging/Inbound/REBATE_PLAN_INTERFACE/Input
mkdir -p ./staging/Inbound/DEMAND_ACTUAL_INTERFACE
mkdir -p ./staging/Inbound/DEMAND_ACTUAL_INTERFACE/Error
mkdir -p ./staging/Inbound/DEMAND_ACTUAL_INTERFACE/Processed
mkdir -p ./staging/Inbound/DEMAND_ACTUAL_INTERFACE/Input
mkdir -p ./staging/Inbound/FORMULA_DETAILS_INTERFACE
mkdir -p ./staging/Inbound/FORMULA_DETAILS_INTERFACE/Error
mkdir -p ./staging/Inbound/FORMULA_DETAILS_INTERFACE/Processed
mkdir -p ./staging/Inbound/FORMULA_DETAILS_INTERFACE/Input
mkdir -p ./staging/Inbound/ITEM_IDENTIFIER_INTERFACE
mkdir -p ./staging/Inbound/ITEM_IDENTIFIER_INTERFACE/Error
mkdir -p ./staging/Inbound/ITEM_IDENTIFIER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ITEM_IDENTIFIER_INTERFACE/Input
mkdir -p ./staging/Inbound/ADJUSTED_DEMAND_FORECAST_INTERFACE
mkdir -p ./staging/Inbound/ADJUSTED_DEMAND_FORECAST_INTERFACE/Error
mkdir -p ./staging/Inbound/ADJUSTED_DEMAND_FORECAST_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADJUSTED_DEMAND_FORECAST_INTERFACE/Input
mkdir -p ./staging/Inbound/CUSTOMER_GTS_FORECAST_INTERFACE
mkdir -p ./staging/Inbound/CUSTOMER_GTS_FORECAST_INTERFACE/Error
mkdir -p ./staging/Inbound/CUSTOMER_GTS_FORECAST_INTERFACE/Processed
mkdir -p ./staging/Inbound/CUSTOMER_GTS_FORECAST_INTERFACE/Input
mkdir -p ./staging/Inbound/PRICE_SCHEDULE_INTERFACE
mkdir -p ./staging/Inbound/PRICE_SCHEDULE_INTERFACE/Error
mkdir -p ./staging/Inbound/PRICE_SCHEDULE_INTERFACE/Processed
mkdir -p ./staging/Inbound/PRICE_SCHEDULE_INTERFACE/Input
mkdir -p ./staging/Inbound/CPI_INTERFACE
mkdir -p ./staging/Inbound/CPI_INTERFACE/Error
mkdir -p ./staging/Inbound/CPI_INTERFACE/Processed
mkdir -p ./staging/Inbound/CPI_INTERFACE/Input
mkdir -p ./staging/Inbound/COMPANY_IDENTIFIER_INTERFACE
mkdir -p ./staging/Inbound/COMPANY_IDENTIFIER_INTERFACE/Error
mkdir -p ./staging/Inbound/COMPANY_IDENTIFIER_INTERFACE/Processed
mkdir -p ./staging/Inbound/COMPANY_IDENTIFIER_INTERFACE/Input
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE/Error
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE/Processed
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_SUMMARY_INTERFACE/Input
mkdir -p ./staging/Inbound/FORECAST_SALES_INTERFACE
mkdir -p ./staging/Inbound/FORECAST_SALES_INTERFACE/Error
mkdir -p ./staging/Inbound/FORECAST_SALES_INTERFACE/Processed
mkdir -p ./staging/Inbound/FORECAST_SALES_INTERFACE/Input
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE/Error
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE/Processed
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_ACTUAL_DETAIL_INTERFACE/Input
mkdir -p ./staging/Inbound/ITEM_MASTER_INTERFACE
mkdir -p ./staging/Inbound/ITEM_MASTER_INTERFACE/Error
mkdir -p ./staging/Inbound/ITEM_MASTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ITEM_MASTER_INTERFACE/Input
mkdir -p ./staging/Inbound/CONTRACT_HEADER_INTERFACE
mkdir -p ./staging/Inbound/CONTRACT_HEADER_INTERFACE/Error
mkdir -p ./staging/Inbound/CONTRACT_HEADER_INTERFACE/Processed
mkdir -p ./staging/Inbound/CONTRACT_HEADER_INTERFACE/Input
mkdir -p ./staging/Inbound/DEMAND_FORECAST_INTERFACE
mkdir -p ./staging/Inbound/DEMAND_FORECAST_INTERFACE/Error
mkdir -p ./staging/Inbound/DEMAND_FORECAST_INTERFACE/Processed
mkdir -p ./staging/Inbound/DEMAND_FORECAST_INTERFACE/Input
mkdir -p ./staging/Inbound/BEST_PRICE_INTERFACE
mkdir -p ./staging/Inbound/BEST_PRICE_INTERFACE/Error
mkdir -p ./staging/Inbound/BEST_PRICE_INTERFACE/Processed
mkdir -p ./staging/Inbound/BEST_PRICE_INTERFACE/Input
mkdir -p ./staging/Inbound/COMPANY_TRADE_CLASS_INTERFACE
mkdir -p ./staging/Inbound/COMPANY_TRADE_CLASS_INTERFACE/Error
mkdir -p ./staging/Inbound/COMPANY_TRADE_CLASS_INTERFACE/Processed
mkdir -p ./staging/Inbound/COMPANY_TRADE_CLASS_INTERFACE/Input
mkdir -p ./staging/Inbound/COMPANY_PARENT_INTERFACE
mkdir -p ./staging/Inbound/COMPANY_PARENT_INTERFACE/Error
mkdir -p ./staging/Inbound/COMPANY_PARENT_INTERFACE/Processed
mkdir -p ./staging/Inbound/COMPANY_PARENT_INTERFACE/Input
mkdir -p ./staging/Inbound/ADJUSTED_DEMAND_ACTUAL_INTERFACE
mkdir -p ./staging/Inbound/ADJUSTED_DEMAND_ACTUAL_INTERFACE/Error
mkdir -p ./staging/Inbound/ADJUSTED_DEMAND_ACTUAL_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADJUSTED_DEMAND_ACTUAL_INTERFACE/Input
mkdir -p ./staging/Inbound/AVERAGE_SHELF_LIFE_INTERFACE
mkdir -p ./staging/Inbound/AVERAGE_SHELF_LIFE_INTERFACE/Error
mkdir -p ./staging/Inbound/AVERAGE_SHELF_LIFE_INTERFACE/Processed
mkdir -p ./staging/Inbound/AVERAGE_SHELF_LIFE_INTERFACE/Input
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE/Error
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE/Processed
mkdir -p ./staging/Inbound/INVENTORY_WITHDRAWAL_PROJECTED_DETAIL_INTERFACE/Input
mkdir -p ./staging/Inbound/CUSTOMER_GTS_ACTUAL_INTERFACE
mkdir -p ./staging/Inbound/CUSTOMER_GTS_ACTUAL_INTERFACE/Error
mkdir -p ./staging/Inbound/CUSTOMER_GTS_ACTUAL_INTERFACE/Processed
mkdir -p ./staging/Inbound/CUSTOMER_GTS_ACTUAL_INTERFACE/Input
mkdir -p ./staging/Inbound/ACCRUAL_INBOUND_INTERFACE
mkdir -p ./staging/Inbound/ACCRUAL_INBOUND_INTERFACE/Error
mkdir -p ./staging/Inbound/ACCRUAL_INBOUND_INTERFACE/Processed
mkdir -p ./staging/Inbound/ACCRUAL_INBOUND_INTERFACE/Input
mkdir -p ./staging/Inbound/SALES_MASTER_INTERFACE
mkdir -p ./staging/Inbound/SALES_MASTER_INTERFACE/Error
mkdir -p ./staging/Inbound/SALES_MASTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/SALES_MASTER_INTERFACE/Input
mkdir -p ./staging/Inbound/ACTUAL_MASTER_INTERFACE
mkdir -p ./staging/Inbound/ACTUAL_MASTER_INTERFACE/Error
mkdir -p ./staging/Inbound/ACTUAL_MASTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ACTUAL_MASTER_INTERFACE/Input
mkdir -p ./staging/Inbound/LOT_MASTER_INTERFACE
mkdir -p ./staging/Inbound/LOT_MASTER_INTERFACE/Error
mkdir -p ./staging/Inbound/LOT_MASTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/LOT_MASTER_INTERFACE/Input
mkdir -p ./staging/Inbound/COMPANY_MASTER_INTERFACE
mkdir -p ./staging/Inbound/COMPANY_MASTER_INTERFACE/Error
mkdir -p ./staging/Inbound/COMPANY_MASTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/COMPANY_MASTER_INTERFACE/Input
mkdir -p ./staging/Inbound/ITEM_HIERARCHY_INTERFACE
mkdir -p ./staging/Inbound/ITEM_HIERARCHY_INTERFACE/Error
mkdir -p ./staging/Inbound/ITEM_HIERARCHY_INTERFACE/Processed
mkdir -p ./staging/Inbound/ITEM_HIERARCHY_INTERFACE/Input
mkdir -p ./staging/Inbound/MASTER_DATA_ATTRIBUTE_INTERFACE
mkdir -p ./staging/Inbound/MASTER_DATA_ATTRIBUTE_INTERFACE/Error
mkdir -p ./staging/Inbound/MASTER_DATA_ATTRIBUTE_INTERFACE/Processed
mkdir -p ./staging/Inbound/MASTER_DATA_ATTRIBUTE_INTERFACE/Input
mkdir -p ./staging/Inbound/ITEM_FAMILY_PLAN_INTERFACE
mkdir -p ./staging/Inbound/ITEM_FAMILY_PLAN_INTERFACE/Error
mkdir -p ./staging/Inbound/ITEM_FAMILY_PLAN_INTERFACE/Processed
mkdir -p ./staging/Inbound/ITEM_FAMILY_PLAN_INTERFACE/Input
mkdir -p ./staging/Inbound/ITEM_HIERARCHY_DEFINATION_INTERFACE
mkdir -p ./staging/Inbound/ITEM_HIERARCHY_DEFINATION_INTERFACE/Error
mkdir -p ./staging/Inbound/ITEM_HIERARCHY_DEFINATION_INTERFACE/Processed
mkdir -p ./staging/Inbound/ITEM_HIERARCHY_DEFINATION_INTERFACE/Input
mkdir -p ./staging/Inbound/COMPANY_FAMILY_PLAN_INTERFACE
mkdir -p ./staging/Inbound/COMPANY_FAMILY_PLAN_INTERFACE/Error
mkdir -p ./staging/Inbound/COMPANY_FAMILY_PLAN_INTERFACE/Processed
mkdir -p ./staging/Inbound/COMPANY_FAMILY_PLAN_INTERFACE/Input
mkdir -p ./staging/Inbound/GL_COST_CENTER_INTERFACE
mkdir -p ./staging/Inbound/GL_COST_CENTER_INTERFACE/Error
mkdir -p ./staging/Inbound/GL_COST_CENTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/GL_COST_CENTER_INTERFACE/Input
mkdir -p ./staging/Inbound/RETURN_RATE_FORECAST_INTERFACE
mkdir -p ./staging/Inbound/RETURN_RATE_FORECAST_INTERFACE/Error
mkdir -p ./staging/Inbound/RETURN_RATE_FORECAST_INTERFACE/Processed
mkdir -p ./staging/Inbound/RETURN_RATE_FORECAST_INTERFACE/Input
mkdir -p ./staging/Inbound/ITEM_UOM_INTERFACE
mkdir -p ./staging/Inbound/ITEM_UOM_INTERFACE/Error
mkdir -p ./staging/Inbound/ITEM_UOM_INTERFACE/Processed
mkdir -p ./staging/Inbound/ITEM_UOM_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_CHARGEBACK_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_CHARGEBACK_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_CHARGEBACK_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_CHARGEBACK_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_MEDICAID_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_MEDICAID_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_MEDICAID_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_MEDICAID_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_REBATE_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_REBATE_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_REBATE_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_REBATE_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_COUPON_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_COUPON_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_COUPON_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ACTUAL_MASTER_COUPON_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ITEM_HIERARCHY_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ITEM_HIERARCHY_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ITEM_HIERARCHY_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ITEM_HIERARCHY_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ITEM_BUSINESS_WAREHOUSE_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ITEM_BUSINESS_WAREHOUSE_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ITEM_BUSINESS_WAREHOUSE_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ITEM_BUSINESS_WAREHOUSE_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_COMPANY_MASTER_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_COMPANY_MASTER_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_COMPANY_MASTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_COMPANY_MASTER_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_COMPANY_IDENTIFIER_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_COMPANY_IDENTIFIER_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_COMPANY_IDENTIFIER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_COMPANY_IDENTIFIER_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_COMPANY_TRADE_CLASS_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_COMPANY_TRADE_CLASS_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_COMPANY_TRADE_CLASS_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_COMPANY_TRADE_CLASS_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ITEM_IDENTIFIER_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ITEM_IDENTIFIER_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ITEM_IDENTIFIER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ITEM_IDENTIFIER_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ITEM_MASTER_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ITEM_MASTER_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ITEM_MASTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ITEM_MASTER_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ITEM_PRICING_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ITEM_PRICING_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ITEM_PRICING_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ITEM_PRICING_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_CONTRACT_HEADER_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_CONTRACT_HEADER_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_CONTRACT_HEADER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_CONTRACT_HEADER_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_COMPANY_FAMILY_PLAN_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_COMPANY_FAMILY_PLAN_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_COMPANY_FAMILY_PLAN_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_COMPANY_FAMILY_PLAN_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ITEM_FAMILY_PLAN_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ITEM_FAMILY_PLAN_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ITEM_FAMILY_PLAN_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ITEM_FAMILY_PLAN_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_REBATE_PLAN_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_REBATE_PLAN_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_REBATE_PLAN_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_REBATE_PLAN_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_PRICE_SCHEDULE_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_PRICE_SCHEDULE_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_PRICE_SCHEDULE_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_PRICE_SCHEDULE_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_REBATE_SCHEDULE_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_REBATE_SCHEDULE_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_REBATE_SCHEDULE_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_REBATE_SCHEDULE_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_SALES_MASTER_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_SALES_MASTER_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_SALES_MASTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_SALES_MASTER_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_CUSTOMER_GTS_ACTUAL_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_CUSTOMER_GTS_ACTUAL_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_CUSTOMER_GTS_ACTUAL_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_CUSTOMER_GTS_ACTUAL_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_CUSTOMER_GTS_FORECAST_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_CUSTOMER_GTS_FORECAST_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_CUSTOMER_GTS_FORECAST_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_CUSTOMER_GTS_FORECAST_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_RETURNS_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_RETURNS_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_RETURNS_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_RETURNS_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_CPI_INDEX_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_CPI_INDEX_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_CPI_INDEX_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_CPI_INDEX_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_GL_COST_CENTER_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_GL_COST_CENTER_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_GL_COST_CENTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_GL_COST_CENTER_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ITEM_UOM_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ITEM_UOM_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ITEM_UOM_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ITEM_UOM_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_ACCRUAL_INBOUND_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_ACCRUAL_INBOUND_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_ACCRUAL_INBOUND_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_ACCRUAL_INBOUND_INTERFACE/Input
mkdir -p ./staging/Inbound/ADROIT_FORECASTING_MASTER_INTERFACE
mkdir -p ./staging/Inbound/ADROIT_FORECASTING_MASTER_INTERFACE/Error
mkdir -p ./staging/Inbound/ADROIT_FORECASTING_MASTER_INTERFACE/Processed
mkdir -p ./staging/Inbound/ADROIT_FORECASTING_MASTER_INTERFACE/Input
