package com.stpl.app.parttwo.model;

import com.stpl.app.parttwo.service.persistence.StArpOutboundPK;

import com.stpl.portal.kernel.bean.AutoEscape;
import com.stpl.portal.model.BaseModel;
import com.stpl.portal.model.CacheModel;
import com.stpl.portal.service.ServiceContext;

import com.stpl.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StArpOutbound service. Represents a row in the &quot;ST_ARP_OUTBOUND&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stpl.app.parttwo.model.impl.StArpOutboundModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stpl.app.parttwo.model.impl.StArpOutboundImpl}.
 * </p>
 *
 * @author
 * @see StArpOutbound
 * @see com.stpl.app.parttwo.model.impl.StArpOutboundImpl
 * @see com.stpl.app.parttwo.model.impl.StArpOutboundModelImpl
 * @generated
 */
public interface StArpOutboundModel extends BaseModel<StArpOutbound> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a st arp outbound model instance should use the {@link StArpOutbound} interface instead.
     */

    /**
     * Returns the primary key of this st arp outbound.
     *
     * @return the primary key of this st arp outbound
     */
    public StArpOutboundPK getPrimaryKey();

    /**
     * Sets the primary key of this st arp outbound.
     *
     * @param primaryKey the primary key of this st arp outbound
     */
    public void setPrimaryKey(StArpOutboundPK primaryKey);

    /**
     * Returns the sales units rate of this st arp outbound.
     *
     * @return the sales units rate of this st arp outbound
     */
    public double getSalesUnitsRate();

    /**
     * Sets the sales units rate of this st arp outbound.
     *
     * @param salesUnitsRate the sales units rate of this st arp outbound
     */
    public void setSalesUnitsRate(double salesUnitsRate);

    /**
     * Returns the account type of this st arp outbound.
     *
     * @return the account type of this st arp outbound
     */
    @AutoEscape
    public String getAccountType();

    /**
     * Sets the account type of this st arp outbound.
     *
     * @param accountType the account type of this st arp outbound
     */
    public void setAccountType(String accountType);

    /**
     * Returns the original batch ID of this st arp outbound.
     *
     * @return the original batch ID of this st arp outbound
     */
    @AutoEscape
    public String getOriginalBatchId();

    /**
     * Sets the original batch ID of this st arp outbound.
     *
     * @param originalBatchId the original batch ID of this st arp outbound
     */
    public void setOriginalBatchId(String originalBatchId);

    /**
     * Returns the company master sid of this st arp outbound.
     *
     * @return the company master sid of this st arp outbound
     */
    public int getCompanyMasterSid();

    /**
     * Sets the company master sid of this st arp outbound.
     *
     * @param companyMasterSid the company master sid of this st arp outbound
     */
    public void setCompanyMasterSid(int companyMasterSid);

    /**
     * Returns the brand master sid of this st arp outbound.
     *
     * @return the brand master sid of this st arp outbound
     */
    public int getBrandMasterSid();

    /**
     * Sets the brand master sid of this st arp outbound.
     *
     * @param brandMasterSid the brand master sid of this st arp outbound
     */
    public void setBrandMasterSid(int brandMasterSid);

    /**
     * Returns the arp approval date of this st arp outbound.
     *
     * @return the arp approval date of this st arp outbound
     */
    public Date getArpApprovalDate();

    /**
     * Sets the arp approval date of this st arp outbound.
     *
     * @param arpApprovalDate the arp approval date of this st arp outbound
     */
    public void setArpApprovalDate(Date arpApprovalDate);

    /**
     * Returns the user ID of this st arp outbound.
     *
     * @return the user ID of this st arp outbound
     */
    public int getUserId();

    /**
     * Sets the user ID of this st arp outbound.
     *
     * @param userId the user ID of this st arp outbound
     */
    public void setUserId(int userId);

    /**
     * Returns the arp master sid of this st arp outbound.
     *
     * @return the arp master sid of this st arp outbound
     */
    public int getArpMasterSid();

    /**
     * Sets the arp master sid of this st arp outbound.
     *
     * @param arpMasterSid the arp master sid of this st arp outbound
     */
    public void setArpMasterSid(int arpMasterSid);

    /**
     * Returns the arp creation date of this st arp outbound.
     *
     * @return the arp creation date of this st arp outbound
     */
    public Date getArpCreationDate();

    /**
     * Sets the arp creation date of this st arp outbound.
     *
     * @param arpCreationDate the arp creation date of this st arp outbound
     */
    public void setArpCreationDate(Date arpCreationDate);

    /**
     * Returns the check record of this st arp outbound.
     *
     * @return the check record of this st arp outbound
     */
    public boolean getCheckRecord();

    /**
     * Returns <code>true</code> if this st arp outbound is check record.
     *
     * @return <code>true</code> if this st arp outbound is check record; <code>false</code> otherwise
     */
    public boolean isCheckRecord();

    /**
     * Sets whether this st arp outbound is check record.
     *
     * @param checkRecord the check record of this st arp outbound
     */
    public void setCheckRecord(boolean checkRecord);

    /**
     * Returns the arp ID of this st arp outbound.
     *
     * @return the arp ID of this st arp outbound
     */
    public int getArpId();

    /**
     * Sets the arp ID of this st arp outbound.
     *
     * @param arpId the arp ID of this st arp outbound
     */
    public void setArpId(int arpId);

    /**
     * Returns the account of this st arp outbound.
     *
     * @return the account of this st arp outbound
     */
    @AutoEscape
    public String getAccount();

    /**
     * Sets the account of this st arp outbound.
     *
     * @param account the account of this st arp outbound
     */
    public void setAccount(String account);

    /**
     * Returns the outbound status of this st arp outbound.
     *
     * @return the outbound status of this st arp outbound
     */
    public boolean getOutboundStatus();

    /**
     * Returns <code>true</code> if this st arp outbound is outbound status.
     *
     * @return <code>true</code> if this st arp outbound is outbound status; <code>false</code> otherwise
     */
    public boolean isOutboundStatus();

    /**
     * Sets whether this st arp outbound is outbound status.
     *
     * @param outboundStatus the outbound status of this st arp outbound
     */
    public void setOutboundStatus(boolean outboundStatus);

    /**
     * Returns the period sid of this st arp outbound.
     *
     * @return the period sid of this st arp outbound
     */
    public int getPeriodSid();

    /**
     * Sets the period sid of this st arp outbound.
     *
     * @param periodSid the period sid of this st arp outbound
     */
    public void setPeriodSid(int periodSid);

    /**
     * Returns the item master sid of this st arp outbound.
     *
     * @return the item master sid of this st arp outbound
     */
    public int getItemMasterSid();

    /**
     * Sets the item master sid of this st arp outbound.
     *
     * @param itemMasterSid the item master sid of this st arp outbound
     */
    public void setItemMasterSid(int itemMasterSid);

    /**
     * Returns the rs model sid of this st arp outbound.
     *
     * @return the rs model sid of this st arp outbound
     */
    public int getRsModelSid();

    /**
     * Sets the rs model sid of this st arp outbound.
     *
     * @param rsModelSid the rs model sid of this st arp outbound
     */
    public void setRsModelSid(int rsModelSid);

    /**
     * Returns the session ID of this st arp outbound.
     *
     * @return the session ID of this st arp outbound
     */
    @AutoEscape
    public String getSessionId();

    /**
     * Sets the session ID of this st arp outbound.
     *
     * @param sessionId the session ID of this st arp outbound
     */
    public void setSessionId(String sessionId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(StArpOutbound stArpOutbound);

    @Override
    public int hashCode();

    @Override
    public CacheModel<StArpOutbound> toCacheModel();

    @Override
    public StArpOutbound toEscapedModel();

    @Override
    public StArpOutbound toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
