package com.stpl.gtn.gtn2o.ui.module.workflowinbox.constants;

import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.List;

public class GtnFrameworkWorkflowInboxClassConstants {

	private GtnFrameworkWorkflowInboxClassConstants() {
	}

	public static final String WORKFLOW_ACTION_PACKAGE_CRUD = "com.stpl.gtn.gtn2o.ui.action.crud.";
	public static final String WORKFLOW_INBOX_DEDUCTION_LEVEL_VALUE_ACTION = "com.stpl.gtn.gtn2o.ui.module.workflowinbox.action.GtnFrameworkWorkflowInboxDeductionLevelValueAction";
	public static final String WORKFLOW_INBOX_ARM_DEDUCTION_LEVEL_VALUE_ACTION = "com.stpl.gtn.gtn2o.ui.module.workflowinbox.action.GtnFrameworkArmWorkflowInboxDeductionLevelValueAction";
	public static final String GTN_PRIVATE_VIEW_VALIDATION_MSG_RESET_HEADER = "Reset Confirmation";
	public static final String GTN_PRIVATE_VIEW_VALIDATION_MSG_RESET = "Are you sure you want to reset the values in the Search Criteria group box?";
	public static final String GTN_CREATED_BY_VALIDATION_MSG_RESET_HEADER = "Confirm Reset";
	public static final String GTN_CREATED_BY_VALIDATION_MSG_RESET = "Are you sure you want to reset the page to default/previous values?";
	public static final String WORKFLOW_ACTION_SAVE_VIEW_ACTION = WORKFLOW_ACTION_PACKAGE_CRUD
			+ "GtnFrameworkConfigureSaveProfilelookupAction";
	public static final String WORKFLOW_VIEW_SAVE_ACTION = WORKFLOW_ACTION_PACKAGE_CRUD
			+ "GtnFrameworkWorkFlowPublicPrivateViewSaveAction";
	public static final String GTN_WORKFLOW_CONFIRMATION_MSG_RESET_HEADER = "Confirmation";
	public static final String GTN_WORKFLOW_CONFIRMATION_MSG_RESET = "Are you sure you want to reset the page to default/previous values?";
	public static final String EMPTY = "";
	public static final String SEARCH_VIEW = "Search View";
	public static final String WORKFLOWROOTLAYOUT = "workFlowRootLayout";
	public static final String SUMMARY_SEARCH_MAINLAYOUT = "summarySearchMainLayout";
	public static final String SUMMARY_SEARCH = "Summary Search";
	public static final String SUMMARY_SEARCH_PANEL = "summarySearchPanel";
	public static final String SUMMARY_SEARCH_MAIN_INNERLAYOUT = "summarySearchMainInnerLayout";
	public static final String SUMMARY_SEARCH_PANEL_INNERLAYOUT = "summarySearchPanelInnerLayout";
	public static final String SUMMARY_SEARCH_ARM_PANEL_INNERLAYOUT = "summarySearchARMPanelInnerLayout";
	public static final String SUMMARY_SEARCH_COMPANY_BUSINESS_PANEL_INNERLAYOUT = "summarySearchcompanybusinessPanelInnerLayout";
	public static final String BUSINESS_PROCESS_LAYOUT = "businessProcessLayout";
	public static final String BUSINESS_PROCESS = "businessProcess";
	public static final String BUSINESSPROCESS_NAME = "Business Process";
	public static final String BUSINESS_PROCESS_TYPE = "BUSINESS_PROCESS_TYPE";
	public static final String BUSINESS_PROCESS_NAR = "BUSINESS_PROCESS_NAR";
	public static final String WORKFLOW_BUSINESS_PROCESS = "WORKFLOW_BUSINESS_PROCESS";
	public static final String PRIVATEVIEW_LAYOUT = "privateViewLayout";
	public static final String VIEW_SMALL = "View";
	public static final String PRIVATEVIEW_NAME = "Private View";
	public static final String VIEW_SEARCH_POPUP = "ViewSearchPopup";
	public static final String VIEW_SEARCHPOPUP = "View Search Popup";
	public static final String PUBLICVIEW_LAYOUT = "publicViewLayout";
	public static final String PUBLICVIEW = "publicView";
	public static final String PRIVATEVIEW = "privateView";
	public static final String PUBLICVIEW_NAME = "Public View";
	public static final String PUBLICVIEW_SEARCHPOPUP = "publicViewSearchPopup";
	public static final String WORKFLOWID_LAYOUT = "workflowIdLayout";
	public static final String WORKFLOWID = "workflowId";
	public static final String WORKFLOWID_NAME = "Workflow ID";
	public static final String WORKFLOWNAME_LAYOUT = "workflowNameLayout";
	public static final String WORKFLOWNAME = "workflowName";
	public static final String WORKFLOWCOMPONENT_NAME = "Workflow Name";
	public static final String WORKFLOWDESC_LAYOUT = "workflowDescLayout";
	public static final String WORKFLOW_DESC = "workflowDesc";
	public static final String WORKFLOWDESCRIPTION_NAME = "Workflow Description";
	public static final String CREATEDFROM_LAYOUT = "createdFromLayout";
	public static final String CREATEDFROM = "createdFrom";
	public static final String CREATEDFROM_NAME = "Created-From";
	public static final String CREATEDTO_LAYOUT = "createdToLayout";
	public static final String CREATEDTO = "createdTo";
	public static final String CREATEDTO_NAME = "Created-To";
	public static final String CREATEDBY_LAYOUT = "createdByLayout";
	public static final String CREATEDBY = "createdBy";
	public static final String CREATEDBY_NAME = "Created By";
	public static final String CREATEDBY_SEARCHPOPUP = "createdBySearchPopup";
	public static final String APPROVEDFROM_LAYOUT = "approvedFromLayout";
	public static final String APPROVEDFROM = "approvedFrom";
	public static final String APPROVEDFROM_NAME = "Approved-From";
	public static final String APPROVEDTO_LAYOUT = "approvedToLayout";
	public static final String APPROVEDTO = "approvedTo";
	public static final String APPROVEDTO_NAME = "Approved-To";
	public static final String APPROVEDBY_LAYOUT = "approvedByLayout";
	public static final String APPROVEDBY = "approvedBy";
	public static final String APPROVEDBY_NAME = "Approved By";
	public static final String APPROVEDBY_SEARCHPOPUP = "approvedBySearchPopup";
	public static final String SEARCHPOPUP = "SearchPopup";
	public static final String WORKFLOWSID_LAYOUT = "workflowSidLayout";
	public static final String WORKFLOWSID = "workflowSid";
	public static final String WORKFLOWSID_NAME = "Workflow Sid";
	public static final String BUTTONMAIN_LAYOUT = "buttonMainLayout";
	public static final String SEARCH_BTN = "searchBtn";
	public static final String SEARCH_NAME = "SEARCH";
	public static final String WORKFLOWSEARCHRESULTTABLE = "workFlowsearchResultTable";
	public static final String RESET_BTN = "resetBtn";
	public static final String RESET = "RESET";
	public static final String CONTRACTID = "contractId";
	public static final String CONTRACTNO = "contractNo";
	public static final String COMPANYNO = "companyNo";
	public static final String COMPANYNAME = "companyName";
	public static final String BUSINESSUNITID = "businessUnitId";
	public static final String BUSINESSUNITNO = "businessUnitNo";
	public static final String BUSINESSUNITNAME = "businessUnitName";
	public static final String CONTRACTNAME = "contractName";
	public static final String ITEMNO = "itemNo";
	public static final String ITEMNAME = "itemName";
	public static final String FORECASTDEDUCTIONLEVEL = "forecastdeductionLevel";
	public static final String FORECASTDEDUCTIONVALUE = "forecastdeductionValue";
	public static final String CONTRACTTYPE = "contractType";
	public static final String COMPANYID = "companyID";
	public static final String ITEMID = "itemId";
	public static final String BUSINESSUNITIDRETURNS = "businessUnitIdReturns";
	public static final String BUSINESSUNITNORETURNS = "businessUnitNoReturns";
	public static final String BUSINESSUNITNAMERETURNS = "businessUnitNameReturns";
	public static final String ITEMNORETURNS = "itemNoReturns";
	public static final String ITEMNAMERETURNS = "itemNameReturns";
	public static final String ITEMIDRETURNS = "itemIdReturns";
	public static final String WORKFLOWSTATUSARM = "workflowStatusArm";
	public static final String ADJUSTMENTTYPE = "adjustmentType";
	public static final String CONTRACTIDARM = "contractIdArm";
	public static final String CONTRACTNOARM = "contractNoArm";
	public static final String CUSTOMERNOARM = "customerNoArm";
	public static final String CUSTOMERNAMEARM = "customerNameArm";
	public static final String BRANDIDARM = "brandIdArm";
	public static final String CONTRACTNAMEARM = "contractNameArm";
	public static final String ITEMNOARM = "itemNoArm";
	public static final String ITEMNAMEARM = "itemNameArm";
	public static final String BRANDNAMEARM = "brandNameArm";
	public static final String GLDATEARM = "glDateArm";
	public static final String DEDUCTIONLEVELARM = "deductionLevelArm";
	public static final String DEDUCTIONVALUEARM = "deductionValueArm";
	public static final String DEDUCTIONNOARM = "deductionNoArm";
	public static final String DEDUCTIONNAMEARM = "deductionNameArm";
	public static final String FORECASTINGDETAILSEARCHPANEL = "forecastingDetailSearchPanel";
	public static final String RETURNDETAILSEARCHPANEL = "returnsDetailSearchPanel";
	public static final String ARMDETAILSEARCHPANEL = "armDetailSearchPanel";
	public static final String DSSAVEVIEW = "dsSaveView";
	public static final String SAVEPROFILE = "SAVE PROFILE";
	public static final String SAVEPROFILENOSEARCH = "No Search Criteria";
	public static final String SAVEPROFILENOSEARCHPLEASEENTER = "No search criteria were found. Please enter search criteria and try again.";
	public static final String DSSAVEVIEWLOOKUP = "dsSaveViewLookUp";
	public static final String SAVEVIEWPOPUP = "Save View Popup";
	public static final String SAVEVIEWNAME = "saveViewName";
	public static final String EMPTY_STRING = "";
	public static final String SAVEVIEWUPDATE = "saveViewUpdate";
	public static final String SAVEVIEWADD = "saveViewAdd";
	public static final String SAVEVIEWTYPE = "saveViewType";
	public static final String PUBLIC = "Public";
	public static final String PRIVATE = "Private";
	public static final String RESULTMAIN_LAYOUT = "resultMainLayout";
	public static final String RESULTS = "Results";
	public static final String RESULTMAIN_PANEL = "resultMainPanel";
	public static final String RESULTMAINPANEL_INNERLAYOUT = "resultMainPanelInnerLayout";
	public static final String NOOFAPPROVALS = "noOfApprovals";
	public static final String APPROVALLEVEL = "approvalLevel";
	public static final String CREATEDBYID = "createdById";
	public static final String WORKFLOWINBOX = "workFlowInbox";
	public static final String WORKFLOWSEARCHQUERY = "workflowSearchQuery";
	public static final String BOTTOMBUTTONMAINLAYOUT = "bottomButtonMainLayout";
	public static final String HISTORYBTN = "historyBtn";
	public static final String HISTORY = "HISTORY";
	public static final String HISTORYLOOKUP = "historyLookUp";
	public static final String WORKFLOW_HISTORY = "Workflow History";
	public static final String HISTORYSEARCHRESULT_TABLE = "historysearchResultTable";
	public static final String OPENBTN = "openBtn";
	public static final String OPEN = "OPEN";
	public static final String VIEWBTN = "viewBtn";
	public static final String VIEW = "VIEW";
	public static final String WORKFLOW_DETAILS = "WorkFlow_Details";
	public static final String DETAILSEARCH = "Detail Search";
	public static final String FORECASTINGDETAILSEARCHPANEL_INNERLAYOUT = "forecastingDetailSearchPanelInnerLayout";
	public static final String CONTRACTIDLAYOUT = "contractIdLayout";
	public static final String CONTRACT_ID = "Contract ID";
	public static final String CONTRACTNO_LAYOUT = "contractNoLayout";
	public static final String CONTRACT_NO = " Contract No";
	public static final String COMPANYNO_LAYOUT = "companyNoLayout";
	public static final String COMPANY_NO = "Company No";
	public static final String COMPANYNAME_LAYOUT = "companyNameLayout";
	public static final String COMPANY_NAME = "Company Name";
	public static final String BUSINESSUNITID_LAYOUT = "businessUnitIdLayout";
	public static final String BUSINESS_UNIT_ID = "Business Unit ID";
	public static final String BUSINESSUNITNO_LAYOUT = "businessUnitNoLayout";
	public static final String BUSINESS_UNIT_NO = "Business Unit No";
	public static final String BUSINESSUNITNAME_LAYOUT = "businessUnitNameLayout";
	public static final String BUSINESS_UNIT_NAME = "Business Unit Name";
	public static final String CONTRACTNAME_LAYOUT = "contractNameLayout";
	public static final String CONTRACT_NAME = "Contract Name";
	public static final String ITEMNO_LAYOUT = "itemNoLayout";
	public static final String ITEM_NO = "Item No";
	public static final String ITEMNAME_LAYOUT = "itemNameLayout";
	public static final String ITEM_NAME = "Item Name";
	public static final String DEDUCTIONLEVEL_LAYOUT = "deductionLevelLayout";
	public static final String DEDUCTION_LEVEL = "Deduction Level";
	public static final String DEDUCTION_LEVELS_NAR = "DEDUCTION_LEVELS_NAR";
	public static final String WORKFLOW_DEDUCTION_LEVELS = "WORKFLOW_DEDUCTION_LEVELS";
	public static final String DEDUCTIONVALUE_LAYOUT = "deductionValuecLayout";
	public static final String DEDUCTION_VALUE = "Deduction Value";
	public static final String CONTRACTTYPE_LAYOUT = "contractTypeLayout";
	public static final String CONTRACTTYPE_NAME = "Contract Type";
	public static final String CONTRACT_TYPE = "CONTRACT_TYPE";
	public static final String COMPANYID_LAYOUT = "companyIDLayout";
	public static final String COMPANY_ID = "Company ID";
	public static final String ITEMID_LAYOUT = "itemIdLayout";
	public static final String ITEM_ID = "Item ID";
	public static final String DETAIL_SEARCH = "Detail Search";
	public static final String ARMDETAILSEARCHPANEL_INNERLAYOUT = "armDetailSearchPanelInnerLayout";
	public static final String WORKFLOWSTATUS_LAYOUT = "workflowStatusLayout";
	public static final String WORKFLOW_STATUS = "Workflow Status";
	public static final String WORKFLOWSTATUS = "WorkFlowStatus";
	public static final String ADJUSTMENTTYPE_LAYOUT = "adjustmentTypeLayout";
	public static final String ADJUSTMENT_TYPE = "Adjustment Type";
	public static final String ADJUSTMENTTYPEDDLB = "adjustmentTypeDdlb";
	public static final String CUSTOMERNO_LAYOUT = "customerNoLayout";
	public static final String CUSTOMER_NO = "Customer No";
	public static final String CUSTOMERNAME_LAYOUT = "customerNameLayout";
	public static final String CUSTOMER_NAME = "Customer Name";
	public static final String BRANDID_LAYOUT = "brandIdLayout";
	public static final String BRAND_ID = "Brand ID";
	public static final String BRANDNAME_LAYOUT = "brandNameLayout";
	public static final String BRAND_NAME = "Brand Name";
	public static final String GLDATE_LAYOUT = "glDateLayout";
	public static final String GL_DATE = "GL Date";
	public static final String DEDUCTION_LEVELS = "DEDUCTION_LEVELS";
	public static final String DEDUCTIONNO_LAYOUT = "deductionNoLayout";
	public static final String DEDUCTION_NO = "Deduction No";
	public static final String DEDUCTIONNAME_LAYOUT = "deductionNameLayout";
	public static final String DEDUCTION_NAME = "Deduction Name";
	public static final String COMPANYARM_LAYOUT = "companyARMLayout";
	public static final String COMPANYARM = "companyARM";
	public static final String COMPANY = "Company";
	public static final String COMPANYARMDDLB = "companyARMddlb";
	public static final String BUSINESSUNITARM_LAYOUT = "businessUnitARMLayout";
	public static final String BUSINESSUNITARM = "businessUnitARM";
	public static final String BUSINESS_UNIT = "Business Unit";
	public static final String BUSINESSUNITARMDDLB = "businessUnitARMDdlb";
	public static final String CUSTOMFILTERCOMBOBOX = "customFilterComboBox";
	public static final String STATUS = "status";
	public static final String USERS = "USERS";
	public static final String ARM_ADJUSTMENT_TYPE = "ARM_ADJUSTMENT_TYPE";
	public static final String UPDATE = "Update";
	public static final String UPDATE_LOWERCASE = "update";
	public static final String YOUHAVESUCESSFULLY = "You have successfully";
	public static final String UPDATED = "updated";
	public static final String ADDED = "added";
	public static final String VIEW_ADDED_SUCESSFULLY = "View Added Successfully";
	public static final String ROOTLAYOUT = "Rootlayout";
	public static final String SEARCH_CRITERIA = " Search Criteria";
	public static final String SEARCHCRITERIA_PANEL = "SearchCriteriaPanel";
	public static final String ARMSEARCHCRITERIA_LAYOUT = "ARMSearchCriterialayout";
	public static final String USERNAME_LAYOUT = "userNamelayout";
	public static final String USERNAME_ID = "UserName";
	public static final String USER_NAME = "User Name";
	public static final String FIRSTNAME_LAYOUT = "firstNamelayout";
	public static final String FIRSTNAME_ID = "FirstName";
	public static final String FIRST_NAME = "First Name";
	public static final String LASTTNAME_LAYOUT = "lastNamelayout";
	public static final String LASTNAME_ID = "LastName";
	public static final String LAST_NAME = "Last Name";
	public static final String BUTTON_LAYOUT = "Buttonlayout";
	public static final String GTNSEARCH_LAYOUT = "gtnSearch01layout";
	public static final String GTNSEARCH = "gtnSearch01";
	public static final String SEARCH = "Search";
	public static final String PLEASE_ENTER_SEARCH_CRITERIA = "Please enter Search Criteria";
	public static final String RESULT_PANEL = "resultPanel";
	public static final String RESULT_LAYOUT = "resultlayout";
	public static final String SEARCHRESULT_TABLE = "searchResultTable";
	public static final String LASTNAME = "lastName";
	public static final String FIRSTNAME = "firstName";
	public static final String ACTIONBUTTON_LAYOUT = "actionButtonlayout";
	public static final String GTNRESET_LAYOUT = "gtnReset01layout";
	public static final String GTNRESET = "gtnReset01";
	public static final String RESET_LOWERCASE = "Reset";
	public static final String SELECTBUTTON_LAYOUT = "SelectButtonlayout";
	public static final String SELECTBUTTON = "SelectButton";
	public static final String SELECT = "Select";
	public static final String CLOSEBUTTON_LAYOUT = "CloseButtonlayout";
	public static final String CLOSEBUTTON = "CloseButton";
	public static final String CLOSE = "Close";
	public static final String GTNBOTTOMRESET_LAYOUT = "gtnbottomReset01layout";
	public static final String GTNBOTTOMRESET = "gtnbottomReset01";
	public static final String CREATEDBY_ROOTLAYOUT = "createdByRootlayout";
	public static final String CREATEDBYSEARCHCRITERIA_PANEL = "createdBySearchCriteriaPanel";
	public static final String CREATEDBYARMSEARCHCRITERIA_LAYOUT = "createdByARMSearchCriterialayout";
	public static final String CREATEDBYUSERNAME_LAYOUT = "createdByuserNamelayout";
	public static final String CREATEDBYUSERNAME = "createdByUserName";
	public static final String CREATEDBYFIRSTNAME_LAYOUT = "createdByfirstNamelayout";
	public static final String CREATEDBYFIRSTNAME = "createdByFirstName";
	public static final String CREATEDBYLASTNAME_LAYOUT = "createdBylastNamelayout";
	public static final String CREATEDBYLASTNAME = "createdByLastName";
	public static final String CREATEDBYBUTTON_LAYOUT = "createdByButtonlayout";
	public static final String CREATEDBYGTNSEARCH_LAYOUT = "createdBygtnSearch01layout";
	public static final String CREATEDBYGTNSEARCH = "createdBygtnSearch01";
	public static final String CREATEDBYRESULTPANEL = "createdByresultPanel";
	public static final String CREATEDBYRESULT_LAYOUT = "createdByresultlayout";
	public static final String CREATEDBYSEARCHRESULT_TABLE = "createdBysearchResultTable";
	public static final String CREATEDBYACTIONBUTTON_LAYOUT = "createdByactionButtonlayout";
	public static final String CREATEDBYGTNRESET_LAYOUT = "createdBygtnReset01layout";
	public static final String CREATEDBYGTNRESET = "createdBygtnReset01";
	public static final String CREATEDBYSELECTBUTTON_LAYOUT = "createdBySelectButtonlayout";
	public static final String CREATEDBYSELECTBUTTON = "createdBySelectButton";
	public static final String CREATEDBYCLOSEBUTTON_LAYOUT = "createdByCloseButtonlayout";
	public static final String CREATEDBYCLOSEBUTTON = "createdByCloseButton";
	public static final String CREATEDBYGTNBOTTOMRESET_LAYOUT = "createdBygtnbottomReset01layout";
	public static final String CREATEDBYGTNBOTTOMRESET = "createdBygtnbottomReset01";
	public static final String HISTORYROOTLAYOUT = "historyRootlayout";
	public static final String SUMMARY = "Summary";
	public static final String HISTORYSEARCHCRITERIA_PANEL = "historySearchCriteriaPanel";
	public static final String HISTORYSEARCHCRITERIA_LAYOUT = "historySearchCriterialayout";
	public static final String COMPANYIDLAYOUT = "companyIdlayout";
	public static final String COMPANYID_HISTORY = "companyId";
	public static final String COMPANYNOLAYOUT = "companyNolayout";
	public static final String COMPANYNAMELAYOUT = "companyNamelayout";
	public static final String BUSINESSUNITIDLAYOUT = "businessUnitIdlayout";
	public static final String BUSINESSUNITNOLAYOUT = "businessUnitNolayout";
	public static final String BUSINESSUNITNAMELAYOUT = "businessUnitNamelayout";
	public static final String BUSINESSPROCESSLAYOUT = "businessProcesslayout";
	public static final String BUSINESSPROCESSTEXT_FIELD = "businessProcesstextfield";
	public static final String WORKFLOWIDLAYOUT = "workflowIdlayout";
	public static final String WORKFLOWID_POPUP = "workflowIdpopup";
	public static final String WORKFLOWNAMELAYOUT = "workflowNamelayout";
	public static final String WORKFLOWNAME_POPUP = "workflowNamepopup";
	public static final String WORKFLOWDESCLAYOUT = "workflowDesclayout";
	public static final String WORKFLOWDESC = "Workflow Desc";
	public static final String WORKFLOWDESCONELAYOUT = "workflowDesc1layout";
	public static final String WORKFLOWDESCONE = "workflowDesc1";
	public static final String WORKFLOW_DESCONE = "Workflow Desc1";
	public static final String PARENTRESULT_LAYOUT = "parentresultlayout";
	public static final String HISTORY_DETAILS = "History Details";
	public static final String HISTORYRESULT_PANEL = "historyresultPanel";
	public static final String ATTACHMENT_DETAILS = "Attachment Details";
	public static final String ATTACHMENTRESULT_PANEL = "attachmentresultPanel";
	public static final String HISTORYDETAILSRESULT_LAYOUT = "historyDetailsresultlayout";
	public static final String ATTACHMENTDETAILSRESULT_LAYOUT = "attachmentDetailsresultlayout";
	public static final String STATUS_LOWERCASE = "Status";
	public static final String MODIFIED_DATE = "Modified Date";
	public static final String MODIFIED_BY = "Modified By";
	public static final String NOTES = "Notes";
	public static final String ATTACHMENT = "Attachement";
	public static final String FILENAME = "fileName";
	public static final String MODIFIEDDATE = "modifiedDate";
	public static final String MODIFIEDBY = "modifiedBy";
	public static final String NOTES_LOWERCASE = "notes";
	public static final String ATTACHMENT_LINK = "attachmentLink";
	public static final String HISTORYSEARCHQUERY = "historySearchQuery";
	public static final String ATTACHMENTSEARCHRESULT_TABLE = "attachmentsearchResultTable";
	public static final String DOCUMENT_NAME = "Document Name";
	public static final String DATE_ADDED = "Date Added";
	public static final String FILETYPE = "fileType";
	public static final String DOCUMENTNAME = "documentName";
	public static final String DATEADDED = "dateAdded";
	public static final String USERNAME = "userName";
	public static final String ATTACHEMENTSEARCHQUERY = "attachmentSearchQuery";
	public static final String ATTACHEMENTSEARCHRESULT_TABLE = "attachmentsearchResultTable";
	public static final String HISTORYACTIONBUTTON_LAYOUT = "historyactionButtonlayout";
	public static final String WORKFLOWHISTORY = "WorkFlow_History";
	public static final String HISTORYCLOSEBUTTON_LAYOUT = "historyCloseButtonlayout";
	public static final String HISTORYCLOSEBUTTON = "historyCloseButton";
	public static final String VIEW_ROOTLAYOUT = "ViewRootlayout";
	public static final String VIEW_SEARCH = "View Search";
	public static final String VIEWSEARCHCRITERIA_PANEL = "ViewSearchCriteriaPanel";
	public static final String VIEWSEARCHCRITERIA_LAYOUT = "ViewSearchCriterialayout";
	public static final String VIEWVIEWNAMELAYOUT = "ViewviewNamelayout";
	public static final String VIEWVIEWNAME = "ViewviewName";
	public static final String VIEW_NAME = "View Name";
	public static final String VIEWBUTTON_LAYOUT = "ViewButtonlayout";
	public static final String VIEWGTNSEARCH_LAYOUT = "ViewgtnSearch01layout";
	public static final String VIEWGTNSEARCH = "ViewgtnSearch01";
	public static final String VIEWSEARCHRESULT_TABLE = "ViewsearchResultTable";
	public static final String VIEWRESULT_PANEL = "ViewresultPanel";
	public static final String VIEWRESULT_LAYOUT = "Viewresultlayout";
	public static final String CREATION_DATE = "Creation Date";
	public static final String APPROVED_DATE = "Approved Date";
	public static final String VIEWNAMEPRIVATE = "viewNamePrivate";
	public static final String WORKFLOWIDPRIVATE = "workflowIdPrivate";
	public static final String WORKFLOWNAMEPRIVATE = "workflowNamePrivate";
	public static final String WORKFLOWDESCPRIVATE = "workflowDescPrivate";
	public static final String WORKFLOWSTATUSPRIVATE = "workflowStatusPrivate";
	public static final String COMPANYNAMEPRIVATE = "companyNamePrivate";
	public static final String BUSINESSUNITNAMEPRIVATE = "businessUnitNamePrivate";
	public static final String CREATEDBYPRIVATE = "createdByPrivate";
	public static final String CREATEDDATEPRIVATE = "createdDatePrivate";
	public static final String APPROVEDBYPRIVATE = "approvedByPrivate";
	public static final String APPROVEDDATETOPRIVATE = "approvedDateToPrivate";
	public static final String SEARCHQUERY = "SearchQuery";
	public static final String VIEWACTIONBUTTON_LAYOUT = "ViewactionButtonlayout";
	public static final String VIEWGTNRESET_LAYOUT = "ViewgtnReset01layout";
	public static final String VIEWGTNRESET = "ViewgtnReset01";
	public static final String VIEWSELECTBUTTON_LAYOUT = "ViewSelectButtonlayout";
	public static final String VIEWSELECTBUTTON = "ViewSelectButton";
	public static final String VIEWCLOSEBUTTON_LAYOUT = "ViewCloseButtonlayout";
	public static final String VIEWCLOSEBUTTON = "ViewCloseButton";
	public static final String VIEWDELETEBUTTON_LAYOUT = "ViewDeleteButtonlayout";
	public static final String VIEWDELETEBUTTON = "ViewDeleteButton";
	public static final String DELETE = "DELETE";
	public static final String ARE_YOU_SURE_DELETE = "Are you sure that you want to delete this view?";
	public static final String SAVEVIEWROOTVERTICAL_LAYOUT = "saveViewLookUp-RootVerticalLayout";
	public static final String SAVEVIEWVIEWNAME = "saveView-ViewName";
	public static final String SAVEVIEWVIEWBUTTONS = "saveView-ViewButtons";
	public static final String VIEWNAMECOLUMN = "View Name:";
	public static final String SAVEVIEWCANCEL = "saveViewCancel";
	public static final String CANCEL = "CANCEL";
	public static final String ADD = "ADD";
	public static final String INVALIDVIEWNAME = "Invalid view name";
	public static final String ENTERTHEVIEWNAME = "Enter the view name";
	public static final String UPDATE_UPPERCASE = "UPDATE";
	public static final String ERROR = "Error";
	public static final String BUSINESSPROCESS_MANDATORY = "Business Process is mandatory. Please select a Business Process.";
	public static final String NO_SEARCH_CRITERIA = "No Search Criteria";
	public static final String PLEASE_ENTER_THE_CRITERIA = "Please enter the search criteria.";
	public static final String INVALID_SEARCH = "Invalid Search";
	public static final String THERE_ARE_NO_USERS = "There are no Users that match the search criteria. Please try again.";
	public static final String USER_FIRST_NAME = "User First Name";
	public static final String USER_LAST_NAME = "User Last Name";
	public static final String EQUALSOF = "EQUALS";
	public static final String SELECT_ONE = "-Select one-";
	public static final String DEDUCTION_CATEGORY = "Deduction Category";
	public static final String RS_CATEGORY = "RS_CATEGORY";
	public static final String DEDUCTION_PROGRAM_TYPE = "Deduction Program Type";
	public static final String REBATE_PROGRAM_TYPE = "REBATE_PROGRAM_TYPE";
	public static final String DEDUCTION_SCHEDULE_TYPE = "Deduction Schedule Type";
	public static final String RS_TYPE = "RS_TYPE";
	public static final String VIEWTYPEPRIVATE = "viewTypePrivate";
	public static final String MODIFIEDDATEPRIVATE = "modifiedDatePrivate";
	public static final String MODIFIEDBYPRIVATE = "modifiedByPrivate";
	public static final String OPEN_LAYOUT = "openLayout";
	public static final String VIEW_LAYOUT = "viewLayout";
	public static final String USERID = "userId";
	public static final String ADJUSTMENTTYPENAME = "adjustmentTypeName";
	public static final String GF = "GF";
	public static final String CF = "CF";
	public static final String CMF = "CMF";
	public static final String ARF = "ARF";
	public static final String REF = "REF";
	public static final String ARM_TRX = "ARM_TRX";
	public static final String APPROVER = "approver";
	public static final String BR = "BR";
	public static final String FD = "FD";
	public static final String YES = "yes";
	public static final String CREATOR = "creator";
	public static final String HTTP = "http://";
	public static final String HTTPS = "https://";
	public static final String ARM = "ARM";
	public static final String WEB_COMMERCIAL = "?nmFlow='true'";
	public static final String WEB_GOVERNMENT = "/web/guest/government?mFlow='true'";
	public static final String WEB_BASERATE = "/web/guest/base-rate?nmFlow='true'";
	public static final String WEB_FIXEDDOLLAR = "/web/guest/fixed-dollar-adjustment?nmFlow='true'";
	public static final String WEB_ARP = "/web/guest/accrual-rate-projection?arFlow='true'";
	public static final String WEB_CONTRACT_DASHBOARD = "?cwFlow='true'";
	public static final String WEB_FORECAST_RETURNS = "/web/guest/forecast-returns?reFlow='true'";
	public static final String WEB_FIXEDDOLLAR_ARMFLOW = "/web/guest/fixed-dollar-adjustment?armFlow='true'";
	public static final String WEB_GOVERNMENT_NMFLOW = "/web/guest/government?nmFlow='true'";
	public static final String WEB_FORECAST_RETURNS_RETFLOW = "/web/guest/forecast-returns?retFlow='true'";
	public static final String WITHDRAWN = "Withdrawn";
	public static final String REJECTED = "Rejected";
	public static final String PENDING = "Pending";
	public static final String BROWSER_HEIGHTWIDTH = "height=800,width=1000,resizable,scrollbars=1";
	public static final String BROWSER_SCROLLBARS = "toolbar=no,scrollbars=1,location=no";
	public static final String PROJECTIONIDWORKFLOW = "projectionIdFromWorkflow";
	public static final String ACCCLOSUREIDMASTERSID = "accClosureIdMasterSid";
	public static final String CONTRACT_MASTERSID = "contractMasterSid";
	public static final String ARM_MASTERSID = "armMasterSid";
	public static final String GOVERNMENT = "Government";
	public static final String COMMERCIAL = "Commercial";
	public static final String ACCRUAL_RATE_PROJ = "AccrualRateProjection";
	public static final String RETURNS = "Returns";
	public static final String FIXEDDOLLAR_ADJUSTMENT = "FixedDollarAdjustment";
	public static final String WORKFLOWISTATUS = "workflowStatus";
	public static final String USERTYPE = "userType";
	public static final String PORTLETNAME = "portletName";
	public static final String SELECTED_ADJUSTMENTTYPE = "selectedAdjustmentType";
	public static final String CONFIGURATION_TYPE = "configurationType";
	public static final String CUSTOMERHIERSID = "customerHierSid";
	public static final String PRODUCTHIERSID = "productHierSid";
	public static final String CUSTOMERHIERLEVEL = "customerHierarchyLevel";
	public static final String CUSTRELATIONSHIPSID = "custRelationshipBuilderSid";
	public static final String PRODHIERLEVEL = "productHierarchyLevel";
	public static final String PRODRELATIONSID = "prodRelationshipBuilderSid";
	public static final String WORKFLOW_ID = "Workflow Id";
	public static final Class<?> JAVA_LANG_STRING = String.class;
	public static final Class<?> JAVA_UTIL_DATE = Date.class;
	public static final String APPROVEDDATE = "approvedDate";
	public static final String BUSINESSUNIT = "businessUnit";
	public static final String COMPANY_LOWERCASE = "company";
	public static final String CREATIONDATE = "creationDate";
	public static final String PROJECTIONMASTER_SID = "projectionMasterSid";
	public static final Class<?> JAVA_LANG_INTEGER = Integer.class;
	public static final String PLEASE_SELECT_RECORD_VIEWHISTORY = "Please select a Workflow to view history.";
	public static final String SLASH = "/";
	public static final String CONTRACT_DASHBOARD = "Contract Dashboard";
	public static final String CREATEDFROM_PRIVATE = "creationFromDatePrivate";
	public static final String CREATEDTO_PRIVATE = "creationToDatePrivate";
	public static final String APPROVEDFROM_PRIVATE = "approvedDateFromPrivate";
	public static final String APPROVEDTO_PRIVATE = "approvedDateToPrivate";
	public static final String DEDUCTIONVALUE_ARMDDLB = "deductionvalueARMddlb";
	public static final String FULLNAME = "fullName";
	public static final String WORKFLOWLOOKUPSLASH = "/workFlowLookup";
	public static final String GETGCMWORKFLOWLIST = "/getGcmWfList";
	public static final String EQUAL = "=";
	public static final String RECORD_BEAN = "RecordBean";
	public static final String WEB_GUEST = "/web/guest";
                    
	private static final List<String> VIEW_SAVE_FIELDS = Arrays.asList(WORKFLOWID, WORKFLOWNAME, WORKFLOW_DESC,
			CREATEDFROM, CREATEDTO, APPROVEDFROM, APPROVEDTO, CONTRACTID, CONTRACTNO, COMPANYNO, COMPANYNAME,
			BUSINESSUNITID, BUSINESSUNITNO, BUSINESSUNITNAME, CONTRACTNAME, ITEMNO, ITEMNAME, FORECASTDEDUCTIONVALUE,
			FORECASTDEDUCTIONLEVEL, CONTRACTTYPE, COMPANYID, ITEMID, BUSINESSUNITIDRETURNS, BUSINESSUNITNORETURNS,
			BUSINESSUNITNAMERETURNS, ITEMNORETURNS, ITEMNAMERETURNS, ITEMIDRETURNS, COMPANYARM, BUSINESSUNITARM,
			WORKFLOWSTATUSARM, ADJUSTMENTTYPE, CONTRACTIDARM, CONTRACTNOARM, CUSTOMERNOARM, CUSTOMERNAMEARM, BRANDIDARM,
			CONTRACTNAMEARM, ITEMNOARM, ITEMNAMEARM, BRANDNAMEARM, GLDATEARM, DEDUCTIONLEVELARM, DEDUCTIONVALUEARM,
			DEDUCTIONNOARM, DEDUCTIONNAMEARM, SAVEVIEWNAME, SAVEVIEWTYPE, BUSINESS_PROCESS, CREATEDBY, APPROVEDBY);
        
private static final String[] ADDRESS_VISIBLE_FIELDS = new String[] { GtnFrameworkWorkflowInboxClassConstants.FORECASTINGDETAILSEARCHPANEL,
				GtnFrameworkWorkflowInboxClassConstants.RETURNDETAILSEARCHPANEL,
				GtnFrameworkWorkflowInboxClassConstants.ARMDETAILSEARCHPANEL };

private static final String[] CUSTOM_PROPERTY_IDS = { GtnFrameworkWorkflowInboxClassConstants.STATUS,
				GtnFrameworkWorkflowInboxClassConstants.CREATEDBY, GtnFrameworkWorkflowInboxClassConstants.APPROVEDBY,
				GtnFrameworkWorkflowInboxClassConstants.ADJUSTMENTTYPE,
				GtnFrameworkWorkflowInboxClassConstants.WORKFLOWSTATUSARM };
private static final String[] CUSTOM_LIST_NAME_ARRAY = { GtnFrameworkWorkflowInboxClassConstants.WORKFLOWSTATUS,
				GtnFrameworkWorkflowInboxClassConstants.USERS, GtnFrameworkWorkflowInboxClassConstants.USERS,
				GtnFrameworkWorkflowInboxClassConstants.ARM_ADJUSTMENT_TYPE,
				GtnFrameworkWorkflowInboxClassConstants.WORKFLOWSTATUS };

    public static String[] getCUSTOM_LIST_NAME_ARRAY() {
        return CUSTOM_LIST_NAME_ARRAY.clone();
    }


    public static String[] getCUSTOM_PROPERTY_IDS() {
        return CUSTOM_PROPERTY_IDS.clone();
    }

    public static String[] getADDRESS_VISIBLE_FIELDS() {
        return ADDRESS_VISIBLE_FIELDS.clone();
    }

	public static List<String> getViewSaveFields() {
		return Collections.unmodifiableList(VIEW_SAVE_FIELDS);
	}

}
