package com.stpl.app.model;

import com.stpl.portal.kernel.bean.AutoEscape;
import com.stpl.portal.model.BaseModel;
import com.stpl.portal.model.CacheModel;
import com.stpl.portal.service.ServiceContext;

import com.stpl.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the NaProjectionSelection service. Represents a row in the &quot;NA_PROJECTION_SELECTION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.stpl.app.model.impl.NaProjectionSelectionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.stpl.app.model.impl.NaProjectionSelectionImpl}.
 * </p>
 *
 * @author
 * @see NaProjectionSelection
 * @see com.stpl.app.model.impl.NaProjectionSelectionImpl
 * @see com.stpl.app.model.impl.NaProjectionSelectionModelImpl
 * @generated
 */
public interface NaProjectionSelectionModel extends BaseModel<NaProjectionSelection> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a na projection selection model instance should use the {@link NaProjectionSelection} interface instead.
     */

    /**
     * Returns the primary key of this na projection selection.
     *
     * @return the primary key of this na projection selection
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this na projection selection.
     *
     * @param primaryKey the primary key of this na projection selection
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the screen name of this na projection selection.
     *
     * @return the screen name of this na projection selection
     */
    @AutoEscape
    public String getScreenName();

    /**
     * Sets the screen name of this na projection selection.
     *
     * @param screenName the screen name of this na projection selection
     */
    public void setScreenName(String screenName);

    /**
     * Returns the field name of this na projection selection.
     *
     * @return the field name of this na projection selection
     */
    @AutoEscape
    public String getFieldName();

    /**
     * Sets the field name of this na projection selection.
     *
     * @param fieldName the field name of this na projection selection
     */
    public void setFieldName(String fieldName);

    /**
     * Returns the field values of this na projection selection.
     *
     * @return the field values of this na projection selection
     */
    @AutoEscape
    public String getFieldValues();

    /**
     * Sets the field values of this na projection selection.
     *
     * @param fieldValues the field values of this na projection selection
     */
    public void setFieldValues(String fieldValues);

    /**
     * Returns the na projection selection sid of this na projection selection.
     *
     * @return the na projection selection sid of this na projection selection
     */
    public int getNaProjectionSelectionSid();

    /**
     * Sets the na projection selection sid of this na projection selection.
     *
     * @param naProjectionSelectionSid the na projection selection sid of this na projection selection
     */
    public void setNaProjectionSelectionSid(int naProjectionSelectionSid);

    /**
     * Returns the na proj master sid of this na projection selection.
     *
     * @return the na proj master sid of this na projection selection
     */
    public int getNaProjMasterSid();

    /**
     * Sets the na proj master sid of this na projection selection.
     *
     * @param naProjMasterSid the na proj master sid of this na projection selection
     */
    public void setNaProjMasterSid(int naProjMasterSid);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(NaProjectionSelection naProjectionSelection);

    @Override
    public int hashCode();

    @Override
    public CacheModel<NaProjectionSelection> toCacheModel();

    @Override
    public NaProjectionSelection toEscapedModel();

    @Override
    public NaProjectionSelection toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
